package org.swtk.commons.dict.wordnet.index.name.controller.t.y;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.c.h.WordnetNounIndexNameInstanceTYCH;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.c.o.WordnetNounIndexNameInstanceTYCO;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.i.n.WordnetNounIndexNameInstanceTYIN;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.i.y.WordnetNounIndexNameInstanceTYIY;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.k.e.WordnetNounIndexNameInstanceTYKE;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.l.e.WordnetNounIndexNameInstanceTYLE;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.m.p.WordnetNounIndexNameInstanceTYMP;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.n.d.WordnetNounIndexNameInstanceTYND;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.n.e.WordnetNounIndexNameInstanceTYNE;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.p.e.WordnetNounIndexNameInstanceTYPE;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.p.h.WordnetNounIndexNameInstanceTYPH;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.p.i.WordnetNounIndexNameInstanceTYPI;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.p.o.WordnetNounIndexNameInstanceTYPO;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.r.a.WordnetNounIndexNameInstanceTYRA;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.r.e.WordnetNounIndexNameInstanceTYRE;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.r.o.WordnetNounIndexNameInstanceTYRO;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.r.r.WordnetNounIndexNameInstanceTYRR;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.s.o.WordnetNounIndexNameInstanceTYSO;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.y.t.o.WordnetNounIndexNameInstanceTYTO;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerTY {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("tych".equals(key)) return WordnetNounIndexNameInstanceTYCH.get(TERM);
	if ("tyco".equals(key)) return WordnetNounIndexNameInstanceTYCO.get(TERM);
	if ("tyin".equals(key)) return WordnetNounIndexNameInstanceTYIN.get(TERM);
	if ("tyiy".equals(key)) return WordnetNounIndexNameInstanceTYIY.get(TERM);
	if ("tyke".equals(key)) return WordnetNounIndexNameInstanceTYKE.get(TERM);
	if ("tyle".equals(key)) return WordnetNounIndexNameInstanceTYLE.get(TERM);
	if ("tymp".equals(key)) return WordnetNounIndexNameInstanceTYMP.get(TERM);
	if ("tynd".equals(key)) return WordnetNounIndexNameInstanceTYND.get(TERM);
	if ("tyne".equals(key)) return WordnetNounIndexNameInstanceTYNE.get(TERM);
	if ("type".equals(key)) return WordnetNounIndexNameInstanceTYPE.get(TERM);
	if ("typh".equals(key)) return WordnetNounIndexNameInstanceTYPH.get(TERM);
	if ("typi".equals(key)) return WordnetNounIndexNameInstanceTYPI.get(TERM);
	if ("typo".equals(key)) return WordnetNounIndexNameInstanceTYPO.get(TERM);
	if ("tyra".equals(key)) return WordnetNounIndexNameInstanceTYRA.get(TERM);
	if ("tyre".equals(key)) return WordnetNounIndexNameInstanceTYRE.get(TERM);
	if ("tyro".equals(key)) return WordnetNounIndexNameInstanceTYRO.get(TERM);
	if ("tyrr".equals(key)) return WordnetNounIndexNameInstanceTYRR.get(TERM);
	if ("tyso".equals(key)) return WordnetNounIndexNameInstanceTYSO.get(TERM);
	if ("tyto".equals(key)) return WordnetNounIndexNameInstanceTYTO.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceTYCH.terms());
	set.addAll(WordnetNounIndexNameInstanceTYCO.terms());
	set.addAll(WordnetNounIndexNameInstanceTYIN.terms());
	set.addAll(WordnetNounIndexNameInstanceTYIY.terms());
	set.addAll(WordnetNounIndexNameInstanceTYKE.terms());
	set.addAll(WordnetNounIndexNameInstanceTYLE.terms());
	set.addAll(WordnetNounIndexNameInstanceTYMP.terms());
	set.addAll(WordnetNounIndexNameInstanceTYND.terms());
	set.addAll(WordnetNounIndexNameInstanceTYNE.terms());
	set.addAll(WordnetNounIndexNameInstanceTYPE.terms());
	set.addAll(WordnetNounIndexNameInstanceTYPH.terms());
	set.addAll(WordnetNounIndexNameInstanceTYPI.terms());
	set.addAll(WordnetNounIndexNameInstanceTYPO.terms());
	set.addAll(WordnetNounIndexNameInstanceTYRA.terms());
	set.addAll(WordnetNounIndexNameInstanceTYRE.terms());
	set.addAll(WordnetNounIndexNameInstanceTYRO.terms());
	set.addAll(WordnetNounIndexNameInstanceTYRR.terms());
	set.addAll(WordnetNounIndexNameInstanceTYSO.terms());
	set.addAll(WordnetNounIndexNameInstanceTYTO.terms());
  		return set; 	} }