package org.swtk.commons.dict.wordnet.indexbyname.instance.h.o.u;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceHOU {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"houdah\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03552577\"]}");
	add("{\"term\":\"houdini\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11081312\"]}");
	add("{\"term\":\"houghton\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09123582\", \"11081547\"]}");
	add("{\"term\":\"houhere\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12201402\"]}");
	add("{\"term\":\"hoummos\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07873707\"]}");
	add("{\"term\":\"hound\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09905672\", \"02090203\"]}");
	add("{\"term\":\"hour\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"05138288\", \"15253706\", \"15253174\", \"15252642\"]}");
	add("{\"term\":\"hourglass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03549323\"]}");
	add("{\"term\":\"houri\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09568129\", \"10388227\"]}");
	add("{\"term\":\"hours\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"15142458\", \"15143042\"]}");
	add("{\"term\":\"housatonic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09328937\"]}");
	add("{\"term\":\"house\", \"synsetCount\":12, \"upperType\":\"NOUN\", \"ids\":[\"03550330\", \"04424944\", \"08094856\", \"08398027\", \"08703415\", \"00433104\", \"07987896\", \"08179924\", \"08239887\", \"08241501\", \"08076706\", \"03549540\"]}");
	add("{\"term\":\"houseboat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03550650\"]}");
	add("{\"term\":\"housebreaker\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10209594\", \"10207845\"]}");
	add("{\"term\":\"housebreaking\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00786917\"]}");
	add("{\"term\":\"housebuilder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10201287\"]}");
	add("{\"term\":\"housecleaning\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00581407\", \"00581602\"]}");
	add("{\"term\":\"housecoat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03823187\"]}");
	add("{\"term\":\"housecraft\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05651567\"]}");
	add("{\"term\":\"housedog\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02106932\"]}");
	add("{\"term\":\"housefather\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10207988\"]}");
	add("{\"term\":\"housefly\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02193442\"]}");
	add("{\"term\":\"houseful\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13789831\"]}");
	add("{\"term\":\"houseguest\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208091\"]}");
	add("{\"term\":\"household\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08094856\"]}");
	add("{\"term\":\"householder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10202130\"]}");
	add("{\"term\":\"househusband\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208195\"]}");
	add("{\"term\":\"housekeeper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208334\"]}");
	add("{\"term\":\"housekeeping\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00581998\"]}");
	add("{\"term\":\"houselights\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03550765\"]}");
	add("{\"term\":\"housemaid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10302369\"]}");
	add("{\"term\":\"houseman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10230873\"]}");
	add("{\"term\":\"housemaster\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208475\"]}");
	add("{\"term\":\"housemate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208576\"]}");
	add("{\"term\":\"housemother\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208678\"]}");
	add("{\"term\":\"housepaint\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03551292\"]}");
	add("{\"term\":\"houseplant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13103783\"]}");
	add("{\"term\":\"houseroom\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13800612\"]}");
	add("{\"term\":\"housetop\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03551415\"]}");
	add("{\"term\":\"housewarming\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08272030\"]}");
	add("{\"term\":\"housewife\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10209395\"]}");
	add("{\"term\":\"housewifery\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00581917\"]}");
	add("{\"term\":\"housework\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00581998\"]}");
	add("{\"term\":\"housewrecker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10209594\"]}");
	add("{\"term\":\"housing\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"02958976\", \"03551946\", \"03551520\"]}");
	add("{\"term\":\"housman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11081729\"]}");
	add("{\"term\":\"houston\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11081848\", \"09167588\"]}");
	add("{\"term\":\"houttuynia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13173369\"]}");
	add("{\"term\":\"houyhnhnm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10209850\"]}");
	add("{\"term\":\"houyhnhnms\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05637928\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }