package org.swtk.commons.dict.wordnet.indexbyname.instance.h.o.u;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceHOU {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"houdah\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03552577\"]}");
	add("{\"term\":\"houdini\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11081312\"]}");
	add("{\"term\":\"houghton\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09123582\", \"11081547\"]}");
	add("{\"term\":\"houhere\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12201402\"]}");
	add("{\"term\":\"hoummos\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07873707\"]}");
	add("{\"term\":\"hound\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09905672\", \"02090203\"]}");
	add("{\"term\":\"hound dog\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02090203\"]}");
	add("{\"term\":\"houndstooth check\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03549125\"]}");
	add("{\"term\":\"hour\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"05138288\", \"15253706\", \"15253174\", \"15252642\"]}");
	add("{\"term\":\"hour angle\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13911476\", \"08604064\"]}");
	add("{\"term\":\"hour circle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08604243\"]}");
	add("{\"term\":\"hour hand\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03549418\"]}");
	add("{\"term\":\"hourglass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03549323\"]}");
	add("{\"term\":\"houri\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09568129\", \"10388227\"]}");
	add("{\"term\":\"hours\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"15142458\", \"15143042\"]}");
	add("{\"term\":\"housatonic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09328937\"]}");
	add("{\"term\":\"housatonic river\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09328937\"]}");
	add("{\"term\":\"house\", \"synsetCount\":12, \"upperType\":\"NOUN\", \"ids\":[\"03550330\", \"04424944\", \"08094856\", \"08398027\", \"08703415\", \"00433104\", \"07987896\", \"08179924\", \"08239887\", \"08241501\", \"08076706\", \"03549540\"]}");
	add("{\"term\":\"house agent\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10529403\"]}");
	add("{\"term\":\"house arrest\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01149648\"]}");
	add("{\"term\":\"house cat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02124460\"]}");
	add("{\"term\":\"house centipede\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01788308\"]}");
	add("{\"term\":\"house decorator\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10230422\"]}");
	add("{\"term\":\"house detective\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10207461\"]}");
	add("{\"term\":\"house dick\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10207461\"]}");
	add("{\"term\":\"house finch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01535470\"]}");
	add("{\"term\":\"house fly\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02193442\"]}");
	add("{\"term\":\"house guest\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208091\"]}");
	add("{\"term\":\"house husband\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208195\"]}");
	add("{\"term\":\"house martin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01598615\"]}");
	add("{\"term\":\"house mouse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02334808\"]}");
	add("{\"term\":\"house of burgesses\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08179474\"]}");
	add("{\"term\":\"house of cards\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03550936\", \"05915845\"]}");
	add("{\"term\":\"house of commons\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08179590\"]}");
	add("{\"term\":\"house of correction\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03551141\"]}");
	add("{\"term\":\"house of detention\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03186333\"]}");
	add("{\"term\":\"house of god\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03959692\"]}");
	add("{\"term\":\"house of hanover\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08171859\"]}");
	add("{\"term\":\"house of ill repute\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04588881\"]}");
	add("{\"term\":\"house of islam\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09201378\"]}");
	add("{\"term\":\"house of lancaster\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08172664\"]}");
	add("{\"term\":\"house of lords\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08179759\"]}");
	add("{\"term\":\"house of prayer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03959692\"]}");
	add("{\"term\":\"house of prostitution\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04588881\"]}");
	add("{\"term\":\"house of representatives\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08178870\"]}");
	add("{\"term\":\"house of tudor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08175930\"]}");
	add("{\"term\":\"house of war\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09201493\"]}");
	add("{\"term\":\"house of windsor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08176639\"]}");
	add("{\"term\":\"house of worship\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03959692\"]}");
	add("{\"term\":\"house of york\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08176823\"]}");
	add("{\"term\":\"house organ\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06607424\"]}");
	add("{\"term\":\"house paint\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03551292\"]}");
	add("{\"term\":\"house painter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208798\"]}");
	add("{\"term\":\"house painting\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00610504\"]}");
	add("{\"term\":\"house party\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07464829\"]}");
	add("{\"term\":\"house physician\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208897\"]}");
	add("{\"term\":\"house servant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10043844\"]}");
	add("{\"term\":\"house sitter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10209216\"]}");
	add("{\"term\":\"house snake\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01737449\"]}");
	add("{\"term\":\"house sparrow\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01542566\"]}");
	add("{\"term\":\"house trailer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04474334\"]}");
	add("{\"term\":\"house wren\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01587494\"]}");
	add("{\"term\":\"houseboat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03550650\"]}");
	add("{\"term\":\"housebreaker\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10209594\", \"10207845\"]}");
	add("{\"term\":\"housebreaking\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00786917\"]}");
	add("{\"term\":\"housebuilder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10201287\"]}");
	add("{\"term\":\"housecleaning\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00581407\", \"00581602\"]}");
	add("{\"term\":\"housecoat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03823187\"]}");
	add("{\"term\":\"housecraft\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05651567\"]}");
	add("{\"term\":\"housedog\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02106932\"]}");
	add("{\"term\":\"housefather\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10207988\"]}");
	add("{\"term\":\"housefly\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02193442\"]}");
	add("{\"term\":\"houseful\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13789831\"]}");
	add("{\"term\":\"houseguest\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208091\"]}");
	add("{\"term\":\"household\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08094856\"]}");
	add("{\"term\":\"household appliance\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03533443\"]}");
	add("{\"term\":\"household arts\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06158795\"]}");
	add("{\"term\":\"household linen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04587584\"]}");
	add("{\"term\":\"householder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10202130\"]}");
	add("{\"term\":\"househusband\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208195\"]}");
	add("{\"term\":\"housekeeper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208334\"]}");
	add("{\"term\":\"housekeeping\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00581998\"]}");
	add("{\"term\":\"houselights\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03550765\"]}");
	add("{\"term\":\"housemaid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10302369\"]}");
	add("{\"term\":\"houseman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10230873\"]}");
	add("{\"term\":\"housemaster\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208475\"]}");
	add("{\"term\":\"housemate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208576\"]}");
	add("{\"term\":\"housemother\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10208678\"]}");
	add("{\"term\":\"housepaint\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03551292\"]}");
	add("{\"term\":\"houseplant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13103783\"]}");
	add("{\"term\":\"houseroom\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13800612\"]}");
	add("{\"term\":\"houses of parliament\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08896505\"]}");
	add("{\"term\":\"housetop\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03551415\"]}");
	add("{\"term\":\"housewarming\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08272030\"]}");
	add("{\"term\":\"housewife\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10209395\"]}");
	add("{\"term\":\"housewifery\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00581917\"]}");
	add("{\"term\":\"housework\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00581998\"]}");
	add("{\"term\":\"housewrecker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10209594\"]}");
	add("{\"term\":\"housing\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"02958976\", \"03551946\", \"03551520\"]}");
	add("{\"term\":\"housing and urban development\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08152044\"]}");
	add("{\"term\":\"housing commissioner\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10209741\"]}");
	add("{\"term\":\"housing development\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08567055\"]}");
	add("{\"term\":\"housing estate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08567308\"]}");
	add("{\"term\":\"housing industry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08084519\"]}");
	add("{\"term\":\"housing project\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08567486\"]}");
	add("{\"term\":\"housing start\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00240533\"]}");
	add("{\"term\":\"housman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11081729\"]}");
	add("{\"term\":\"houston\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11081848\", \"09167588\"]}");
	add("{\"term\":\"houttuynia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13173369\"]}");
	add("{\"term\":\"houyhnhnm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10209850\"]}");
	add("{\"term\":\"houyhnhnms\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05637928\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }