package org.swtk.commons.dict.wordnet.index.name.instance.m.e.t.r;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceMETR {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"metralgia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14352371\"]}");
	add("{\"term\":\"metrazol\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03919821\"]}");
	add("{\"term\":\"metre\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04998860\", \"07108759\", \"13681046\"]}");
	add("{\"term\":\"metrestick\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03759005\"]}");
	add("{\"term\":\"metric\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"13598374\", \"13625518\", \"13807118\"]}");
	add("{\"term\":\"metrication\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00195494\"]}");
	add("{\"term\":\"metrics\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06179741\"]}");
	add("{\"term\":\"metrification\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00195494\", \"00933115\"]}");
	add("{\"term\":\"metritis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14373297\"]}");
	add("{\"term\":\"metro\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03762667\"]}");
	add("{\"term\":\"metrology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06145257\"]}");
	add("{\"term\":\"metronidazole\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03762957\"]}");
	add("{\"term\":\"metronome\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03763133\"]}");
	add("{\"term\":\"metronymic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06347519\"]}");
	add("{\"term\":\"metropolis\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08243256\", \"08542298\"]}");
	add("{\"term\":\"metropolitan\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10332804\", \"10332897\"]}");
	add("{\"term\":\"metroptosis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14582393\"]}");
	add("{\"term\":\"metrorrhagia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14394230\"]}");
	add("{\"term\":\"metroxylon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12612284\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }