package org.swtk.commons.dict.wordnet.indexbyname.instance.d.e.b;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceDEB {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"de bakey\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10945990\"]}");
	add("{\"term\":\"de broglie\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10884916\"]}");
	add("{\"term\":\"deb\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10017372\"]}");
	add("{\"term\":\"debacle\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"07491763\", \"11475370\", \"07380032\"]}");
	add("{\"term\":\"debarkation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00058822\"]}");
	add("{\"term\":\"debarment\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01079805\", \"14451395\"]}");
	add("{\"term\":\"debasement\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00272107\", \"14511027\"]}");
	add("{\"term\":\"debaser\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10016750\"]}");
	add("{\"term\":\"debate\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07256764\", \"07155686\"]}");
	add("{\"term\":\"debater\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10016942\"]}");
	add("{\"term\":\"debauch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00512223\"]}");
	add("{\"term\":\"debauchee\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10277344\"]}");
	add("{\"term\":\"debaucher\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10773949\"]}");
	add("{\"term\":\"debauchery\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00512223\"]}");
	add("{\"term\":\"debenture\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06537995\", \"13360859\"]}");
	add("{\"term\":\"debenture bond\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13360859\"]}");
	add("{\"term\":\"debilitation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07345810\"]}");
	add("{\"term\":\"debility\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14571235\"]}");
	add("{\"term\":\"debit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13426980\"]}");
	add("{\"term\":\"debit card\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13397937\"]}");
	add("{\"term\":\"debit entry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13426980\"]}");
	add("{\"term\":\"debit side\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13427682\"]}");
	add("{\"term\":\"debitor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10017160\"]}");
	add("{\"term\":\"debridement\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00671175\"]}");
	add("{\"term\":\"debriefing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07235126\"]}");
	add("{\"term\":\"debris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14882048\"]}");
	add("{\"term\":\"debris storm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07455011\"]}");
	add("{\"term\":\"debris surge\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07455011\"]}");
	add("{\"term\":\"debs\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10946181\"]}");
	add("{\"term\":\"debt\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"06786148\", \"13418347\", \"14514148\"]}");
	add("{\"term\":\"debt ceiling\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13419105\"]}");
	add("{\"term\":\"debt instrument\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13419414\"]}");
	add("{\"term\":\"debt limit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13419105\"]}");
	add("{\"term\":\"debtor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10017160\"]}");
	add("{\"term\":\"debugger\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06586510\"]}");
	add("{\"term\":\"debunking\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00523394\"]}");
	add("{\"term\":\"debussy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10946349\"]}");
	add("{\"term\":\"debut\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07232239\", \"00238889\"]}");
	add("{\"term\":\"debutante\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10017372\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }