package org.swtk.commons.dict.wordnet.indexbyname.instance.e.l.a;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceELA {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"e layer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08600141\"]}");
	add("{\"term\":\"el aaium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08992299\"]}");
	add("{\"term\":\"el alamein\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01280725\", \"08919168\"]}");
	add("{\"term\":\"ela\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08059921\"]}");
	add("{\"term\":\"elaborateness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04705460\", \"04774107\"]}");
	add("{\"term\":\"elaboration\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"00251577\", \"04774107\", \"07187407\", \"07372279\", \"00372295\"]}");
	add("{\"term\":\"elaeagnaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12346014\"]}");
	add("{\"term\":\"elaeagnus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12346184\"]}");
	add("{\"term\":\"elaeagnus augustifolia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12346886\"]}");
	add("{\"term\":\"elaeagnus commutata\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12346695\"]}");
	add("{\"term\":\"elaeagnus latifolia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12346550\"]}");
	add("{\"term\":\"elaeis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12610878\"]}");
	add("{\"term\":\"elaeis guineensis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12611260\"]}");
	add("{\"term\":\"elaeis oleifera\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12611361\"]}");
	add("{\"term\":\"elaeocarpaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12212890\"]}");
	add("{\"term\":\"elaeocarpus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12213239\"]}");
	add("{\"term\":\"elaeocarpus family\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12212890\"]}");
	add("{\"term\":\"elaeocarpus grandis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12213394\"]}");
	add("{\"term\":\"elaeostearic acid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14871980\"]}");
	add("{\"term\":\"elagatis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02579922\"]}");
	add("{\"term\":\"elagatis bipinnulata\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02580034\"]}");
	add("{\"term\":\"elaidic acid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14864512\"]}");
	add("{\"term\":\"elam\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08933015\"]}");
	add("{\"term\":\"elamite\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06981128\", \"09661694\"]}");
	add("{\"term\":\"elamitic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06981128\"]}");
	add("{\"term\":\"elan\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04640927\", \"04820120\", \"07570967\"]}");
	add("{\"term\":\"elan vital\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11544272\"]}");
	add("{\"term\":\"eland\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02429459\"]}");
	add("{\"term\":\"elanoides\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01611575\"]}");
	add("{\"term\":\"elanoides forficatus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01611703\"]}");
	add("{\"term\":\"elanus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01611877\"]}");
	add("{\"term\":\"elanus leucurus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01612032\"]}");
	add("{\"term\":\"elaphe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01735086\"]}");
	add("{\"term\":\"elaphe guttata\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01735255\"]}");
	add("{\"term\":\"elaphe obsoleta\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01735430\"]}");
	add("{\"term\":\"elaphure\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02438148\"]}");
	add("{\"term\":\"elaphurus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02438017\"]}");
	add("{\"term\":\"elaphurus davidianus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02438148\"]}");
	add("{\"term\":\"elapid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01747766\"]}");
	add("{\"term\":\"elapid snake\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01747766\"]}");
	add("{\"term\":\"elapidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01747298\"]}");
	add("{\"term\":\"elapsed time\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15156075\"]}");
	add("{\"term\":\"elasmobranch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01484712\"]}");
	add("{\"term\":\"elasmobranchii\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01484240\"]}");
	add("{\"term\":\"elastance\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11453812\"]}");
	add("{\"term\":\"elastance unit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13655057\"]}");
	add("{\"term\":\"elastase\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14873710\"]}");
	add("{\"term\":\"elastic\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03272607\", \"04123192\"]}");
	add("{\"term\":\"elastic band\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04123192\"]}");
	add("{\"term\":\"elastic bandage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03272732\"]}");
	add("{\"term\":\"elastic device\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03272883\"]}");
	add("{\"term\":\"elastic energy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11469172\"]}");
	add("{\"term\":\"elastic modulus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13609166\"]}");
	add("{\"term\":\"elastic potential energy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11469172\"]}");
	add("{\"term\":\"elastic tissue\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05294867\"]}");
	add("{\"term\":\"elasticity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05027524\"]}");
	add("{\"term\":\"elasticity of shear\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05028906\"]}");
	add("{\"term\":\"elastin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05295230\"]}");
	add("{\"term\":\"elastomer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14864753\"]}");
	add("{\"term\":\"elastoplast\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03273053\"]}");
	add("{\"term\":\"elastosis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14058984\"]}");
	add("{\"term\":\"elater\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02178913\"]}");
	add("{\"term\":\"elaterid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02178913\"]}");
	add("{\"term\":\"elaterid beetle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02178913\"]}");
	add("{\"term\":\"elateridae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02178725\"]}");
	add("{\"term\":\"elation\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07543044\", \"14428629\"]}");
	add("{\"term\":\"elavil\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02705434\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }