package org.swtk.commons.dict.wordnet.index.name.instance.s.i.m.p;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceSIMP {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"simper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06891040\"]}");
	add("{\"term\":\"simperer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10618623\"]}");
	add("{\"term\":\"simple\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10618762\", \"12233207\"]}");
	add("{\"term\":\"simpleness\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"04704790\", \"04715389\", \"04773314\", \"04888564\"]}");
	add("{\"term\":\"simpleton\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10618762\"]}");
	add("{\"term\":\"simplicity\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"04704790\", \"04715389\", \"04793718\", \"04888564\", \"04773314\"]}");
	add("{\"term\":\"simplification\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"00193149\", \"01214378\", \"06751929\"]}");
	add("{\"term\":\"simplism\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01214527\", \"06752094\"]}");
	add("{\"term\":\"simpson\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11321592\", \"11321804\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }