package org.swtk.commons.dict.wordnet.index.name.instance.m.i.c.h;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceMICH {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"michael\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09562628\"]}");
	add("{\"term\":\"michaelmas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15211247\"]}");
	add("{\"term\":\"michaelmastide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15211431\"]}");
	add("{\"term\":\"micheas\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06451772\", \"11198049\"]}");
	add("{\"term\":\"michelangelo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11198151\"]}");
	add("{\"term\":\"michelson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11198383\"]}");
	add("{\"term\":\"michener\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11198621\"]}");
	add("{\"term\":\"michigan\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"00494319\", \"09354956\", \"09122118\"]}");
	add("{\"term\":\"michigander\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09763021\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }