package org.swtk.commons.dict.wordnet.indexbyname.instance.t.i.t;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceTIT {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"tit\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"01594338\", \"05562286\", \"05562038\"]}");
	add("{\"term\":\"tit for tat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01239645\"]}");
	add("{\"term\":\"titan\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"09482399\", \"09595603\", \"09958449\"]}");
	add("{\"term\":\"titan arum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11803957\"]}");
	add("{\"term\":\"titaness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09596003\"]}");
	add("{\"term\":\"titania\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09569582\", \"14640918\"]}");
	add("{\"term\":\"titanic acid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14640798\"]}");
	add("{\"term\":\"titanic oxide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14640918\"]}");
	add("{\"term\":\"titanium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14683390\"]}");
	add("{\"term\":\"titanium dioxide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14640918\"]}");
	add("{\"term\":\"titanium oxide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14640918\"]}");
	add("{\"term\":\"titanosaur\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01713388\"]}");
	add("{\"term\":\"titanosaurian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01713388\"]}");
	add("{\"term\":\"titanosauridae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01712989\"]}");
	add("{\"term\":\"titanosaurus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01713170\"]}");
	add("{\"term\":\"titbit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07610308\"]}");
	add("{\"term\":\"titer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05045978\"]}");
	add("{\"term\":\"titfer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04448662\"]}");
	add("{\"term\":\"tithe\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13291568\", \"13336765\"]}");
	add("{\"term\":\"tithe barn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04448796\"]}");
	add("{\"term\":\"tither\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10732661\"]}");
	add("{\"term\":\"tithonia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12046487\"]}");
	add("{\"term\":\"titi\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"02496140\", \"12262926\", \"12771932\"]}");
	add("{\"term\":\"titi family\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12771066\"]}");
	add("{\"term\":\"titi monkey\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02496140\"]}");
	add("{\"term\":\"titian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11363502\"]}");
	add("{\"term\":\"titillation\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"00145265\", \"01264838\", \"07544364\"]}");
	add("{\"term\":\"titivation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00264335\"]}");
	add("{\"term\":\"titlark\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01531295\"]}");
	add("{\"term\":\"title\", \"synsetCount\":10, \"upperType\":\"NOUN\", \"ids\":[\"05183431\", \"06354487\", \"06357590\", \"05188726\", \"06350786\", \"06557128\", \"13972130\", \"06357831\", \"06354890\", \"06357363\"]}");
	add("{\"term\":\"title bar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07288321\"]}");
	add("{\"term\":\"title deed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06558252\"]}");
	add("{\"term\":\"title of respect\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06350786\"]}");
	add("{\"term\":\"title page\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06268230\"]}");
	add("{\"term\":\"title role\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05938673\"]}");
	add("{\"term\":\"titmouse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01594338\"]}");
	add("{\"term\":\"tito\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11363620\"]}");
	add("{\"term\":\"titration\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00649480\"]}");
	add("{\"term\":\"titrator\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04448924\"]}");
	add("{\"term\":\"titre\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05045978\"]}");
	add("{\"term\":\"titter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07142933\"]}");
	add("{\"term\":\"titterer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10732773\"]}");
	add("{\"term\":\"tittivation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00264335\"]}");
	add("{\"term\":\"tittle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13795925\"]}");
	add("{\"term\":\"titty\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05562038\"]}");
	add("{\"term\":\"titus\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"06457659\", \"11363842\", \"11363993\"]}");
	add("{\"term\":\"titus flavius domitianus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10958813\"]}");
	add("{\"term\":\"titus flavius sabinus vespasianus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11384794\"]}");
	add("{\"term\":\"titus flavius vespasianus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11363842\"]}");
	add("{\"term\":\"titus livius\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11155981\"]}");
	add("{\"term\":\"titus lucretius carus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11164058\"]}");
	add("{\"term\":\"titus maccius plautus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11259433\"]}");
	add("{\"term\":\"titus oates\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11231061\"]}");
	add("{\"term\":\"titus vespasianus augustus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11363842\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }