package org.swtk.commons.dict.wordnet.indexbyname.instance.c.l.u;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceCLU {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"club\", \"synsetCount\":7, \"upperType\":\"NOUN\", \"ids\":[\"02934801\", \"03057773\", \"03451003\", \"03058296\", \"03057459\", \"08244135\", \"08096490\"]}");
	add("{\"term\":\"club car\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03057961\"]}");
	add("{\"term\":\"club drug\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03058083\"]}");
	add("{\"term\":\"club fungus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13006533\"]}");
	add("{\"term\":\"club head\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03451212\"]}");
	add("{\"term\":\"club member\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10328061\"]}");
	add("{\"term\":\"club moss\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13242427\"]}");
	add("{\"term\":\"club sandwich\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07712584\"]}");
	add("{\"term\":\"club soda\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07952788\"]}");
	add("{\"term\":\"club steak\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07676208\"]}");
	add("{\"term\":\"clubbing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14326367\"]}");
	add("{\"term\":\"clubfoot\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14238066\"]}");
	add("{\"term\":\"clubhead\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03451212\"]}");
	add("{\"term\":\"clubhouse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03058296\"]}");
	add("{\"term\":\"clubmoss family\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13243375\"]}");
	add("{\"term\":\"clubroom\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03058476\"]}");
	add("{\"term\":\"clubroot fungus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13004414\"]}");
	add("{\"term\":\"cluck\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07395700\"]}");
	add("{\"term\":\"clucking\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07395700\"]}");
	add("{\"term\":\"clue\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06656526\", \"06815643\"]}");
	add("{\"term\":\"clumber\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02104208\"]}");
	add("{\"term\":\"clumber spaniel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02104208\"]}");
	add("{\"term\":\"clump\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"07411545\", \"07977630\", \"07976557\"]}");
	add("{\"term\":\"clumping\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07395534\"]}");
	add("{\"term\":\"clumsiness\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04822855\", \"05011459\", \"05656304\"]}");
	add("{\"term\":\"clumsy person\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09950725\"]}");
	add("{\"term\":\"clunch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14838701\"]}");
	add("{\"term\":\"clunk\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07411545\"]}");
	add("{\"term\":\"clunking\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07395534\"]}");
	add("{\"term\":\"clupea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02534451\"]}");
	add("{\"term\":\"clupea harangus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02534659\"]}");
	add("{\"term\":\"clupea harengus harengus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02534903\"]}");
	add("{\"term\":\"clupea harengus pallasii\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02535082\"]}");
	add("{\"term\":\"clupea sprattus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02535549\"]}");
	add("{\"term\":\"clupeid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02532403\"]}");
	add("{\"term\":\"clupeid fish\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02532403\"]}");
	add("{\"term\":\"clupeidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02532146\"]}");
	add("{\"term\":\"clusia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12386417\"]}");
	add("{\"term\":\"clusia flava\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12386570\"]}");
	add("{\"term\":\"clusia insignis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12386703\"]}");
	add("{\"term\":\"clusia major\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12386830\"]}");
	add("{\"term\":\"clusia rosea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12386830\"]}");
	add("{\"term\":\"clusiaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12384505\"]}");
	add("{\"term\":\"cluster\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07976557\"]}");
	add("{\"term\":\"cluster bean\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12540911\"]}");
	add("{\"term\":\"cluster bomb\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03058590\"]}");
	add("{\"term\":\"cluster bomblet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02871580\"]}");
	add("{\"term\":\"cluster headache\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14350948\"]}");
	add("{\"term\":\"clustered bellflower\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12058875\"]}");
	add("{\"term\":\"clustered poppy mallow\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12196115\"]}");
	add("{\"term\":\"clustering\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07976557\"]}");
	add("{\"term\":\"clutch\", \"synsetCount\":7, \"upperType\":\"NOUN\", \"ids\":[\"03058886\", \"03059144\", \"03059403\", \"08417409\", \"08417827\", \"14056219\", \"00814187\"]}");
	add("{\"term\":\"clutch bag\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03059403\"]}");
	add("{\"term\":\"clutch pedal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03059144\"]}");
	add("{\"term\":\"clutches\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00814187\"]}");
	add("{\"term\":\"clutter\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07278413\", \"14524151\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }