package org.swtk.commons.dict.wordnet.index.name.controller.t.s;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.a.r.WordnetNounIndexNameInstanceTSAR;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.a.t.WordnetNounIndexNameInstanceTSAT;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.e.t.WordnetNounIndexNameInstanceTSET;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.h.a.WordnetNounIndexNameInstanceTSHA;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.h.i.WordnetNounIndexNameInstanceTSHI;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.i.m.WordnetNounIndexNameInstanceTSIM;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.i.n.WordnetNounIndexNameInstanceTSIN;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.o.r.WordnetNounIndexNameInstanceTSOR;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.o.u.WordnetNounIndexNameInstanceTSOU;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.u.g.WordnetNounIndexNameInstanceTSUG;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.u.n.WordnetNounIndexNameInstanceTSUN;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.u.r.WordnetNounIndexNameInstanceTSUR;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.u.s.WordnetNounIndexNameInstanceTSUS;
	import org.swtk.commons.dict.wordnet.index.name.instance.t.s.w.a.WordnetNounIndexNameInstanceTSWA;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerTS {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("tsar".equals(key)) return WordnetNounIndexNameInstanceTSAR.get(TERM);
	if ("tsat".equals(key)) return WordnetNounIndexNameInstanceTSAT.get(TERM);
	if ("tset".equals(key)) return WordnetNounIndexNameInstanceTSET.get(TERM);
	if ("tsha".equals(key)) return WordnetNounIndexNameInstanceTSHA.get(TERM);
	if ("tshi".equals(key)) return WordnetNounIndexNameInstanceTSHI.get(TERM);
	if ("tsim".equals(key)) return WordnetNounIndexNameInstanceTSIM.get(TERM);
	if ("tsin".equals(key)) return WordnetNounIndexNameInstanceTSIN.get(TERM);
	if ("tsor".equals(key)) return WordnetNounIndexNameInstanceTSOR.get(TERM);
	if ("tsou".equals(key)) return WordnetNounIndexNameInstanceTSOU.get(TERM);
	if ("tsug".equals(key)) return WordnetNounIndexNameInstanceTSUG.get(TERM);
	if ("tsun".equals(key)) return WordnetNounIndexNameInstanceTSUN.get(TERM);
	if ("tsur".equals(key)) return WordnetNounIndexNameInstanceTSUR.get(TERM);
	if ("tsus".equals(key)) return WordnetNounIndexNameInstanceTSUS.get(TERM);
	if ("tswa".equals(key)) return WordnetNounIndexNameInstanceTSWA.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceTSAR.terms());
	set.addAll(WordnetNounIndexNameInstanceTSAT.terms());
	set.addAll(WordnetNounIndexNameInstanceTSET.terms());
	set.addAll(WordnetNounIndexNameInstanceTSHA.terms());
	set.addAll(WordnetNounIndexNameInstanceTSHI.terms());
	set.addAll(WordnetNounIndexNameInstanceTSIM.terms());
	set.addAll(WordnetNounIndexNameInstanceTSIN.terms());
	set.addAll(WordnetNounIndexNameInstanceTSOR.terms());
	set.addAll(WordnetNounIndexNameInstanceTSOU.terms());
	set.addAll(WordnetNounIndexNameInstanceTSUG.terms());
	set.addAll(WordnetNounIndexNameInstanceTSUN.terms());
	set.addAll(WordnetNounIndexNameInstanceTSUR.terms());
	set.addAll(WordnetNounIndexNameInstanceTSUS.terms());
	set.addAll(WordnetNounIndexNameInstanceTSWA.terms());
  		return set; 	} }