package org.swtk.commons.dict.wordnet.indexbyname.instance.l.i.t;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceLIT {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"lit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06179204\"]}");
	add("{\"term\":\"litany\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06469112\", \"07255423\"]}");
	add("{\"term\":\"litas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13723720\"]}");
	add("{\"term\":\"litchee\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07782149\"]}");
	add("{\"term\":\"litchi\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07782149\", \"12765147\"]}");
	add("{\"term\":\"liter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13645547\"]}");
	add("{\"term\":\"literacy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05646331\"]}");
	add("{\"term\":\"literal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06782461\"]}");
	add("{\"term\":\"literalism\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06209628\", \"05973189\"]}");
	add("{\"term\":\"literalness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04767866\"]}");
	add("{\"term\":\"literate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10286025\"]}");
	add("{\"term\":\"literati\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08404334\"]}");
	add("{\"term\":\"literature\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"00611860\", \"06376547\", \"06179204\", \"06376048\"]}");
	add("{\"term\":\"lithane\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14966022\"]}");
	add("{\"term\":\"litheness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05011256\"]}");
	add("{\"term\":\"lithiasis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14139396\"]}");
	add("{\"term\":\"lithium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14667971\"]}");
	add("{\"term\":\"lithocarpus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12285783\"]}");
	add("{\"term\":\"lithodidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01983634\"]}");
	add("{\"term\":\"lithoglyptics\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03447411\"]}");
	add("{\"term\":\"lithograph\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03683302\", \"03683546\"]}");
	add("{\"term\":\"lithographer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10286183\"]}");
	add("{\"term\":\"lithography\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00941154\", \"06692747\"]}");
	add("{\"term\":\"lithology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06130982\"]}");
	add("{\"term\":\"lithomancer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10286441\"]}");
	add("{\"term\":\"lithomancy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05785295\"]}");
	add("{\"term\":\"lithonate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14966022\"]}");
	add("{\"term\":\"lithophragma\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12820340\"]}");
	add("{\"term\":\"lithophyte\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13144600\"]}");
	add("{\"term\":\"lithops\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11840932\"]}");
	add("{\"term\":\"lithospermum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12841194\"]}");
	add("{\"term\":\"lithosphere\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09362716\"]}");
	add("{\"term\":\"lithotomy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00684611\"]}");
	add("{\"term\":\"lithuania\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09036200\"]}");
	add("{\"term\":\"lithuanian\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06958961\", \"09726685\"]}");
	add("{\"term\":\"lithuresis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13530153\"]}");
	add("{\"term\":\"litigant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10286545\"]}");
	add("{\"term\":\"litigation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01189300\"]}");
	add("{\"term\":\"litigator\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10286545\"]}");
	add("{\"term\":\"litigiousness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04651663\"]}");
	add("{\"term\":\"litmus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14965545\"]}");
	add("{\"term\":\"litocranius\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02423321\"]}");
	add("{\"term\":\"litoral\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08613632\"]}");
	add("{\"term\":\"litotes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07118958\"]}");
	add("{\"term\":\"litre\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13645547\"]}");
	add("{\"term\":\"litter\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"02823567\", \"03683688\", \"14882443\", \"08417288\"]}");
	add("{\"term\":\"litterateur\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10084212\"]}");
	add("{\"term\":\"litterbin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03683884\"]}");
	add("{\"term\":\"litterbug\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10286863\"]}");
	add("{\"term\":\"litterer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10286863\"]}");
	add("{\"term\":\"little\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13784857\"]}");
	add("{\"term\":\"littleneck\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01960987\", \"07803084\"]}");
	add("{\"term\":\"littleness\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04841304\", \"05038522\", \"05113933\"]}");
	add("{\"term\":\"littoral\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08613632\"]}");
	add("{\"term\":\"littorina\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01950925\"]}");
	add("{\"term\":\"littorinidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01950795\"]}");
	add("{\"term\":\"littre\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11155361\"]}");
	add("{\"term\":\"liturgics\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06193368\"]}");
	add("{\"term\":\"liturgiology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06193368\"]}");
	add("{\"term\":\"liturgist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10287638\"]}");
	add("{\"term\":\"liturgy\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01035216\", \"01037885\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }