package org.swtk.commons.dict.wordnet.index.name.controller.a.d;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.a.c.WordnetNounIndexNameInstanceADAC;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.a.d.WordnetNounIndexNameInstanceADAD;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.a.g.WordnetNounIndexNameInstanceADAG;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.a.l.WordnetNounIndexNameInstanceADAL;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.a.m.WordnetNounIndexNameInstanceADAM;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.a.n.WordnetNounIndexNameInstanceADAN;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.a.p.WordnetNounIndexNameInstanceADAP;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.a.r.WordnetNounIndexNameInstanceADAR;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.d.a.WordnetNounIndexNameInstanceADDA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.d.e.WordnetNounIndexNameInstanceADDE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.d.i.WordnetNounIndexNameInstanceADDI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.d.l.WordnetNounIndexNameInstanceADDL;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.d.r.WordnetNounIndexNameInstanceADDR;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.d.u.WordnetNounIndexNameInstanceADDU;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.e.l.WordnetNounIndexNameInstanceADEL;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.e.n.WordnetNounIndexNameInstanceADEN;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.e.p.WordnetNounIndexNameInstanceADEP;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.e.q.WordnetNounIndexNameInstanceADEQ;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.e.r.WordnetNounIndexNameInstanceADER;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.e.s.WordnetNounIndexNameInstanceADES;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.h.d.WordnetNounIndexNameInstanceADHD;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.h.e.WordnetNounIndexNameInstanceADHE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.h.o.WordnetNounIndexNameInstanceADHO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.i.a.WordnetNounIndexNameInstanceADIA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.i.e.WordnetNounIndexNameInstanceADIE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.i.g.WordnetNounIndexNameInstanceADIG;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.i.o.WordnetNounIndexNameInstanceADIO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.i.p.WordnetNounIndexNameInstanceADIP;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.i.r.WordnetNounIndexNameInstanceADIR;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.i.t.WordnetNounIndexNameInstanceADIT;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.j.a.WordnetNounIndexNameInstanceADJA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.j.e.WordnetNounIndexNameInstanceADJE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.j.o.WordnetNounIndexNameInstanceADJO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.j.u.WordnetNounIndexNameInstanceADJU;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.l.u.WordnetNounIndexNameInstanceADLU;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.m.a.WordnetNounIndexNameInstanceADMA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.m.i.WordnetNounIndexNameInstanceADMI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.m.o.WordnetNounIndexNameInstanceADMO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.n.e.WordnetNounIndexNameInstanceADNE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.n.o.WordnetNounIndexNameInstanceADNO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.o.b.WordnetNounIndexNameInstanceADOB;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.o.l.WordnetNounIndexNameInstanceADOL;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.o.n.WordnetNounIndexNameInstanceADON;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.o.p.WordnetNounIndexNameInstanceADOP;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.o.r.WordnetNounIndexNameInstanceADOR;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.o.x.WordnetNounIndexNameInstanceADOX;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.p.s.WordnetNounIndexNameInstanceADPS;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.r.e.WordnetNounIndexNameInstanceADRE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.r.i.WordnetNounIndexNameInstanceADRI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.r.o.WordnetNounIndexNameInstanceADRO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.s.o.WordnetNounIndexNameInstanceADSO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.u.l.WordnetNounIndexNameInstanceADUL;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.u.m.WordnetNounIndexNameInstanceADUM;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.v.a.WordnetNounIndexNameInstanceADVA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.v.e.WordnetNounIndexNameInstanceADVE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.v.i.WordnetNounIndexNameInstanceADVI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.v.o.WordnetNounIndexNameInstanceADVO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.y.n.WordnetNounIndexNameInstanceADYN;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.z.e.WordnetNounIndexNameInstanceADZE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.d.z.h.WordnetNounIndexNameInstanceADZH;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerAD {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("adac".equals(key)) return WordnetNounIndexNameInstanceADAC.get(TERM);
	if ("adad".equals(key)) return WordnetNounIndexNameInstanceADAD.get(TERM);
	if ("adag".equals(key)) return WordnetNounIndexNameInstanceADAG.get(TERM);
	if ("adal".equals(key)) return WordnetNounIndexNameInstanceADAL.get(TERM);
	if ("adam".equals(key)) return WordnetNounIndexNameInstanceADAM.get(TERM);
	if ("adan".equals(key)) return WordnetNounIndexNameInstanceADAN.get(TERM);
	if ("adap".equals(key)) return WordnetNounIndexNameInstanceADAP.get(TERM);
	if ("adar".equals(key)) return WordnetNounIndexNameInstanceADAR.get(TERM);
	if ("adda".equals(key)) return WordnetNounIndexNameInstanceADDA.get(TERM);
	if ("adde".equals(key)) return WordnetNounIndexNameInstanceADDE.get(TERM);
	if ("addi".equals(key)) return WordnetNounIndexNameInstanceADDI.get(TERM);
	if ("addl".equals(key)) return WordnetNounIndexNameInstanceADDL.get(TERM);
	if ("addr".equals(key)) return WordnetNounIndexNameInstanceADDR.get(TERM);
	if ("addu".equals(key)) return WordnetNounIndexNameInstanceADDU.get(TERM);
	if ("adel".equals(key)) return WordnetNounIndexNameInstanceADEL.get(TERM);
	if ("aden".equals(key)) return WordnetNounIndexNameInstanceADEN.get(TERM);
	if ("adep".equals(key)) return WordnetNounIndexNameInstanceADEP.get(TERM);
	if ("adeq".equals(key)) return WordnetNounIndexNameInstanceADEQ.get(TERM);
	if ("ader".equals(key)) return WordnetNounIndexNameInstanceADER.get(TERM);
	if ("ades".equals(key)) return WordnetNounIndexNameInstanceADES.get(TERM);
	if ("adhd".equals(key)) return WordnetNounIndexNameInstanceADHD.get(TERM);
	if ("adhe".equals(key)) return WordnetNounIndexNameInstanceADHE.get(TERM);
	if ("adho".equals(key)) return WordnetNounIndexNameInstanceADHO.get(TERM);
	if ("adia".equals(key)) return WordnetNounIndexNameInstanceADIA.get(TERM);
	if ("adie".equals(key)) return WordnetNounIndexNameInstanceADIE.get(TERM);
	if ("adig".equals(key)) return WordnetNounIndexNameInstanceADIG.get(TERM);
	if ("adio".equals(key)) return WordnetNounIndexNameInstanceADIO.get(TERM);
	if ("adip".equals(key)) return WordnetNounIndexNameInstanceADIP.get(TERM);
	if ("adir".equals(key)) return WordnetNounIndexNameInstanceADIR.get(TERM);
	if ("adit".equals(key)) return WordnetNounIndexNameInstanceADIT.get(TERM);
	if ("adja".equals(key)) return WordnetNounIndexNameInstanceADJA.get(TERM);
	if ("adje".equals(key)) return WordnetNounIndexNameInstanceADJE.get(TERM);
	if ("adjo".equals(key)) return WordnetNounIndexNameInstanceADJO.get(TERM);
	if ("adju".equals(key)) return WordnetNounIndexNameInstanceADJU.get(TERM);
	if ("adlu".equals(key)) return WordnetNounIndexNameInstanceADLU.get(TERM);
	if ("adma".equals(key)) return WordnetNounIndexNameInstanceADMA.get(TERM);
	if ("admi".equals(key)) return WordnetNounIndexNameInstanceADMI.get(TERM);
	if ("admo".equals(key)) return WordnetNounIndexNameInstanceADMO.get(TERM);
	if ("adne".equals(key)) return WordnetNounIndexNameInstanceADNE.get(TERM);
	if ("adno".equals(key)) return WordnetNounIndexNameInstanceADNO.get(TERM);
	if ("adob".equals(key)) return WordnetNounIndexNameInstanceADOB.get(TERM);
	if ("adol".equals(key)) return WordnetNounIndexNameInstanceADOL.get(TERM);
	if ("adon".equals(key)) return WordnetNounIndexNameInstanceADON.get(TERM);
	if ("adop".equals(key)) return WordnetNounIndexNameInstanceADOP.get(TERM);
	if ("ador".equals(key)) return WordnetNounIndexNameInstanceADOR.get(TERM);
	if ("adox".equals(key)) return WordnetNounIndexNameInstanceADOX.get(TERM);
	if ("adps".equals(key)) return WordnetNounIndexNameInstanceADPS.get(TERM);
	if ("adre".equals(key)) return WordnetNounIndexNameInstanceADRE.get(TERM);
	if ("adri".equals(key)) return WordnetNounIndexNameInstanceADRI.get(TERM);
	if ("adro".equals(key)) return WordnetNounIndexNameInstanceADRO.get(TERM);
	if ("adso".equals(key)) return WordnetNounIndexNameInstanceADSO.get(TERM);
	if ("adul".equals(key)) return WordnetNounIndexNameInstanceADUL.get(TERM);
	if ("adum".equals(key)) return WordnetNounIndexNameInstanceADUM.get(TERM);
	if ("adva".equals(key)) return WordnetNounIndexNameInstanceADVA.get(TERM);
	if ("adve".equals(key)) return WordnetNounIndexNameInstanceADVE.get(TERM);
	if ("advi".equals(key)) return WordnetNounIndexNameInstanceADVI.get(TERM);
	if ("advo".equals(key)) return WordnetNounIndexNameInstanceADVO.get(TERM);
	if ("adyn".equals(key)) return WordnetNounIndexNameInstanceADYN.get(TERM);
	if ("adze".equals(key)) return WordnetNounIndexNameInstanceADZE.get(TERM);
	if ("adzh".equals(key)) return WordnetNounIndexNameInstanceADZH.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceADAC.terms());
	set.addAll(WordnetNounIndexNameInstanceADAD.terms());
	set.addAll(WordnetNounIndexNameInstanceADAG.terms());
	set.addAll(WordnetNounIndexNameInstanceADAL.terms());
	set.addAll(WordnetNounIndexNameInstanceADAM.terms());
	set.addAll(WordnetNounIndexNameInstanceADAN.terms());
	set.addAll(WordnetNounIndexNameInstanceADAP.terms());
	set.addAll(WordnetNounIndexNameInstanceADAR.terms());
	set.addAll(WordnetNounIndexNameInstanceADDA.terms());
	set.addAll(WordnetNounIndexNameInstanceADDE.terms());
	set.addAll(WordnetNounIndexNameInstanceADDI.terms());
	set.addAll(WordnetNounIndexNameInstanceADDL.terms());
	set.addAll(WordnetNounIndexNameInstanceADDR.terms());
	set.addAll(WordnetNounIndexNameInstanceADDU.terms());
	set.addAll(WordnetNounIndexNameInstanceADEL.terms());
	set.addAll(WordnetNounIndexNameInstanceADEN.terms());
	set.addAll(WordnetNounIndexNameInstanceADEP.terms());
	set.addAll(WordnetNounIndexNameInstanceADEQ.terms());
	set.addAll(WordnetNounIndexNameInstanceADER.terms());
	set.addAll(WordnetNounIndexNameInstanceADES.terms());
	set.addAll(WordnetNounIndexNameInstanceADHD.terms());
	set.addAll(WordnetNounIndexNameInstanceADHE.terms());
	set.addAll(WordnetNounIndexNameInstanceADHO.terms());
	set.addAll(WordnetNounIndexNameInstanceADIA.terms());
	set.addAll(WordnetNounIndexNameInstanceADIE.terms());
	set.addAll(WordnetNounIndexNameInstanceADIG.terms());
	set.addAll(WordnetNounIndexNameInstanceADIO.terms());
	set.addAll(WordnetNounIndexNameInstanceADIP.terms());
	set.addAll(WordnetNounIndexNameInstanceADIR.terms());
	set.addAll(WordnetNounIndexNameInstanceADIT.terms());
	set.addAll(WordnetNounIndexNameInstanceADJA.terms());
	set.addAll(WordnetNounIndexNameInstanceADJE.terms());
	set.addAll(WordnetNounIndexNameInstanceADJO.terms());
	set.addAll(WordnetNounIndexNameInstanceADJU.terms());
	set.addAll(WordnetNounIndexNameInstanceADLU.terms());
	set.addAll(WordnetNounIndexNameInstanceADMA.terms());
	set.addAll(WordnetNounIndexNameInstanceADMI.terms());
	set.addAll(WordnetNounIndexNameInstanceADMO.terms());
	set.addAll(WordnetNounIndexNameInstanceADNE.terms());
	set.addAll(WordnetNounIndexNameInstanceADNO.terms());
	set.addAll(WordnetNounIndexNameInstanceADOB.terms());
	set.addAll(WordnetNounIndexNameInstanceADOL.terms());
	set.addAll(WordnetNounIndexNameInstanceADON.terms());
	set.addAll(WordnetNounIndexNameInstanceADOP.terms());
	set.addAll(WordnetNounIndexNameInstanceADOR.terms());
	set.addAll(WordnetNounIndexNameInstanceADOX.terms());
	set.addAll(WordnetNounIndexNameInstanceADPS.terms());
	set.addAll(WordnetNounIndexNameInstanceADRE.terms());
	set.addAll(WordnetNounIndexNameInstanceADRI.terms());
	set.addAll(WordnetNounIndexNameInstanceADRO.terms());
	set.addAll(WordnetNounIndexNameInstanceADSO.terms());
	set.addAll(WordnetNounIndexNameInstanceADUL.terms());
	set.addAll(WordnetNounIndexNameInstanceADUM.terms());
	set.addAll(WordnetNounIndexNameInstanceADVA.terms());
	set.addAll(WordnetNounIndexNameInstanceADVE.terms());
	set.addAll(WordnetNounIndexNameInstanceADVI.terms());
	set.addAll(WordnetNounIndexNameInstanceADVO.terms());
	set.addAll(WordnetNounIndexNameInstanceADYN.terms());
	set.addAll(WordnetNounIndexNameInstanceADZE.terms());
	set.addAll(WordnetNounIndexNameInstanceADZH.terms());
  		return set; 	} }