package org.swtk.commons.dict.wordnet.index.name.controller.p.i;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.a.f.WordnetNounIndexNameInstancePIAF;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.a.g.WordnetNounIndexNameInstancePIAG;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.a.n.WordnetNounIndexNameInstancePIAN;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.a.s.WordnetNounIndexNameInstancePIAS;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.a.z.WordnetNounIndexNameInstancePIAZ;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.b.g.WordnetNounIndexNameInstancePIBG;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.b.i.WordnetNounIndexNameInstancePIBI;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.b.r.WordnetNounIndexNameInstancePIBR;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.c.a.WordnetNounIndexNameInstancePICA;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.c.c.WordnetNounIndexNameInstancePICC;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.c.e.WordnetNounIndexNameInstancePICE;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.c.h.WordnetNounIndexNameInstancePICH;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.c.i.WordnetNounIndexNameInstancePICI;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.c.k.WordnetNounIndexNameInstancePICK;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.c.n.WordnetNounIndexNameInstancePICN;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.c.o.WordnetNounIndexNameInstancePICO;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.c.r.WordnetNounIndexNameInstancePICR;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.c.t.WordnetNounIndexNameInstancePICT;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.c.u.WordnetNounIndexNameInstancePICU;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.d.d.WordnetNounIndexNameInstancePIDD;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.d.g.WordnetNounIndexNameInstancePIDG;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.d.l.WordnetNounIndexNameInstancePIDL;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.e.c.WordnetNounIndexNameInstancePIEC;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.e.d.WordnetNounIndexNameInstancePIED;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.e.m.WordnetNounIndexNameInstancePIEM;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.e.p.WordnetNounIndexNameInstancePIEP;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.e.r.WordnetNounIndexNameInstancePIER;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.e.t.WordnetNounIndexNameInstancePIET;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.e.z.WordnetNounIndexNameInstancePIEZ;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.f.f.WordnetNounIndexNameInstancePIFF;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.g.b.WordnetNounIndexNameInstancePIGB;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.g.e.WordnetNounIndexNameInstancePIGE;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.g.f.WordnetNounIndexNameInstancePIGF;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.g.g.WordnetNounIndexNameInstancePIGG;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.g.h.WordnetNounIndexNameInstancePIGH;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.g.l.WordnetNounIndexNameInstancePIGL;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.g.m.WordnetNounIndexNameInstancePIGM;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.g.n.WordnetNounIndexNameInstancePIGN;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.g.p.WordnetNounIndexNameInstancePIGP;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.g.s.WordnetNounIndexNameInstancePIGS;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.g.t.WordnetNounIndexNameInstancePIGT;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.g.w.WordnetNounIndexNameInstancePIGW;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.k.a.WordnetNounIndexNameInstancePIKA;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.k.e.WordnetNounIndexNameInstancePIKE;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.l.a.WordnetNounIndexNameInstancePILA;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.l.c.WordnetNounIndexNameInstancePILC;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.l.e.WordnetNounIndexNameInstancePILE;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.l.f.WordnetNounIndexNameInstancePILF;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.l.g.WordnetNounIndexNameInstancePILG;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.l.i.WordnetNounIndexNameInstancePILI;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.l.l.WordnetNounIndexNameInstancePILL;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.l.o.WordnetNounIndexNameInstancePILO;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.l.s.WordnetNounIndexNameInstancePILS;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.l.u.WordnetNounIndexNameInstancePILU;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.m.a.WordnetNounIndexNameInstancePIMA;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.m.e.WordnetNounIndexNameInstancePIME;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.m.i.WordnetNounIndexNameInstancePIMI;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.m.l.WordnetNounIndexNameInstancePIML;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.m.o.WordnetNounIndexNameInstancePIMO;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.m.p.WordnetNounIndexNameInstancePIMP;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.a.WordnetNounIndexNameInstancePINA;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.b.WordnetNounIndexNameInstancePINB;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.c.WordnetNounIndexNameInstancePINC;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.d.WordnetNounIndexNameInstancePIND;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.e.WordnetNounIndexNameInstancePINE;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.f.WordnetNounIndexNameInstancePINF;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.g.WordnetNounIndexNameInstancePING;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.h.WordnetNounIndexNameInstancePINH;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.i.WordnetNounIndexNameInstancePINI;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.k.WordnetNounIndexNameInstancePINK;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.n.WordnetNounIndexNameInstancePINN;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.o.WordnetNounIndexNameInstancePINO;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.p.WordnetNounIndexNameInstancePINP;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.s.WordnetNounIndexNameInstancePINS;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.t.WordnetNounIndexNameInstancePINT;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.u.WordnetNounIndexNameInstancePINU;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.w.WordnetNounIndexNameInstancePINW;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.n.y.WordnetNounIndexNameInstancePINY;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.o.l.WordnetNounIndexNameInstancePIOL;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.o.n.WordnetNounIndexNameInstancePION;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.o.u.WordnetNounIndexNameInstancePIOU;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.p.a.WordnetNounIndexNameInstancePIPA;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.p.e.WordnetNounIndexNameInstancePIPE;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.p.i.WordnetNounIndexNameInstancePIPI;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.p.p.WordnetNounIndexNameInstancePIPP;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.p.r.WordnetNounIndexNameInstancePIPR;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.p.s.WordnetNounIndexNameInstancePIPS;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.p.t.WordnetNounIndexNameInstancePIPT;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.p.u.WordnetNounIndexNameInstancePIPU;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.q.u.WordnetNounIndexNameInstancePIQU;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.r.a.WordnetNounIndexNameInstancePIRA;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.r.o.WordnetNounIndexNameInstancePIRO;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.s.a.WordnetNounIndexNameInstancePISA;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.s.c.WordnetNounIndexNameInstancePISC;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.s.i.WordnetNounIndexNameInstancePISI;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.s.m.WordnetNounIndexNameInstancePISM;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.s.o.WordnetNounIndexNameInstancePISO;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.s.s.WordnetNounIndexNameInstancePISS;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.s.t.WordnetNounIndexNameInstancePIST;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.s.u.WordnetNounIndexNameInstancePISU;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.a.WordnetNounIndexNameInstancePITA;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.c.WordnetNounIndexNameInstancePITC;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.f.WordnetNounIndexNameInstancePITF;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.h.WordnetNounIndexNameInstancePITH;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.i.WordnetNounIndexNameInstancePITI;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.m.WordnetNounIndexNameInstancePITM;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.o.WordnetNounIndexNameInstancePITO;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.p.WordnetNounIndexNameInstancePITP;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.r.WordnetNounIndexNameInstancePITR;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.s.WordnetNounIndexNameInstancePITS;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.t.WordnetNounIndexNameInstancePITT;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.u.WordnetNounIndexNameInstancePITU;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.t.y.WordnetNounIndexNameInstancePITY;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.u.t.WordnetNounIndexNameInstancePIUT;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.v.o.WordnetNounIndexNameInstancePIVO;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.x.e.WordnetNounIndexNameInstancePIXE;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.x.i.WordnetNounIndexNameInstancePIXI;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.x.y.WordnetNounIndexNameInstancePIXY;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.z.a.WordnetNounIndexNameInstancePIZA;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.i.z.z.WordnetNounIndexNameInstancePIZZ;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerPI {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("piaf".equals(key)) return WordnetNounIndexNameInstancePIAF.get(TERM);
	if ("piag".equals(key)) return WordnetNounIndexNameInstancePIAG.get(TERM);
	if ("pian".equals(key)) return WordnetNounIndexNameInstancePIAN.get(TERM);
	if ("pias".equals(key)) return WordnetNounIndexNameInstancePIAS.get(TERM);
	if ("piaz".equals(key)) return WordnetNounIndexNameInstancePIAZ.get(TERM);
	if ("pibg".equals(key)) return WordnetNounIndexNameInstancePIBG.get(TERM);
	if ("pibi".equals(key)) return WordnetNounIndexNameInstancePIBI.get(TERM);
	if ("pibr".equals(key)) return WordnetNounIndexNameInstancePIBR.get(TERM);
	if ("pica".equals(key)) return WordnetNounIndexNameInstancePICA.get(TERM);
	if ("picc".equals(key)) return WordnetNounIndexNameInstancePICC.get(TERM);
	if ("pice".equals(key)) return WordnetNounIndexNameInstancePICE.get(TERM);
	if ("pich".equals(key)) return WordnetNounIndexNameInstancePICH.get(TERM);
	if ("pici".equals(key)) return WordnetNounIndexNameInstancePICI.get(TERM);
	if ("pick".equals(key)) return WordnetNounIndexNameInstancePICK.get(TERM);
	if ("picn".equals(key)) return WordnetNounIndexNameInstancePICN.get(TERM);
	if ("pico".equals(key)) return WordnetNounIndexNameInstancePICO.get(TERM);
	if ("picr".equals(key)) return WordnetNounIndexNameInstancePICR.get(TERM);
	if ("pict".equals(key)) return WordnetNounIndexNameInstancePICT.get(TERM);
	if ("picu".equals(key)) return WordnetNounIndexNameInstancePICU.get(TERM);
	if ("pidd".equals(key)) return WordnetNounIndexNameInstancePIDD.get(TERM);
	if ("pidg".equals(key)) return WordnetNounIndexNameInstancePIDG.get(TERM);
	if ("pidl".equals(key)) return WordnetNounIndexNameInstancePIDL.get(TERM);
	if ("piec".equals(key)) return WordnetNounIndexNameInstancePIEC.get(TERM);
	if ("pied".equals(key)) return WordnetNounIndexNameInstancePIED.get(TERM);
	if ("piem".equals(key)) return WordnetNounIndexNameInstancePIEM.get(TERM);
	if ("piep".equals(key)) return WordnetNounIndexNameInstancePIEP.get(TERM);
	if ("pier".equals(key)) return WordnetNounIndexNameInstancePIER.get(TERM);
	if ("piet".equals(key)) return WordnetNounIndexNameInstancePIET.get(TERM);
	if ("piez".equals(key)) return WordnetNounIndexNameInstancePIEZ.get(TERM);
	if ("piff".equals(key)) return WordnetNounIndexNameInstancePIFF.get(TERM);
	if ("pigb".equals(key)) return WordnetNounIndexNameInstancePIGB.get(TERM);
	if ("pige".equals(key)) return WordnetNounIndexNameInstancePIGE.get(TERM);
	if ("pigf".equals(key)) return WordnetNounIndexNameInstancePIGF.get(TERM);
	if ("pigg".equals(key)) return WordnetNounIndexNameInstancePIGG.get(TERM);
	if ("pigh".equals(key)) return WordnetNounIndexNameInstancePIGH.get(TERM);
	if ("pigl".equals(key)) return WordnetNounIndexNameInstancePIGL.get(TERM);
	if ("pigm".equals(key)) return WordnetNounIndexNameInstancePIGM.get(TERM);
	if ("pign".equals(key)) return WordnetNounIndexNameInstancePIGN.get(TERM);
	if ("pigp".equals(key)) return WordnetNounIndexNameInstancePIGP.get(TERM);
	if ("pigs".equals(key)) return WordnetNounIndexNameInstancePIGS.get(TERM);
	if ("pigt".equals(key)) return WordnetNounIndexNameInstancePIGT.get(TERM);
	if ("pigw".equals(key)) return WordnetNounIndexNameInstancePIGW.get(TERM);
	if ("pika".equals(key)) return WordnetNounIndexNameInstancePIKA.get(TERM);
	if ("pike".equals(key)) return WordnetNounIndexNameInstancePIKE.get(TERM);
	if ("pila".equals(key)) return WordnetNounIndexNameInstancePILA.get(TERM);
	if ("pilc".equals(key)) return WordnetNounIndexNameInstancePILC.get(TERM);
	if ("pile".equals(key)) return WordnetNounIndexNameInstancePILE.get(TERM);
	if ("pilf".equals(key)) return WordnetNounIndexNameInstancePILF.get(TERM);
	if ("pilg".equals(key)) return WordnetNounIndexNameInstancePILG.get(TERM);
	if ("pili".equals(key)) return WordnetNounIndexNameInstancePILI.get(TERM);
	if ("pill".equals(key)) return WordnetNounIndexNameInstancePILL.get(TERM);
	if ("pilo".equals(key)) return WordnetNounIndexNameInstancePILO.get(TERM);
	if ("pils".equals(key)) return WordnetNounIndexNameInstancePILS.get(TERM);
	if ("pilu".equals(key)) return WordnetNounIndexNameInstancePILU.get(TERM);
	if ("pima".equals(key)) return WordnetNounIndexNameInstancePIMA.get(TERM);
	if ("pime".equals(key)) return WordnetNounIndexNameInstancePIME.get(TERM);
	if ("pimi".equals(key)) return WordnetNounIndexNameInstancePIMI.get(TERM);
	if ("piml".equals(key)) return WordnetNounIndexNameInstancePIML.get(TERM);
	if ("pimo".equals(key)) return WordnetNounIndexNameInstancePIMO.get(TERM);
	if ("pimp".equals(key)) return WordnetNounIndexNameInstancePIMP.get(TERM);
	if ("pina".equals(key)) return WordnetNounIndexNameInstancePINA.get(TERM);
	if ("pinb".equals(key)) return WordnetNounIndexNameInstancePINB.get(TERM);
	if ("pinc".equals(key)) return WordnetNounIndexNameInstancePINC.get(TERM);
	if ("pind".equals(key)) return WordnetNounIndexNameInstancePIND.get(TERM);
	if ("pine".equals(key)) return WordnetNounIndexNameInstancePINE.get(TERM);
	if ("pinf".equals(key)) return WordnetNounIndexNameInstancePINF.get(TERM);
	if ("ping".equals(key)) return WordnetNounIndexNameInstancePING.get(TERM);
	if ("pinh".equals(key)) return WordnetNounIndexNameInstancePINH.get(TERM);
	if ("pini".equals(key)) return WordnetNounIndexNameInstancePINI.get(TERM);
	if ("pink".equals(key)) return WordnetNounIndexNameInstancePINK.get(TERM);
	if ("pinn".equals(key)) return WordnetNounIndexNameInstancePINN.get(TERM);
	if ("pino".equals(key)) return WordnetNounIndexNameInstancePINO.get(TERM);
	if ("pinp".equals(key)) return WordnetNounIndexNameInstancePINP.get(TERM);
	if ("pins".equals(key)) return WordnetNounIndexNameInstancePINS.get(TERM);
	if ("pint".equals(key)) return WordnetNounIndexNameInstancePINT.get(TERM);
	if ("pinu".equals(key)) return WordnetNounIndexNameInstancePINU.get(TERM);
	if ("pinw".equals(key)) return WordnetNounIndexNameInstancePINW.get(TERM);
	if ("piny".equals(key)) return WordnetNounIndexNameInstancePINY.get(TERM);
	if ("piol".equals(key)) return WordnetNounIndexNameInstancePIOL.get(TERM);
	if ("pion".equals(key)) return WordnetNounIndexNameInstancePION.get(TERM);
	if ("piou".equals(key)) return WordnetNounIndexNameInstancePIOU.get(TERM);
	if ("pipa".equals(key)) return WordnetNounIndexNameInstancePIPA.get(TERM);
	if ("pipe".equals(key)) return WordnetNounIndexNameInstancePIPE.get(TERM);
	if ("pipi".equals(key)) return WordnetNounIndexNameInstancePIPI.get(TERM);
	if ("pipp".equals(key)) return WordnetNounIndexNameInstancePIPP.get(TERM);
	if ("pipr".equals(key)) return WordnetNounIndexNameInstancePIPR.get(TERM);
	if ("pips".equals(key)) return WordnetNounIndexNameInstancePIPS.get(TERM);
	if ("pipt".equals(key)) return WordnetNounIndexNameInstancePIPT.get(TERM);
	if ("pipu".equals(key)) return WordnetNounIndexNameInstancePIPU.get(TERM);
	if ("piqu".equals(key)) return WordnetNounIndexNameInstancePIQU.get(TERM);
	if ("pira".equals(key)) return WordnetNounIndexNameInstancePIRA.get(TERM);
	if ("piro".equals(key)) return WordnetNounIndexNameInstancePIRO.get(TERM);
	if ("pisa".equals(key)) return WordnetNounIndexNameInstancePISA.get(TERM);
	if ("pisc".equals(key)) return WordnetNounIndexNameInstancePISC.get(TERM);
	if ("pisi".equals(key)) return WordnetNounIndexNameInstancePISI.get(TERM);
	if ("pism".equals(key)) return WordnetNounIndexNameInstancePISM.get(TERM);
	if ("piso".equals(key)) return WordnetNounIndexNameInstancePISO.get(TERM);
	if ("piss".equals(key)) return WordnetNounIndexNameInstancePISS.get(TERM);
	if ("pist".equals(key)) return WordnetNounIndexNameInstancePIST.get(TERM);
	if ("pisu".equals(key)) return WordnetNounIndexNameInstancePISU.get(TERM);
	if ("pita".equals(key)) return WordnetNounIndexNameInstancePITA.get(TERM);
	if ("pitc".equals(key)) return WordnetNounIndexNameInstancePITC.get(TERM);
	if ("pitf".equals(key)) return WordnetNounIndexNameInstancePITF.get(TERM);
	if ("pith".equals(key)) return WordnetNounIndexNameInstancePITH.get(TERM);
	if ("piti".equals(key)) return WordnetNounIndexNameInstancePITI.get(TERM);
	if ("pitm".equals(key)) return WordnetNounIndexNameInstancePITM.get(TERM);
	if ("pito".equals(key)) return WordnetNounIndexNameInstancePITO.get(TERM);
	if ("pitp".equals(key)) return WordnetNounIndexNameInstancePITP.get(TERM);
	if ("pitr".equals(key)) return WordnetNounIndexNameInstancePITR.get(TERM);
	if ("pits".equals(key)) return WordnetNounIndexNameInstancePITS.get(TERM);
	if ("pitt".equals(key)) return WordnetNounIndexNameInstancePITT.get(TERM);
	if ("pitu".equals(key)) return WordnetNounIndexNameInstancePITU.get(TERM);
	if ("pity".equals(key)) return WordnetNounIndexNameInstancePITY.get(TERM);
	if ("piut".equals(key)) return WordnetNounIndexNameInstancePIUT.get(TERM);
	if ("pivo".equals(key)) return WordnetNounIndexNameInstancePIVO.get(TERM);
	if ("pixe".equals(key)) return WordnetNounIndexNameInstancePIXE.get(TERM);
	if ("pixi".equals(key)) return WordnetNounIndexNameInstancePIXI.get(TERM);
	if ("pixy".equals(key)) return WordnetNounIndexNameInstancePIXY.get(TERM);
	if ("piza".equals(key)) return WordnetNounIndexNameInstancePIZA.get(TERM);
	if ("pizz".equals(key)) return WordnetNounIndexNameInstancePIZZ.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstancePIAF.terms());
	set.addAll(WordnetNounIndexNameInstancePIAG.terms());
	set.addAll(WordnetNounIndexNameInstancePIAN.terms());
	set.addAll(WordnetNounIndexNameInstancePIAS.terms());
	set.addAll(WordnetNounIndexNameInstancePIAZ.terms());
	set.addAll(WordnetNounIndexNameInstancePIBG.terms());
	set.addAll(WordnetNounIndexNameInstancePIBI.terms());
	set.addAll(WordnetNounIndexNameInstancePIBR.terms());
	set.addAll(WordnetNounIndexNameInstancePICA.terms());
	set.addAll(WordnetNounIndexNameInstancePICC.terms());
	set.addAll(WordnetNounIndexNameInstancePICE.terms());
	set.addAll(WordnetNounIndexNameInstancePICH.terms());
	set.addAll(WordnetNounIndexNameInstancePICI.terms());
	set.addAll(WordnetNounIndexNameInstancePICK.terms());
	set.addAll(WordnetNounIndexNameInstancePICN.terms());
	set.addAll(WordnetNounIndexNameInstancePICO.terms());
	set.addAll(WordnetNounIndexNameInstancePICR.terms());
	set.addAll(WordnetNounIndexNameInstancePICT.terms());
	set.addAll(WordnetNounIndexNameInstancePICU.terms());
	set.addAll(WordnetNounIndexNameInstancePIDD.terms());
	set.addAll(WordnetNounIndexNameInstancePIDG.terms());
	set.addAll(WordnetNounIndexNameInstancePIDL.terms());
	set.addAll(WordnetNounIndexNameInstancePIEC.terms());
	set.addAll(WordnetNounIndexNameInstancePIED.terms());
	set.addAll(WordnetNounIndexNameInstancePIEM.terms());
	set.addAll(WordnetNounIndexNameInstancePIEP.terms());
	set.addAll(WordnetNounIndexNameInstancePIER.terms());
	set.addAll(WordnetNounIndexNameInstancePIET.terms());
	set.addAll(WordnetNounIndexNameInstancePIEZ.terms());
	set.addAll(WordnetNounIndexNameInstancePIFF.terms());
	set.addAll(WordnetNounIndexNameInstancePIGB.terms());
	set.addAll(WordnetNounIndexNameInstancePIGE.terms());
	set.addAll(WordnetNounIndexNameInstancePIGF.terms());
	set.addAll(WordnetNounIndexNameInstancePIGG.terms());
	set.addAll(WordnetNounIndexNameInstancePIGH.terms());
	set.addAll(WordnetNounIndexNameInstancePIGL.terms());
	set.addAll(WordnetNounIndexNameInstancePIGM.terms());
	set.addAll(WordnetNounIndexNameInstancePIGN.terms());
	set.addAll(WordnetNounIndexNameInstancePIGP.terms());
	set.addAll(WordnetNounIndexNameInstancePIGS.terms());
	set.addAll(WordnetNounIndexNameInstancePIGT.terms());
	set.addAll(WordnetNounIndexNameInstancePIGW.terms());
	set.addAll(WordnetNounIndexNameInstancePIKA.terms());
	set.addAll(WordnetNounIndexNameInstancePIKE.terms());
	set.addAll(WordnetNounIndexNameInstancePILA.terms());
	set.addAll(WordnetNounIndexNameInstancePILC.terms());
	set.addAll(WordnetNounIndexNameInstancePILE.terms());
	set.addAll(WordnetNounIndexNameInstancePILF.terms());
	set.addAll(WordnetNounIndexNameInstancePILG.terms());
	set.addAll(WordnetNounIndexNameInstancePILI.terms());
	set.addAll(WordnetNounIndexNameInstancePILL.terms());
	set.addAll(WordnetNounIndexNameInstancePILO.terms());
	set.addAll(WordnetNounIndexNameInstancePILS.terms());
	set.addAll(WordnetNounIndexNameInstancePILU.terms());
	set.addAll(WordnetNounIndexNameInstancePIMA.terms());
	set.addAll(WordnetNounIndexNameInstancePIME.terms());
	set.addAll(WordnetNounIndexNameInstancePIMI.terms());
	set.addAll(WordnetNounIndexNameInstancePIML.terms());
	set.addAll(WordnetNounIndexNameInstancePIMO.terms());
	set.addAll(WordnetNounIndexNameInstancePIMP.terms());
	set.addAll(WordnetNounIndexNameInstancePINA.terms());
	set.addAll(WordnetNounIndexNameInstancePINB.terms());
	set.addAll(WordnetNounIndexNameInstancePINC.terms());
	set.addAll(WordnetNounIndexNameInstancePIND.terms());
	set.addAll(WordnetNounIndexNameInstancePINE.terms());
	set.addAll(WordnetNounIndexNameInstancePINF.terms());
	set.addAll(WordnetNounIndexNameInstancePING.terms());
	set.addAll(WordnetNounIndexNameInstancePINH.terms());
	set.addAll(WordnetNounIndexNameInstancePINI.terms());
	set.addAll(WordnetNounIndexNameInstancePINK.terms());
	set.addAll(WordnetNounIndexNameInstancePINN.terms());
	set.addAll(WordnetNounIndexNameInstancePINO.terms());
	set.addAll(WordnetNounIndexNameInstancePINP.terms());
	set.addAll(WordnetNounIndexNameInstancePINS.terms());
	set.addAll(WordnetNounIndexNameInstancePINT.terms());
	set.addAll(WordnetNounIndexNameInstancePINU.terms());
	set.addAll(WordnetNounIndexNameInstancePINW.terms());
	set.addAll(WordnetNounIndexNameInstancePINY.terms());
	set.addAll(WordnetNounIndexNameInstancePIOL.terms());
	set.addAll(WordnetNounIndexNameInstancePION.terms());
	set.addAll(WordnetNounIndexNameInstancePIOU.terms());
	set.addAll(WordnetNounIndexNameInstancePIPA.terms());
	set.addAll(WordnetNounIndexNameInstancePIPE.terms());
	set.addAll(WordnetNounIndexNameInstancePIPI.terms());
	set.addAll(WordnetNounIndexNameInstancePIPP.terms());
	set.addAll(WordnetNounIndexNameInstancePIPR.terms());
	set.addAll(WordnetNounIndexNameInstancePIPS.terms());
	set.addAll(WordnetNounIndexNameInstancePIPT.terms());
	set.addAll(WordnetNounIndexNameInstancePIPU.terms());
	set.addAll(WordnetNounIndexNameInstancePIQU.terms());
	set.addAll(WordnetNounIndexNameInstancePIRA.terms());
	set.addAll(WordnetNounIndexNameInstancePIRO.terms());
	set.addAll(WordnetNounIndexNameInstancePISA.terms());
	set.addAll(WordnetNounIndexNameInstancePISC.terms());
	set.addAll(WordnetNounIndexNameInstancePISI.terms());
	set.addAll(WordnetNounIndexNameInstancePISM.terms());
	set.addAll(WordnetNounIndexNameInstancePISO.terms());
	set.addAll(WordnetNounIndexNameInstancePISS.terms());
	set.addAll(WordnetNounIndexNameInstancePIST.terms());
	set.addAll(WordnetNounIndexNameInstancePISU.terms());
	set.addAll(WordnetNounIndexNameInstancePITA.terms());
	set.addAll(WordnetNounIndexNameInstancePITC.terms());
	set.addAll(WordnetNounIndexNameInstancePITF.terms());
	set.addAll(WordnetNounIndexNameInstancePITH.terms());
	set.addAll(WordnetNounIndexNameInstancePITI.terms());
	set.addAll(WordnetNounIndexNameInstancePITM.terms());
	set.addAll(WordnetNounIndexNameInstancePITO.terms());
	set.addAll(WordnetNounIndexNameInstancePITP.terms());
	set.addAll(WordnetNounIndexNameInstancePITR.terms());
	set.addAll(WordnetNounIndexNameInstancePITS.terms());
	set.addAll(WordnetNounIndexNameInstancePITT.terms());
	set.addAll(WordnetNounIndexNameInstancePITU.terms());
	set.addAll(WordnetNounIndexNameInstancePITY.terms());
	set.addAll(WordnetNounIndexNameInstancePIUT.terms());
	set.addAll(WordnetNounIndexNameInstancePIVO.terms());
	set.addAll(WordnetNounIndexNameInstancePIXE.terms());
	set.addAll(WordnetNounIndexNameInstancePIXI.terms());
	set.addAll(WordnetNounIndexNameInstancePIXY.terms());
	set.addAll(WordnetNounIndexNameInstancePIZA.terms());
	set.addAll(WordnetNounIndexNameInstancePIZZ.terms());
  		return set; 	} }