package org.swtk.commons.dict.wordnet.indexbyname.instance.n.i.k;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceNIK {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"nike\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09590896\"]}");
	add("{\"term\":\"nikita khrushchev\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11124277\"]}");
	add("{\"term\":\"nikita sergeyevich khrushchev\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11124277\"]}");
	add("{\"term\":\"nikola tesla\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11356845\"]}");
	add("{\"term\":\"nikolaas tinbergen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11363035\"]}");
	add("{\"term\":\"nikolai ivanovich bukharin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10890278\"]}");
	add("{\"term\":\"nikolai ivanovich lobachevsky\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11156612\"]}");
	add("{\"term\":\"nikolai lenin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11146480\"]}");
	add("{\"term\":\"nikolai vasilievich gogol\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11024329\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }