package org.swtk.commons.dict.wordnet.index.name.controller.d.o;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.b.b.WordnetNounIndexNameInstanceDOBB;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.b.e.WordnetNounIndexNameInstanceDOBE;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.b.r.WordnetNounIndexNameInstanceDOBR;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.b.s.WordnetNounIndexNameInstanceDOBS;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.c.e.WordnetNounIndexNameInstanceDOCE;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.c.i.WordnetNounIndexNameInstanceDOCI;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.c.k.WordnetNounIndexNameInstanceDOCK;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.c.t.WordnetNounIndexNameInstanceDOCT;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.c.u.WordnetNounIndexNameInstanceDOCU;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.d.d.WordnetNounIndexNameInstanceDODD;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.d.e.WordnetNounIndexNameInstanceDODE;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.d.g.WordnetNounIndexNameInstanceDODG;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.d.o.WordnetNounIndexNameInstanceDODO;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.e.i.WordnetNounIndexNameInstanceDOEI;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.e.r.WordnetNounIndexNameInstanceDOER;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.e.s.WordnetNounIndexNameInstanceDOES;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.b.WordnetNounIndexNameInstanceDOGB;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.c.WordnetNounIndexNameInstanceDOGC;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.e.WordnetNounIndexNameInstanceDOGE;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.f.WordnetNounIndexNameInstanceDOGF;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.g.WordnetNounIndexNameInstanceDOGG;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.h.WordnetNounIndexNameInstanceDOGH;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.i.WordnetNounIndexNameInstanceDOGI;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.l.WordnetNounIndexNameInstanceDOGL;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.m.WordnetNounIndexNameInstanceDOGM;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.s.WordnetNounIndexNameInstanceDOGS;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.t.WordnetNounIndexNameInstanceDOGT;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.w.WordnetNounIndexNameInstanceDOGW;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.g.y.WordnetNounIndexNameInstanceDOGY;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.h.a.WordnetNounIndexNameInstanceDOHA;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.i.l.WordnetNounIndexNameInstanceDOIL;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.i.n.WordnetNounIndexNameInstanceDOIN;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.j.c.WordnetNounIndexNameInstanceDOJC;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.l.b.WordnetNounIndexNameInstanceDOLB;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.l.d.WordnetNounIndexNameInstanceDOLD;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.l.e.WordnetNounIndexNameInstanceDOLE;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.l.i.WordnetNounIndexNameInstanceDOLI;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.l.l.WordnetNounIndexNameInstanceDOLL;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.l.m.WordnetNounIndexNameInstanceDOLM;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.l.o.WordnetNounIndexNameInstanceDOLO;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.l.p.WordnetNounIndexNameInstanceDOLP;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.l.t.WordnetNounIndexNameInstanceDOLT;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.m.a.WordnetNounIndexNameInstanceDOMA;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.m.b.WordnetNounIndexNameInstanceDOMB;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.m.e.WordnetNounIndexNameInstanceDOME;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.m.i.WordnetNounIndexNameInstanceDOMI;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.n.a.WordnetNounIndexNameInstanceDONA;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.n.b.WordnetNounIndexNameInstanceDONB;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.n.e.WordnetNounIndexNameInstanceDONE;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.n.g.WordnetNounIndexNameInstanceDONG;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.n.i.WordnetNounIndexNameInstanceDONI;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.n.j.WordnetNounIndexNameInstanceDONJ;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.n.k.WordnetNounIndexNameInstanceDONK;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.n.n.WordnetNounIndexNameInstanceDONN;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.n.o.WordnetNounIndexNameInstanceDONO;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.n.u.WordnetNounIndexNameInstanceDONU;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.o.b.WordnetNounIndexNameInstanceDOOB;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.o.d.WordnetNounIndexNameInstanceDOOD;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.o.f.WordnetNounIndexNameInstanceDOOF;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.o.h.WordnetNounIndexNameInstanceDOOH;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.o.j.WordnetNounIndexNameInstanceDOOJ;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.o.l.WordnetNounIndexNameInstanceDOOL;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.o.m.WordnetNounIndexNameInstanceDOOM;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.o.r.WordnetNounIndexNameInstanceDOOR;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.p.a.WordnetNounIndexNameInstanceDOPA;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.p.e.WordnetNounIndexNameInstanceDOPE;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.p.p.WordnetNounIndexNameInstanceDOPP;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.r.a.WordnetNounIndexNameInstanceDORA;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.r.b.WordnetNounIndexNameInstanceDORB;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.r.i.WordnetNounIndexNameInstanceDORI;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.r.k.WordnetNounIndexNameInstanceDORK;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.r.m.WordnetNounIndexNameInstanceDORM;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.r.o.WordnetNounIndexNameInstanceDORO;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.r.s.WordnetNounIndexNameInstanceDORS;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.r.t.WordnetNounIndexNameInstanceDORT;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.r.y.WordnetNounIndexNameInstanceDORY;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.s.a.WordnetNounIndexNameInstanceDOSA;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.s.e.WordnetNounIndexNameInstanceDOSE;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.s.i.WordnetNounIndexNameInstanceDOSI;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.s.s.WordnetNounIndexNameInstanceDOSS;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.s.t.WordnetNounIndexNameInstanceDOST;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.t.a.WordnetNounIndexNameInstanceDOTA;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.t.r.WordnetNounIndexNameInstanceDOTR;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.t.t.WordnetNounIndexNameInstanceDOTT;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.u.a.WordnetNounIndexNameInstanceDOUA;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.u.b.WordnetNounIndexNameInstanceDOUB;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.u.c.WordnetNounIndexNameInstanceDOUC;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.u.g.WordnetNounIndexNameInstanceDOUG;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.u.l.WordnetNounIndexNameInstanceDOUL;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.u.r.WordnetNounIndexNameInstanceDOUR;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.u.s.WordnetNounIndexNameInstanceDOUS;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.v.e.WordnetNounIndexNameInstanceDOVE;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.v.i.WordnetNounIndexNameInstanceDOVI;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.v.y.WordnetNounIndexNameInstanceDOVY;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.w.a.WordnetNounIndexNameInstanceDOWA;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.w.d.WordnetNounIndexNameInstanceDOWD;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.w.e.WordnetNounIndexNameInstanceDOWE;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.w.i.WordnetNounIndexNameInstanceDOWI;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.w.l.WordnetNounIndexNameInstanceDOWL;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.w.n.WordnetNounIndexNameInstanceDOWN;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.w.r.WordnetNounIndexNameInstanceDOWR;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.w.s.WordnetNounIndexNameInstanceDOWS;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.x.a.WordnetNounIndexNameInstanceDOXA;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.x.e.WordnetNounIndexNameInstanceDOXE;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.x.o.WordnetNounIndexNameInstanceDOXO;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.x.y.WordnetNounIndexNameInstanceDOXY;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.y.e.WordnetNounIndexNameInstanceDOYE;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.y.l.WordnetNounIndexNameInstanceDOYL;
	import org.swtk.commons.dict.wordnet.index.name.instance.d.o.z.e.WordnetNounIndexNameInstanceDOZE;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerDO {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("dobb".equals(key)) return WordnetNounIndexNameInstanceDOBB.get(TERM);
	if ("dobe".equals(key)) return WordnetNounIndexNameInstanceDOBE.get(TERM);
	if ("dobr".equals(key)) return WordnetNounIndexNameInstanceDOBR.get(TERM);
	if ("dobs".equals(key)) return WordnetNounIndexNameInstanceDOBS.get(TERM);
	if ("doce".equals(key)) return WordnetNounIndexNameInstanceDOCE.get(TERM);
	if ("doci".equals(key)) return WordnetNounIndexNameInstanceDOCI.get(TERM);
	if ("dock".equals(key)) return WordnetNounIndexNameInstanceDOCK.get(TERM);
	if ("doct".equals(key)) return WordnetNounIndexNameInstanceDOCT.get(TERM);
	if ("docu".equals(key)) return WordnetNounIndexNameInstanceDOCU.get(TERM);
	if ("dodd".equals(key)) return WordnetNounIndexNameInstanceDODD.get(TERM);
	if ("dode".equals(key)) return WordnetNounIndexNameInstanceDODE.get(TERM);
	if ("dodg".equals(key)) return WordnetNounIndexNameInstanceDODG.get(TERM);
	if ("dodo".equals(key)) return WordnetNounIndexNameInstanceDODO.get(TERM);
	if ("doei".equals(key)) return WordnetNounIndexNameInstanceDOEI.get(TERM);
	if ("doer".equals(key)) return WordnetNounIndexNameInstanceDOER.get(TERM);
	if ("does".equals(key)) return WordnetNounIndexNameInstanceDOES.get(TERM);
	if ("dogb".equals(key)) return WordnetNounIndexNameInstanceDOGB.get(TERM);
	if ("dogc".equals(key)) return WordnetNounIndexNameInstanceDOGC.get(TERM);
	if ("doge".equals(key)) return WordnetNounIndexNameInstanceDOGE.get(TERM);
	if ("dogf".equals(key)) return WordnetNounIndexNameInstanceDOGF.get(TERM);
	if ("dogg".equals(key)) return WordnetNounIndexNameInstanceDOGG.get(TERM);
	if ("dogh".equals(key)) return WordnetNounIndexNameInstanceDOGH.get(TERM);
	if ("dogi".equals(key)) return WordnetNounIndexNameInstanceDOGI.get(TERM);
	if ("dogl".equals(key)) return WordnetNounIndexNameInstanceDOGL.get(TERM);
	if ("dogm".equals(key)) return WordnetNounIndexNameInstanceDOGM.get(TERM);
	if ("dogs".equals(key)) return WordnetNounIndexNameInstanceDOGS.get(TERM);
	if ("dogt".equals(key)) return WordnetNounIndexNameInstanceDOGT.get(TERM);
	if ("dogw".equals(key)) return WordnetNounIndexNameInstanceDOGW.get(TERM);
	if ("dogy".equals(key)) return WordnetNounIndexNameInstanceDOGY.get(TERM);
	if ("doha".equals(key)) return WordnetNounIndexNameInstanceDOHA.get(TERM);
	if ("doil".equals(key)) return WordnetNounIndexNameInstanceDOIL.get(TERM);
	if ("doin".equals(key)) return WordnetNounIndexNameInstanceDOIN.get(TERM);
	if ("dojc".equals(key)) return WordnetNounIndexNameInstanceDOJC.get(TERM);
	if ("dolb".equals(key)) return WordnetNounIndexNameInstanceDOLB.get(TERM);
	if ("dold".equals(key)) return WordnetNounIndexNameInstanceDOLD.get(TERM);
	if ("dole".equals(key)) return WordnetNounIndexNameInstanceDOLE.get(TERM);
	if ("doli".equals(key)) return WordnetNounIndexNameInstanceDOLI.get(TERM);
	if ("doll".equals(key)) return WordnetNounIndexNameInstanceDOLL.get(TERM);
	if ("dolm".equals(key)) return WordnetNounIndexNameInstanceDOLM.get(TERM);
	if ("dolo".equals(key)) return WordnetNounIndexNameInstanceDOLO.get(TERM);
	if ("dolp".equals(key)) return WordnetNounIndexNameInstanceDOLP.get(TERM);
	if ("dolt".equals(key)) return WordnetNounIndexNameInstanceDOLT.get(TERM);
	if ("doma".equals(key)) return WordnetNounIndexNameInstanceDOMA.get(TERM);
	if ("domb".equals(key)) return WordnetNounIndexNameInstanceDOMB.get(TERM);
	if ("dome".equals(key)) return WordnetNounIndexNameInstanceDOME.get(TERM);
	if ("domi".equals(key)) return WordnetNounIndexNameInstanceDOMI.get(TERM);
	if ("dona".equals(key)) return WordnetNounIndexNameInstanceDONA.get(TERM);
	if ("donb".equals(key)) return WordnetNounIndexNameInstanceDONB.get(TERM);
	if ("done".equals(key)) return WordnetNounIndexNameInstanceDONE.get(TERM);
	if ("dong".equals(key)) return WordnetNounIndexNameInstanceDONG.get(TERM);
	if ("doni".equals(key)) return WordnetNounIndexNameInstanceDONI.get(TERM);
	if ("donj".equals(key)) return WordnetNounIndexNameInstanceDONJ.get(TERM);
	if ("donk".equals(key)) return WordnetNounIndexNameInstanceDONK.get(TERM);
	if ("donn".equals(key)) return WordnetNounIndexNameInstanceDONN.get(TERM);
	if ("dono".equals(key)) return WordnetNounIndexNameInstanceDONO.get(TERM);
	if ("donu".equals(key)) return WordnetNounIndexNameInstanceDONU.get(TERM);
	if ("doob".equals(key)) return WordnetNounIndexNameInstanceDOOB.get(TERM);
	if ("dood".equals(key)) return WordnetNounIndexNameInstanceDOOD.get(TERM);
	if ("doof".equals(key)) return WordnetNounIndexNameInstanceDOOF.get(TERM);
	if ("dooh".equals(key)) return WordnetNounIndexNameInstanceDOOH.get(TERM);
	if ("dooj".equals(key)) return WordnetNounIndexNameInstanceDOOJ.get(TERM);
	if ("dool".equals(key)) return WordnetNounIndexNameInstanceDOOL.get(TERM);
	if ("doom".equals(key)) return WordnetNounIndexNameInstanceDOOM.get(TERM);
	if ("door".equals(key)) return WordnetNounIndexNameInstanceDOOR.get(TERM);
	if ("dopa".equals(key)) return WordnetNounIndexNameInstanceDOPA.get(TERM);
	if ("dope".equals(key)) return WordnetNounIndexNameInstanceDOPE.get(TERM);
	if ("dopp".equals(key)) return WordnetNounIndexNameInstanceDOPP.get(TERM);
	if ("dora".equals(key)) return WordnetNounIndexNameInstanceDORA.get(TERM);
	if ("dorb".equals(key)) return WordnetNounIndexNameInstanceDORB.get(TERM);
	if ("dori".equals(key)) return WordnetNounIndexNameInstanceDORI.get(TERM);
	if ("dork".equals(key)) return WordnetNounIndexNameInstanceDORK.get(TERM);
	if ("dorm".equals(key)) return WordnetNounIndexNameInstanceDORM.get(TERM);
	if ("doro".equals(key)) return WordnetNounIndexNameInstanceDORO.get(TERM);
	if ("dors".equals(key)) return WordnetNounIndexNameInstanceDORS.get(TERM);
	if ("dort".equals(key)) return WordnetNounIndexNameInstanceDORT.get(TERM);
	if ("dory".equals(key)) return WordnetNounIndexNameInstanceDORY.get(TERM);
	if ("dosa".equals(key)) return WordnetNounIndexNameInstanceDOSA.get(TERM);
	if ("dose".equals(key)) return WordnetNounIndexNameInstanceDOSE.get(TERM);
	if ("dosi".equals(key)) return WordnetNounIndexNameInstanceDOSI.get(TERM);
	if ("doss".equals(key)) return WordnetNounIndexNameInstanceDOSS.get(TERM);
	if ("dost".equals(key)) return WordnetNounIndexNameInstanceDOST.get(TERM);
	if ("dota".equals(key)) return WordnetNounIndexNameInstanceDOTA.get(TERM);
	if ("dotr".equals(key)) return WordnetNounIndexNameInstanceDOTR.get(TERM);
	if ("dott".equals(key)) return WordnetNounIndexNameInstanceDOTT.get(TERM);
	if ("doua".equals(key)) return WordnetNounIndexNameInstanceDOUA.get(TERM);
	if ("doub".equals(key)) return WordnetNounIndexNameInstanceDOUB.get(TERM);
	if ("douc".equals(key)) return WordnetNounIndexNameInstanceDOUC.get(TERM);
	if ("doug".equals(key)) return WordnetNounIndexNameInstanceDOUG.get(TERM);
	if ("doul".equals(key)) return WordnetNounIndexNameInstanceDOUL.get(TERM);
	if ("dour".equals(key)) return WordnetNounIndexNameInstanceDOUR.get(TERM);
	if ("dous".equals(key)) return WordnetNounIndexNameInstanceDOUS.get(TERM);
	if ("dove".equals(key)) return WordnetNounIndexNameInstanceDOVE.get(TERM);
	if ("dovi".equals(key)) return WordnetNounIndexNameInstanceDOVI.get(TERM);
	if ("dovy".equals(key)) return WordnetNounIndexNameInstanceDOVY.get(TERM);
	if ("dowa".equals(key)) return WordnetNounIndexNameInstanceDOWA.get(TERM);
	if ("dowd".equals(key)) return WordnetNounIndexNameInstanceDOWD.get(TERM);
	if ("dowe".equals(key)) return WordnetNounIndexNameInstanceDOWE.get(TERM);
	if ("dowi".equals(key)) return WordnetNounIndexNameInstanceDOWI.get(TERM);
	if ("dowl".equals(key)) return WordnetNounIndexNameInstanceDOWL.get(TERM);
	if ("down".equals(key)) return WordnetNounIndexNameInstanceDOWN.get(TERM);
	if ("dowr".equals(key)) return WordnetNounIndexNameInstanceDOWR.get(TERM);
	if ("dows".equals(key)) return WordnetNounIndexNameInstanceDOWS.get(TERM);
	if ("doxa".equals(key)) return WordnetNounIndexNameInstanceDOXA.get(TERM);
	if ("doxe".equals(key)) return WordnetNounIndexNameInstanceDOXE.get(TERM);
	if ("doxo".equals(key)) return WordnetNounIndexNameInstanceDOXO.get(TERM);
	if ("doxy".equals(key)) return WordnetNounIndexNameInstanceDOXY.get(TERM);
	if ("doye".equals(key)) return WordnetNounIndexNameInstanceDOYE.get(TERM);
	if ("doyl".equals(key)) return WordnetNounIndexNameInstanceDOYL.get(TERM);
	if ("doze".equals(key)) return WordnetNounIndexNameInstanceDOZE.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceDOBB.terms());
	set.addAll(WordnetNounIndexNameInstanceDOBE.terms());
	set.addAll(WordnetNounIndexNameInstanceDOBR.terms());
	set.addAll(WordnetNounIndexNameInstanceDOBS.terms());
	set.addAll(WordnetNounIndexNameInstanceDOCE.terms());
	set.addAll(WordnetNounIndexNameInstanceDOCI.terms());
	set.addAll(WordnetNounIndexNameInstanceDOCK.terms());
	set.addAll(WordnetNounIndexNameInstanceDOCT.terms());
	set.addAll(WordnetNounIndexNameInstanceDOCU.terms());
	set.addAll(WordnetNounIndexNameInstanceDODD.terms());
	set.addAll(WordnetNounIndexNameInstanceDODE.terms());
	set.addAll(WordnetNounIndexNameInstanceDODG.terms());
	set.addAll(WordnetNounIndexNameInstanceDODO.terms());
	set.addAll(WordnetNounIndexNameInstanceDOEI.terms());
	set.addAll(WordnetNounIndexNameInstanceDOER.terms());
	set.addAll(WordnetNounIndexNameInstanceDOES.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGB.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGC.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGE.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGF.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGG.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGH.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGI.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGL.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGM.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGS.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGT.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGW.terms());
	set.addAll(WordnetNounIndexNameInstanceDOGY.terms());
	set.addAll(WordnetNounIndexNameInstanceDOHA.terms());
	set.addAll(WordnetNounIndexNameInstanceDOIL.terms());
	set.addAll(WordnetNounIndexNameInstanceDOIN.terms());
	set.addAll(WordnetNounIndexNameInstanceDOJC.terms());
	set.addAll(WordnetNounIndexNameInstanceDOLB.terms());
	set.addAll(WordnetNounIndexNameInstanceDOLD.terms());
	set.addAll(WordnetNounIndexNameInstanceDOLE.terms());
	set.addAll(WordnetNounIndexNameInstanceDOLI.terms());
	set.addAll(WordnetNounIndexNameInstanceDOLL.terms());
	set.addAll(WordnetNounIndexNameInstanceDOLM.terms());
	set.addAll(WordnetNounIndexNameInstanceDOLO.terms());
	set.addAll(WordnetNounIndexNameInstanceDOLP.terms());
	set.addAll(WordnetNounIndexNameInstanceDOLT.terms());
	set.addAll(WordnetNounIndexNameInstanceDOMA.terms());
	set.addAll(WordnetNounIndexNameInstanceDOMB.terms());
	set.addAll(WordnetNounIndexNameInstanceDOME.terms());
	set.addAll(WordnetNounIndexNameInstanceDOMI.terms());
	set.addAll(WordnetNounIndexNameInstanceDONA.terms());
	set.addAll(WordnetNounIndexNameInstanceDONB.terms());
	set.addAll(WordnetNounIndexNameInstanceDONE.terms());
	set.addAll(WordnetNounIndexNameInstanceDONG.terms());
	set.addAll(WordnetNounIndexNameInstanceDONI.terms());
	set.addAll(WordnetNounIndexNameInstanceDONJ.terms());
	set.addAll(WordnetNounIndexNameInstanceDONK.terms());
	set.addAll(WordnetNounIndexNameInstanceDONN.terms());
	set.addAll(WordnetNounIndexNameInstanceDONO.terms());
	set.addAll(WordnetNounIndexNameInstanceDONU.terms());
	set.addAll(WordnetNounIndexNameInstanceDOOB.terms());
	set.addAll(WordnetNounIndexNameInstanceDOOD.terms());
	set.addAll(WordnetNounIndexNameInstanceDOOF.terms());
	set.addAll(WordnetNounIndexNameInstanceDOOH.terms());
	set.addAll(WordnetNounIndexNameInstanceDOOJ.terms());
	set.addAll(WordnetNounIndexNameInstanceDOOL.terms());
	set.addAll(WordnetNounIndexNameInstanceDOOM.terms());
	set.addAll(WordnetNounIndexNameInstanceDOOR.terms());
	set.addAll(WordnetNounIndexNameInstanceDOPA.terms());
	set.addAll(WordnetNounIndexNameInstanceDOPE.terms());
	set.addAll(WordnetNounIndexNameInstanceDOPP.terms());
	set.addAll(WordnetNounIndexNameInstanceDORA.terms());
	set.addAll(WordnetNounIndexNameInstanceDORB.terms());
	set.addAll(WordnetNounIndexNameInstanceDORI.terms());
	set.addAll(WordnetNounIndexNameInstanceDORK.terms());
	set.addAll(WordnetNounIndexNameInstanceDORM.terms());
	set.addAll(WordnetNounIndexNameInstanceDORO.terms());
	set.addAll(WordnetNounIndexNameInstanceDORS.terms());
	set.addAll(WordnetNounIndexNameInstanceDORT.terms());
	set.addAll(WordnetNounIndexNameInstanceDORY.terms());
	set.addAll(WordnetNounIndexNameInstanceDOSA.terms());
	set.addAll(WordnetNounIndexNameInstanceDOSE.terms());
	set.addAll(WordnetNounIndexNameInstanceDOSI.terms());
	set.addAll(WordnetNounIndexNameInstanceDOSS.terms());
	set.addAll(WordnetNounIndexNameInstanceDOST.terms());
	set.addAll(WordnetNounIndexNameInstanceDOTA.terms());
	set.addAll(WordnetNounIndexNameInstanceDOTR.terms());
	set.addAll(WordnetNounIndexNameInstanceDOTT.terms());
	set.addAll(WordnetNounIndexNameInstanceDOUA.terms());
	set.addAll(WordnetNounIndexNameInstanceDOUB.terms());
	set.addAll(WordnetNounIndexNameInstanceDOUC.terms());
	set.addAll(WordnetNounIndexNameInstanceDOUG.terms());
	set.addAll(WordnetNounIndexNameInstanceDOUL.terms());
	set.addAll(WordnetNounIndexNameInstanceDOUR.terms());
	set.addAll(WordnetNounIndexNameInstanceDOUS.terms());
	set.addAll(WordnetNounIndexNameInstanceDOVE.terms());
	set.addAll(WordnetNounIndexNameInstanceDOVI.terms());
	set.addAll(WordnetNounIndexNameInstanceDOVY.terms());
	set.addAll(WordnetNounIndexNameInstanceDOWA.terms());
	set.addAll(WordnetNounIndexNameInstanceDOWD.terms());
	set.addAll(WordnetNounIndexNameInstanceDOWE.terms());
	set.addAll(WordnetNounIndexNameInstanceDOWI.terms());
	set.addAll(WordnetNounIndexNameInstanceDOWL.terms());
	set.addAll(WordnetNounIndexNameInstanceDOWN.terms());
	set.addAll(WordnetNounIndexNameInstanceDOWR.terms());
	set.addAll(WordnetNounIndexNameInstanceDOWS.terms());
	set.addAll(WordnetNounIndexNameInstanceDOXA.terms());
	set.addAll(WordnetNounIndexNameInstanceDOXE.terms());
	set.addAll(WordnetNounIndexNameInstanceDOXO.terms());
	set.addAll(WordnetNounIndexNameInstanceDOXY.terms());
	set.addAll(WordnetNounIndexNameInstanceDOYE.terms());
	set.addAll(WordnetNounIndexNameInstanceDOYL.terms());
	set.addAll(WordnetNounIndexNameInstanceDOZE.terms());
  		return set; 	} }