package org.swtk.commons.dict.wordnet.indexbyname.instance.g.e.r;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceGER {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"geraint\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11016529\"]}");
	add("{\"term\":\"geraniaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12705975\"]}");
	add("{\"term\":\"geraniales\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12705401\"]}");
	add("{\"term\":\"geranium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12706192\"]}");
	add("{\"term\":\"gerardia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12904388\"]}");
	add("{\"term\":\"gerbera\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11992069\"]}");
	add("{\"term\":\"gerbert\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11347393\"]}");
	add("{\"term\":\"gerbil\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02346424\"]}");
	add("{\"term\":\"gerbille\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02346424\"]}");
	add("{\"term\":\"gerbillinae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02346139\"]}");
	add("{\"term\":\"gerbillus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02346285\"]}");
	add("{\"term\":\"gerea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11992610\"]}");
	add("{\"term\":\"gerenuk\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02423474\"]}");
	add("{\"term\":\"gerfalcon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01614441\"]}");
	add("{\"term\":\"geriatrician\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10147918\"]}");
	add("{\"term\":\"geriatrics\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06060181\"]}");
	add("{\"term\":\"germ\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"01387132\", \"05237135\", \"05843082\"]}");
	add("{\"term\":\"german\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06963290\", \"09767053\"]}");
	add("{\"term\":\"germander\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12890238\"]}");
	add("{\"term\":\"germaneness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13817254\"]}");
	add("{\"term\":\"germanic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06959259\"]}");
	add("{\"term\":\"germanism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00415084\"]}");
	add("{\"term\":\"germanist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10147791\"]}");
	add("{\"term\":\"germanite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14700769\"]}");
	add("{\"term\":\"germanium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14662695\"]}");
	add("{\"term\":\"germany\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08784821\"]}");
	add("{\"term\":\"germicide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03212950\"]}");
	add("{\"term\":\"germinal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15201984\"]}");
	add("{\"term\":\"germination\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07338835\", \"13508410\"]}");
	add("{\"term\":\"geronimo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11016673\"]}");
	add("{\"term\":\"gerontocracy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08378647\"]}");
	add("{\"term\":\"gerontologist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10147918\"]}");
	add("{\"term\":\"gerontology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06060181\"]}");
	add("{\"term\":\"gerreidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02639296\"]}");
	add("{\"term\":\"gerres\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02639676\"]}");
	add("{\"term\":\"gerrhonotus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01692319\"]}");
	add("{\"term\":\"gerridae\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02246003\", \"02639296\"]}");
	add("{\"term\":\"gerrididae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02246003\"]}");
	add("{\"term\":\"gerris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02246396\"]}");
	add("{\"term\":\"gerrymander\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00755936\"]}");
	add("{\"term\":\"gershwin\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11016872\", \"11017064\"]}");
	add("{\"term\":\"gerund\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06329345\"]}");
	add("{\"term\":\"geryon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09518082\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }