package org.swtk.commons.dict.wordnet.indexbyname.instance.d.a.m;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceDAM {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"dam\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"01326134\", \"13681341\", \"03164975\"]}");
	add("{\"term\":\"dama\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02435836\"]}");
	add("{\"term\":\"damage\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"00745429\", \"13324337\", \"00403900\", \"07354253\", \"07435370\"]}");
	add("{\"term\":\"damages\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13311699\"]}");
	add("{\"term\":\"damaliscus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02424895\"]}");
	add("{\"term\":\"damar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14919958\"]}");
	add("{\"term\":\"damascene\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03165259\", \"09753012\"]}");
	add("{\"term\":\"damascus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09056411\"]}");
	add("{\"term\":\"damask\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03165406\", \"03165560\"]}");
	add("{\"term\":\"dame\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10008828\", \"10008583\"]}");
	add("{\"term\":\"damgalnunna\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09540477\"]}");
	add("{\"term\":\"daminozide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14732692\"]}");
	add("{\"term\":\"damkina\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09540477\"]}");
	add("{\"term\":\"dammar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14919958\"]}");
	add("{\"term\":\"damn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05148040\"]}");
	add("{\"term\":\"damnation\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"14482041\", \"07248202\"]}");
	add("{\"term\":\"damned\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07962076\"]}");
	add("{\"term\":\"damocles\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10941323\"]}");
	add("{\"term\":\"damoiselle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10008706\"]}");
	add("{\"term\":\"damon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10941631\"]}");
	add("{\"term\":\"damosel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10008706\"]}");
	add("{\"term\":\"damourite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14697830\"]}");
	add("{\"term\":\"damozel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10008706\"]}");
	add("{\"term\":\"damp\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14559507\"]}");
	add("{\"term\":\"dampener\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03165682\"]}");
	add("{\"term\":\"dampening\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00278884\"]}");
	add("{\"term\":\"damper\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"01148418\", \"03166116\", \"03166391\"]}");
	add("{\"term\":\"dampness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14559507\"]}");
	add("{\"term\":\"damsel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10008706\"]}");
	add("{\"term\":\"damselfish\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02609014\"]}");
	add("{\"term\":\"damselfly\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02271505\"]}");
	add("{\"term\":\"damson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07767713\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }