package org.swtk.commons.dict.wordnet.index.name.instance.s.a.n.t;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceSANT {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"santa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10570230\"]}");
	add("{\"term\":\"santalaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12755482\"]}");
	add("{\"term\":\"santalales\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12755206\"]}");
	add("{\"term\":\"santalum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12755769\"]}");
	add("{\"term\":\"santee\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06925614\", \"09687277\"]}");
	add("{\"term\":\"santiago\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"01296325\", \"08739392\", \"08768655\", \"08770504\"]}");
	add("{\"term\":\"santims\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13723499\"]}");
	add("{\"term\":\"santolina\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12029719\"]}");
	add("{\"term\":\"santos\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08875622\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }