package org.swtk.commons.dict.wordnet.indexbyname.instance.p.o.w;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstancePOW {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"pow\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10495916\"]}");
	add("{\"term\":\"pow camp\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04012288\"]}");
	add("{\"term\":\"powder\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04000366\", \"15040881\", \"15021579\"]}");
	add("{\"term\":\"powder and shot\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04000655\"]}");
	add("{\"term\":\"powder blue\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04976608\"]}");
	add("{\"term\":\"powder compact\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03082999\"]}");
	add("{\"term\":\"powder flask\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04000972\"]}");
	add("{\"term\":\"powder horn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04000972\"]}");
	add("{\"term\":\"powder keg\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04001115\", \"14566747\"]}");
	add("{\"term\":\"powder magazine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03709577\"]}");
	add("{\"term\":\"powder metallurgy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06135447\"]}");
	add("{\"term\":\"powder method\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13560788\"]}");
	add("{\"term\":\"powder monkey\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10480846\"]}");
	add("{\"term\":\"powder photography\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13560788\"]}");
	add("{\"term\":\"powder room\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03638254\"]}");
	add("{\"term\":\"powder store\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03709577\"]}");
	add("{\"term\":\"powder technique\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13560788\"]}");
	add("{\"term\":\"powdered ginger\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07831139\"]}");
	add("{\"term\":\"powdered milk\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07862119\"]}");
	add("{\"term\":\"powdered mustard\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04000775\"]}");
	add("{\"term\":\"powdered sugar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07611485\"]}");
	add("{\"term\":\"powderer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10480735\"]}");
	add("{\"term\":\"powderiness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04955246\"]}");
	add("{\"term\":\"powderpuff\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04001232\"]}");
	add("{\"term\":\"powdery mildew\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12984388\"]}");
	add("{\"term\":\"powell\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11264877\", \"11265100\"]}");
	add("{\"term\":\"power\", \"synsetCount\":10, \"upperType\":\"NOUN\", \"ids\":[\"09859605\", \"11470903\", \"08194510\", \"05037846\", \"06825275\", \"10480990\", \"13968154\", \"05624029\", \"11473433\", \"05198072\"]}");
	add("{\"term\":\"power brake\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04001376\"]}");
	add("{\"term\":\"power breakfast\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08402720\"]}");
	add("{\"term\":\"power broker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10481783\"]}");
	add("{\"term\":\"power cable\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04001893\"]}");
	add("{\"term\":\"power company\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08203311\"]}");
	add("{\"term\":\"power cord\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04001623\"]}");
	add("{\"term\":\"power couple\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08005525\"]}");
	add("{\"term\":\"power dive\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00327960\"]}");
	add("{\"term\":\"power drill\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04001730\"]}");
	add("{\"term\":\"power failure\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07436636\"]}");
	add("{\"term\":\"power grid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04003385\"]}");
	add("{\"term\":\"power hammer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03486604\"]}");
	add("{\"term\":\"power hunger\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04843814\"]}");
	add("{\"term\":\"power law\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06005270\"]}");
	add("{\"term\":\"power line\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04001893\"]}");
	add("{\"term\":\"power loading\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13848827\"]}");
	add("{\"term\":\"power loom\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04002019\"]}");
	add("{\"term\":\"power meter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03277721\"]}");
	add("{\"term\":\"power module\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04002104\"]}");
	add("{\"term\":\"power mower\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04002214\"]}");
	add("{\"term\":\"power of appointment\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05041203\"]}");
	add("{\"term\":\"power of attorney\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06542780\"]}");
	add("{\"term\":\"power outage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07436636\"]}");
	add("{\"term\":\"power pack\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04002362\"]}");
	add("{\"term\":\"power plant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04003013\"]}");
	add("{\"term\":\"power play\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"00559433\", \"00561903\", \"00789758\"]}");
	add("{\"term\":\"power point\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03981029\"]}");
	add("{\"term\":\"power politics\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07163646\"]}");
	add("{\"term\":\"power pylon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04035057\"]}");
	add("{\"term\":\"power saw\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04002503\"]}");
	add("{\"term\":\"power series\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05871554\"]}");
	add("{\"term\":\"power service\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08203311\"]}");
	add("{\"term\":\"power shovel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04002774\"]}");
	add("{\"term\":\"power station\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04003013\"]}");
	add("{\"term\":\"power steering\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04003207\"]}");
	add("{\"term\":\"power structure\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08392782\"]}");
	add("{\"term\":\"power system\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04003385\"]}");
	add("{\"term\":\"power takeoff\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04003632\"]}");
	add("{\"term\":\"power tool\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04003842\"]}");
	add("{\"term\":\"power train\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03436655\"]}");
	add("{\"term\":\"power trip\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00812697\"]}");
	add("{\"term\":\"power unit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13656569\"]}");
	add("{\"term\":\"power user\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10482154\"]}");
	add("{\"term\":\"power walking\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00630249\"]}");
	add("{\"term\":\"power worker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10482317\"]}");
	add("{\"term\":\"powerboat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03795763\"]}");
	add("{\"term\":\"powerbroker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10481783\"]}");
	add("{\"term\":\"powerfulness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05198072\"]}");
	add("{\"term\":\"powerhouse\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04003013\", \"08098019\", \"10481995\"]}");
	add("{\"term\":\"powerlessness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05211905\"]}");
	add("{\"term\":\"powhatan\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"06924738\", \"09686181\", \"11265372\"]}");
	add("{\"term\":\"powwow\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08339360\", \"07159124\"]}");
	add("{\"term\":\"powys\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"11265580\", \"11265734\", \"11265892\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }