package org.swtk.commons.dict.wordnet.indexbyname.instance.a.s.p;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceASP {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"asp\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01751030\", \"01755377\"]}");
	add("{\"term\":\"asp viper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01755377\"]}");
	add("{\"term\":\"aspadana\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08931785\"]}");
	add("{\"term\":\"aspalathus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12528175\"]}");
	add("{\"term\":\"aspalathus cedcarbergensis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12528328\"]}");
	add("{\"term\":\"aspalathus linearis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12528328\"]}");
	add("{\"term\":\"asparagaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12461128\"]}");
	add("{\"term\":\"asparaginase\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02750920\"]}");
	add("{\"term\":\"asparagine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14627029\"]}");
	add("{\"term\":\"asparagus\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07734958\", \"12461688\"]}");
	add("{\"term\":\"asparagus asparagoides\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12462057\"]}");
	add("{\"term\":\"asparagus bean\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12599786\"]}");
	add("{\"term\":\"asparagus bed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02751093\"]}");
	add("{\"term\":\"asparagus fern\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12461895\"]}");
	add("{\"term\":\"asparagus officinales\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12461688\"]}");
	add("{\"term\":\"asparagus pea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12566370\"]}");
	add("{\"term\":\"asparagus plumosus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12461895\"]}");
	add("{\"term\":\"asparagus setaceous\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12461895\"]}");
	add("{\"term\":\"aspartame\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07874817\"]}");
	add("{\"term\":\"aspartic acid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14627165\"]}");
	add("{\"term\":\"aspect\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"04687095\", \"13826881\", \"05941982\", \"04740358\", \"05859151\"]}");
	add("{\"term\":\"aspect ratio\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13842756\"]}");
	add("{\"term\":\"aspen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12754407\"]}");
	add("{\"term\":\"aspen poplar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12752769\"]}");
	add("{\"term\":\"asper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13709525\"]}");
	add("{\"term\":\"aspergill\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02751188\"]}");
	add("{\"term\":\"aspergillaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13047950\"]}");
	add("{\"term\":\"aspergillales\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13047523\"]}");
	add("{\"term\":\"aspergillosis\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"14095041\", \"14206353\", \"14283851\"]}");
	add("{\"term\":\"aspergillus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13048135\"]}");
	add("{\"term\":\"aspergillus fumigatus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13048317\"]}");
	add("{\"term\":\"asperity\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04650456\", \"04717403\"]}");
	add("{\"term\":\"aspersion\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"01040293\", \"01222825\", \"06731387\"]}");
	add("{\"term\":\"aspersorium\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02751188\", \"02751364\"]}");
	add("{\"term\":\"asperula\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12682181\"]}");
	add("{\"term\":\"asperula odorata\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12686032\"]}");
	add("{\"term\":\"asperula tinctoria\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12682422\"]}");
	add("{\"term\":\"asphalt\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"14691634\", \"14793644\"]}");
	add("{\"term\":\"asphodel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12462463\"]}");
	add("{\"term\":\"asphodelaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12462275\"]}");
	add("{\"term\":\"asphodeline\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12462725\"]}");
	add("{\"term\":\"asphodeline lutea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12463202\"]}");
	add("{\"term\":\"asphodelus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12463370\"]}");
	add("{\"term\":\"asphyxia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14065905\"]}");
	add("{\"term\":\"asphyxiation\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00226460\", \"14067364\"]}");
	add("{\"term\":\"asphyxiator\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03350683\"]}");
	add("{\"term\":\"aspic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07824651\"]}");
	add("{\"term\":\"aspidelaps\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01749459\"]}");
	add("{\"term\":\"aspidelaps lubricus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01749593\"]}");
	add("{\"term\":\"aspidiotus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02252325\"]}");
	add("{\"term\":\"aspidiotus perniciosus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02252461\"]}");
	add("{\"term\":\"aspidistra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12463828\"]}");
	add("{\"term\":\"aspidistra elatio\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12463828\"]}");
	add("{\"term\":\"aspidophoroides\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02650804\"]}");
	add("{\"term\":\"aspidophoroides monopterygius\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02650943\"]}");
	add("{\"term\":\"aspinwall\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08757502\"]}");
	add("{\"term\":\"aspirant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09820956\"]}");
	add("{\"term\":\"aspirate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07131466\"]}");
	add("{\"term\":\"aspiration\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"00838449\", \"07131577\", \"07499687\", \"04843722\"]}");
	add("{\"term\":\"aspiration pneumonia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14284052\"]}");
	add("{\"term\":\"aspirator\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02751496\"]}");
	add("{\"term\":\"aspirer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09820956\"]}");
	add("{\"term\":\"aspirin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02751623\"]}");
	add("{\"term\":\"aspirin powder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02752174\"]}");
	add("{\"term\":\"aspis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01755995\"]}");
	add("{\"term\":\"aspleniaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13200870\"]}");
	add("{\"term\":\"asplenium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13201202\"]}");
	add("{\"term\":\"asplenium billotii\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13203835\"]}");
	add("{\"term\":\"asplenium bradleyi\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13203560\"]}");
	add("{\"term\":\"asplenium ceterach\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13204387\"]}");
	add("{\"term\":\"asplenium montanum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13203236\"]}");
	add("{\"term\":\"asplenium nidus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13201953\"]}");
	add("{\"term\":\"asplenium nigripes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13204899\"]}");
	add("{\"term\":\"asplenium pinnatifidum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13203697\"]}");
	add("{\"term\":\"asplenium platyneuron\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13202142\"]}");
	add("{\"term\":\"asplenium rhizophyllum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13202709\"]}");
	add("{\"term\":\"asplenium scolopendrium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13203954\"]}");
	add("{\"term\":\"asplenium trichomanes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13202886\"]}");
	add("{\"term\":\"asplenium viride\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13203062\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }