package org.swtk.commons.dict.wordnet.index.name.instance.g.e.o.p;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceGEOP {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"geophagia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00842559\"]}");
	add("{\"term\":\"geophagy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00842559\"]}");
	add("{\"term\":\"geophilidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01788689\"]}");
	add("{\"term\":\"geophilomorpha\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01788472\"]}");
	add("{\"term\":\"geophilus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01788860\"]}");
	add("{\"term\":\"geophysicist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10148056\"]}");
	add("{\"term\":\"geophysics\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06127169\"]}");
	add("{\"term\":\"geophyte\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13141717\"]}");
	add("{\"term\":\"geopolitics\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06158199\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public boolean has(final String TERM) { 		return map.containsKey(TERM); 	} }