package org.swtk.commons.dict.wordnet.indexbyname.instance.h.o.r;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceHOR {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"horace\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11080411\"]}");
	add("{\"term\":\"horace greeley\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11033187\"]}");
	add("{\"term\":\"horace mann\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11174164\"]}");
	add("{\"term\":\"horace walpole\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11392594\"]}");
	add("{\"term\":\"horatian ode\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06395577\"]}");
	add("{\"term\":\"horatio alger\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10833131\"]}");
	add("{\"term\":\"horatio herbert kitchener\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11126469\"]}");
	add("{\"term\":\"horatio hornblower\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09623613\"]}");
	add("{\"term\":\"horatio nelson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11223049\"]}");
	add("{\"term\":\"horatio walpole\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11392594\"]}");
	add("{\"term\":\"horde\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"08201135\", \"08267810\", \"08199880\"]}");
	add("{\"term\":\"hordeolum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14208701\"]}");
	add("{\"term\":\"hordeum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12143567\"]}");
	add("{\"term\":\"hordeum jubatum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12144449\"]}");
	add("{\"term\":\"hordeum murinum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12144258\"]}");
	add("{\"term\":\"hordeum pusillum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12144689\"]}");
	add("{\"term\":\"hordeum vulgare\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12143967\"]}");
	add("{\"term\":\"horehound\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07622028\", \"12874808\"]}");
	add("{\"term\":\"horizon\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"08603373\", \"08675749\", \"05135047\", \"08603184\"]}");
	add("{\"term\":\"horizontal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13850894\"]}");
	add("{\"term\":\"horizontal bar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03540960\"]}");
	add("{\"term\":\"horizontal combination\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01241412\"]}");
	add("{\"term\":\"horizontal integration\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01241412\"]}");
	add("{\"term\":\"horizontal parallax\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11549609\"]}");
	add("{\"term\":\"horizontal section\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03541150\"]}");
	add("{\"term\":\"horizontal stabiliser\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03541302\"]}");
	add("{\"term\":\"horizontal stabilizer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03541302\"]}");
	add("{\"term\":\"horizontal surface\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03541528\"]}");
	add("{\"term\":\"horizontal tail\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03541748\"]}");
	add("{\"term\":\"horizontality\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05086681\"]}");
	add("{\"term\":\"hormone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05414462\"]}");
	add("{\"term\":\"hormone replacement therapy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00664337\"]}");
	add("{\"term\":\"horn\", \"synsetCount\":11, \"upperType\":\"NOUN\", \"ids\":[\"02764839\", \"03399752\", \"03541941\", \"03542421\", \"14782206\", \"01328494\", \"03115320\", \"03542111\", \"07280214\", \"01328058\", \"03542265\"]}");
	add("{\"term\":\"horn button\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03542593\"]}");
	add("{\"term\":\"horn fly\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02202154\"]}");
	add("{\"term\":\"horn of africa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09021524\"]}");
	add("{\"term\":\"horn of plenty\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06820979\"]}");
	add("{\"term\":\"horn poppy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11926218\"]}");
	add("{\"term\":\"hornbeam\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12307343\"]}");
	add("{\"term\":\"hornbill\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01832054\"]}");
	add("{\"term\":\"hornblende\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14750303\"]}");
	add("{\"term\":\"hornbook\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06433181\"]}");
	add("{\"term\":\"horne\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11080530\", \"11080683\"]}");
	add("{\"term\":\"horned asp\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01756129\"]}");
	add("{\"term\":\"horned chameleon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01696952\"]}");
	add("{\"term\":\"horned dinosaur\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01706210\"]}");
	add("{\"term\":\"horned lizard\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01684581\"]}");
	add("{\"term\":\"horned owl\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01624993\"]}");
	add("{\"term\":\"horned pondweed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12638907\"]}");
	add("{\"term\":\"horned poppy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11926218\"]}");
	add("{\"term\":\"horned pout\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02521971\"]}");
	add("{\"term\":\"horned puffin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02050769\"]}");
	add("{\"term\":\"horned rattlesnake\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01758932\"]}");
	add("{\"term\":\"horned screamer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01863505\"]}");
	add("{\"term\":\"horned toad\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01684581\"]}");
	add("{\"term\":\"horned violet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12409506\"]}");
	add("{\"term\":\"horned viper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01756129\"]}");
	add("{\"term\":\"horned whiff\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02665027\"]}");
	add("{\"term\":\"horneophyton\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13239402\"]}");
	add("{\"term\":\"hornet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02215759\"]}");
	add("{\"term\":\"horney\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11080800\"]}");
	add("{\"term\":\"hornfels\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14723229\"]}");
	add("{\"term\":\"horniness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14061509\"]}");
	add("{\"term\":\"hornist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10205102\"]}");
	add("{\"term\":\"hornpipe\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"03542731\", \"07069760\", \"00539913\"]}");
	add("{\"term\":\"hornpout\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02521971\"]}");
	add("{\"term\":\"hornstone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14723229\"]}");
	add("{\"term\":\"hornwort\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11559271\", \"11722721\"]}");
	add("{\"term\":\"horny frog\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01684581\"]}");
	add("{\"term\":\"horny layer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05250420\"]}");
	add("{\"term\":\"horny structure\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05589145\"]}");
	add("{\"term\":\"horologe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04445087\"]}");
	add("{\"term\":\"horologer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10789573\"]}");
	add("{\"term\":\"horologist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10789573\"]}");
	add("{\"term\":\"horology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05643686\"]}");
	add("{\"term\":\"horoscope\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03542895\", \"06762308\"]}");
	add("{\"term\":\"horoscopy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05786643\"]}");
	add("{\"term\":\"horowitz\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11080932\"]}");
	add("{\"term\":\"horridness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04789380\"]}");
	add("{\"term\":\"horripilation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00868284\"]}");
	add("{\"term\":\"horror\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"07519226\", \"03543047\", \"07535650\"]}");
	add("{\"term\":\"horse\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"03629976\", \"04147696\", \"08414813\", \"03543217\", \"02377103\"]}");
	add("{\"term\":\"horse balm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12865169\"]}");
	add("{\"term\":\"horse barn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04302017\"]}");
	add("{\"term\":\"horse bean\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07817868\"]}");
	add("{\"term\":\"horse blanket\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04131303\"]}");
	add("{\"term\":\"horse botfly\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02196317\"]}");
	add("{\"term\":\"horse breeding\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00917477\"]}");
	add("{\"term\":\"horse brier\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12491017\"]}");
	add("{\"term\":\"horse cart\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03543586\"]}");
	add("{\"term\":\"horse cassia\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12512965\", \"12513405\"]}");
	add("{\"term\":\"horse cavalry\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08406857\", \"08414813\"]}");
	add("{\"term\":\"horse chestnut\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12789442\", \"12789129\"]}");
	add("{\"term\":\"horse doctor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10205210\"]}");
	add("{\"term\":\"horse fancier\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10205301\"]}");
	add("{\"term\":\"horse fly\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02198178\"]}");
	add("{\"term\":\"horse gentian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12700637\"]}");
	add("{\"term\":\"horse grain\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12568377\"]}");
	add("{\"term\":\"horse gram\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12568377\"]}");
	add("{\"term\":\"horse latitude\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08603563\"]}");
	add("{\"term\":\"horse mackerel\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"02583310\", \"02583461\", \"02629922\"]}");
	add("{\"term\":\"horse manure\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14888230\"]}");
	add("{\"term\":\"horse mushroom\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13022126\"]}");
	add("{\"term\":\"horse nettle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12914753\"]}");
	add("{\"term\":\"horse of the wood\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01799661\"]}");
	add("{\"term\":\"horse opera\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06628388\"]}");
	add("{\"term\":\"horse parsley\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12966588\"]}");
	add("{\"term\":\"horse pistol\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03544473\"]}");
	add("{\"term\":\"horse race\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07476368\"]}");
	add("{\"term\":\"horse racing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00451055\"]}");
	add("{\"term\":\"horse radish\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11893442\"]}");
	add("{\"term\":\"horse sense\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05622440\"]}");
	add("{\"term\":\"horse thistle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12007980\"]}");
	add("{\"term\":\"horse tick\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02201511\"]}");
	add("{\"term\":\"horse trade\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01111839\"]}");
	add("{\"term\":\"horse trader\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10205687\"]}");
	add("{\"term\":\"horse trading\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07165207\", \"01111839\"]}");
	add("{\"term\":\"horse wrangler\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10205835\"]}");
	add("{\"term\":\"horseback\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09327282\", \"01904915\"]}");
	add("{\"term\":\"horseback rider\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10205412\"]}");
	add("{\"term\":\"horseback riding\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00300043\", \"00451320\"]}");
	add("{\"term\":\"horsebean\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12518174\", \"12596828\"]}");
	add("{\"term\":\"horsebox\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03543359\"]}");
	add("{\"term\":\"horsecar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03543480\"]}");
	add("{\"term\":\"horsecloth\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03543722\"]}");
	add("{\"term\":\"horsefish\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02580864\"]}");
	add("{\"term\":\"horseflesh\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07682151\"]}");
	add("{\"term\":\"horsefly\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02198178\", \"02201511\"]}");
	add("{\"term\":\"horsefly weed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12530498\"]}");
	add("{\"term\":\"horsehair\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03543997\", \"14932735\"]}");
	add("{\"term\":\"horsehair lichen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13011357\"]}");
	add("{\"term\":\"horsehair wig\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03544137\"]}");
	add("{\"term\":\"horsehead\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02580864\"]}");
	add("{\"term\":\"horsehide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14786937\"]}");
	add("{\"term\":\"horselaugh\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07142619\"]}");
	add("{\"term\":\"horseleech\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01941376\"]}");
	add("{\"term\":\"horseless carriage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03544283\"]}");
	add("{\"term\":\"horseman\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10205301\", \"10205412\"]}");
	add("{\"term\":\"horsemanship\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05646219\"]}");
	add("{\"term\":\"horsemeat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07682151\"]}");
	add("{\"term\":\"horsemint\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"12876646\", \"12879378\", \"12879747\"]}");
	add("{\"term\":\"horseplay\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00514772\"]}");
	add("{\"term\":\"horsepond\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09328552\"]}");
	add("{\"term\":\"horsepower\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13666489\"]}");
	add("{\"term\":\"horseradish\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"07840359\", \"11893442\", \"11893651\"]}");
	add("{\"term\":\"horseradish peroxidase\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14636796\"]}");
	add("{\"term\":\"horseradish root\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11893651\"]}");
	add("{\"term\":\"horseradish sauce\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07846817\"]}");
	add("{\"term\":\"horseshit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06623729\"]}");
	add("{\"term\":\"horseshoe\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03544613\", \"03544726\"]}");
	add("{\"term\":\"horseshoe arch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03790429\"]}");
	add("{\"term\":\"horseshoe bat\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02146091\", \"02146543\"]}");
	add("{\"term\":\"horseshoe crab\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01790476\"]}");
	add("{\"term\":\"horseshoe falls\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09255072\"]}");
	add("{\"term\":\"horseshoe vetch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12555759\"]}");
	add("{\"term\":\"horseshoe whipsnake\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01733918\"]}");
	add("{\"term\":\"horseshoer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10099457\"]}");
	add("{\"term\":\"horseshoes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00468388\"]}");
	add("{\"term\":\"horseshow\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00520635\"]}");
	add("{\"term\":\"horsetail\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13240320\"]}");
	add("{\"term\":\"horsetail family\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13239965\"]}");
	add("{\"term\":\"horsetail lichen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13011357\"]}");
	add("{\"term\":\"horsetail milkweed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13256217\"]}");
	add("{\"term\":\"horseweed\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11976817\", \"12865169\"]}");
	add("{\"term\":\"horsewhip\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03544934\"]}");
	add("{\"term\":\"horsewhipping\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01165919\"]}");
	add("{\"term\":\"horsewoman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10205762\"]}");
	add("{\"term\":\"horsey set\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08268526\"]}");
	add("{\"term\":\"horst\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09328634\"]}");
	add("{\"term\":\"horsy set\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08268526\"]}");
	add("{\"term\":\"horta\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11081084\"]}");
	add("{\"term\":\"hortensia\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12029516\", \"12809614\"]}");
	add("{\"term\":\"horticulture\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00920197\"]}");
	add("{\"term\":\"horticulturist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10205969\"]}");
	add("{\"term\":\"horus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09535401\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }