package org.swtk.commons.dict.wordnet.indexbyname.instance.g.a.r;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceGAR {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"gar\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02552620\", \"02644009\"]}");
	add("{\"term\":\"garage\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03421550\", \"03421399\"]}");
	add("{\"term\":\"garambulla\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07784981\", \"11870990\"]}");
	add("{\"term\":\"garamycin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03440292\"]}");
	add("{\"term\":\"garand\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03421685\"]}");
	add("{\"term\":\"garb\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02759103\"]}");
	add("{\"term\":\"garbage\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"03421810\", \"06624619\", \"14881302\"]}");
	add("{\"term\":\"garbageman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10139987\"]}");
	add("{\"term\":\"garbanzo\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07742071\", \"12536430\"]}");
	add("{\"term\":\"garbo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11009797\"]}");
	add("{\"term\":\"garboard\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03422112\"]}");
	add("{\"term\":\"garboil\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14002194\"]}");
	add("{\"term\":\"garbology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06157221\"]}");
	add("{\"term\":\"garcinia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12387024\"]}");
	add("{\"term\":\"garden\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"03422659\", \"08456800\", \"03422255\"]}");
	add("{\"term\":\"gardener\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10140328\", \"10140190\"]}");
	add("{\"term\":\"gardenia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12687529\"]}");
	add("{\"term\":\"gardening\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00920197\"]}");
	add("{\"term\":\"gardiner\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11010208\"]}");
	add("{\"term\":\"gardner\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11010367\", \"11010505\"]}");
	add("{\"term\":\"garfield\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11010729\"]}");
	add("{\"term\":\"garfish\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02644009\"]}");
	add("{\"term\":\"garganey\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01851196\"]}");
	add("{\"term\":\"gargantua\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09511578\"]}");
	add("{\"term\":\"garget\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11876022\"]}");
	add("{\"term\":\"gargle\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07398623\", \"14872812\"]}");
	add("{\"term\":\"gargoyle\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03423398\", \"03423528\"]}");
	add("{\"term\":\"gargoylism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14180645\"]}");
	add("{\"term\":\"gari\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12947449\"]}");
	add("{\"term\":\"garibaldi\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03423659\", \"11010959\"]}");
	add("{\"term\":\"garishness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04698100\", \"04825931\"]}");
	add("{\"term\":\"garland\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"04613372\", \"06604903\", \"09167467\", \"11011161\"]}");
	add("{\"term\":\"garlic\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07834253\", \"12455280\"]}");
	add("{\"term\":\"garment\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03423924\"]}");
	add("{\"term\":\"garmentmaker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10140473\"]}");
	add("{\"term\":\"garner\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03457393\"]}");
	add("{\"term\":\"garnet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14700203\"]}");
	add("{\"term\":\"garnier\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11011299\"]}");
	add("{\"term\":\"garnierite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14700487\"]}");
	add("{\"term\":\"garnish\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03425350\", \"07637227\"]}");
	add("{\"term\":\"garnishee\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10140801\"]}");
	add("{\"term\":\"garnishment\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06569818\"]}");
	add("{\"term\":\"garonne\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09310030\"]}");
	add("{\"term\":\"garotte\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03425845\"]}");
	add("{\"term\":\"garpike\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02644009\"]}");
	add("{\"term\":\"garret\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03691456\"]}");
	add("{\"term\":\"garrick\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11011411\"]}");
	add("{\"term\":\"garrison\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"08414993\", \"11011579\", \"03425469\"]}");
	add("{\"term\":\"garrote\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03425845\"]}");
	add("{\"term\":\"garroter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10140903\"]}");
	add("{\"term\":\"garrotte\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03425845\"]}");
	add("{\"term\":\"garrotter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10140903\"]}");
	add("{\"term\":\"garrulinae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01582509\"]}");
	add("{\"term\":\"garrulity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04658739\"]}");
	add("{\"term\":\"garrulousness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04658739\"]}");
	add("{\"term\":\"garrulus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01582866\"]}");
	add("{\"term\":\"garter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03426027\"]}");
	add("{\"term\":\"garuda\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09549241\"]}");
	add("{\"term\":\"gary\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09107986\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }