package org.swtk.commons.dict.wordnet.indexbyname.instance.v.i.s;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceVIS {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"vis major\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07329950\"]}");
	add("{\"term\":\"visa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06700628\"]}");
	add("{\"term\":\"visage\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04686906\", \"05609112\"]}");
	add("{\"term\":\"visayan\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10775316\"]}");
	add("{\"term\":\"visayan islands\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09004822\"]}");
	add("{\"term\":\"viscaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12759619\"]}");
	add("{\"term\":\"viscacha\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02370768\"]}");
	add("{\"term\":\"viscera\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05306487\"]}");
	add("{\"term\":\"visceral brain\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05506424\"]}");
	add("{\"term\":\"visceral leishmaniasis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14204531\"]}");
	add("{\"term\":\"visceral pericardium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05436222\"]}");
	add("{\"term\":\"visceral pleura\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05395780\"]}");
	add("{\"term\":\"viscid mushroom\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13029845\"]}");
	add("{\"term\":\"viscidity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04943081\"]}");
	add("{\"term\":\"viscidness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04943081\"]}");
	add("{\"term\":\"viscometer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04545544\"]}");
	add("{\"term\":\"viscometry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01119639\"]}");
	add("{\"term\":\"visconti\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11387576\"]}");
	add("{\"term\":\"viscose\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04545698\", \"14989955\"]}");
	add("{\"term\":\"viscose rayon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04545698\"]}");
	add("{\"term\":\"viscosimeter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04545544\"]}");
	add("{\"term\":\"viscosimetry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01119639\"]}");
	add("{\"term\":\"viscosity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04942180\"]}");
	add("{\"term\":\"viscount\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10775483\", \"10775816\"]}");
	add("{\"term\":\"viscount nelson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11223049\"]}");
	add("{\"term\":\"viscount northcliffe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11049294\"]}");
	add("{\"term\":\"viscountcy\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06354810\", \"14456698\"]}");
	add("{\"term\":\"viscountess\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10775594\", \"10775729\"]}");
	add("{\"term\":\"viscountess astor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10846321\"]}");
	add("{\"term\":\"viscounty\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08575513\", \"14456698\"]}");
	add("{\"term\":\"viscousness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04942180\"]}");
	add("{\"term\":\"viscum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12759832\"]}");
	add("{\"term\":\"viscum album\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12760092\"]}");
	add("{\"term\":\"viscus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05306228\"]}");
	add("{\"term\":\"vise\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04545847\"]}");
	add("{\"term\":\"vishnu\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09553121\"]}");
	add("{\"term\":\"vishnuism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06249351\"]}");
	add("{\"term\":\"visibility\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04709893\", \"14457795\", \"05024624\"]}");
	add("{\"term\":\"visible balance\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13430536\"]}");
	add("{\"term\":\"visible horizon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08603184\"]}");
	add("{\"term\":\"visible light\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11494354\"]}");
	add("{\"term\":\"visible radiation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11494354\"]}");
	add("{\"term\":\"visible spectrum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11543802\"]}");
	add("{\"term\":\"visible speech\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04546054\", \"06512630\"]}");
	add("{\"term\":\"visibleness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05024624\"]}");
	add("{\"term\":\"visigoth\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10775929\"]}");
	add("{\"term\":\"vision\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"07303190\", \"05633248\", \"05721471\", \"05662207\", \"05776249\"]}");
	add("{\"term\":\"vision defect\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14576394\"]}");
	add("{\"term\":\"visionary\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10776101\", \"10776309\"]}");
	add("{\"term\":\"visit\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"01057284\", \"01235249\", \"01235407\", \"08402011\", \"01235721\"]}");
	add("{\"term\":\"visitant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10776861\"]}");
	add("{\"term\":\"visitation\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"00653312\", \"07331324\", \"07387559\"]}");
	add("{\"term\":\"visitation right\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05197854\"]}");
	add("{\"term\":\"visiting\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01058160\"]}");
	add("{\"term\":\"visiting card\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06645712\"]}");
	add("{\"term\":\"visiting fireman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10776505\"]}");
	add("{\"term\":\"visiting nurse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10776605\"]}");
	add("{\"term\":\"visiting professor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10776718\"]}");
	add("{\"term\":\"visitor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10776861\"]}");
	add("{\"term\":\"visken\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03948520\"]}");
	add("{\"term\":\"visor\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02841963\", \"04546173\"]}");
	add("{\"term\":\"vista\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05941982\"]}");
	add("{\"term\":\"vistaril\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03559311\"]}");
	add("{\"term\":\"vistula\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09495265\"]}");
	add("{\"term\":\"vistula river\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09495265\"]}");
	add("{\"term\":\"visual acuity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05663412\"]}");
	add("{\"term\":\"visual agnosia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14123852\"]}");
	add("{\"term\":\"visual aphasia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14122532\"]}");
	add("{\"term\":\"visual area\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05497856\"]}");
	add("{\"term\":\"visual aspect\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04681322\"]}");
	add("{\"term\":\"visual cell\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05463488\"]}");
	add("{\"term\":\"visual communication\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06886302\"]}");
	add("{\"term\":\"visual cortex\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05497856\"]}");
	add("{\"term\":\"visual defect\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14576394\"]}");
	add("{\"term\":\"visual disorder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14576394\"]}");
	add("{\"term\":\"visual display unit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04546348\"]}");
	add("{\"term\":\"visual field\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05942374\"]}");
	add("{\"term\":\"visual hallucination\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14401844\"]}");
	add("{\"term\":\"visual image\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05941213\", \"05945099\"]}");
	add("{\"term\":\"visual impairment\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14576394\"]}");
	add("{\"term\":\"visual joke\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06792753\"]}");
	add("{\"term\":\"visual modality\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05662207\"]}");
	add("{\"term\":\"visual percept\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05941213\"]}");
	add("{\"term\":\"visual perception\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05718807\"]}");
	add("{\"term\":\"visual property\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04957303\"]}");
	add("{\"term\":\"visual purple\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15113436\"]}");
	add("{\"term\":\"visual range\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05024923\"]}");
	add("{\"term\":\"visual sensation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05721471\"]}");
	add("{\"term\":\"visual sense\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05662207\"]}");
	add("{\"term\":\"visual signal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06886621\"]}");
	add("{\"term\":\"visual space\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05719361\"]}");
	add("{\"term\":\"visual system\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05308425\"]}");
	add("{\"term\":\"visualisation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05945099\"]}");
	add("{\"term\":\"visualiser\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10777160\"]}");
	add("{\"term\":\"visualization\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05945099\"]}");
	add("{\"term\":\"visualizer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10777160\"]}");
	add("{\"term\":\"visually impaired person\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10777293\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }