package org.swtk.commons.dict.wordnet.index.name.controller.r.u;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.a.n.WordnetNounIndexNameInstanceRUAN;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.b.a.WordnetNounIndexNameInstanceRUBA;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.b.b.WordnetNounIndexNameInstanceRUBB;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.b.d.WordnetNounIndexNameInstanceRUBD;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.b.e.WordnetNounIndexNameInstanceRUBE;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.b.i.WordnetNounIndexNameInstanceRUBI;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.b.l.WordnetNounIndexNameInstanceRUBL;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.b.o.WordnetNounIndexNameInstanceRUBO;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.b.r.WordnetNounIndexNameInstanceRUBR;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.b.u.WordnetNounIndexNameInstanceRUBU;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.b.y.WordnetNounIndexNameInstanceRUBY;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.c.k.WordnetNounIndexNameInstanceRUCK;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.c.t.WordnetNounIndexNameInstanceRUCT;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.d.a.WordnetNounIndexNameInstanceRUDA;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.d.b.WordnetNounIndexNameInstanceRUDB;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.d.d.WordnetNounIndexNameInstanceRUDD;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.d.e.WordnetNounIndexNameInstanceRUDE;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.d.i.WordnetNounIndexNameInstanceRUDI;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.d.r.WordnetNounIndexNameInstanceRUDR;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.e.f.WordnetNounIndexNameInstanceRUEF;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.f.f.WordnetNounIndexNameInstanceRUFF;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.g.a.WordnetNounIndexNameInstanceRUGA;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.g.b.WordnetNounIndexNameInstanceRUGB;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.g.e.WordnetNounIndexNameInstanceRUGE;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.g.g.WordnetNounIndexNameInstanceRUGG;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.g.u.WordnetNounIndexNameInstanceRUGU;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.h.r.WordnetNounIndexNameInstanceRUHR;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.i.n.WordnetNounIndexNameInstanceRUIN;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.l.e.WordnetNounIndexNameInstanceRULE;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.l.i.WordnetNounIndexNameInstanceRULI;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.m.a.WordnetNounIndexNameInstanceRUMA;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.m.b.WordnetNounIndexNameInstanceRUMB;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.m.e.WordnetNounIndexNameInstanceRUME;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.m.i.WordnetNounIndexNameInstanceRUMI;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.m.m.WordnetNounIndexNameInstanceRUMM;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.m.o.WordnetNounIndexNameInstanceRUMO;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.m.p.WordnetNounIndexNameInstanceRUMP;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.m.r.WordnetNounIndexNameInstanceRUMR;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.n.a.WordnetNounIndexNameInstanceRUNA;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.n.c.WordnetNounIndexNameInstanceRUNC;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.n.d.WordnetNounIndexNameInstanceRUND;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.n.e.WordnetNounIndexNameInstanceRUNE;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.n.g.WordnetNounIndexNameInstanceRUNG;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.n.n.WordnetNounIndexNameInstanceRUNN;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.n.o.WordnetNounIndexNameInstanceRUNO;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.n.t.WordnetNounIndexNameInstanceRUNT;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.n.u.WordnetNounIndexNameInstanceRUNU;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.n.w.WordnetNounIndexNameInstanceRUNW;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.n.y.WordnetNounIndexNameInstanceRUNY;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.p.e.WordnetNounIndexNameInstanceRUPE;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.p.i.WordnetNounIndexNameInstanceRUPI;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.p.t.WordnetNounIndexNameInstanceRUPT;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.r.a.WordnetNounIndexNameInstanceRURA;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.r.i.WordnetNounIndexNameInstanceRURI;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.s.c.WordnetNounIndexNameInstanceRUSC;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.s.e.WordnetNounIndexNameInstanceRUSE;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.s.h.WordnetNounIndexNameInstanceRUSH;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.s.k.WordnetNounIndexNameInstanceRUSK;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.s.s.WordnetNounIndexNameInstanceRUSS;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.s.t.WordnetNounIndexNameInstanceRUST;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.t.a.WordnetNounIndexNameInstanceRUTA;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.t.h.WordnetNounIndexNameInstanceRUTH;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.t.i.WordnetNounIndexNameInstanceRUTI;
	import org.swtk.commons.dict.wordnet.index.name.instance.r.u.t.l.WordnetNounIndexNameInstanceRUTL;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerRU {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("ruan".equals(key)) return WordnetNounIndexNameInstanceRUAN.get(TERM);
	if ("ruba".equals(key)) return WordnetNounIndexNameInstanceRUBA.get(TERM);
	if ("rubb".equals(key)) return WordnetNounIndexNameInstanceRUBB.get(TERM);
	if ("rubd".equals(key)) return WordnetNounIndexNameInstanceRUBD.get(TERM);
	if ("rube".equals(key)) return WordnetNounIndexNameInstanceRUBE.get(TERM);
	if ("rubi".equals(key)) return WordnetNounIndexNameInstanceRUBI.get(TERM);
	if ("rubl".equals(key)) return WordnetNounIndexNameInstanceRUBL.get(TERM);
	if ("rubo".equals(key)) return WordnetNounIndexNameInstanceRUBO.get(TERM);
	if ("rubr".equals(key)) return WordnetNounIndexNameInstanceRUBR.get(TERM);
	if ("rubu".equals(key)) return WordnetNounIndexNameInstanceRUBU.get(TERM);
	if ("ruby".equals(key)) return WordnetNounIndexNameInstanceRUBY.get(TERM);
	if ("ruck".equals(key)) return WordnetNounIndexNameInstanceRUCK.get(TERM);
	if ("ruct".equals(key)) return WordnetNounIndexNameInstanceRUCT.get(TERM);
	if ("ruda".equals(key)) return WordnetNounIndexNameInstanceRUDA.get(TERM);
	if ("rudb".equals(key)) return WordnetNounIndexNameInstanceRUDB.get(TERM);
	if ("rudd".equals(key)) return WordnetNounIndexNameInstanceRUDD.get(TERM);
	if ("rude".equals(key)) return WordnetNounIndexNameInstanceRUDE.get(TERM);
	if ("rudi".equals(key)) return WordnetNounIndexNameInstanceRUDI.get(TERM);
	if ("rudr".equals(key)) return WordnetNounIndexNameInstanceRUDR.get(TERM);
	if ("ruef".equals(key)) return WordnetNounIndexNameInstanceRUEF.get(TERM);
	if ("ruff".equals(key)) return WordnetNounIndexNameInstanceRUFF.get(TERM);
	if ("ruga".equals(key)) return WordnetNounIndexNameInstanceRUGA.get(TERM);
	if ("rugb".equals(key)) return WordnetNounIndexNameInstanceRUGB.get(TERM);
	if ("ruge".equals(key)) return WordnetNounIndexNameInstanceRUGE.get(TERM);
	if ("rugg".equals(key)) return WordnetNounIndexNameInstanceRUGG.get(TERM);
	if ("rugu".equals(key)) return WordnetNounIndexNameInstanceRUGU.get(TERM);
	if ("ruhr".equals(key)) return WordnetNounIndexNameInstanceRUHR.get(TERM);
	if ("ruin".equals(key)) return WordnetNounIndexNameInstanceRUIN.get(TERM);
	if ("rule".equals(key)) return WordnetNounIndexNameInstanceRULE.get(TERM);
	if ("ruli".equals(key)) return WordnetNounIndexNameInstanceRULI.get(TERM);
	if ("ruma".equals(key)) return WordnetNounIndexNameInstanceRUMA.get(TERM);
	if ("rumb".equals(key)) return WordnetNounIndexNameInstanceRUMB.get(TERM);
	if ("rume".equals(key)) return WordnetNounIndexNameInstanceRUME.get(TERM);
	if ("rumi".equals(key)) return WordnetNounIndexNameInstanceRUMI.get(TERM);
	if ("rumm".equals(key)) return WordnetNounIndexNameInstanceRUMM.get(TERM);
	if ("rumo".equals(key)) return WordnetNounIndexNameInstanceRUMO.get(TERM);
	if ("rump".equals(key)) return WordnetNounIndexNameInstanceRUMP.get(TERM);
	if ("rumr".equals(key)) return WordnetNounIndexNameInstanceRUMR.get(TERM);
	if ("runa".equals(key)) return WordnetNounIndexNameInstanceRUNA.get(TERM);
	if ("runc".equals(key)) return WordnetNounIndexNameInstanceRUNC.get(TERM);
	if ("rund".equals(key)) return WordnetNounIndexNameInstanceRUND.get(TERM);
	if ("rune".equals(key)) return WordnetNounIndexNameInstanceRUNE.get(TERM);
	if ("rung".equals(key)) return WordnetNounIndexNameInstanceRUNG.get(TERM);
	if ("runn".equals(key)) return WordnetNounIndexNameInstanceRUNN.get(TERM);
	if ("runo".equals(key)) return WordnetNounIndexNameInstanceRUNO.get(TERM);
	if ("runt".equals(key)) return WordnetNounIndexNameInstanceRUNT.get(TERM);
	if ("runu".equals(key)) return WordnetNounIndexNameInstanceRUNU.get(TERM);
	if ("runw".equals(key)) return WordnetNounIndexNameInstanceRUNW.get(TERM);
	if ("runy".equals(key)) return WordnetNounIndexNameInstanceRUNY.get(TERM);
	if ("rupe".equals(key)) return WordnetNounIndexNameInstanceRUPE.get(TERM);
	if ("rupi".equals(key)) return WordnetNounIndexNameInstanceRUPI.get(TERM);
	if ("rupt".equals(key)) return WordnetNounIndexNameInstanceRUPT.get(TERM);
	if ("rura".equals(key)) return WordnetNounIndexNameInstanceRURA.get(TERM);
	if ("ruri".equals(key)) return WordnetNounIndexNameInstanceRURI.get(TERM);
	if ("rusc".equals(key)) return WordnetNounIndexNameInstanceRUSC.get(TERM);
	if ("ruse".equals(key)) return WordnetNounIndexNameInstanceRUSE.get(TERM);
	if ("rush".equals(key)) return WordnetNounIndexNameInstanceRUSH.get(TERM);
	if ("rusk".equals(key)) return WordnetNounIndexNameInstanceRUSK.get(TERM);
	if ("russ".equals(key)) return WordnetNounIndexNameInstanceRUSS.get(TERM);
	if ("rust".equals(key)) return WordnetNounIndexNameInstanceRUST.get(TERM);
	if ("ruta".equals(key)) return WordnetNounIndexNameInstanceRUTA.get(TERM);
	if ("ruth".equals(key)) return WordnetNounIndexNameInstanceRUTH.get(TERM);
	if ("ruti".equals(key)) return WordnetNounIndexNameInstanceRUTI.get(TERM);
	if ("rutl".equals(key)) return WordnetNounIndexNameInstanceRUTL.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceRUAN.terms());
	set.addAll(WordnetNounIndexNameInstanceRUBA.terms());
	set.addAll(WordnetNounIndexNameInstanceRUBB.terms());
	set.addAll(WordnetNounIndexNameInstanceRUBD.terms());
	set.addAll(WordnetNounIndexNameInstanceRUBE.terms());
	set.addAll(WordnetNounIndexNameInstanceRUBI.terms());
	set.addAll(WordnetNounIndexNameInstanceRUBL.terms());
	set.addAll(WordnetNounIndexNameInstanceRUBO.terms());
	set.addAll(WordnetNounIndexNameInstanceRUBR.terms());
	set.addAll(WordnetNounIndexNameInstanceRUBU.terms());
	set.addAll(WordnetNounIndexNameInstanceRUBY.terms());
	set.addAll(WordnetNounIndexNameInstanceRUCK.terms());
	set.addAll(WordnetNounIndexNameInstanceRUCT.terms());
	set.addAll(WordnetNounIndexNameInstanceRUDA.terms());
	set.addAll(WordnetNounIndexNameInstanceRUDB.terms());
	set.addAll(WordnetNounIndexNameInstanceRUDD.terms());
	set.addAll(WordnetNounIndexNameInstanceRUDE.terms());
	set.addAll(WordnetNounIndexNameInstanceRUDI.terms());
	set.addAll(WordnetNounIndexNameInstanceRUDR.terms());
	set.addAll(WordnetNounIndexNameInstanceRUEF.terms());
	set.addAll(WordnetNounIndexNameInstanceRUFF.terms());
	set.addAll(WordnetNounIndexNameInstanceRUGA.terms());
	set.addAll(WordnetNounIndexNameInstanceRUGB.terms());
	set.addAll(WordnetNounIndexNameInstanceRUGE.terms());
	set.addAll(WordnetNounIndexNameInstanceRUGG.terms());
	set.addAll(WordnetNounIndexNameInstanceRUGU.terms());
	set.addAll(WordnetNounIndexNameInstanceRUHR.terms());
	set.addAll(WordnetNounIndexNameInstanceRUIN.terms());
	set.addAll(WordnetNounIndexNameInstanceRULE.terms());
	set.addAll(WordnetNounIndexNameInstanceRULI.terms());
	set.addAll(WordnetNounIndexNameInstanceRUMA.terms());
	set.addAll(WordnetNounIndexNameInstanceRUMB.terms());
	set.addAll(WordnetNounIndexNameInstanceRUME.terms());
	set.addAll(WordnetNounIndexNameInstanceRUMI.terms());
	set.addAll(WordnetNounIndexNameInstanceRUMM.terms());
	set.addAll(WordnetNounIndexNameInstanceRUMO.terms());
	set.addAll(WordnetNounIndexNameInstanceRUMP.terms());
	set.addAll(WordnetNounIndexNameInstanceRUMR.terms());
	set.addAll(WordnetNounIndexNameInstanceRUNA.terms());
	set.addAll(WordnetNounIndexNameInstanceRUNC.terms());
	set.addAll(WordnetNounIndexNameInstanceRUND.terms());
	set.addAll(WordnetNounIndexNameInstanceRUNE.terms());
	set.addAll(WordnetNounIndexNameInstanceRUNG.terms());
	set.addAll(WordnetNounIndexNameInstanceRUNN.terms());
	set.addAll(WordnetNounIndexNameInstanceRUNO.terms());
	set.addAll(WordnetNounIndexNameInstanceRUNT.terms());
	set.addAll(WordnetNounIndexNameInstanceRUNU.terms());
	set.addAll(WordnetNounIndexNameInstanceRUNW.terms());
	set.addAll(WordnetNounIndexNameInstanceRUNY.terms());
	set.addAll(WordnetNounIndexNameInstanceRUPE.terms());
	set.addAll(WordnetNounIndexNameInstanceRUPI.terms());
	set.addAll(WordnetNounIndexNameInstanceRUPT.terms());
	set.addAll(WordnetNounIndexNameInstanceRURA.terms());
	set.addAll(WordnetNounIndexNameInstanceRURI.terms());
	set.addAll(WordnetNounIndexNameInstanceRUSC.terms());
	set.addAll(WordnetNounIndexNameInstanceRUSE.terms());
	set.addAll(WordnetNounIndexNameInstanceRUSH.terms());
	set.addAll(WordnetNounIndexNameInstanceRUSK.terms());
	set.addAll(WordnetNounIndexNameInstanceRUSS.terms());
	set.addAll(WordnetNounIndexNameInstanceRUST.terms());
	set.addAll(WordnetNounIndexNameInstanceRUTA.terms());
	set.addAll(WordnetNounIndexNameInstanceRUTH.terms());
	set.addAll(WordnetNounIndexNameInstanceRUTI.terms());
	set.addAll(WordnetNounIndexNameInstanceRUTL.terms());
  		return set; 	} }