package org.swtk.commons.dict.wordnet.indexbyname.instance.p.e.t;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstancePET {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"pet\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"00904074\", \"07568642\", \"10011405\", \"01321385\"]}");
	add("{\"term\":\"pet food\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07821707\"]}");
	add("{\"term\":\"pet name\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06350614\"]}");
	add("{\"term\":\"pet peeve\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07226264\"]}");
	add("{\"term\":\"pet scanner\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03994348\"]}");
	add("{\"term\":\"pet shop\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03926763\"]}");
	add("{\"term\":\"pet sitter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10440252\"]}");
	add("{\"term\":\"pet sitting\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00657121\"]}");
	add("{\"term\":\"petabit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13652006\"]}");
	add("{\"term\":\"petabyte\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13651674\", \"13651848\"]}");
	add("{\"term\":\"petal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11710924\"]}");
	add("{\"term\":\"petard\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03925824\"]}");
	add("{\"term\":\"petasites\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12022666\"]}");
	add("{\"term\":\"petasites fragrans\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12023120\"]}");
	add("{\"term\":\"petasites hybridus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12022897\"]}");
	add("{\"term\":\"petasites sagitattus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12023295\"]}");
	add("{\"term\":\"petasites vulgaris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12022897\"]}");
	add("{\"term\":\"petaurista\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02365072\"]}");
	add("{\"term\":\"petaurista petaurista\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02365221\"]}");
	add("{\"term\":\"petauristidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02364677\"]}");
	add("{\"term\":\"petaurus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01884632\"]}");
	add("{\"term\":\"petchary\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01551694\"]}");
	add("{\"term\":\"petcock\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03925930\"]}");
	add("{\"term\":\"pete seeger\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11310974\"]}");
	add("{\"term\":\"petechia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14312695\"]}");
	add("{\"term\":\"peter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11251147\"]}");
	add("{\"term\":\"peter abelard\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10826921\"]}");
	add("{\"term\":\"peter alexander ustinov\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11378060\"]}");
	add("{\"term\":\"peter behrens\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10861476\"]}");
	add("{\"term\":\"peter carl faberge\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10984821\"]}");
	add("{\"term\":\"peter carl goldmark\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11025046\"]}");
	add("{\"term\":\"peter cooper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10929223\"]}");
	add("{\"term\":\"peter goldmark\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11025046\"]}");
	add("{\"term\":\"peter i\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11251423\"]}");
	add("{\"term\":\"peter ilich tchaikovsky\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11353757\"]}");
	add("{\"term\":\"peter lorre\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11158914\"]}");
	add("{\"term\":\"peter mark roget\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11289075\"]}");
	add("{\"term\":\"peter medawar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11190903\"]}");
	add("{\"term\":\"peter minnewit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11201428\"]}");
	add("{\"term\":\"peter minuit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11201428\"]}");
	add("{\"term\":\"peter pan\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09626002\", \"10439530\"]}");
	add("{\"term\":\"peter pan collar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03926096\"]}");
	add("{\"term\":\"peter paul mauser\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11185844\"]}");
	add("{\"term\":\"peter paul rubens\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11293094\"]}");
	add("{\"term\":\"peter seeger\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11310974\"]}");
	add("{\"term\":\"peter sellers\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11312095\"]}");
	add("{\"term\":\"peter stuyvesant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11343089\"]}");
	add("{\"term\":\"peter tchaikovsky\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11353757\"]}");
	add("{\"term\":\"peter the great\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11251423\"]}");
	add("{\"term\":\"peterburg\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09030824\"]}");
	add("{\"term\":\"petersburg\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01292928\", \"09174973\"]}");
	add("{\"term\":\"petersburg campaign\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01292928\"]}");
	add("{\"term\":\"petfood\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07821707\"]}");
	add("{\"term\":\"petiole\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13152377\"]}");
	add("{\"term\":\"petiolule\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11698750\"]}");
	add("{\"term\":\"petit bourgeois\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08199023\", \"10439661\"]}");
	add("{\"term\":\"petit dejeuner\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07590345\"]}");
	add("{\"term\":\"petit four\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07649249\"]}");
	add("{\"term\":\"petit juror\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10440022\"]}");
	add("{\"term\":\"petit jury\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08432229\"]}");
	add("{\"term\":\"petit larceny\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00785737\"]}");
	add("{\"term\":\"petit mal\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"14107041\", \"14111609\"]}");
	add("{\"term\":\"petit mal epilepsy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14111609\"]}");
	add("{\"term\":\"petit point\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03926209\", \"03926303\"]}");
	add("{\"term\":\"petite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05103970\"]}");
	add("{\"term\":\"petite bourgeoisie\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08199023\"]}");
	add("{\"term\":\"petite marmite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07602465\"]}");
	add("{\"term\":\"petiteness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05114228\"]}");
	add("{\"term\":\"petitio\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05903421\"]}");
	add("{\"term\":\"petitio principii\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05903421\"]}");
	add("{\"term\":\"petition\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07203790\", \"06525357\"]}");
	add("{\"term\":\"petitioner\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10691631\", \"10439776\"]}");
	add("{\"term\":\"petrarca\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11251673\"]}");
	add("{\"term\":\"petrarch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11251673\"]}");
	add("{\"term\":\"petrarchan sonnet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06394359\"]}");
	add("{\"term\":\"petrel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02061815\"]}");
	add("{\"term\":\"petri dish\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03926410\"]}");
	add("{\"term\":\"petrifaction\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09413573\", \"13556786\"]}");
	add("{\"term\":\"petrification\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13556786\"]}");
	add("{\"term\":\"petrified forest national park\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08625871\"]}");
	add("{\"term\":\"petrissage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00661077\"]}");
	add("{\"term\":\"petrochemical\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15005027\"]}");
	add("{\"term\":\"petrocoptis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11834299\"]}");
	add("{\"term\":\"petrogale\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01881444\"]}");
	add("{\"term\":\"petroglyph\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00944256\"]}");
	add("{\"term\":\"petrograd\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09030824\"]}");
	add("{\"term\":\"petrol\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14711074\"]}");
	add("{\"term\":\"petrol bomb\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03786588\"]}");
	add("{\"term\":\"petrol engine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03429540\"]}");
	add("{\"term\":\"petrol gage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03429772\"]}");
	add("{\"term\":\"petrol gauge\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03429772\"]}");
	add("{\"term\":\"petrol line\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03406415\"]}");
	add("{\"term\":\"petrol pump\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03430323\"]}");
	add("{\"term\":\"petrol station\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03430002\"]}");
	add("{\"term\":\"petrol tank\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03431044\"]}");
	add("{\"term\":\"petrolatum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15005469\"]}");
	add("{\"term\":\"petrolatum gauze\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03926506\"]}");
	add("{\"term\":\"petroleum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15005138\"]}");
	add("{\"term\":\"petroleum future\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03849244\"]}");
	add("{\"term\":\"petroleum geologist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10440137\"]}");
	add("{\"term\":\"petroleum geology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06131297\"]}");
	add("{\"term\":\"petroleum jelly\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15005469\"]}");
	add("{\"term\":\"petroleum refinery\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03850193\"]}");
	add("{\"term\":\"petrology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06130982\"]}");
	add("{\"term\":\"petromyzon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01480386\"]}");
	add("{\"term\":\"petromyzon marinus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01480516\"]}");
	add("{\"term\":\"petromyzoniformes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01479825\"]}");
	add("{\"term\":\"petromyzontidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01480014\"]}");
	add("{\"term\":\"petronas towers\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03926619\"]}");
	add("{\"term\":\"petronius\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11251811\"]}");
	add("{\"term\":\"petronius arbiter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11251811\"]}");
	add("{\"term\":\"petroselinum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12963030\"]}");
	add("{\"term\":\"petroselinum crispum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12963155\"]}");
	add("{\"term\":\"petroselinum crispum neapolitanum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12963332\"]}");
	add("{\"term\":\"petroselinum crispum tuberosum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12963489\"]}");
	add("{\"term\":\"petrus stuyvesant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11343089\"]}");
	add("{\"term\":\"petter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10440394\"]}");
	add("{\"term\":\"petteria\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12518821\"]}");
	add("{\"term\":\"petteria ramentacea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12518962\"]}");
	add("{\"term\":\"petticoat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03926859\"]}");
	add("{\"term\":\"pettifogger\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10520788\", \"10614265\"]}");
	add("{\"term\":\"pettifoggery\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07199395\"]}");
	add("{\"term\":\"pettiness\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04841304\", \"05180732\", \"06215562\"]}");
	add("{\"term\":\"petting\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00855630\"]}");
	add("{\"term\":\"petting zoo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08009968\"]}");
	add("{\"term\":\"pettishness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04649615\"]}");
	add("{\"term\":\"petty\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00785737\"]}");
	add("{\"term\":\"petty apartheid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08396186\"]}");
	add("{\"term\":\"petty bourgeoisie\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08199023\"]}");
	add("{\"term\":\"petty cash\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13443584\"]}");
	add("{\"term\":\"petty criticism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06731952\"]}");
	add("{\"term\":\"petty juror\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10440022\"]}");
	add("{\"term\":\"petty jury\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08432229\"]}");
	add("{\"term\":\"petty larceny\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00785737\"]}");
	add("{\"term\":\"petty morel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11818450\"]}");
	add("{\"term\":\"petty officer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10440554\"]}");
	add("{\"term\":\"petty spurge\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12939570\"]}");
	add("{\"term\":\"petty whin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12550944\"]}");
	add("{\"term\":\"petulance\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07568195\"]}");
	add("{\"term\":\"petunia\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12930012\", \"12930181\"]}");
	add("{\"term\":\"petunia axillaris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12930374\"]}");
	add("{\"term\":\"petunia hybrida\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12930677\"]}");
	add("{\"term\":\"petunia integrifolia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12930519\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }