package org.swtk.commons.dict.wordnet.index.name.instance.s.u.b.c;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceSUBC {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"subclass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08123627\"]}");
	add("{\"term\":\"subcommittee\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08342923\"]}");
	add("{\"term\":\"subcompact\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04354197\"]}");
	add("{\"term\":\"subconscious\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05621261\"]}");
	add("{\"term\":\"subconsciousness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05690272\"]}");
	add("{\"term\":\"subcontinent\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09473098\"]}");
	add("{\"term\":\"subcontract\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06536758\"]}");
	add("{\"term\":\"subcontractor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10687302\"]}");
	add("{\"term\":\"subculture\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08305674\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public boolean has(final String TERM) { 		return map.containsKey(TERM); 	} }