package org.swtk.commons.dict.wordnet.index.name.controller.b.i;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.a.l.WordnetNounIndexNameInstanceBIAL;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.a.s.WordnetNounIndexNameInstanceBIAS;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.b.l.WordnetNounIndexNameInstanceBIBL;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.b.o.WordnetNounIndexNameInstanceBIBO;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.c.a.WordnetNounIndexNameInstanceBICA;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.c.e.WordnetNounIndexNameInstanceBICE;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.c.h.WordnetNounIndexNameInstanceBICH;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.c.k.WordnetNounIndexNameInstanceBICK;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.c.o.WordnetNounIndexNameInstanceBICO;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.c.u.WordnetNounIndexNameInstanceBICU;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.c.y.WordnetNounIndexNameInstanceBICY;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.d.a.WordnetNounIndexNameInstanceBIDA;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.d.d.WordnetNounIndexNameInstanceBIDD;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.d.e.WordnetNounIndexNameInstanceBIDE;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.e.n.WordnetNounIndexNameInstanceBIEN;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.e.r.WordnetNounIndexNameInstanceBIER;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.f.f.WordnetNounIndexNameInstanceBIFF;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.f.o.WordnetNounIndexNameInstanceBIFO;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.f.u.WordnetNounIndexNameInstanceBIFU;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.g.a.WordnetNounIndexNameInstanceBIGA;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.g.e.WordnetNounIndexNameInstanceBIGE;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.g.f.WordnetNounIndexNameInstanceBIGF;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.g.g.WordnetNounIndexNameInstanceBIGG;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.g.h.WordnetNounIndexNameInstanceBIGH;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.g.n.WordnetNounIndexNameInstanceBIGN;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.g.o.WordnetNounIndexNameInstanceBIGO;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.g.r.WordnetNounIndexNameInstanceBIGR;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.g.w.WordnetNounIndexNameInstanceBIGW;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.h.a.WordnetNounIndexNameInstanceBIHA;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.j.o.WordnetNounIndexNameInstanceBIJO;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.k.e.WordnetNounIndexNameInstanceBIKE;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.k.i.WordnetNounIndexNameInstanceBIKI;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.l.a.WordnetNounIndexNameInstanceBILA;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.l.b.WordnetNounIndexNameInstanceBILB;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.l.e.WordnetNounIndexNameInstanceBILE;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.l.g.WordnetNounIndexNameInstanceBILG;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.l.h.WordnetNounIndexNameInstanceBILH;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.l.i.WordnetNounIndexNameInstanceBILI;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.l.l.WordnetNounIndexNameInstanceBILL;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.l.o.WordnetNounIndexNameInstanceBILO;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.l.s.WordnetNounIndexNameInstanceBILS;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.l.t.WordnetNounIndexNameInstanceBILT;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.m.b.WordnetNounIndexNameInstanceBIMB;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.m.e.WordnetNounIndexNameInstanceBIME;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.m.i.WordnetNounIndexNameInstanceBIMI;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.m.l.WordnetNounIndexNameInstanceBIML;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.m.o.WordnetNounIndexNameInstanceBIMO;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.n.a.WordnetNounIndexNameInstanceBINA;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.n.d.WordnetNounIndexNameInstanceBIND;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.n.e.WordnetNounIndexNameInstanceBINE;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.n.f.WordnetNounIndexNameInstanceBINF;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.n.g.WordnetNounIndexNameInstanceBING;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.n.n.WordnetNounIndexNameInstanceBINN;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.n.o.WordnetNounIndexNameInstanceBINO;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.n.t.WordnetNounIndexNameInstanceBINT;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.a.WordnetNounIndexNameInstanceBIOA;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.c.WordnetNounIndexNameInstanceBIOC;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.d.WordnetNounIndexNameInstanceBIOD;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.e.WordnetNounIndexNameInstanceBIOE;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.f.WordnetNounIndexNameInstanceBIOF;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.g.WordnetNounIndexNameInstanceBIOG;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.h.WordnetNounIndexNameInstanceBIOH;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.k.WordnetNounIndexNameInstanceBIOK;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.l.WordnetNounIndexNameInstanceBIOL;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.m.WordnetNounIndexNameInstanceBIOM;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.n.WordnetNounIndexNameInstanceBION;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.p.WordnetNounIndexNameInstanceBIOP;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.r.WordnetNounIndexNameInstanceBIOR;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.s.WordnetNounIndexNameInstanceBIOS;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.t.WordnetNounIndexNameInstanceBIOT;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.o.w.WordnetNounIndexNameInstanceBIOW;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.p.e.WordnetNounIndexNameInstanceBIPE;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.p.l.WordnetNounIndexNameInstanceBIPL;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.p.r.WordnetNounIndexNameInstanceBIPR;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.q.u.WordnetNounIndexNameInstanceBIQU;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.r.c.WordnetNounIndexNameInstanceBIRC;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.r.d.WordnetNounIndexNameInstanceBIRD;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.r.e.WordnetNounIndexNameInstanceBIRE;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.r.i.WordnetNounIndexNameInstanceBIRI;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.r.l.WordnetNounIndexNameInstanceBIRL;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.r.m.WordnetNounIndexNameInstanceBIRM;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.r.o.WordnetNounIndexNameInstanceBIRO;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.r.r.WordnetNounIndexNameInstanceBIRR;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.r.t.WordnetNounIndexNameInstanceBIRT;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.r.y.WordnetNounIndexNameInstanceBIRY;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.s.a.WordnetNounIndexNameInstanceBISA;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.s.c.WordnetNounIndexNameInstanceBISC;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.s.e.WordnetNounIndexNameInstanceBISE;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.s.h.WordnetNounIndexNameInstanceBISH;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.s.k.WordnetNounIndexNameInstanceBISK;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.s.m.WordnetNounIndexNameInstanceBISM;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.s.o.WordnetNounIndexNameInstanceBISO;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.s.q.WordnetNounIndexNameInstanceBISQ;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.s.s.WordnetNounIndexNameInstanceBISS;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.s.t.WordnetNounIndexNameInstanceBIST;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.t.a.WordnetNounIndexNameInstanceBITA;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.t.c.WordnetNounIndexNameInstanceBITC;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.t.e.WordnetNounIndexNameInstanceBITE;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.t.h.WordnetNounIndexNameInstanceBITH;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.t.i.WordnetNounIndexNameInstanceBITI;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.t.m.WordnetNounIndexNameInstanceBITM;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.t.o.WordnetNounIndexNameInstanceBITO;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.t.s.WordnetNounIndexNameInstanceBITS;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.t.t.WordnetNounIndexNameInstanceBITT;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.t.u.WordnetNounIndexNameInstanceBITU;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.v.a.WordnetNounIndexNameInstanceBIVA;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.v.o.WordnetNounIndexNameInstanceBIVO;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.w.e.WordnetNounIndexNameInstanceBIWE;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.z.a.WordnetNounIndexNameInstanceBIZA;
	import org.swtk.commons.dict.wordnet.index.name.instance.b.i.z.e.WordnetNounIndexNameInstanceBIZE;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerBI {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("bial".equals(key)) return WordnetNounIndexNameInstanceBIAL.get(TERM);
	if ("bias".equals(key)) return WordnetNounIndexNameInstanceBIAS.get(TERM);
	if ("bibl".equals(key)) return WordnetNounIndexNameInstanceBIBL.get(TERM);
	if ("bibo".equals(key)) return WordnetNounIndexNameInstanceBIBO.get(TERM);
	if ("bica".equals(key)) return WordnetNounIndexNameInstanceBICA.get(TERM);
	if ("bice".equals(key)) return WordnetNounIndexNameInstanceBICE.get(TERM);
	if ("bich".equals(key)) return WordnetNounIndexNameInstanceBICH.get(TERM);
	if ("bick".equals(key)) return WordnetNounIndexNameInstanceBICK.get(TERM);
	if ("bico".equals(key)) return WordnetNounIndexNameInstanceBICO.get(TERM);
	if ("bicu".equals(key)) return WordnetNounIndexNameInstanceBICU.get(TERM);
	if ("bicy".equals(key)) return WordnetNounIndexNameInstanceBICY.get(TERM);
	if ("bida".equals(key)) return WordnetNounIndexNameInstanceBIDA.get(TERM);
	if ("bidd".equals(key)) return WordnetNounIndexNameInstanceBIDD.get(TERM);
	if ("bide".equals(key)) return WordnetNounIndexNameInstanceBIDE.get(TERM);
	if ("bien".equals(key)) return WordnetNounIndexNameInstanceBIEN.get(TERM);
	if ("bier".equals(key)) return WordnetNounIndexNameInstanceBIER.get(TERM);
	if ("biff".equals(key)) return WordnetNounIndexNameInstanceBIFF.get(TERM);
	if ("bifo".equals(key)) return WordnetNounIndexNameInstanceBIFO.get(TERM);
	if ("bifu".equals(key)) return WordnetNounIndexNameInstanceBIFU.get(TERM);
	if ("biga".equals(key)) return WordnetNounIndexNameInstanceBIGA.get(TERM);
	if ("bige".equals(key)) return WordnetNounIndexNameInstanceBIGE.get(TERM);
	if ("bigf".equals(key)) return WordnetNounIndexNameInstanceBIGF.get(TERM);
	if ("bigg".equals(key)) return WordnetNounIndexNameInstanceBIGG.get(TERM);
	if ("bigh".equals(key)) return WordnetNounIndexNameInstanceBIGH.get(TERM);
	if ("bign".equals(key)) return WordnetNounIndexNameInstanceBIGN.get(TERM);
	if ("bigo".equals(key)) return WordnetNounIndexNameInstanceBIGO.get(TERM);
	if ("bigr".equals(key)) return WordnetNounIndexNameInstanceBIGR.get(TERM);
	if ("bigw".equals(key)) return WordnetNounIndexNameInstanceBIGW.get(TERM);
	if ("biha".equals(key)) return WordnetNounIndexNameInstanceBIHA.get(TERM);
	if ("bijo".equals(key)) return WordnetNounIndexNameInstanceBIJO.get(TERM);
	if ("bike".equals(key)) return WordnetNounIndexNameInstanceBIKE.get(TERM);
	if ("biki".equals(key)) return WordnetNounIndexNameInstanceBIKI.get(TERM);
	if ("bila".equals(key)) return WordnetNounIndexNameInstanceBILA.get(TERM);
	if ("bilb".equals(key)) return WordnetNounIndexNameInstanceBILB.get(TERM);
	if ("bile".equals(key)) return WordnetNounIndexNameInstanceBILE.get(TERM);
	if ("bilg".equals(key)) return WordnetNounIndexNameInstanceBILG.get(TERM);
	if ("bilh".equals(key)) return WordnetNounIndexNameInstanceBILH.get(TERM);
	if ("bili".equals(key)) return WordnetNounIndexNameInstanceBILI.get(TERM);
	if ("bill".equals(key)) return WordnetNounIndexNameInstanceBILL.get(TERM);
	if ("bilo".equals(key)) return WordnetNounIndexNameInstanceBILO.get(TERM);
	if ("bils".equals(key)) return WordnetNounIndexNameInstanceBILS.get(TERM);
	if ("bilt".equals(key)) return WordnetNounIndexNameInstanceBILT.get(TERM);
	if ("bimb".equals(key)) return WordnetNounIndexNameInstanceBIMB.get(TERM);
	if ("bime".equals(key)) return WordnetNounIndexNameInstanceBIME.get(TERM);
	if ("bimi".equals(key)) return WordnetNounIndexNameInstanceBIMI.get(TERM);
	if ("biml".equals(key)) return WordnetNounIndexNameInstanceBIML.get(TERM);
	if ("bimo".equals(key)) return WordnetNounIndexNameInstanceBIMO.get(TERM);
	if ("bina".equals(key)) return WordnetNounIndexNameInstanceBINA.get(TERM);
	if ("bind".equals(key)) return WordnetNounIndexNameInstanceBIND.get(TERM);
	if ("bine".equals(key)) return WordnetNounIndexNameInstanceBINE.get(TERM);
	if ("binf".equals(key)) return WordnetNounIndexNameInstanceBINF.get(TERM);
	if ("bing".equals(key)) return WordnetNounIndexNameInstanceBING.get(TERM);
	if ("binn".equals(key)) return WordnetNounIndexNameInstanceBINN.get(TERM);
	if ("bino".equals(key)) return WordnetNounIndexNameInstanceBINO.get(TERM);
	if ("bint".equals(key)) return WordnetNounIndexNameInstanceBINT.get(TERM);
	if ("bioa".equals(key)) return WordnetNounIndexNameInstanceBIOA.get(TERM);
	if ("bioc".equals(key)) return WordnetNounIndexNameInstanceBIOC.get(TERM);
	if ("biod".equals(key)) return WordnetNounIndexNameInstanceBIOD.get(TERM);
	if ("bioe".equals(key)) return WordnetNounIndexNameInstanceBIOE.get(TERM);
	if ("biof".equals(key)) return WordnetNounIndexNameInstanceBIOF.get(TERM);
	if ("biog".equals(key)) return WordnetNounIndexNameInstanceBIOG.get(TERM);
	if ("bioh".equals(key)) return WordnetNounIndexNameInstanceBIOH.get(TERM);
	if ("biok".equals(key)) return WordnetNounIndexNameInstanceBIOK.get(TERM);
	if ("biol".equals(key)) return WordnetNounIndexNameInstanceBIOL.get(TERM);
	if ("biom".equals(key)) return WordnetNounIndexNameInstanceBIOM.get(TERM);
	if ("bion".equals(key)) return WordnetNounIndexNameInstanceBION.get(TERM);
	if ("biop".equals(key)) return WordnetNounIndexNameInstanceBIOP.get(TERM);
	if ("bior".equals(key)) return WordnetNounIndexNameInstanceBIOR.get(TERM);
	if ("bios".equals(key)) return WordnetNounIndexNameInstanceBIOS.get(TERM);
	if ("biot".equals(key)) return WordnetNounIndexNameInstanceBIOT.get(TERM);
	if ("biow".equals(key)) return WordnetNounIndexNameInstanceBIOW.get(TERM);
	if ("bipe".equals(key)) return WordnetNounIndexNameInstanceBIPE.get(TERM);
	if ("bipl".equals(key)) return WordnetNounIndexNameInstanceBIPL.get(TERM);
	if ("bipr".equals(key)) return WordnetNounIndexNameInstanceBIPR.get(TERM);
	if ("biqu".equals(key)) return WordnetNounIndexNameInstanceBIQU.get(TERM);
	if ("birc".equals(key)) return WordnetNounIndexNameInstanceBIRC.get(TERM);
	if ("bird".equals(key)) return WordnetNounIndexNameInstanceBIRD.get(TERM);
	if ("bire".equals(key)) return WordnetNounIndexNameInstanceBIRE.get(TERM);
	if ("biri".equals(key)) return WordnetNounIndexNameInstanceBIRI.get(TERM);
	if ("birl".equals(key)) return WordnetNounIndexNameInstanceBIRL.get(TERM);
	if ("birm".equals(key)) return WordnetNounIndexNameInstanceBIRM.get(TERM);
	if ("biro".equals(key)) return WordnetNounIndexNameInstanceBIRO.get(TERM);
	if ("birr".equals(key)) return WordnetNounIndexNameInstanceBIRR.get(TERM);
	if ("birt".equals(key)) return WordnetNounIndexNameInstanceBIRT.get(TERM);
	if ("biry".equals(key)) return WordnetNounIndexNameInstanceBIRY.get(TERM);
	if ("bisa".equals(key)) return WordnetNounIndexNameInstanceBISA.get(TERM);
	if ("bisc".equals(key)) return WordnetNounIndexNameInstanceBISC.get(TERM);
	if ("bise".equals(key)) return WordnetNounIndexNameInstanceBISE.get(TERM);
	if ("bish".equals(key)) return WordnetNounIndexNameInstanceBISH.get(TERM);
	if ("bisk".equals(key)) return WordnetNounIndexNameInstanceBISK.get(TERM);
	if ("bism".equals(key)) return WordnetNounIndexNameInstanceBISM.get(TERM);
	if ("biso".equals(key)) return WordnetNounIndexNameInstanceBISO.get(TERM);
	if ("bisq".equals(key)) return WordnetNounIndexNameInstanceBISQ.get(TERM);
	if ("biss".equals(key)) return WordnetNounIndexNameInstanceBISS.get(TERM);
	if ("bist".equals(key)) return WordnetNounIndexNameInstanceBIST.get(TERM);
	if ("bita".equals(key)) return WordnetNounIndexNameInstanceBITA.get(TERM);
	if ("bitc".equals(key)) return WordnetNounIndexNameInstanceBITC.get(TERM);
	if ("bite".equals(key)) return WordnetNounIndexNameInstanceBITE.get(TERM);
	if ("bith".equals(key)) return WordnetNounIndexNameInstanceBITH.get(TERM);
	if ("biti".equals(key)) return WordnetNounIndexNameInstanceBITI.get(TERM);
	if ("bitm".equals(key)) return WordnetNounIndexNameInstanceBITM.get(TERM);
	if ("bito".equals(key)) return WordnetNounIndexNameInstanceBITO.get(TERM);
	if ("bits".equals(key)) return WordnetNounIndexNameInstanceBITS.get(TERM);
	if ("bitt".equals(key)) return WordnetNounIndexNameInstanceBITT.get(TERM);
	if ("bitu".equals(key)) return WordnetNounIndexNameInstanceBITU.get(TERM);
	if ("biva".equals(key)) return WordnetNounIndexNameInstanceBIVA.get(TERM);
	if ("bivo".equals(key)) return WordnetNounIndexNameInstanceBIVO.get(TERM);
	if ("biwe".equals(key)) return WordnetNounIndexNameInstanceBIWE.get(TERM);
	if ("biza".equals(key)) return WordnetNounIndexNameInstanceBIZA.get(TERM);
	if ("bize".equals(key)) return WordnetNounIndexNameInstanceBIZE.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceBIAL.terms());
	set.addAll(WordnetNounIndexNameInstanceBIAS.terms());
	set.addAll(WordnetNounIndexNameInstanceBIBL.terms());
	set.addAll(WordnetNounIndexNameInstanceBIBO.terms());
	set.addAll(WordnetNounIndexNameInstanceBICA.terms());
	set.addAll(WordnetNounIndexNameInstanceBICE.terms());
	set.addAll(WordnetNounIndexNameInstanceBICH.terms());
	set.addAll(WordnetNounIndexNameInstanceBICK.terms());
	set.addAll(WordnetNounIndexNameInstanceBICO.terms());
	set.addAll(WordnetNounIndexNameInstanceBICU.terms());
	set.addAll(WordnetNounIndexNameInstanceBICY.terms());
	set.addAll(WordnetNounIndexNameInstanceBIDA.terms());
	set.addAll(WordnetNounIndexNameInstanceBIDD.terms());
	set.addAll(WordnetNounIndexNameInstanceBIDE.terms());
	set.addAll(WordnetNounIndexNameInstanceBIEN.terms());
	set.addAll(WordnetNounIndexNameInstanceBIER.terms());
	set.addAll(WordnetNounIndexNameInstanceBIFF.terms());
	set.addAll(WordnetNounIndexNameInstanceBIFO.terms());
	set.addAll(WordnetNounIndexNameInstanceBIFU.terms());
	set.addAll(WordnetNounIndexNameInstanceBIGA.terms());
	set.addAll(WordnetNounIndexNameInstanceBIGE.terms());
	set.addAll(WordnetNounIndexNameInstanceBIGF.terms());
	set.addAll(WordnetNounIndexNameInstanceBIGG.terms());
	set.addAll(WordnetNounIndexNameInstanceBIGH.terms());
	set.addAll(WordnetNounIndexNameInstanceBIGN.terms());
	set.addAll(WordnetNounIndexNameInstanceBIGO.terms());
	set.addAll(WordnetNounIndexNameInstanceBIGR.terms());
	set.addAll(WordnetNounIndexNameInstanceBIGW.terms());
	set.addAll(WordnetNounIndexNameInstanceBIHA.terms());
	set.addAll(WordnetNounIndexNameInstanceBIJO.terms());
	set.addAll(WordnetNounIndexNameInstanceBIKE.terms());
	set.addAll(WordnetNounIndexNameInstanceBIKI.terms());
	set.addAll(WordnetNounIndexNameInstanceBILA.terms());
	set.addAll(WordnetNounIndexNameInstanceBILB.terms());
	set.addAll(WordnetNounIndexNameInstanceBILE.terms());
	set.addAll(WordnetNounIndexNameInstanceBILG.terms());
	set.addAll(WordnetNounIndexNameInstanceBILH.terms());
	set.addAll(WordnetNounIndexNameInstanceBILI.terms());
	set.addAll(WordnetNounIndexNameInstanceBILL.terms());
	set.addAll(WordnetNounIndexNameInstanceBILO.terms());
	set.addAll(WordnetNounIndexNameInstanceBILS.terms());
	set.addAll(WordnetNounIndexNameInstanceBILT.terms());
	set.addAll(WordnetNounIndexNameInstanceBIMB.terms());
	set.addAll(WordnetNounIndexNameInstanceBIME.terms());
	set.addAll(WordnetNounIndexNameInstanceBIMI.terms());
	set.addAll(WordnetNounIndexNameInstanceBIML.terms());
	set.addAll(WordnetNounIndexNameInstanceBIMO.terms());
	set.addAll(WordnetNounIndexNameInstanceBINA.terms());
	set.addAll(WordnetNounIndexNameInstanceBIND.terms());
	set.addAll(WordnetNounIndexNameInstanceBINE.terms());
	set.addAll(WordnetNounIndexNameInstanceBINF.terms());
	set.addAll(WordnetNounIndexNameInstanceBING.terms());
	set.addAll(WordnetNounIndexNameInstanceBINN.terms());
	set.addAll(WordnetNounIndexNameInstanceBINO.terms());
	set.addAll(WordnetNounIndexNameInstanceBINT.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOA.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOC.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOD.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOE.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOF.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOG.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOH.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOK.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOL.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOM.terms());
	set.addAll(WordnetNounIndexNameInstanceBION.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOP.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOR.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOS.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOT.terms());
	set.addAll(WordnetNounIndexNameInstanceBIOW.terms());
	set.addAll(WordnetNounIndexNameInstanceBIPE.terms());
	set.addAll(WordnetNounIndexNameInstanceBIPL.terms());
	set.addAll(WordnetNounIndexNameInstanceBIPR.terms());
	set.addAll(WordnetNounIndexNameInstanceBIQU.terms());
	set.addAll(WordnetNounIndexNameInstanceBIRC.terms());
	set.addAll(WordnetNounIndexNameInstanceBIRD.terms());
	set.addAll(WordnetNounIndexNameInstanceBIRE.terms());
	set.addAll(WordnetNounIndexNameInstanceBIRI.terms());
	set.addAll(WordnetNounIndexNameInstanceBIRL.terms());
	set.addAll(WordnetNounIndexNameInstanceBIRM.terms());
	set.addAll(WordnetNounIndexNameInstanceBIRO.terms());
	set.addAll(WordnetNounIndexNameInstanceBIRR.terms());
	set.addAll(WordnetNounIndexNameInstanceBIRT.terms());
	set.addAll(WordnetNounIndexNameInstanceBIRY.terms());
	set.addAll(WordnetNounIndexNameInstanceBISA.terms());
	set.addAll(WordnetNounIndexNameInstanceBISC.terms());
	set.addAll(WordnetNounIndexNameInstanceBISE.terms());
	set.addAll(WordnetNounIndexNameInstanceBISH.terms());
	set.addAll(WordnetNounIndexNameInstanceBISK.terms());
	set.addAll(WordnetNounIndexNameInstanceBISM.terms());
	set.addAll(WordnetNounIndexNameInstanceBISO.terms());
	set.addAll(WordnetNounIndexNameInstanceBISQ.terms());
	set.addAll(WordnetNounIndexNameInstanceBISS.terms());
	set.addAll(WordnetNounIndexNameInstanceBIST.terms());
	set.addAll(WordnetNounIndexNameInstanceBITA.terms());
	set.addAll(WordnetNounIndexNameInstanceBITC.terms());
	set.addAll(WordnetNounIndexNameInstanceBITE.terms());
	set.addAll(WordnetNounIndexNameInstanceBITH.terms());
	set.addAll(WordnetNounIndexNameInstanceBITI.terms());
	set.addAll(WordnetNounIndexNameInstanceBITM.terms());
	set.addAll(WordnetNounIndexNameInstanceBITO.terms());
	set.addAll(WordnetNounIndexNameInstanceBITS.terms());
	set.addAll(WordnetNounIndexNameInstanceBITT.terms());
	set.addAll(WordnetNounIndexNameInstanceBITU.terms());
	set.addAll(WordnetNounIndexNameInstanceBIVA.terms());
	set.addAll(WordnetNounIndexNameInstanceBIVO.terms());
	set.addAll(WordnetNounIndexNameInstanceBIWE.terms());
	set.addAll(WordnetNounIndexNameInstanceBIZA.terms());
	set.addAll(WordnetNounIndexNameInstanceBIZE.terms());
  		return set; 	} }