package org.swtk.commons.dict.wordnet.indexbyname.instance.a.n.n;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceANN {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"an nafud\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09194273\"]}");
	add("{\"term\":\"an nefud\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09194273\"]}");
	add("{\"term\":\"ann arbor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09122823\"]}");
	add("{\"term\":\"anna\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13726523\"]}");
	add("{\"term\":\"anna amalia mercouri\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11195738\"]}");
	add("{\"term\":\"anna eleanor roosevelt\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11290370\"]}");
	add("{\"term\":\"anna howard shaw\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11316129\"]}");
	add("{\"term\":\"anna mary robertson moses\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11213635\"]}");
	add("{\"term\":\"anna pavlova\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11247390\"]}");
	add("{\"term\":\"annaba\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08724061\"]}");
	add("{\"term\":\"annalist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09814238\"]}");
	add("{\"term\":\"annals\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06527653\", \"06609970\"]}");
	add("{\"term\":\"annam\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09185985\"]}");
	add("{\"term\":\"annamese\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06950006\", \"09766522\"]}");
	add("{\"term\":\"annamite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06950006\"]}");
	add("{\"term\":\"annapolis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09116801\"]}");
	add("{\"term\":\"annapurna\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09220823\", \"09550694\"]}");
	add("{\"term\":\"anne\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10838073\"]}");
	add("{\"term\":\"anne boleyn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10875027\"]}");
	add("{\"term\":\"anne bradstreet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10880770\"]}");
	add("{\"term\":\"anne bronte\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10885447\"]}");
	add("{\"term\":\"anne dudley bradstreet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10880770\"]}");
	add("{\"term\":\"anne hathaway\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11054481\"]}");
	add("{\"term\":\"anne hutchinson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11089075\"]}");
	add("{\"term\":\"anne mansfield sullivan\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11344423\"]}");
	add("{\"term\":\"anne robert jacques turgot\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11372187\"]}");
	add("{\"term\":\"anne sexton\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11314572\"]}");
	add("{\"term\":\"anne sullivan\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11344423\"]}");
	add("{\"term\":\"annealing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00403759\"]}");
	add("{\"term\":\"annelid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01937081\"]}");
	add("{\"term\":\"annelid worm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01937081\"]}");
	add("{\"term\":\"annelida\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01936848\"]}");
	add("{\"term\":\"annex\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02716453\"]}");
	add("{\"term\":\"annexa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05228942\"]}");
	add("{\"term\":\"annexation\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00079356\", \"00374226\"]}");
	add("{\"term\":\"annexe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02716453\"]}");
	add("{\"term\":\"annie oakley\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11230796\"]}");
	add("{\"term\":\"anniellidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01693726\"]}");
	add("{\"term\":\"annihilation\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07345428\", \"00219075\"]}");
	add("{\"term\":\"annihilator\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09814358\"]}");
	add("{\"term\":\"anniversary\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15274610\"]}");
	add("{\"term\":\"annon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07777587\"]}");
	add("{\"term\":\"annona\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11714281\"]}");
	add("{\"term\":\"annona cherimola\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11714769\"]}");
	add("{\"term\":\"annona diversifolia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11714938\"]}");
	add("{\"term\":\"annona glabra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11715754\"]}");
	add("{\"term\":\"annona muricata\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11715133\"]}");
	add("{\"term\":\"annona reticulata\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11715335\"]}");
	add("{\"term\":\"annona squamosa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11715554\"]}");
	add("{\"term\":\"annonaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11714035\"]}");
	add("{\"term\":\"annotating\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00372543\"]}");
	add("{\"term\":\"annotation\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00372543\", \"06775984\"]}");
	add("{\"term\":\"annotator\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09814451\"]}");
	add("{\"term\":\"announcement\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06759293\", \"06738907\"]}");
	add("{\"term\":\"announcer\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09814565\", \"09814775\"]}");
	add("{\"term\":\"annoyance\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"00419407\", \"05838383\", \"09797978\", \"07533500\", \"14429977\"]}");
	add("{\"term\":\"annoyer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10715051\"]}");
	add("{\"term\":\"annoying\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00419407\"]}");
	add("{\"term\":\"annual\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06438138\", \"11573257\"]}");
	add("{\"term\":\"annual fern\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13229200\"]}");
	add("{\"term\":\"annual parallax\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11549087\"]}");
	add("{\"term\":\"annual ring\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11444930\"]}");
	add("{\"term\":\"annualry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05575122\"]}");
	add("{\"term\":\"annuitant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09814997\"]}");
	add("{\"term\":\"annuity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13315526\"]}");
	add("{\"term\":\"annuity in advance\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13315786\"]}");
	add("{\"term\":\"annular eclipse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07383699\"]}");
	add("{\"term\":\"annular scotoma\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14580018\"]}");
	add("{\"term\":\"annulet\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02716628\", \"02716929\"]}");
	add("{\"term\":\"annulment\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"00232754\", \"01243544\", \"14587637\"]}");
	add("{\"term\":\"annulus\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13116107\", \"13898031\"]}");
	add("{\"term\":\"annum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15228997\"]}");
	add("{\"term\":\"annunciation\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"06738907\", \"06759903\", \"15210982\"]}");
	add("{\"term\":\"annunciation day\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15210982\"]}");
	add("{\"term\":\"annunciation lily\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12447483\"]}");
	add("{\"term\":\"annunciator\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02717050\"]}");
	add("{\"term\":\"annwfn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05634401\"]}");
	add("{\"term\":\"annwn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05634401\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }