package org.swtk.commons.dict.wordnet.index.name.controller.l.a;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.a.g.WordnetNounIndexNameInstanceLAAG;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.b.a.WordnetNounIndexNameInstanceLABA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.b.d.WordnetNounIndexNameInstanceLABD;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.b.e.WordnetNounIndexNameInstanceLABE;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.b.i.WordnetNounIndexNameInstanceLABI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.b.l.WordnetNounIndexNameInstanceLABL;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.b.o.WordnetNounIndexNameInstanceLABO;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.b.r.WordnetNounIndexNameInstanceLABR;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.b.u.WordnetNounIndexNameInstanceLABU;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.b.y.WordnetNounIndexNameInstanceLABY;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.c.c.WordnetNounIndexNameInstanceLACC;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.c.e.WordnetNounIndexNameInstanceLACE;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.c.h.WordnetNounIndexNameInstanceLACH;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.c.i.WordnetNounIndexNameInstanceLACI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.c.k.WordnetNounIndexNameInstanceLACK;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.c.o.WordnetNounIndexNameInstanceLACO;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.c.q.WordnetNounIndexNameInstanceLACQ;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.c.r.WordnetNounIndexNameInstanceLACR;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.c.t.WordnetNounIndexNameInstanceLACT;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.c.u.WordnetNounIndexNameInstanceLACU;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.d.a.WordnetNounIndexNameInstanceLADA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.d.d.WordnetNounIndexNameInstanceLADD;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.d.i.WordnetNounIndexNameInstanceLADI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.d.l.WordnetNounIndexNameInstanceLADL;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.d.o.WordnetNounIndexNameInstanceLADO;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.d.y.WordnetNounIndexNameInstanceLADY;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.e.l.WordnetNounIndexNameInstanceLAEL;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.e.r.WordnetNounIndexNameInstanceLAER;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.e.t.WordnetNounIndexNameInstanceLAET;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.e.v.WordnetNounIndexNameInstanceLAEV;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.f.a.WordnetNounIndexNameInstanceLAFA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.f.f.WordnetNounIndexNameInstanceLAFF;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.f.i.WordnetNounIndexNameInstanceLAFI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.g.a.WordnetNounIndexNameInstanceLAGA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.g.e.WordnetNounIndexNameInstanceLAGE;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.g.g.WordnetNounIndexNameInstanceLAGG;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.g.i.WordnetNounIndexNameInstanceLAGI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.g.n.WordnetNounIndexNameInstanceLAGN;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.g.o.WordnetNounIndexNameInstanceLAGO;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.g.u.WordnetNounIndexNameInstanceLAGU;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.h.a.WordnetNounIndexNameInstanceLAHA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.h.o.WordnetNounIndexNameInstanceLAHO;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.h.u.WordnetNounIndexNameInstanceLAHU;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.i.r.WordnetNounIndexNameInstanceLAIR;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.i.t.WordnetNounIndexNameInstanceLAIT;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.i.u.WordnetNounIndexNameInstanceLAIU;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.k.e.WordnetNounIndexNameInstanceLAKE;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.k.h.WordnetNounIndexNameInstanceLAKH;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.k.o.WordnetNounIndexNameInstanceLAKO;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.k.s.WordnetNounIndexNameInstanceLAKS;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.l.l.WordnetNounIndexNameInstanceLALL;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.m.a.WordnetNounIndexNameInstanceLAMA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.m.b.WordnetNounIndexNameInstanceLAMB;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.m.e.WordnetNounIndexNameInstanceLAME;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.m.i.WordnetNounIndexNameInstanceLAMI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.m.m.WordnetNounIndexNameInstanceLAMM;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.m.n.WordnetNounIndexNameInstanceLAMN;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.m.p.WordnetNounIndexNameInstanceLAMP;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.a.WordnetNounIndexNameInstanceLANA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.c.WordnetNounIndexNameInstanceLANC;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.d.WordnetNounIndexNameInstanceLAND;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.e.WordnetNounIndexNameInstanceLANE;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.g.WordnetNounIndexNameInstanceLANG;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.i.WordnetNounIndexNameInstanceLANI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.k.WordnetNounIndexNameInstanceLANK;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.o.WordnetNounIndexNameInstanceLANO;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.s.WordnetNounIndexNameInstanceLANS;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.t.WordnetNounIndexNameInstanceLANT;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.u.WordnetNounIndexNameInstanceLANU;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.y.WordnetNounIndexNameInstanceLANY;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.n.z.WordnetNounIndexNameInstanceLANZ;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.o.c.WordnetNounIndexNameInstanceLAOC;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.o.s.WordnetNounIndexNameInstanceLAOS;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.o.t.WordnetNounIndexNameInstanceLAOT;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.a.WordnetNounIndexNameInstanceLAPA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.b.WordnetNounIndexNameInstanceLAPB;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.d.WordnetNounIndexNameInstanceLAPD;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.e.WordnetNounIndexNameInstanceLAPE;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.f.WordnetNounIndexNameInstanceLAPF;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.i.WordnetNounIndexNameInstanceLAPI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.l.WordnetNounIndexNameInstanceLAPL;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.o.WordnetNounIndexNameInstanceLAPO;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.p.WordnetNounIndexNameInstanceLAPP;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.s.WordnetNounIndexNameInstanceLAPS;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.t.WordnetNounIndexNameInstanceLAPT;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.u.WordnetNounIndexNameInstanceLAPU;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.p.w.WordnetNounIndexNameInstanceLAPW;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.a.WordnetNounIndexNameInstanceLARA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.b.WordnetNounIndexNameInstanceLARB;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.c.WordnetNounIndexNameInstanceLARC;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.d.WordnetNounIndexNameInstanceLARD;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.e.WordnetNounIndexNameInstanceLARE;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.g.WordnetNounIndexNameInstanceLARG;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.i.WordnetNounIndexNameInstanceLARI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.k.WordnetNounIndexNameInstanceLARK;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.o.WordnetNounIndexNameInstanceLARO;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.r.WordnetNounIndexNameInstanceLARR;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.u.WordnetNounIndexNameInstanceLARU;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.v.WordnetNounIndexNameInstanceLARV;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.r.y.WordnetNounIndexNameInstanceLARY;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.s.a.WordnetNounIndexNameInstanceLASA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.s.c.WordnetNounIndexNameInstanceLASC;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.s.e.WordnetNounIndexNameInstanceLASE;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.s.h.WordnetNounIndexNameInstanceLASH;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.s.i.WordnetNounIndexNameInstanceLASI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.s.s.WordnetNounIndexNameInstanceLASS;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.s.t.WordnetNounIndexNameInstanceLAST;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.t.a.WordnetNounIndexNameInstanceLATA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.t.c.WordnetNounIndexNameInstanceLATC;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.t.e.WordnetNounIndexNameInstanceLATE;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.t.h.WordnetNounIndexNameInstanceLATH;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.t.i.WordnetNounIndexNameInstanceLATI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.t.k.WordnetNounIndexNameInstanceLATK;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.t.o.WordnetNounIndexNameInstanceLATO;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.t.r.WordnetNounIndexNameInstanceLATR;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.t.s.WordnetNounIndexNameInstanceLATS;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.t.t.WordnetNounIndexNameInstanceLATT;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.t.v.WordnetNounIndexNameInstanceLATV;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.u.d.WordnetNounIndexNameInstanceLAUD;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.u.g.WordnetNounIndexNameInstanceLAUG;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.u.h.WordnetNounIndexNameInstanceLAUH;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.u.n.WordnetNounIndexNameInstanceLAUN;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.u.r.WordnetNounIndexNameInstanceLAUR;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.u.s.WordnetNounIndexNameInstanceLAUS;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.v.a.WordnetNounIndexNameInstanceLAVA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.v.e.WordnetNounIndexNameInstanceLAVE;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.v.i.WordnetNounIndexNameInstanceLAVI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.v.o.WordnetNounIndexNameInstanceLAVO;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.w.b.WordnetNounIndexNameInstanceLAWB;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.w.c.WordnetNounIndexNameInstanceLAWC;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.w.f.WordnetNounIndexNameInstanceLAWF;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.w.g.WordnetNounIndexNameInstanceLAWG;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.w.l.WordnetNounIndexNameInstanceLAWL;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.w.m.WordnetNounIndexNameInstanceLAWM;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.w.n.WordnetNounIndexNameInstanceLAWN;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.w.r.WordnetNounIndexNameInstanceLAWR;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.w.s.WordnetNounIndexNameInstanceLAWS;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.w.t.WordnetNounIndexNameInstanceLAWT;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.w.y.WordnetNounIndexNameInstanceLAWY;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.x.a.WordnetNounIndexNameInstanceLAXA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.x.i.WordnetNounIndexNameInstanceLAXI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.x.n.WordnetNounIndexNameInstanceLAXN;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.y.a.WordnetNounIndexNameInstanceLAYA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.y.b.WordnetNounIndexNameInstanceLAYB;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.y.e.WordnetNounIndexNameInstanceLAYE;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.y.i.WordnetNounIndexNameInstanceLAYI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.y.m.WordnetNounIndexNameInstanceLAYM;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.y.o.WordnetNounIndexNameInstanceLAYO;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.y.p.WordnetNounIndexNameInstanceLAYP;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.y.u.WordnetNounIndexNameInstanceLAYU;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.z.a.WordnetNounIndexNameInstanceLAZA;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.z.i.WordnetNounIndexNameInstanceLAZI;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.z.u.WordnetNounIndexNameInstanceLAZU;
	import org.swtk.commons.dict.wordnet.index.name.instance.l.a.z.y.WordnetNounIndexNameInstanceLAZY;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerLA {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("laag".equals(key)) return WordnetNounIndexNameInstanceLAAG.get(TERM);
	if ("laba".equals(key)) return WordnetNounIndexNameInstanceLABA.get(TERM);
	if ("labd".equals(key)) return WordnetNounIndexNameInstanceLABD.get(TERM);
	if ("labe".equals(key)) return WordnetNounIndexNameInstanceLABE.get(TERM);
	if ("labi".equals(key)) return WordnetNounIndexNameInstanceLABI.get(TERM);
	if ("labl".equals(key)) return WordnetNounIndexNameInstanceLABL.get(TERM);
	if ("labo".equals(key)) return WordnetNounIndexNameInstanceLABO.get(TERM);
	if ("labr".equals(key)) return WordnetNounIndexNameInstanceLABR.get(TERM);
	if ("labu".equals(key)) return WordnetNounIndexNameInstanceLABU.get(TERM);
	if ("laby".equals(key)) return WordnetNounIndexNameInstanceLABY.get(TERM);
	if ("lacc".equals(key)) return WordnetNounIndexNameInstanceLACC.get(TERM);
	if ("lace".equals(key)) return WordnetNounIndexNameInstanceLACE.get(TERM);
	if ("lach".equals(key)) return WordnetNounIndexNameInstanceLACH.get(TERM);
	if ("laci".equals(key)) return WordnetNounIndexNameInstanceLACI.get(TERM);
	if ("lack".equals(key)) return WordnetNounIndexNameInstanceLACK.get(TERM);
	if ("laco".equals(key)) return WordnetNounIndexNameInstanceLACO.get(TERM);
	if ("lacq".equals(key)) return WordnetNounIndexNameInstanceLACQ.get(TERM);
	if ("lacr".equals(key)) return WordnetNounIndexNameInstanceLACR.get(TERM);
	if ("lact".equals(key)) return WordnetNounIndexNameInstanceLACT.get(TERM);
	if ("lacu".equals(key)) return WordnetNounIndexNameInstanceLACU.get(TERM);
	if ("lada".equals(key)) return WordnetNounIndexNameInstanceLADA.get(TERM);
	if ("ladd".equals(key)) return WordnetNounIndexNameInstanceLADD.get(TERM);
	if ("ladi".equals(key)) return WordnetNounIndexNameInstanceLADI.get(TERM);
	if ("ladl".equals(key)) return WordnetNounIndexNameInstanceLADL.get(TERM);
	if ("lado".equals(key)) return WordnetNounIndexNameInstanceLADO.get(TERM);
	if ("lady".equals(key)) return WordnetNounIndexNameInstanceLADY.get(TERM);
	if ("lael".equals(key)) return WordnetNounIndexNameInstanceLAEL.get(TERM);
	if ("laer".equals(key)) return WordnetNounIndexNameInstanceLAER.get(TERM);
	if ("laet".equals(key)) return WordnetNounIndexNameInstanceLAET.get(TERM);
	if ("laev".equals(key)) return WordnetNounIndexNameInstanceLAEV.get(TERM);
	if ("lafa".equals(key)) return WordnetNounIndexNameInstanceLAFA.get(TERM);
	if ("laff".equals(key)) return WordnetNounIndexNameInstanceLAFF.get(TERM);
	if ("lafi".equals(key)) return WordnetNounIndexNameInstanceLAFI.get(TERM);
	if ("laga".equals(key)) return WordnetNounIndexNameInstanceLAGA.get(TERM);
	if ("lage".equals(key)) return WordnetNounIndexNameInstanceLAGE.get(TERM);
	if ("lagg".equals(key)) return WordnetNounIndexNameInstanceLAGG.get(TERM);
	if ("lagi".equals(key)) return WordnetNounIndexNameInstanceLAGI.get(TERM);
	if ("lagn".equals(key)) return WordnetNounIndexNameInstanceLAGN.get(TERM);
	if ("lago".equals(key)) return WordnetNounIndexNameInstanceLAGO.get(TERM);
	if ("lagu".equals(key)) return WordnetNounIndexNameInstanceLAGU.get(TERM);
	if ("laha".equals(key)) return WordnetNounIndexNameInstanceLAHA.get(TERM);
	if ("laho".equals(key)) return WordnetNounIndexNameInstanceLAHO.get(TERM);
	if ("lahu".equals(key)) return WordnetNounIndexNameInstanceLAHU.get(TERM);
	if ("lair".equals(key)) return WordnetNounIndexNameInstanceLAIR.get(TERM);
	if ("lait".equals(key)) return WordnetNounIndexNameInstanceLAIT.get(TERM);
	if ("laiu".equals(key)) return WordnetNounIndexNameInstanceLAIU.get(TERM);
	if ("lake".equals(key)) return WordnetNounIndexNameInstanceLAKE.get(TERM);
	if ("lakh".equals(key)) return WordnetNounIndexNameInstanceLAKH.get(TERM);
	if ("lako".equals(key)) return WordnetNounIndexNameInstanceLAKO.get(TERM);
	if ("laks".equals(key)) return WordnetNounIndexNameInstanceLAKS.get(TERM);
	if ("lall".equals(key)) return WordnetNounIndexNameInstanceLALL.get(TERM);
	if ("lama".equals(key)) return WordnetNounIndexNameInstanceLAMA.get(TERM);
	if ("lamb".equals(key)) return WordnetNounIndexNameInstanceLAMB.get(TERM);
	if ("lame".equals(key)) return WordnetNounIndexNameInstanceLAME.get(TERM);
	if ("lami".equals(key)) return WordnetNounIndexNameInstanceLAMI.get(TERM);
	if ("lamm".equals(key)) return WordnetNounIndexNameInstanceLAMM.get(TERM);
	if ("lamn".equals(key)) return WordnetNounIndexNameInstanceLAMN.get(TERM);
	if ("lamp".equals(key)) return WordnetNounIndexNameInstanceLAMP.get(TERM);
	if ("lana".equals(key)) return WordnetNounIndexNameInstanceLANA.get(TERM);
	if ("lanc".equals(key)) return WordnetNounIndexNameInstanceLANC.get(TERM);
	if ("land".equals(key)) return WordnetNounIndexNameInstanceLAND.get(TERM);
	if ("lane".equals(key)) return WordnetNounIndexNameInstanceLANE.get(TERM);
	if ("lang".equals(key)) return WordnetNounIndexNameInstanceLANG.get(TERM);
	if ("lani".equals(key)) return WordnetNounIndexNameInstanceLANI.get(TERM);
	if ("lank".equals(key)) return WordnetNounIndexNameInstanceLANK.get(TERM);
	if ("lano".equals(key)) return WordnetNounIndexNameInstanceLANO.get(TERM);
	if ("lans".equals(key)) return WordnetNounIndexNameInstanceLANS.get(TERM);
	if ("lant".equals(key)) return WordnetNounIndexNameInstanceLANT.get(TERM);
	if ("lanu".equals(key)) return WordnetNounIndexNameInstanceLANU.get(TERM);
	if ("lany".equals(key)) return WordnetNounIndexNameInstanceLANY.get(TERM);
	if ("lanz".equals(key)) return WordnetNounIndexNameInstanceLANZ.get(TERM);
	if ("laoc".equals(key)) return WordnetNounIndexNameInstanceLAOC.get(TERM);
	if ("laos".equals(key)) return WordnetNounIndexNameInstanceLAOS.get(TERM);
	if ("laot".equals(key)) return WordnetNounIndexNameInstanceLAOT.get(TERM);
	if ("lapa".equals(key)) return WordnetNounIndexNameInstanceLAPA.get(TERM);
	if ("lapb".equals(key)) return WordnetNounIndexNameInstanceLAPB.get(TERM);
	if ("lapd".equals(key)) return WordnetNounIndexNameInstanceLAPD.get(TERM);
	if ("lape".equals(key)) return WordnetNounIndexNameInstanceLAPE.get(TERM);
	if ("lapf".equals(key)) return WordnetNounIndexNameInstanceLAPF.get(TERM);
	if ("lapi".equals(key)) return WordnetNounIndexNameInstanceLAPI.get(TERM);
	if ("lapl".equals(key)) return WordnetNounIndexNameInstanceLAPL.get(TERM);
	if ("lapo".equals(key)) return WordnetNounIndexNameInstanceLAPO.get(TERM);
	if ("lapp".equals(key)) return WordnetNounIndexNameInstanceLAPP.get(TERM);
	if ("laps".equals(key)) return WordnetNounIndexNameInstanceLAPS.get(TERM);
	if ("lapt".equals(key)) return WordnetNounIndexNameInstanceLAPT.get(TERM);
	if ("lapu".equals(key)) return WordnetNounIndexNameInstanceLAPU.get(TERM);
	if ("lapw".equals(key)) return WordnetNounIndexNameInstanceLAPW.get(TERM);
	if ("lara".equals(key)) return WordnetNounIndexNameInstanceLARA.get(TERM);
	if ("larb".equals(key)) return WordnetNounIndexNameInstanceLARB.get(TERM);
	if ("larc".equals(key)) return WordnetNounIndexNameInstanceLARC.get(TERM);
	if ("lard".equals(key)) return WordnetNounIndexNameInstanceLARD.get(TERM);
	if ("lare".equals(key)) return WordnetNounIndexNameInstanceLARE.get(TERM);
	if ("larg".equals(key)) return WordnetNounIndexNameInstanceLARG.get(TERM);
	if ("lari".equals(key)) return WordnetNounIndexNameInstanceLARI.get(TERM);
	if ("lark".equals(key)) return WordnetNounIndexNameInstanceLARK.get(TERM);
	if ("laro".equals(key)) return WordnetNounIndexNameInstanceLARO.get(TERM);
	if ("larr".equals(key)) return WordnetNounIndexNameInstanceLARR.get(TERM);
	if ("laru".equals(key)) return WordnetNounIndexNameInstanceLARU.get(TERM);
	if ("larv".equals(key)) return WordnetNounIndexNameInstanceLARV.get(TERM);
	if ("lary".equals(key)) return WordnetNounIndexNameInstanceLARY.get(TERM);
	if ("lasa".equals(key)) return WordnetNounIndexNameInstanceLASA.get(TERM);
	if ("lasc".equals(key)) return WordnetNounIndexNameInstanceLASC.get(TERM);
	if ("lase".equals(key)) return WordnetNounIndexNameInstanceLASE.get(TERM);
	if ("lash".equals(key)) return WordnetNounIndexNameInstanceLASH.get(TERM);
	if ("lasi".equals(key)) return WordnetNounIndexNameInstanceLASI.get(TERM);
	if ("lass".equals(key)) return WordnetNounIndexNameInstanceLASS.get(TERM);
	if ("last".equals(key)) return WordnetNounIndexNameInstanceLAST.get(TERM);
	if ("lata".equals(key)) return WordnetNounIndexNameInstanceLATA.get(TERM);
	if ("latc".equals(key)) return WordnetNounIndexNameInstanceLATC.get(TERM);
	if ("late".equals(key)) return WordnetNounIndexNameInstanceLATE.get(TERM);
	if ("lath".equals(key)) return WordnetNounIndexNameInstanceLATH.get(TERM);
	if ("lati".equals(key)) return WordnetNounIndexNameInstanceLATI.get(TERM);
	if ("latk".equals(key)) return WordnetNounIndexNameInstanceLATK.get(TERM);
	if ("lato".equals(key)) return WordnetNounIndexNameInstanceLATO.get(TERM);
	if ("latr".equals(key)) return WordnetNounIndexNameInstanceLATR.get(TERM);
	if ("lats".equals(key)) return WordnetNounIndexNameInstanceLATS.get(TERM);
	if ("latt".equals(key)) return WordnetNounIndexNameInstanceLATT.get(TERM);
	if ("latv".equals(key)) return WordnetNounIndexNameInstanceLATV.get(TERM);
	if ("laud".equals(key)) return WordnetNounIndexNameInstanceLAUD.get(TERM);
	if ("laug".equals(key)) return WordnetNounIndexNameInstanceLAUG.get(TERM);
	if ("lauh".equals(key)) return WordnetNounIndexNameInstanceLAUH.get(TERM);
	if ("laun".equals(key)) return WordnetNounIndexNameInstanceLAUN.get(TERM);
	if ("laur".equals(key)) return WordnetNounIndexNameInstanceLAUR.get(TERM);
	if ("laus".equals(key)) return WordnetNounIndexNameInstanceLAUS.get(TERM);
	if ("lava".equals(key)) return WordnetNounIndexNameInstanceLAVA.get(TERM);
	if ("lave".equals(key)) return WordnetNounIndexNameInstanceLAVE.get(TERM);
	if ("lavi".equals(key)) return WordnetNounIndexNameInstanceLAVI.get(TERM);
	if ("lavo".equals(key)) return WordnetNounIndexNameInstanceLAVO.get(TERM);
	if ("lawb".equals(key)) return WordnetNounIndexNameInstanceLAWB.get(TERM);
	if ("lawc".equals(key)) return WordnetNounIndexNameInstanceLAWC.get(TERM);
	if ("lawf".equals(key)) return WordnetNounIndexNameInstanceLAWF.get(TERM);
	if ("lawg".equals(key)) return WordnetNounIndexNameInstanceLAWG.get(TERM);
	if ("lawl".equals(key)) return WordnetNounIndexNameInstanceLAWL.get(TERM);
	if ("lawm".equals(key)) return WordnetNounIndexNameInstanceLAWM.get(TERM);
	if ("lawn".equals(key)) return WordnetNounIndexNameInstanceLAWN.get(TERM);
	if ("lawr".equals(key)) return WordnetNounIndexNameInstanceLAWR.get(TERM);
	if ("laws".equals(key)) return WordnetNounIndexNameInstanceLAWS.get(TERM);
	if ("lawt".equals(key)) return WordnetNounIndexNameInstanceLAWT.get(TERM);
	if ("lawy".equals(key)) return WordnetNounIndexNameInstanceLAWY.get(TERM);
	if ("laxa".equals(key)) return WordnetNounIndexNameInstanceLAXA.get(TERM);
	if ("laxi".equals(key)) return WordnetNounIndexNameInstanceLAXI.get(TERM);
	if ("laxn".equals(key)) return WordnetNounIndexNameInstanceLAXN.get(TERM);
	if ("laya".equals(key)) return WordnetNounIndexNameInstanceLAYA.get(TERM);
	if ("layb".equals(key)) return WordnetNounIndexNameInstanceLAYB.get(TERM);
	if ("laye".equals(key)) return WordnetNounIndexNameInstanceLAYE.get(TERM);
	if ("layi".equals(key)) return WordnetNounIndexNameInstanceLAYI.get(TERM);
	if ("laym".equals(key)) return WordnetNounIndexNameInstanceLAYM.get(TERM);
	if ("layo".equals(key)) return WordnetNounIndexNameInstanceLAYO.get(TERM);
	if ("layp".equals(key)) return WordnetNounIndexNameInstanceLAYP.get(TERM);
	if ("layu".equals(key)) return WordnetNounIndexNameInstanceLAYU.get(TERM);
	if ("laza".equals(key)) return WordnetNounIndexNameInstanceLAZA.get(TERM);
	if ("lazi".equals(key)) return WordnetNounIndexNameInstanceLAZI.get(TERM);
	if ("lazu".equals(key)) return WordnetNounIndexNameInstanceLAZU.get(TERM);
	if ("lazy".equals(key)) return WordnetNounIndexNameInstanceLAZY.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceLAAG.terms());
	set.addAll(WordnetNounIndexNameInstanceLABA.terms());
	set.addAll(WordnetNounIndexNameInstanceLABD.terms());
	set.addAll(WordnetNounIndexNameInstanceLABE.terms());
	set.addAll(WordnetNounIndexNameInstanceLABI.terms());
	set.addAll(WordnetNounIndexNameInstanceLABL.terms());
	set.addAll(WordnetNounIndexNameInstanceLABO.terms());
	set.addAll(WordnetNounIndexNameInstanceLABR.terms());
	set.addAll(WordnetNounIndexNameInstanceLABU.terms());
	set.addAll(WordnetNounIndexNameInstanceLABY.terms());
	set.addAll(WordnetNounIndexNameInstanceLACC.terms());
	set.addAll(WordnetNounIndexNameInstanceLACE.terms());
	set.addAll(WordnetNounIndexNameInstanceLACH.terms());
	set.addAll(WordnetNounIndexNameInstanceLACI.terms());
	set.addAll(WordnetNounIndexNameInstanceLACK.terms());
	set.addAll(WordnetNounIndexNameInstanceLACO.terms());
	set.addAll(WordnetNounIndexNameInstanceLACQ.terms());
	set.addAll(WordnetNounIndexNameInstanceLACR.terms());
	set.addAll(WordnetNounIndexNameInstanceLACT.terms());
	set.addAll(WordnetNounIndexNameInstanceLACU.terms());
	set.addAll(WordnetNounIndexNameInstanceLADA.terms());
	set.addAll(WordnetNounIndexNameInstanceLADD.terms());
	set.addAll(WordnetNounIndexNameInstanceLADI.terms());
	set.addAll(WordnetNounIndexNameInstanceLADL.terms());
	set.addAll(WordnetNounIndexNameInstanceLADO.terms());
	set.addAll(WordnetNounIndexNameInstanceLADY.terms());
	set.addAll(WordnetNounIndexNameInstanceLAEL.terms());
	set.addAll(WordnetNounIndexNameInstanceLAER.terms());
	set.addAll(WordnetNounIndexNameInstanceLAET.terms());
	set.addAll(WordnetNounIndexNameInstanceLAEV.terms());
	set.addAll(WordnetNounIndexNameInstanceLAFA.terms());
	set.addAll(WordnetNounIndexNameInstanceLAFF.terms());
	set.addAll(WordnetNounIndexNameInstanceLAFI.terms());
	set.addAll(WordnetNounIndexNameInstanceLAGA.terms());
	set.addAll(WordnetNounIndexNameInstanceLAGE.terms());
	set.addAll(WordnetNounIndexNameInstanceLAGG.terms());
	set.addAll(WordnetNounIndexNameInstanceLAGI.terms());
	set.addAll(WordnetNounIndexNameInstanceLAGN.terms());
	set.addAll(WordnetNounIndexNameInstanceLAGO.terms());
	set.addAll(WordnetNounIndexNameInstanceLAGU.terms());
	set.addAll(WordnetNounIndexNameInstanceLAHA.terms());
	set.addAll(WordnetNounIndexNameInstanceLAHO.terms());
	set.addAll(WordnetNounIndexNameInstanceLAHU.terms());
	set.addAll(WordnetNounIndexNameInstanceLAIR.terms());
	set.addAll(WordnetNounIndexNameInstanceLAIT.terms());
	set.addAll(WordnetNounIndexNameInstanceLAIU.terms());
	set.addAll(WordnetNounIndexNameInstanceLAKE.terms());
	set.addAll(WordnetNounIndexNameInstanceLAKH.terms());
	set.addAll(WordnetNounIndexNameInstanceLAKO.terms());
	set.addAll(WordnetNounIndexNameInstanceLAKS.terms());
	set.addAll(WordnetNounIndexNameInstanceLALL.terms());
	set.addAll(WordnetNounIndexNameInstanceLAMA.terms());
	set.addAll(WordnetNounIndexNameInstanceLAMB.terms());
	set.addAll(WordnetNounIndexNameInstanceLAME.terms());
	set.addAll(WordnetNounIndexNameInstanceLAMI.terms());
	set.addAll(WordnetNounIndexNameInstanceLAMM.terms());
	set.addAll(WordnetNounIndexNameInstanceLAMN.terms());
	set.addAll(WordnetNounIndexNameInstanceLAMP.terms());
	set.addAll(WordnetNounIndexNameInstanceLANA.terms());
	set.addAll(WordnetNounIndexNameInstanceLANC.terms());
	set.addAll(WordnetNounIndexNameInstanceLAND.terms());
	set.addAll(WordnetNounIndexNameInstanceLANE.terms());
	set.addAll(WordnetNounIndexNameInstanceLANG.terms());
	set.addAll(WordnetNounIndexNameInstanceLANI.terms());
	set.addAll(WordnetNounIndexNameInstanceLANK.terms());
	set.addAll(WordnetNounIndexNameInstanceLANO.terms());
	set.addAll(WordnetNounIndexNameInstanceLANS.terms());
	set.addAll(WordnetNounIndexNameInstanceLANT.terms());
	set.addAll(WordnetNounIndexNameInstanceLANU.terms());
	set.addAll(WordnetNounIndexNameInstanceLANY.terms());
	set.addAll(WordnetNounIndexNameInstanceLANZ.terms());
	set.addAll(WordnetNounIndexNameInstanceLAOC.terms());
	set.addAll(WordnetNounIndexNameInstanceLAOS.terms());
	set.addAll(WordnetNounIndexNameInstanceLAOT.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPA.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPB.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPD.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPE.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPF.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPI.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPL.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPO.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPP.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPS.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPT.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPU.terms());
	set.addAll(WordnetNounIndexNameInstanceLAPW.terms());
	set.addAll(WordnetNounIndexNameInstanceLARA.terms());
	set.addAll(WordnetNounIndexNameInstanceLARB.terms());
	set.addAll(WordnetNounIndexNameInstanceLARC.terms());
	set.addAll(WordnetNounIndexNameInstanceLARD.terms());
	set.addAll(WordnetNounIndexNameInstanceLARE.terms());
	set.addAll(WordnetNounIndexNameInstanceLARG.terms());
	set.addAll(WordnetNounIndexNameInstanceLARI.terms());
	set.addAll(WordnetNounIndexNameInstanceLARK.terms());
	set.addAll(WordnetNounIndexNameInstanceLARO.terms());
	set.addAll(WordnetNounIndexNameInstanceLARR.terms());
	set.addAll(WordnetNounIndexNameInstanceLARU.terms());
	set.addAll(WordnetNounIndexNameInstanceLARV.terms());
	set.addAll(WordnetNounIndexNameInstanceLARY.terms());
	set.addAll(WordnetNounIndexNameInstanceLASA.terms());
	set.addAll(WordnetNounIndexNameInstanceLASC.terms());
	set.addAll(WordnetNounIndexNameInstanceLASE.terms());
	set.addAll(WordnetNounIndexNameInstanceLASH.terms());
	set.addAll(WordnetNounIndexNameInstanceLASI.terms());
	set.addAll(WordnetNounIndexNameInstanceLASS.terms());
	set.addAll(WordnetNounIndexNameInstanceLAST.terms());
	set.addAll(WordnetNounIndexNameInstanceLATA.terms());
	set.addAll(WordnetNounIndexNameInstanceLATC.terms());
	set.addAll(WordnetNounIndexNameInstanceLATE.terms());
	set.addAll(WordnetNounIndexNameInstanceLATH.terms());
	set.addAll(WordnetNounIndexNameInstanceLATI.terms());
	set.addAll(WordnetNounIndexNameInstanceLATK.terms());
	set.addAll(WordnetNounIndexNameInstanceLATO.terms());
	set.addAll(WordnetNounIndexNameInstanceLATR.terms());
	set.addAll(WordnetNounIndexNameInstanceLATS.terms());
	set.addAll(WordnetNounIndexNameInstanceLATT.terms());
	set.addAll(WordnetNounIndexNameInstanceLATV.terms());
	set.addAll(WordnetNounIndexNameInstanceLAUD.terms());
	set.addAll(WordnetNounIndexNameInstanceLAUG.terms());
	set.addAll(WordnetNounIndexNameInstanceLAUH.terms());
	set.addAll(WordnetNounIndexNameInstanceLAUN.terms());
	set.addAll(WordnetNounIndexNameInstanceLAUR.terms());
	set.addAll(WordnetNounIndexNameInstanceLAUS.terms());
	set.addAll(WordnetNounIndexNameInstanceLAVA.terms());
	set.addAll(WordnetNounIndexNameInstanceLAVE.terms());
	set.addAll(WordnetNounIndexNameInstanceLAVI.terms());
	set.addAll(WordnetNounIndexNameInstanceLAVO.terms());
	set.addAll(WordnetNounIndexNameInstanceLAWB.terms());
	set.addAll(WordnetNounIndexNameInstanceLAWC.terms());
	set.addAll(WordnetNounIndexNameInstanceLAWF.terms());
	set.addAll(WordnetNounIndexNameInstanceLAWG.terms());
	set.addAll(WordnetNounIndexNameInstanceLAWL.terms());
	set.addAll(WordnetNounIndexNameInstanceLAWM.terms());
	set.addAll(WordnetNounIndexNameInstanceLAWN.terms());
	set.addAll(WordnetNounIndexNameInstanceLAWR.terms());
	set.addAll(WordnetNounIndexNameInstanceLAWS.terms());
	set.addAll(WordnetNounIndexNameInstanceLAWT.terms());
	set.addAll(WordnetNounIndexNameInstanceLAWY.terms());
	set.addAll(WordnetNounIndexNameInstanceLAXA.terms());
	set.addAll(WordnetNounIndexNameInstanceLAXI.terms());
	set.addAll(WordnetNounIndexNameInstanceLAXN.terms());
	set.addAll(WordnetNounIndexNameInstanceLAYA.terms());
	set.addAll(WordnetNounIndexNameInstanceLAYB.terms());
	set.addAll(WordnetNounIndexNameInstanceLAYE.terms());
	set.addAll(WordnetNounIndexNameInstanceLAYI.terms());
	set.addAll(WordnetNounIndexNameInstanceLAYM.terms());
	set.addAll(WordnetNounIndexNameInstanceLAYO.terms());
	set.addAll(WordnetNounIndexNameInstanceLAYP.terms());
	set.addAll(WordnetNounIndexNameInstanceLAYU.terms());
	set.addAll(WordnetNounIndexNameInstanceLAZA.terms());
	set.addAll(WordnetNounIndexNameInstanceLAZI.terms());
	set.addAll(WordnetNounIndexNameInstanceLAZU.terms());
	set.addAll(WordnetNounIndexNameInstanceLAZY.terms());
  		return set; 	} }