package org.swtk.commons.dict.wordnet.index.name.instance.a.b.o.r;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceABOR {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"abor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06946601\"]}");
	add("{\"term\":\"aboriginal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09643964\"]}");
	add("{\"term\":\"aborigine\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09695957\", \"09643964\"]}");
	add("{\"term\":\"abort\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00035660\"]}");
	add("{\"term\":\"aborticide\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00232182\", \"02670536\"]}");
	add("{\"term\":\"abortifacient\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02670536\"]}");
	add("{\"term\":\"abortion\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07334252\", \"00231191\"]}");
	add("{\"term\":\"abortionist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09776506\"]}");
	add("{\"term\":\"abortus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01462944\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public boolean has(final String TERM) { 		return map.containsKey(TERM); 	} }