package org.swtk.commons.dict.wordnet.index.name.instance.t.r.e.n;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceTREN {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"trenail\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04485301\"]}");
	add("{\"term\":\"trench\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04486124\", \"09484445\", \"04485892\"]}");
	add("{\"term\":\"trenchancy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05206948\"]}");
	add("{\"term\":\"trencher\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04486390\", \"10747769\"]}");
	add("{\"term\":\"trencherman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10152508\"]}");
	add("{\"term\":\"trend\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"05758160\", \"06207399\", \"08698960\", \"08699515\"]}");
	add("{\"term\":\"trent\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08830404\", \"09484645\"]}");
	add("{\"term\":\"trental\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03919556\"]}");
	add("{\"term\":\"trento\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08830404\"]}");
	add("{\"term\":\"trenton\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09135675\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public boolean has(final String TERM) { 		return map.containsKey(TERM); 	} }