package org.swtk.commons.dict.wordnet.index.name.instance.c.h.r.i;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceCHRI {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"chrism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03030033\"]}");
	add("{\"term\":\"chrisom\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03030033\"]}");
	add("{\"term\":\"christ\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09560771\", \"11103646\"]}");
	add("{\"term\":\"christchurch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08995415\"]}");
	add("{\"term\":\"christella\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13249434\"]}");
	add("{\"term\":\"christendom\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08099113\"]}");
	add("{\"term\":\"christening\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01040407\"]}");
	add("{\"term\":\"christian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09697405\"]}");
	add("{\"term\":\"christiania\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08782902\"]}");
	add("{\"term\":\"christianisation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07369947\"]}");
	add("{\"term\":\"christianity\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08099113\", \"06236188\"]}");
	add("{\"term\":\"christianization\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07369947\"]}");
	add("{\"term\":\"christie\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10916739\"]}");
	add("{\"term\":\"christmas\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"15221021\", \"15221372\"]}");
	add("{\"term\":\"christmasberry\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12653822\", \"12926172\"]}");
	add("{\"term\":\"christmastide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15221372\"]}");
	add("{\"term\":\"christmastime\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15221372\"]}");
	add("{\"term\":\"christology\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06194309\", \"06196748\"]}");
	add("{\"term\":\"christopher\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10916906\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }