package org.swtk.commons.dict.wordnet.indexbyname.controller.l.u;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.a.WordnetNounIndexNameInstanceLUA;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.b.WordnetNounIndexNameInstanceLUB;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.c.WordnetNounIndexNameInstanceLUC;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.d.WordnetNounIndexNameInstanceLUD;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.e.WordnetNounIndexNameInstanceLUE;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.f.WordnetNounIndexNameInstanceLUF;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.g.WordnetNounIndexNameInstanceLUG;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.i.WordnetNounIndexNameInstanceLUI;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.k.WordnetNounIndexNameInstanceLUK;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.l.WordnetNounIndexNameInstanceLUL;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.m.WordnetNounIndexNameInstanceLUM;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.n.WordnetNounIndexNameInstanceLUN;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.o.WordnetNounIndexNameInstanceLUO;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.p.WordnetNounIndexNameInstanceLUP;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.r.WordnetNounIndexNameInstanceLUR;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.s.WordnetNounIndexNameInstanceLUS;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.t.WordnetNounIndexNameInstanceLUT;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.v.WordnetNounIndexNameInstanceLUV;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.w.WordnetNounIndexNameInstanceLUW;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.x.WordnetNounIndexNameInstanceLUX;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.y.WordnetNounIndexNameInstanceLUY;
	import org.swtk.commons.dict.wordnet.indexbyname.instance.l.u.z.WordnetNounIndexNameInstanceLUZ;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerLU {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException { 		if (TERM.length() < 3) throw new BusinessException("TERM not found (term = %s)", TERM); 		 		String key = TERM.replaceAll(" ", "").substring(0, 3).toLowerCase(); 			if ("lua".equals(key)) return WordnetNounIndexNameInstanceLUA.get(TERM);
	if ("lub".equals(key)) return WordnetNounIndexNameInstanceLUB.get(TERM);
	if ("luc".equals(key)) return WordnetNounIndexNameInstanceLUC.get(TERM);
	if ("lud".equals(key)) return WordnetNounIndexNameInstanceLUD.get(TERM);
	if ("lue".equals(key)) return WordnetNounIndexNameInstanceLUE.get(TERM);
	if ("luf".equals(key)) return WordnetNounIndexNameInstanceLUF.get(TERM);
	if ("lug".equals(key)) return WordnetNounIndexNameInstanceLUG.get(TERM);
	if ("lui".equals(key)) return WordnetNounIndexNameInstanceLUI.get(TERM);
	if ("luk".equals(key)) return WordnetNounIndexNameInstanceLUK.get(TERM);
	if ("lul".equals(key)) return WordnetNounIndexNameInstanceLUL.get(TERM);
	if ("lum".equals(key)) return WordnetNounIndexNameInstanceLUM.get(TERM);
	if ("lun".equals(key)) return WordnetNounIndexNameInstanceLUN.get(TERM);
	if ("luo".equals(key)) return WordnetNounIndexNameInstanceLUO.get(TERM);
	if ("lup".equals(key)) return WordnetNounIndexNameInstanceLUP.get(TERM);
	if ("lur".equals(key)) return WordnetNounIndexNameInstanceLUR.get(TERM);
	if ("lus".equals(key)) return WordnetNounIndexNameInstanceLUS.get(TERM);
	if ("lut".equals(key)) return WordnetNounIndexNameInstanceLUT.get(TERM);
	if ("luv".equals(key)) return WordnetNounIndexNameInstanceLUV.get(TERM);
	if ("luw".equals(key)) return WordnetNounIndexNameInstanceLUW.get(TERM);
	if ("lux".equals(key)) return WordnetNounIndexNameInstanceLUX.get(TERM);
	if ("luy".equals(key)) return WordnetNounIndexNameInstanceLUY.get(TERM);
	if ("luz".equals(key)) return WordnetNounIndexNameInstanceLUZ.get(TERM);
  		throw new BusinessException("TERM not found (term = %s)", TERM); 	}  	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceLUA.terms());
	set.addAll(WordnetNounIndexNameInstanceLUB.terms());
	set.addAll(WordnetNounIndexNameInstanceLUC.terms());
	set.addAll(WordnetNounIndexNameInstanceLUD.terms());
	set.addAll(WordnetNounIndexNameInstanceLUE.terms());
	set.addAll(WordnetNounIndexNameInstanceLUF.terms());
	set.addAll(WordnetNounIndexNameInstanceLUG.terms());
	set.addAll(WordnetNounIndexNameInstanceLUI.terms());
	set.addAll(WordnetNounIndexNameInstanceLUK.terms());
	set.addAll(WordnetNounIndexNameInstanceLUL.terms());
	set.addAll(WordnetNounIndexNameInstanceLUM.terms());
	set.addAll(WordnetNounIndexNameInstanceLUN.terms());
	set.addAll(WordnetNounIndexNameInstanceLUO.terms());
	set.addAll(WordnetNounIndexNameInstanceLUP.terms());
	set.addAll(WordnetNounIndexNameInstanceLUR.terms());
	set.addAll(WordnetNounIndexNameInstanceLUS.terms());
	set.addAll(WordnetNounIndexNameInstanceLUT.terms());
	set.addAll(WordnetNounIndexNameInstanceLUV.terms());
	set.addAll(WordnetNounIndexNameInstanceLUW.terms());
	set.addAll(WordnetNounIndexNameInstanceLUX.terms());
	set.addAll(WordnetNounIndexNameInstanceLUY.terms());
	set.addAll(WordnetNounIndexNameInstanceLUZ.terms());
  		return set; 	} }