package org.swtk.commons.dict.wordnet.indexbyname.instance.n.e.o;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceNEO {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"neobiotic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03823630\"]}");
	add("{\"term\":\"neoceratodus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02519498\"]}");
	add("{\"term\":\"neoclassicism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06163988\"]}");
	add("{\"term\":\"neoclassicist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10372288\"]}");
	add("{\"term\":\"neocolonialism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00427760\"]}");
	add("{\"term\":\"neocon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10372394\"]}");
	add("{\"term\":\"neoconservatism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06226345\"]}");
	add("{\"term\":\"neoconservative\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10372394\"]}");
	add("{\"term\":\"neocortex\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05489398\"]}");
	add("{\"term\":\"neodymium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14670060\"]}");
	add("{\"term\":\"neoencephalon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05489201\"]}");
	add("{\"term\":\"neoexpressionism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08484587\"]}");
	add("{\"term\":\"neofiber\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02340971\"]}");
	add("{\"term\":\"neohygrophorus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13094286\"]}");
	add("{\"term\":\"neolentinus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13071956\"]}");
	add("{\"term\":\"neoliberal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10372513\"]}");
	add("{\"term\":\"neoliberalism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06228946\"]}");
	add("{\"term\":\"neolith\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03823541\"]}");
	add("{\"term\":\"neolithic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15258208\"]}");
	add("{\"term\":\"neologism\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00942376\", \"06305222\"]}");
	add("{\"term\":\"neologist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10372629\"]}");
	add("{\"term\":\"neology\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00942376\", \"06305222\"]}");
	add("{\"term\":\"neomycin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03823630\"]}");
	add("{\"term\":\"neomys\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01895517\"]}");
	add("{\"term\":\"neon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14670330\"]}");
	add("{\"term\":\"neonate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10372747\"]}");
	add("{\"term\":\"neonatology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06071467\"]}");
	add("{\"term\":\"neopallium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05489398\"]}");
	add("{\"term\":\"neophobia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14407366\"]}");
	add("{\"term\":\"neophron\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01620274\"]}");
	add("{\"term\":\"neophyte\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"09920955\", \"10375148\", \"11574085\"]}");
	add("{\"term\":\"neoplasia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13542052\"]}");
	add("{\"term\":\"neoplasm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14258682\"]}");
	add("{\"term\":\"neoplatonism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05982470\"]}");
	add("{\"term\":\"neoplatonist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10372968\"]}");
	add("{\"term\":\"neopolitan\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09736233\"]}");
	add("{\"term\":\"neoprene\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15031944\"]}");
	add("{\"term\":\"neoromanticism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08486796\"]}");
	add("{\"term\":\"neosho\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09391376\"]}");
	add("{\"term\":\"neosporin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03824169\"]}");
	add("{\"term\":\"neostigmine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03824383\"]}");
	add("{\"term\":\"neoteny\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06207818\"]}");
	add("{\"term\":\"neotoma\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02342420\"]}");
	add("{\"term\":\"neotony\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14593264\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }