package org.swtk.commons.dict.wordnet.index.name.controller.w.r;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.a.c.WordnetNounIndexNameInstanceWRAC;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.a.i.WordnetNounIndexNameInstanceWRAI;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.a.n.WordnetNounIndexNameInstanceWRAN;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.a.p.WordnetNounIndexNameInstanceWRAP;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.a.s.WordnetNounIndexNameInstanceWRAS;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.a.t.WordnetNounIndexNameInstanceWRAT;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.e.a.WordnetNounIndexNameInstanceWREA;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.e.c.WordnetNounIndexNameInstanceWREC;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.e.n.WordnetNounIndexNameInstanceWREN;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.e.s.WordnetNounIndexNameInstanceWRES;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.e.t.WordnetNounIndexNameInstanceWRET;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.i.c.WordnetNounIndexNameInstanceWRIC;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.i.g.WordnetNounIndexNameInstanceWRIG;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.i.n.WordnetNounIndexNameInstanceWRIN;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.i.s.WordnetNounIndexNameInstanceWRIS;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.i.t.WordnetNounIndexNameInstanceWRIT;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.o.c.WordnetNounIndexNameInstanceWROC;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.o.n.WordnetNounIndexNameInstanceWRON;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.y.m.WordnetNounIndexNameInstanceWRYM;
	import org.swtk.commons.dict.wordnet.index.name.instance.w.r.y.n.WordnetNounIndexNameInstanceWRYN;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerWR {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("wrac".equals(key)) return WordnetNounIndexNameInstanceWRAC.get(TERM);
	if ("wrai".equals(key)) return WordnetNounIndexNameInstanceWRAI.get(TERM);
	if ("wran".equals(key)) return WordnetNounIndexNameInstanceWRAN.get(TERM);
	if ("wrap".equals(key)) return WordnetNounIndexNameInstanceWRAP.get(TERM);
	if ("wras".equals(key)) return WordnetNounIndexNameInstanceWRAS.get(TERM);
	if ("wrat".equals(key)) return WordnetNounIndexNameInstanceWRAT.get(TERM);
	if ("wrea".equals(key)) return WordnetNounIndexNameInstanceWREA.get(TERM);
	if ("wrec".equals(key)) return WordnetNounIndexNameInstanceWREC.get(TERM);
	if ("wren".equals(key)) return WordnetNounIndexNameInstanceWREN.get(TERM);
	if ("wres".equals(key)) return WordnetNounIndexNameInstanceWRES.get(TERM);
	if ("wret".equals(key)) return WordnetNounIndexNameInstanceWRET.get(TERM);
	if ("wric".equals(key)) return WordnetNounIndexNameInstanceWRIC.get(TERM);
	if ("wrig".equals(key)) return WordnetNounIndexNameInstanceWRIG.get(TERM);
	if ("wrin".equals(key)) return WordnetNounIndexNameInstanceWRIN.get(TERM);
	if ("wris".equals(key)) return WordnetNounIndexNameInstanceWRIS.get(TERM);
	if ("writ".equals(key)) return WordnetNounIndexNameInstanceWRIT.get(TERM);
	if ("wroc".equals(key)) return WordnetNounIndexNameInstanceWROC.get(TERM);
	if ("wron".equals(key)) return WordnetNounIndexNameInstanceWRON.get(TERM);
	if ("wrym".equals(key)) return WordnetNounIndexNameInstanceWRYM.get(TERM);
	if ("wryn".equals(key)) return WordnetNounIndexNameInstanceWRYN.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceWRAC.terms());
	set.addAll(WordnetNounIndexNameInstanceWRAI.terms());
	set.addAll(WordnetNounIndexNameInstanceWRAN.terms());
	set.addAll(WordnetNounIndexNameInstanceWRAP.terms());
	set.addAll(WordnetNounIndexNameInstanceWRAS.terms());
	set.addAll(WordnetNounIndexNameInstanceWRAT.terms());
	set.addAll(WordnetNounIndexNameInstanceWREA.terms());
	set.addAll(WordnetNounIndexNameInstanceWREC.terms());
	set.addAll(WordnetNounIndexNameInstanceWREN.terms());
	set.addAll(WordnetNounIndexNameInstanceWRES.terms());
	set.addAll(WordnetNounIndexNameInstanceWRET.terms());
	set.addAll(WordnetNounIndexNameInstanceWRIC.terms());
	set.addAll(WordnetNounIndexNameInstanceWRIG.terms());
	set.addAll(WordnetNounIndexNameInstanceWRIN.terms());
	set.addAll(WordnetNounIndexNameInstanceWRIS.terms());
	set.addAll(WordnetNounIndexNameInstanceWRIT.terms());
	set.addAll(WordnetNounIndexNameInstanceWROC.terms());
	set.addAll(WordnetNounIndexNameInstanceWRON.terms());
	set.addAll(WordnetNounIndexNameInstanceWRYM.terms());
	set.addAll(WordnetNounIndexNameInstanceWRYN.terms());
  		return set; 	} }