package org.swtk.commons.dict.wordnet.index.name.instance.c.a.r.a;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceCARA {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"carabao\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02411463\"]}");
	add("{\"term\":\"carabidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02169638\"]}");
	add("{\"term\":\"carabineer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09913198\"]}");
	add("{\"term\":\"carabiner\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02964126\"]}");
	add("{\"term\":\"carabinier\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09913198\"]}");
	add("{\"term\":\"caracal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02130330\"]}");
	add("{\"term\":\"caracara\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01615269\"]}");
	add("{\"term\":\"caracas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09185069\"]}");
	add("{\"term\":\"carack\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02971669\"]}");
	add("{\"term\":\"caracolito\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12722884\"]}");
	add("{\"term\":\"caracul\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02416689\"]}");
	add("{\"term\":\"carafate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04356779\"]}");
	add("{\"term\":\"carafe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02964339\"]}");
	add("{\"term\":\"caragana\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12532361\"]}");
	add("{\"term\":\"carageen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01417274\"]}");
	add("{\"term\":\"carambola\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07762527\", \"12725103\"]}");
	add("{\"term\":\"caramel\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04981224\", \"07610751\", \"07617380\"]}");
	add("{\"term\":\"carancha\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01615818\"]}");
	add("{\"term\":\"caranda\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12609541\"]}");
	add("{\"term\":\"caranday\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12609541\"]}");
	add("{\"term\":\"carangid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02578854\"]}");
	add("{\"term\":\"carangidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02578397\"]}");
	add("{\"term\":\"caranx\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02579091\"]}");
	add("{\"term\":\"carapace\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01906397\"]}");
	add("{\"term\":\"carapidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02561863\"]}");
	add("{\"term\":\"carassius\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01446039\"]}");
	add("{\"term\":\"carat\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13606330\", \"13745687\"]}");
	add("{\"term\":\"caravaggio\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10901841\"]}");
	add("{\"term\":\"caravan\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04527677\", \"08444586\"]}");
	add("{\"term\":\"caravanning\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01067985\"]}");
	add("{\"term\":\"caravansary\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02964471\"]}");
	add("{\"term\":\"caravanserai\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02964471\"]}");
	add("{\"term\":\"caraway\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07832702\", \"12955239\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public boolean has(final String TERM) { 		return map.containsKey(TERM); 	} }