package org.swtk.commons.dict.wordnet.indexbyname.instance.t.h.o;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceTHO {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"tho\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06948847\"]}");
	add("{\"term\":\"thole\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03911849\"]}");
	add("{\"term\":\"tholepin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03911849\"]}");
	add("{\"term\":\"thomas\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"11358791\", \"11359036\", \"11359150\", \"11359356\", \"11359529\"]}");
	add("{\"term\":\"thomas a becket\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10859617\"]}");
	add("{\"term\":\"thomas a kempis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10830422\"]}");
	add("{\"term\":\"thomas alva edison\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10969184\"]}");
	add("{\"term\":\"thomas aquinas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10840394\"]}");
	add("{\"term\":\"thomas augustus watson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11396560\"]}");
	add("{\"term\":\"thomas babington macaulay\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11166904\"]}");
	add("{\"term\":\"thomas bayes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10858593\"]}");
	add("{\"term\":\"thomas bowdler\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10879265\"]}");
	add("{\"term\":\"thomas bradley\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10880595\"]}");
	add("{\"term\":\"thomas carew\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10902188\"]}");
	add("{\"term\":\"thomas carlyle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10902458\"]}");
	add("{\"term\":\"thomas chippendale\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10915798\"]}");
	add("{\"term\":\"thomas clayton wolfe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11414486\"]}");
	add("{\"term\":\"thomas crawford\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10934410\"]}");
	add("{\"term\":\"thomas de quincey\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10950918\"]}");
	add("{\"term\":\"thomas decker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10947891\"]}");
	add("{\"term\":\"thomas dekker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10947891\"]}");
	add("{\"term\":\"thomas edison\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10969184\"]}");
	add("{\"term\":\"thomas edward lawrence\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11140824\"]}");
	add("{\"term\":\"thomas gainsborough\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11007040\"]}");
	add("{\"term\":\"thomas gray\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11032842\"]}");
	add("{\"term\":\"thomas hardy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11048671\"]}");
	add("{\"term\":\"thomas hart benton\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10865359\", \"10865522\"]}");
	add("{\"term\":\"thomas hastings\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11054303\"]}");
	add("{\"term\":\"thomas henry huxley\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11089524\"]}");
	add("{\"term\":\"thomas higginson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11069603\"]}");
	add("{\"term\":\"thomas hobbes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11072950\"]}");
	add("{\"term\":\"thomas hodgkin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11074029\"]}");
	add("{\"term\":\"thomas hopkins gallaudet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11008055\"]}");
	add("{\"term\":\"thomas hunt morgan\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11210944\"]}");
	add("{\"term\":\"thomas huxley\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11089524\"]}");
	add("{\"term\":\"thomas jackson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11096069\"]}");
	add("{\"term\":\"thomas jefferson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11101818\"]}");
	add("{\"term\":\"thomas jonathan jackson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11096069\"]}");
	add("{\"term\":\"thomas kid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11133479\"]}");
	add("{\"term\":\"thomas kyd\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11133479\"]}");
	add("{\"term\":\"thomas lanier williams\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11409476\"]}");
	add("{\"term\":\"thomas malory\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11172321\"]}");
	add("{\"term\":\"thomas malthus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11172846\"]}");
	add("{\"term\":\"thomas mann\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11174013\"]}");
	add("{\"term\":\"thomas merton\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11196787\"]}");
	add("{\"term\":\"thomas middleton\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11198771\"]}");
	add("{\"term\":\"thomas moore\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11209569\"]}");
	add("{\"term\":\"thomas more\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11210173\"]}");
	add("{\"term\":\"thomas nast\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11220939\"]}");
	add("{\"term\":\"thomas nelson page\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11239982\"]}");
	add("{\"term\":\"thomas paine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11240826\"]}");
	add("{\"term\":\"thomas pynchon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11269702\"]}");
	add("{\"term\":\"thomas reid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11277537\"]}");
	add("{\"term\":\"thomas robert malthus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11172846\"]}");
	add("{\"term\":\"thomas stearns eliot\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10977064\"]}");
	add("{\"term\":\"thomas straussler\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11340240\"]}");
	add("{\"term\":\"thomas sully\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11345260\"]}");
	add("{\"term\":\"thomas sydenham\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11347268\"]}");
	add("{\"term\":\"thomas tallis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11349803\"]}");
	add("{\"term\":\"thomas the doubting apostle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11358791\"]}");
	add("{\"term\":\"thomas wentworth storrow higginson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11069603\"]}");
	add("{\"term\":\"thomas willis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11410544\"]}");
	add("{\"term\":\"thomas wolfe\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11414486\", \"11414652\"]}");
	add("{\"term\":\"thomas woodrow wilson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11410850\"]}");
	add("{\"term\":\"thomas wright waller\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11392237\"]}");
	add("{\"term\":\"thomas young\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11423824\"]}");
	add("{\"term\":\"thomism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06197085\"]}");
	add("{\"term\":\"thomomys\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02357122\"]}");
	add("{\"term\":\"thomomys bottae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02357273\"]}");
	add("{\"term\":\"thomomys talpoides\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02357433\"]}");
	add("{\"term\":\"thompson\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11359664\", \"11359900\"]}");
	add("{\"term\":\"thompson seedless\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07776731\"]}");
	add("{\"term\":\"thompson submachine gun\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04457404\"]}");
	add("{\"term\":\"thomson\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"11360141\", \"11360406\", \"11360637\", \"11360819\"]}");
	add("{\"term\":\"thong\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"03368854\", \"03468985\", \"04433451\", \"04433562\", \"03649221\"]}");
	add("{\"term\":\"thor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09606681\"]}");
	add("{\"term\":\"thor hyerdahl\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11068581\"]}");
	add("{\"term\":\"thoracentesis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00946112\"]}");
	add("{\"term\":\"thoracic actinomycosis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14283118\"]}");
	add("{\"term\":\"thoracic aorta\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05344296\"]}");
	add("{\"term\":\"thoracic cavity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05560682\"]}");
	add("{\"term\":\"thoracic duct\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05404033\"]}");
	add("{\"term\":\"thoracic medicine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06074233\"]}");
	add("{\"term\":\"thoracic nerve\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05577610\"]}");
	add("{\"term\":\"thoracic outlet syndrome\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14334257\"]}");
	add("{\"term\":\"thoracic vein\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05390810\"]}");
	add("{\"term\":\"thoracic vertebra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05596782\"]}");
	add("{\"term\":\"thoracocentesis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00946112\"]}");
	add("{\"term\":\"thoracoepigastric vein\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05390347\"]}");
	add("{\"term\":\"thoracotomy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00699601\"]}");
	add("{\"term\":\"thorax\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"02668173\", \"05560240\", \"05561251\"]}");
	add("{\"term\":\"thorazine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03026858\"]}");
	add("{\"term\":\"thoreau\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11360987\"]}");
	add("{\"term\":\"thorite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15094933\"]}");
	add("{\"term\":\"thorium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14682288\"]}");
	add("{\"term\":\"thorn\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"06853492\", \"13110391\", \"05840108\"]}");
	add("{\"term\":\"thorn apple\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12924127\"]}");
	add("{\"term\":\"thornbill\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01837181\"]}");
	add("{\"term\":\"thorndike\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11361132\", \"11361262\"]}");
	add("{\"term\":\"thorniness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04650754\", \"04956976\"]}");
	add("{\"term\":\"thornton\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11361369\"]}");
	add("{\"term\":\"thornton niven wilder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11406687\"]}");
	add("{\"term\":\"thornton wilder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11406687\"]}");
	add("{\"term\":\"thorny amaranth\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11844813\"]}");
	add("{\"term\":\"thorny skate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01504589\"]}");
	add("{\"term\":\"thorough bass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07046043\"]}");
	add("{\"term\":\"thoroughbred\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"01326240\", \"02385883\", \"10729007\"]}");
	add("{\"term\":\"thoroughbred race\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07478128\"]}");
	add("{\"term\":\"thoroughbred racing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00451215\"]}");
	add("{\"term\":\"thoroughfare\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04433753\"]}");
	add("{\"term\":\"thoroughness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04680215\"]}");
	add("{\"term\":\"thoroughwort\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11989400\"]}");
	add("{\"term\":\"thorpe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11361474\"]}");
	add("{\"term\":\"thorshavn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08972802\"]}");
	add("{\"term\":\"thorstein bunde veblen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11382017\"]}");
	add("{\"term\":\"thorstein veblen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11382017\"]}");
	add("{\"term\":\"thortveitite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15095117\"]}");
	add("{\"term\":\"thoth\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09536879\"]}");
	add("{\"term\":\"thou\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13772984\"]}");
	add("{\"term\":\"thought\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"05954491\", \"05963348\", \"05778923\", \"05842164\"]}");
	add("{\"term\":\"thought process\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05778923\"]}");
	add("{\"term\":\"thought transference\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07270666\"]}");
	add("{\"term\":\"thoughtfulness\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"01232282\", \"04667893\", \"04848589\", \"05793513\"]}");
	add("{\"term\":\"thoughtlessness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04669063\", \"04853198\"]}");
	add("{\"term\":\"thousand\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13772984\"]}");
	add("{\"term\":\"thousand and one nights\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07236890\"]}");
	add("{\"term\":\"thousand island dressing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07851149\"]}");
	add("{\"term\":\"thousandth\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13761310\", \"13872007\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }