package org.swtk.commons.dict.wordnet.indexbyname.instance.y.e.l;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceYEL {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"yell\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07135865\", \"07135232\"]}");
	add("{\"term\":\"yeller\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10553540\"]}");
	add("{\"term\":\"yelling\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07138260\"]}");
	add("{\"term\":\"yellow\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04972838\"]}");
	add("{\"term\":\"yellow ageratum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12013275\"]}");
	add("{\"term\":\"yellow asphodel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12463202\"]}");
	add("{\"term\":\"yellow avens\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12652398\", \"12652693\"]}");
	add("{\"term\":\"yellow bass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02569296\"]}");
	add("{\"term\":\"yellow bean\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07744684\"]}");
	add("{\"term\":\"yellow bedstraw\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12686618\"]}");
	add("{\"term\":\"yellow bells\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12856091\"]}");
	add("{\"term\":\"yellow berry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13162192\"]}");
	add("{\"term\":\"yellow bile\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05414301\"]}");
	add("{\"term\":\"yellow birch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12302305\"]}");
	add("{\"term\":\"yellow bone marrow\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05293507\"]}");
	add("{\"term\":\"yellow bristle grass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12155353\"]}");
	add("{\"term\":\"yellow bristlegrass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12155353\"]}");
	add("{\"term\":\"yellow bugle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12862232\"]}");
	add("{\"term\":\"yellow bunting\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01540841\"]}");
	add("{\"term\":\"yellow cattley guava\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12354288\"]}");
	add("{\"term\":\"yellow cedar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11656281\"]}");
	add("{\"term\":\"yellow chamomile\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11943866\"]}");
	add("{\"term\":\"yellow chestnut oak\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12296192\"]}");
	add("{\"term\":\"yellow cleavers\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12686618\"]}");
	add("{\"term\":\"yellow clintonia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12493064\"]}");
	add("{\"term\":\"yellow colicroot\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12451180\"]}");
	add("{\"term\":\"yellow cypress\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11656281\"]}");
	add("{\"term\":\"yellow delicious\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07756318\"]}");
	add("{\"term\":\"yellow dock\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12625400\"]}");
	add("{\"term\":\"yellow dwarf\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14308190\"]}");
	add("{\"term\":\"yellow dwarf of potato\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14308378\"]}");
	add("{\"term\":\"yellow fever\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14168442\"]}");
	add("{\"term\":\"yellow flag\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12435107\"]}");
	add("{\"term\":\"yellow foxglove\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12904025\"]}");
	add("{\"term\":\"yellow foxtail\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12155353\"]}");
	add("{\"term\":\"yellow giant hyssop\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12860928\"]}");
	add("{\"term\":\"yellow globe lily\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12467626\"]}");
	add("{\"term\":\"yellow goatfish\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02603428\"]}");
	add("{\"term\":\"yellow granadilla\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07770255\", \"12404892\"]}");
	add("{\"term\":\"yellow green\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04975434\"]}");
	add("{\"term\":\"yellow gurnard\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02653043\"]}");
	add("{\"term\":\"yellow hawkweed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12002811\"]}");
	add("{\"term\":\"yellow henbane\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12932674\"]}");
	add("{\"term\":\"yellow honeysuckle\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12695861\", \"12696060\"]}");
	add("{\"term\":\"yellow horned poppy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11926218\"]}");
	add("{\"term\":\"yellow hornet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02216440\"]}");
	add("{\"term\":\"yellow iris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12435107\"]}");
	add("{\"term\":\"yellow ironweed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12051377\"]}");
	add("{\"term\":\"yellow jacaranda\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12594416\"]}");
	add("{\"term\":\"yellow jack\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"02579672\", \"04619980\", \"14168442\"]}");
	add("{\"term\":\"yellow jacket\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02216440\", \"03919248\"]}");
	add("{\"term\":\"yellow jasmine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12506486\"]}");
	add("{\"term\":\"yellow jessamine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12506486\"]}");
	add("{\"term\":\"yellow journalism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06278644\"]}");
	add("{\"term\":\"yellow light\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06887887\"]}");
	add("{\"term\":\"yellow locust\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12588691\"]}");
	add("{\"term\":\"yellow loosestrife\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12116298\"]}");
	add("{\"term\":\"yellow lupine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12567337\"]}");
	add("{\"term\":\"yellow mariposa tulip\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12468641\"]}");
	add("{\"term\":\"yellow marrow\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05293507\"]}");
	add("{\"term\":\"yellow metal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14744399\"]}");
	add("{\"term\":\"yellow milkwort\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12726218\"]}");
	add("{\"term\":\"yellow mombin\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07781588\", \"12786606\"]}");
	add("{\"term\":\"yellow mombin tree\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12786606\"]}");
	add("{\"term\":\"yellow mountain saxifrage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12814044\"]}");
	add("{\"term\":\"yellow nutgrass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12171486\"]}");
	add("{\"term\":\"yellow oak\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12299975\"]}");
	add("{\"term\":\"yellow ocher\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14868451\"]}");
	add("{\"term\":\"yellow ochre\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14868451\"]}");
	add("{\"term\":\"yellow oleander\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11797549\"]}");
	add("{\"term\":\"yellow pages\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07266041\"]}");
	add("{\"term\":\"yellow paper daisy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12000787\"]}");
	add("{\"term\":\"yellow parilla\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11733839\"]}");
	add("{\"term\":\"yellow pea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12593979\"]}");
	add("{\"term\":\"yellow perch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02559813\"]}");
	add("{\"term\":\"yellow peril\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14567013\"]}");
	add("{\"term\":\"yellow pimpernel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12115929\"]}");
	add("{\"term\":\"yellow pine\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11629813\", \"11634701\"]}");
	add("{\"term\":\"yellow pitcher plant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12801323\"]}");
	add("{\"term\":\"yellow pond lily\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11736891\"]}");
	add("{\"term\":\"yellow poplar\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11732751\", \"11733090\"]}");
	add("{\"term\":\"yellow prussiate of potash\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15019628\"]}");
	add("{\"term\":\"yellow river\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09329163\"]}");
	add("{\"term\":\"yellow rocket\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11894550\"]}");
	add("{\"term\":\"yellow root\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11756039\"]}");
	add("{\"term\":\"yellow salsify\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12047450\"]}");
	add("{\"term\":\"yellow sand verbena\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11857820\"]}");
	add("{\"term\":\"yellow sea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09505088\"]}");
	add("{\"term\":\"yellow spiny daisy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11996980\"]}");
	add("{\"term\":\"yellow spot\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05463266\", \"14308615\"]}");
	add("{\"term\":\"yellow spot fungus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13101626\"]}");
	add("{\"term\":\"yellow spruce\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11647277\"]}");
	add("{\"term\":\"yellow squash\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07731779\", \"12179905\"]}");
	add("{\"term\":\"yellow sweet clover\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11771816\"]}");
	add("{\"term\":\"yellow trefoil\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12569697\"]}");
	add("{\"term\":\"yellow trumpet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12801323\"]}");
	add("{\"term\":\"yellow turnip\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07752063\"]}");
	add("{\"term\":\"yellow twining snapdragon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12898397\"]}");
	add("{\"term\":\"yellow vetchling\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12561662\"]}");
	add("{\"term\":\"yellow warbler\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01571533\"]}");
	add("{\"term\":\"yellow water flag\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12435107\"]}");
	add("{\"term\":\"yellow water lily\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11737346\"]}");
	add("{\"term\":\"yellow watercress\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11915941\"]}");
	add("{\"term\":\"yellowbelly marmot\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02364502\"]}");
	add("{\"term\":\"yellowbird\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01534966\", \"01571533\"]}");
	add("{\"term\":\"yellowcake\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15131096\"]}");
	add("{\"term\":\"yellowfin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02630162\"]}");
	add("{\"term\":\"yellowfin croaker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02599634\"]}");
	add("{\"term\":\"yellowfin mojarra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02639809\"]}");
	add("{\"term\":\"yellowfin tuna\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02630162\"]}");
	add("{\"term\":\"yellowhammer\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01540841\", \"01842391\"]}");
	add("{\"term\":\"yellowish brown\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04981224\"]}");
	add("{\"term\":\"yellowish green\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04975434\"]}");
	add("{\"term\":\"yellowish pink\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04978942\"]}");
	add("{\"term\":\"yellowknife\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08845142\"]}");
	add("{\"term\":\"yellowlegs\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02030829\"]}");
	add("{\"term\":\"yellowness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04972838\"]}");
	add("{\"term\":\"yellowstone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09505261\"]}");
	add("{\"term\":\"yellowstone national park\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08627862\"]}");
	add("{\"term\":\"yellowstone river\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09505261\"]}");
	add("{\"term\":\"yellowtail\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02581559\", \"02590507\"]}");
	add("{\"term\":\"yellowtail flounder\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02661806\", \"07806776\"]}");
	add("{\"term\":\"yellowtail snapper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02590507\"]}");
	add("{\"term\":\"yellowthroat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01573317\"]}");
	add("{\"term\":\"yellowwood\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11671009\", \"11671584\"]}");
	add("{\"term\":\"yellowwood tree\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11671009\"]}");
	add("{\"term\":\"yelp\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07415152\"]}");
	add("{\"term\":\"yelping\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07415152\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }