package org.swtk.commons.dict.wordnet.index.name.instance.p.a.l.e;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstancePALE {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"pale\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03936190\"]}");
	add("{\"term\":\"paleacrita\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02289856\"]}");
	add("{\"term\":\"paleencephalon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05489781\"]}");
	add("{\"term\":\"paleness\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04982879\", \"04984514\", \"04984828\"]}");
	add("{\"term\":\"paleoanthropology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06083739\"]}");
	add("{\"term\":\"paleobiology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06088274\"]}");
	add("{\"term\":\"paleobotany\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06083922\"]}");
	add("{\"term\":\"paleocene\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15150952\"]}");
	add("{\"term\":\"paleocerebellum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05493971\"]}");
	add("{\"term\":\"paleoclimatology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06154777\"]}");
	add("{\"term\":\"paleocortex\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05489522\"]}");
	add("{\"term\":\"paleodendrology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06084278\"]}");
	add("{\"term\":\"paleoecology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06092297\"]}");
	add("{\"term\":\"paleoencephalon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05489781\"]}");
	add("{\"term\":\"paleoethnography\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06156211\"]}");
	add("{\"term\":\"paleogeography\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06154897\"]}");
	add("{\"term\":\"paleogeology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06127002\"]}");
	add("{\"term\":\"paleographer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10414372\"]}");
	add("{\"term\":\"paleographist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10414372\"]}");
	add("{\"term\":\"paleography\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06155037\"]}");
	add("{\"term\":\"paleolith\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03884115\"]}");
	add("{\"term\":\"paleolithic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15257202\"]}");
	add("{\"term\":\"paleology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06155593\"]}");
	add("{\"term\":\"paleomammalogy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06084566\"]}");
	add("{\"term\":\"paleontologist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10414485\"]}");
	add("{\"term\":\"paleontology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06083438\"]}");
	add("{\"term\":\"paleopathology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06155180\"]}");
	add("{\"term\":\"paleornithology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06084662\"]}");
	add("{\"term\":\"paleostriatum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05505951\"]}");
	add("{\"term\":\"paleozoic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15151883\"]}");
	add("{\"term\":\"paleozoology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06084410\"]}");
	add("{\"term\":\"palermo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08829325\"]}");
	add("{\"term\":\"palestine\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08816234\", \"08816623\"]}");
	add("{\"term\":\"palestinian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09732753\"]}");
	add("{\"term\":\"palestra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03884208\"]}");
	add("{\"term\":\"palestrina\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11241258\"]}");
	add("{\"term\":\"paletiology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06155348\"]}");
	add("{\"term\":\"palette\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"03885402\", \"03884371\", \"05135635\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public boolean has(final String TERM) { 		return map.containsKey(TERM); 	} }