package org.swtk.commons.dict.wordnet.indexbyname.instance.c.o.s;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceCOS {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"cos\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07740237\", \"13809935\"]}");
	add("{\"term\":\"cos lettuce\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07740237\", \"12007198\"]}");
	add("{\"term\":\"cosa nostra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08262723\"]}");
	add("{\"term\":\"coscoroba\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01860922\"]}");
	add("{\"term\":\"cosec\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13811214\"]}");
	add("{\"term\":\"cosecant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13811214\"]}");
	add("{\"term\":\"cosh\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02850699\"]}");
	add("{\"term\":\"cosignatory\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09636720\"]}");
	add("{\"term\":\"cosigner\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09636883\", \"09636720\"]}");
	add("{\"term\":\"cosimo de medici\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10932203\"]}");
	add("{\"term\":\"cosimo the elder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10932203\"]}");
	add("{\"term\":\"cosine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13809935\"]}");
	add("{\"term\":\"cosiness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14469764\"]}");
	add("{\"term\":\"cosmea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11978549\"]}");
	add("{\"term\":\"cosmetic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03117803\"]}");
	add("{\"term\":\"cosmetic dentistry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06057454\"]}");
	add("{\"term\":\"cosmetic surgeon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09986800\"]}");
	add("{\"term\":\"cosmetic surgery\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00675401\"]}");
	add("{\"term\":\"cosmetician\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09865407\", \"09986593\"]}");
	add("{\"term\":\"cosmetologist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09986689\"]}");
	add("{\"term\":\"cosmetology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00633130\"]}");
	add("{\"term\":\"cosmic background radiation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11461173\"]}");
	add("{\"term\":\"cosmic dust\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11461512\"]}");
	add("{\"term\":\"cosmic microwave background\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11461173\"]}");
	add("{\"term\":\"cosmic microwave background radiation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11461173\"]}");
	add("{\"term\":\"cosmic radiation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11461657\"]}");
	add("{\"term\":\"cosmic ray\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11461803\"]}");
	add("{\"term\":\"cosmic string\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09472431\"]}");
	add("{\"term\":\"cosmic time\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15141309\"]}");
	add("{\"term\":\"cosmid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01374840\"]}");
	add("{\"term\":\"cosmocampus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01458937\"]}");
	add("{\"term\":\"cosmocampus profundus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01459095\"]}");
	add("{\"term\":\"cosmogeny\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06107802\"]}");
	add("{\"term\":\"cosmogony\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06107802\"]}");
	add("{\"term\":\"cosmographer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09838882\"]}");
	add("{\"term\":\"cosmographist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09838882\"]}");
	add("{\"term\":\"cosmography\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03117988\", \"06132733\"]}");
	add("{\"term\":\"cosmolatry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01047848\"]}");
	add("{\"term\":\"cosmological constant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13610749\"]}");
	add("{\"term\":\"cosmologist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09839072\"]}");
	add("{\"term\":\"cosmology\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06107802\", \"06172939\"]}");
	add("{\"term\":\"cosmonaut\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09837427\"]}");
	add("{\"term\":\"cosmopolitan\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09986936\"]}");
	add("{\"term\":\"cosmopolite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09986936\"]}");
	add("{\"term\":\"cosmos\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11978549\", \"09489410\"]}");
	add("{\"term\":\"cosmotron\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03118156\"]}");
	add("{\"term\":\"coss\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13674147\"]}");
	add("{\"term\":\"cossack\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09987085\"]}");
	add("{\"term\":\"cost\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"05171334\", \"05152365\", \"13296870\"]}");
	add("{\"term\":\"cost accountant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09987346\"]}");
	add("{\"term\":\"cost accounting\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00620251\"]}");
	add("{\"term\":\"cost analysis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00650033\"]}");
	add("{\"term\":\"cost cutting\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00353604\"]}");
	add("{\"term\":\"cost increase\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05117708\"]}");
	add("{\"term\":\"cost ledger\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13425707\"]}");
	add("{\"term\":\"cost of capital\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13326954\"]}");
	add("{\"term\":\"cost of living\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13323023\"]}");
	add("{\"term\":\"cost overrun\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13322857\"]}");
	add("{\"term\":\"costa\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05286525\", \"05599881\"]}");
	add("{\"term\":\"costa rica\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08753940\"]}");
	add("{\"term\":\"costa rican\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09718184\"]}");
	add("{\"term\":\"costa rican colon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13689477\"]}");
	add("{\"term\":\"costa rican monetary unit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13689360\"]}");
	add("{\"term\":\"costal cartilage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05600057\"]}");
	add("{\"term\":\"costal groove\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05230541\"]}");
	add("{\"term\":\"costalgia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14353451\"]}");
	add("{\"term\":\"costanoan\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06937337\", \"09673510\"]}");
	add("{\"term\":\"costermonger\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09987658\"]}");
	add("{\"term\":\"costia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01422214\"]}");
	add("{\"term\":\"costia necatrix\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01422214\"]}");
	add("{\"term\":\"costiasis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14286242\"]}");
	add("{\"term\":\"costing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00620382\"]}");
	add("{\"term\":\"costliness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05153519\"]}");
	add("{\"term\":\"costmary\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07833575\", \"12041968\"]}");
	add("{\"term\":\"costoaxillary vein\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05372278\"]}");
	add("{\"term\":\"costochondritis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14365057\"]}");
	add("{\"term\":\"costs\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13314648\"]}");
	add("{\"term\":\"costume\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"03118486\", \"03118887\", \"03118692\", \"03118308\"]}");
	add("{\"term\":\"costume designer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09987789\"]}");
	add("{\"term\":\"costumer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09987789\"]}");
	add("{\"term\":\"costumier\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09987789\"]}");
	add("{\"term\":\"costus oil\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14917557\"]}");
	add("{\"term\":\"costusroot\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12030657\"]}");
	add("{\"term\":\"cosy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03119030\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }