package org.swtk.commons.dict.wordnet.index.name.controller.g.h;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.a.n.WordnetNounIndexNameInstanceGHAN;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.a.r.WordnetNounIndexNameInstanceGHAR;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.a.s.WordnetNounIndexNameInstanceGHAS;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.a.t.WordnetNounIndexNameInstanceGHAT;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.e.e.WordnetNounIndexNameInstanceGHEE;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.e.g.WordnetNounIndexNameInstanceGHEG;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.e.n.WordnetNounIndexNameInstanceGHEN;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.e.r.WordnetNounIndexNameInstanceGHER;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.e.t.WordnetNounIndexNameInstanceGHET;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.i.l.WordnetNounIndexNameInstanceGHIL;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.o.s.WordnetNounIndexNameInstanceGHOS;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.o.u.WordnetNounIndexNameInstanceGHOU;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.r.e.WordnetNounIndexNameInstanceGHRE;
	import org.swtk.commons.dict.wordnet.index.name.instance.g.h.r.f.WordnetNounIndexNameInstanceGHRF;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerGH {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("ghan".equals(key)) return WordnetNounIndexNameInstanceGHAN.get(TERM);
	if ("ghar".equals(key)) return WordnetNounIndexNameInstanceGHAR.get(TERM);
	if ("ghas".equals(key)) return WordnetNounIndexNameInstanceGHAS.get(TERM);
	if ("ghat".equals(key)) return WordnetNounIndexNameInstanceGHAT.get(TERM);
	if ("ghee".equals(key)) return WordnetNounIndexNameInstanceGHEE.get(TERM);
	if ("gheg".equals(key)) return WordnetNounIndexNameInstanceGHEG.get(TERM);
	if ("ghen".equals(key)) return WordnetNounIndexNameInstanceGHEN.get(TERM);
	if ("gher".equals(key)) return WordnetNounIndexNameInstanceGHER.get(TERM);
	if ("ghet".equals(key)) return WordnetNounIndexNameInstanceGHET.get(TERM);
	if ("ghil".equals(key)) return WordnetNounIndexNameInstanceGHIL.get(TERM);
	if ("ghos".equals(key)) return WordnetNounIndexNameInstanceGHOS.get(TERM);
	if ("ghou".equals(key)) return WordnetNounIndexNameInstanceGHOU.get(TERM);
	if ("ghre".equals(key)) return WordnetNounIndexNameInstanceGHRE.get(TERM);
	if ("ghrf".equals(key)) return WordnetNounIndexNameInstanceGHRF.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceGHAN.terms());
	set.addAll(WordnetNounIndexNameInstanceGHAR.terms());
	set.addAll(WordnetNounIndexNameInstanceGHAS.terms());
	set.addAll(WordnetNounIndexNameInstanceGHAT.terms());
	set.addAll(WordnetNounIndexNameInstanceGHEE.terms());
	set.addAll(WordnetNounIndexNameInstanceGHEG.terms());
	set.addAll(WordnetNounIndexNameInstanceGHEN.terms());
	set.addAll(WordnetNounIndexNameInstanceGHER.terms());
	set.addAll(WordnetNounIndexNameInstanceGHET.terms());
	set.addAll(WordnetNounIndexNameInstanceGHIL.terms());
	set.addAll(WordnetNounIndexNameInstanceGHOS.terms());
	set.addAll(WordnetNounIndexNameInstanceGHOU.terms());
	set.addAll(WordnetNounIndexNameInstanceGHRE.terms());
	set.addAll(WordnetNounIndexNameInstanceGHRF.terms());
  		return set; 	} }