package org.swtk.commons.dict.wiktionary.terms;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.commons.dict.wiktionary.generated.w.a.a.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.c.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.d.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.f.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.g.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.h.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.i.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.k.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.l.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.m.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.n.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.p.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.q.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.r.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.s.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.t.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.v.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.x.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.y.*;
import org.swtk.commons.dict.wiktionary.generated.w.a.z.*;
import org.swtk.commons.dict.wiktionary.generated.w.e.a.*;
import org.swtk.commons.dict.wiktionary.generated.w.e.b.*;
import org.swtk.commons.dict.wiktionary.generated.w.e.d.*;
import org.swtk.commons.dict.wiktionary.generated.w.e.e.*;
import org.swtk.commons.dict.wiktionary.generated.w.e.g.*;
import org.swtk.commons.dict.wiktionary.generated.w.e.i.*;
import org.swtk.commons.dict.wiktionary.generated.w.e.l.*;
import org.swtk.commons.dict.wiktionary.generated.w.e.n.*;
import org.swtk.commons.dict.wiktionary.generated.w.e.r.*;
import org.swtk.commons.dict.wiktionary.generated.w.e.s.*;
import org.swtk.commons.dict.wiktionary.generated.w.e.t.*;
import org.swtk.commons.dict.wiktionary.generated.w.h.a.*;
import org.swtk.commons.dict.wiktionary.generated.w.h.e.*;
import org.swtk.commons.dict.wiktionary.generated.w.h.i.*;
import org.swtk.commons.dict.wiktionary.generated.w.h.o.*;
import org.swtk.commons.dict.wiktionary.generated.w.h.u.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.c.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.d.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.e.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.f.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.g.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.k.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.l.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.m.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.n.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.p.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.r.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.s.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.t.*;
import org.swtk.commons.dict.wiktionary.generated.w.i.z.*;
import org.swtk.commons.dict.wiktionary.generated.w.l.a.*;
import org.swtk.commons.dict.wiktionary.generated.w.o.a.*;
import org.swtk.commons.dict.wiktionary.generated.w.o.b.*;
import org.swtk.commons.dict.wiktionary.generated.w.o.d.*;
import org.swtk.commons.dict.wiktionary.generated.w.o.g.*;
import org.swtk.commons.dict.wiktionary.generated.w.o.k.*;
import org.swtk.commons.dict.wiktionary.generated.w.o.l.*;
import org.swtk.commons.dict.wiktionary.generated.w.o.m.*;
import org.swtk.commons.dict.wiktionary.generated.w.o.n.*;
import org.swtk.commons.dict.wiktionary.generated.w.o.o.*;
import org.swtk.commons.dict.wiktionary.generated.w.o.r.*;
import org.swtk.commons.dict.wiktionary.generated.w.o.u.*;
import org.swtk.commons.dict.wiktionary.generated.w.o.w.*;
import org.swtk.commons.dict.wiktionary.generated.w.r.a.*;
import org.swtk.commons.dict.wiktionary.generated.w.r.e.*;
import org.swtk.commons.dict.wiktionary.generated.w.r.i.*;
import org.swtk.commons.dict.wiktionary.generated.w.r.o.*;
import org.swtk.commons.dict.wiktionary.generated.w.r.y.*;
import org.swtk.commons.dict.wiktionary.generated.w.u.d.*;
import org.swtk.commons.dict.wiktionary.generated.w.u.l.*;
import org.swtk.commons.dict.wiktionary.generated.w.u.n.*;
import org.swtk.commons.dict.wiktionary.generated.w.u.r.*;
import org.swtk.commons.dict.wiktionary.generated.w.u.s.*;
import org.swtk.commons.dict.wiktionary.generated.w.y.n.*;
import org.swtk.commons.dict.wiktionary.generated.w.y.o.*;
import org.swtk.commons.dict.wiktionary.generated.w.y.t.*;
import org.swtk.commons.dict.wiktionary.generated.w.y.v.*;  public final class WiktionaryTermsW {  	public static Collection<String> terms() { 		Set<String> set = new TreeSet<String>();  		set.addAll(WiktionaryWAA000.terms());
set.addAll(WiktionaryWAC000.terms());
set.addAll(WiktionaryWAD000.terms());
set.addAll(WiktionaryWAF000.terms());
set.addAll(WiktionaryWAG000.terms());
set.addAll(WiktionaryWAH000.terms());
set.addAll(WiktionaryWAI000.terms());
set.addAll(WiktionaryWAK000.terms());
set.addAll(WiktionaryWAL000.terms());
set.addAll(WiktionaryWAM000.terms());
set.addAll(WiktionaryWAN000.terms());
set.addAll(WiktionaryWAP000.terms());
set.addAll(WiktionaryWAQ000.terms());
set.addAll(WiktionaryWAR000.terms());
set.addAll(WiktionaryWAS000.terms());
set.addAll(WiktionaryWAT000.terms());
set.addAll(WiktionaryWAV000.terms());
set.addAll(WiktionaryWAX000.terms());
set.addAll(WiktionaryWAY000.terms());
set.addAll(WiktionaryWAZ000.terms());
set.addAll(WiktionaryWEA000.terms());
set.addAll(WiktionaryWEB000.terms());
set.addAll(WiktionaryWED000.terms());
set.addAll(WiktionaryWEE000.terms());
set.addAll(WiktionaryWEG000.terms());
set.addAll(WiktionaryWEI000.terms());
set.addAll(WiktionaryWEL000.terms());
set.addAll(WiktionaryWEN000.terms());
set.addAll(WiktionaryWER000.terms());
set.addAll(WiktionaryWES000.terms());
set.addAll(WiktionaryWET000.terms());
set.addAll(WiktionaryWHA000.terms());
set.addAll(WiktionaryWHE000.terms());
set.addAll(WiktionaryWHI000.terms());
set.addAll(WiktionaryWHO000.terms());
set.addAll(WiktionaryWHU000.terms());
set.addAll(WiktionaryWIC000.terms());
set.addAll(WiktionaryWID000.terms());
set.addAll(WiktionaryWIE000.terms());
set.addAll(WiktionaryWIF000.terms());
set.addAll(WiktionaryWIG000.terms());
set.addAll(WiktionaryWIK000.terms());
set.addAll(WiktionaryWIL000.terms());
set.addAll(WiktionaryWIM000.terms());
set.addAll(WiktionaryWIN000.terms());
set.addAll(WiktionaryWIP000.terms());
set.addAll(WiktionaryWIR000.terms());
set.addAll(WiktionaryWIS000.terms());
set.addAll(WiktionaryWIT000.terms());
set.addAll(WiktionaryWIZ000.terms());
set.addAll(WiktionaryWLA000.terms());
set.addAll(WiktionaryWOA000.terms());
set.addAll(WiktionaryWOB000.terms());
set.addAll(WiktionaryWOD000.terms());
set.addAll(WiktionaryWOG000.terms());
set.addAll(WiktionaryWOK000.terms());
set.addAll(WiktionaryWOL000.terms());
set.addAll(WiktionaryWOM000.terms());
set.addAll(WiktionaryWON000.terms());
set.addAll(WiktionaryWOO000.terms());
set.addAll(WiktionaryWOR000.terms());
set.addAll(WiktionaryWOU000.terms());
set.addAll(WiktionaryWOW000.terms());
set.addAll(WiktionaryWRA000.terms());
set.addAll(WiktionaryWRE000.terms());
set.addAll(WiktionaryWRI000.terms());
set.addAll(WiktionaryWRO000.terms());
set.addAll(WiktionaryWRY000.terms());
set.addAll(WiktionaryWUD000.terms());
set.addAll(WiktionaryWUL000.terms());
set.addAll(WiktionaryWUN000.terms());
set.addAll(WiktionaryWUR000.terms());
set.addAll(WiktionaryWUS000.terms());
set.addAll(WiktionaryWYN000.terms());
set.addAll(WiktionaryWYO000.terms());
set.addAll(WiktionaryWYT000.terms());
set.addAll(WiktionaryWYV000.terms());  		return set; 	} }