package org.swtk.commons.dict.wordnet.indexbyname.instance.b.e.n;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceBEN {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"ben\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09241548\"]}");
	add("{\"term\":\"ben gurion\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10864401\"]}");
	add("{\"term\":\"ben hecht\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11057962\"]}");
	add("{\"term\":\"ben hogan\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11075449\"]}");
	add("{\"term\":\"ben jonson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11111174\"]}");
	add("{\"term\":\"ben shahn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11315023\"]}");
	add("{\"term\":\"ben sira\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06471965\"]}");
	add("{\"term\":\"benadryl\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03207909\"]}");
	add("{\"term\":\"bench\", \"synsetCount\":7, \"upperType\":\"NOUN\", \"ids\":[\"02832300\", \"08226440\", \"08345627\", \"04607813\", \"08183086\", \"09479337\", \"02832068\"]}");
	add("{\"term\":\"bench clamp\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02832430\"]}");
	add("{\"term\":\"bench hook\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02832537\"]}");
	add("{\"term\":\"bench lathe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02832694\"]}");
	add("{\"term\":\"bench mark\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07273813\"]}");
	add("{\"term\":\"bench press\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02832780\", \"00627814\"]}");
	add("{\"term\":\"bench vise\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04545847\"]}");
	add("{\"term\":\"bench warmer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09869282\"]}");
	add("{\"term\":\"bench warrant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06559606\"]}");
	add("{\"term\":\"benchley\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10863301\"]}");
	add("{\"term\":\"benchmark\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07273813\", \"07275811\"]}");
	add("{\"term\":\"bend\", \"synsetCount\":6, \"upperType\":\"NOUN\", \"ids\":[\"02833197\", \"09156059\", \"13930429\", \"02832880\", \"07325609\", \"13891966\"]}");
	add("{\"term\":\"bend dexter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02833197\"]}");
	add("{\"term\":\"bend sinister\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06808147\"]}");
	add("{\"term\":\"bendability\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05029875\"]}");
	add("{\"term\":\"benday process\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05673469\"]}");
	add("{\"term\":\"bender\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"00108695\", \"00512052\", \"02833341\"]}");
	add("{\"term\":\"bending\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"00406027\", \"05018461\", \"07325609\"]}");
	add("{\"term\":\"bendopa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14629310\"]}");
	add("{\"term\":\"bends\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14091826\"]}");
	add("{\"term\":\"bendy tree\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12209152\"]}");
	add("{\"term\":\"benedetto caetani\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10876395\"]}");
	add("{\"term\":\"benedetto odescalchi\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11092386\"]}");
	add("{\"term\":\"benedick\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09869398\"]}");
	add("{\"term\":\"benedict\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"09869398\", \"10863454\", \"10863997\"]}");
	add("{\"term\":\"benedict arnold\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10843133\"]}");
	add("{\"term\":\"benedict de spinoza\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11331445\"]}");
	add("{\"term\":\"benedict xiv\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10863627\"]}");
	add("{\"term\":\"benedict xv\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10863827\"]}");
	add("{\"term\":\"benedictine\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07925052\", \"10132203\"]}");
	add("{\"term\":\"benedictine order\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08165608\"]}");
	add("{\"term\":\"benediction\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07204071\", \"01045725\"]}");
	add("{\"term\":\"benefaction\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01229168\", \"13291283\"]}");
	add("{\"term\":\"benefactive role\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06343538\"]}");
	add("{\"term\":\"benefactor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09631739\"]}");
	add("{\"term\":\"benefactress\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09632185\"]}");
	add("{\"term\":\"benefice\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13268986\"]}");
	add("{\"term\":\"beneficence\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04847768\", \"07561203\"]}");
	add("{\"term\":\"beneficiary\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06343538\", \"09869529\"]}");
	add("{\"term\":\"beneficiation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13537515\"]}");
	add("{\"term\":\"benefit\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"06905573\", \"05149888\", \"13317922\"]}");
	add("{\"term\":\"benefit album\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06604625\"]}");
	add("{\"term\":\"benefit concert\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06905696\"]}");
	add("{\"term\":\"benefit of clergy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01141811\"]}");
	add("{\"term\":\"benelux\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08322696\"]}");
	add("{\"term\":\"benet\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10864123\", \"10864263\"]}");
	add("{\"term\":\"benevolence\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"01229168\", \"04847516\", \"07561087\"]}");
	add("{\"term\":\"bengal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08728368\"]}");
	add("{\"term\":\"bengal bean\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12570913\"]}");
	add("{\"term\":\"bengal kino\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14925416\"]}");
	add("{\"term\":\"bengal light\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07279152\"]}");
	add("{\"term\":\"bengal rose\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12642021\"]}");
	add("{\"term\":\"bengal tiger\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02132489\"]}");
	add("{\"term\":\"bengali\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"06983620\", \"08500364\", \"09711826\"]}");
	add("{\"term\":\"benghal bean\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12570913\"]}");
	add("{\"term\":\"benghazi\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08980136\"]}");
	add("{\"term\":\"benign prostatic hyperplasia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14392322\"]}");
	add("{\"term\":\"benign tumor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14259708\"]}");
	add("{\"term\":\"benign tumour\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14259708\"]}");
	add("{\"term\":\"benignancy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04848212\"]}");
	add("{\"term\":\"benignity\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00035041\", \"04848212\"]}");
	add("{\"term\":\"benin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08777253\"]}");
	add("{\"term\":\"benin franc\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13699124\"]}");
	add("{\"term\":\"beninese\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09713665\"]}");
	add("{\"term\":\"benison\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07204222\"]}");
	add("{\"term\":\"benito mussolini\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11218243\"]}");
	add("{\"term\":\"benjamin\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10864646\", \"14922092\"]}");
	add("{\"term\":\"benjamin britten\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10884231\"]}");
	add("{\"term\":\"benjamin bush\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11726794\"]}");
	add("{\"term\":\"benjamin david goodman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11027328\"]}");
	add("{\"term\":\"benjamin disraeli\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10957356\"]}");
	add("{\"term\":\"benjamin franklin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10999075\"]}");
	add("{\"term\":\"benjamin franklin bridge\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02833478\"]}");
	add("{\"term\":\"benjamin harris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11050256\"]}");
	add("{\"term\":\"benjamin harrison\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11051664\"]}");
	add("{\"term\":\"benjamin henry latrobe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11138592\"]}");
	add("{\"term\":\"benjamin jonson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11111174\"]}");
	add("{\"term\":\"benjamin jowett\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11112928\"]}");
	add("{\"term\":\"benjamin kubelsky\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10865020\"]}");
	add("{\"term\":\"benjamin peirce\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11248476\"]}");
	add("{\"term\":\"benjamin ricketson tucker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11371524\"]}");
	add("{\"term\":\"benjamin rush\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11294259\"]}");
	add("{\"term\":\"benjamin shahn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11315023\"]}");
	add("{\"term\":\"benjamin spock\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11331618\"]}");
	add("{\"term\":\"benjamin thompson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11359664\"]}");
	add("{\"term\":\"benjamin west\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11402107\"]}");
	add("{\"term\":\"benne\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12895543\"]}");
	add("{\"term\":\"bennet\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12652574\", \"12653494\"]}");
	add("{\"term\":\"bennett\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10864844\"]}");
	add("{\"term\":\"bennettitaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11624844\"]}");
	add("{\"term\":\"bennettitales\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11624676\"]}");
	add("{\"term\":\"bennettitis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11625027\"]}");
	add("{\"term\":\"benni\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12895543\"]}");
	add("{\"term\":\"bennie\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02833780\"]}");
	add("{\"term\":\"bennington\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09171171\"]}");
	add("{\"term\":\"benniseed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07843386\"]}");
	add("{\"term\":\"benny\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10865020\", \"12895543\"]}");
	add("{\"term\":\"benny goodman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11027328\"]}");
	add("{\"term\":\"benny hill\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11069933\"]}");
	add("{\"term\":\"benoit mandelbrot\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11173446\"]}");
	add("{\"term\":\"bent\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"05632037\", \"08588062\", \"12127303\", \"06209437\"]}");
	add("{\"term\":\"bent grass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12127303\"]}");
	add("{\"term\":\"bent hang\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00437549\"]}");
	add("{\"term\":\"bentham\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10865199\"]}");
	add("{\"term\":\"benthic division\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08596045\"]}");
	add("{\"term\":\"benthonic zone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08596045\"]}");
	add("{\"term\":\"benthos\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00005787\", \"08596045\"]}");
	add("{\"term\":\"benton\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10865359\", \"10865522\"]}");
	add("{\"term\":\"bentonite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14837879\"]}");
	add("{\"term\":\"bentwood\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02833614\"]}");
	add("{\"term\":\"benvenuto cellini\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10908540\"]}");
	add("{\"term\":\"benweed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12032722\"]}");
	add("{\"term\":\"benzedrine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02833780\"]}");
	add("{\"term\":\"benzene\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14798860\"]}");
	add("{\"term\":\"benzene formula\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14799053\"]}");
	add("{\"term\":\"benzene nucleus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14799053\"]}");
	add("{\"term\":\"benzene ring\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14799053\"]}");
	add("{\"term\":\"benzine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14798860\"]}");
	add("{\"term\":\"benzoate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14799226\"]}");
	add("{\"term\":\"benzoate of soda\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14799332\"]}");
	add("{\"term\":\"benzocaine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02833905\"]}");
	add("{\"term\":\"benzodiazepine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02834036\"]}");
	add("{\"term\":\"benzofuran\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14922252\"]}");
	add("{\"term\":\"benzoic acid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14799480\"]}");
	add("{\"term\":\"benzoin\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11726589\", \"14922092\"]}");
	add("{\"term\":\"benzoin odoriferum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11726794\"]}");
	add("{\"term\":\"benzol\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14798860\"]}");
	add("{\"term\":\"benzoquinone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15025540\"]}");
	add("{\"term\":\"benzoyl group\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14646946\"]}");
	add("{\"term\":\"benzoyl peroxide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14799589\"]}");
	add("{\"term\":\"benzoyl radical\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14646946\"]}");
	add("{\"term\":\"benzyl\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14646801\"]}");
	add("{\"term\":\"benzyl group\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14646801\"]}");
	add("{\"term\":\"benzyl radical\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14646801\"]}");
	add("{\"term\":\"benzylpenicillin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03916842\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }