package org.swtk.commons.dict.wordnet.indexbyname.instance.s.o.m;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceSOM {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"som\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13724033\", \"13725610\"]}");
	add("{\"term\":\"soma\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"05224424\", \"09552205\", \"13258886\"]}");
	add("{\"term\":\"somaesthesia\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05667701\", \"05729127\"]}");
	add("{\"term\":\"somaesthesis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05667701\"]}");
	add("{\"term\":\"somali\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07003664\", \"09769211\"]}");
	add("{\"term\":\"somalia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09020930\"]}");
	add("{\"term\":\"somalian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09769211\"]}");
	add("{\"term\":\"soman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15080939\"]}");
	add("{\"term\":\"somataesthesis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05667701\"]}");
	add("{\"term\":\"somateria\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01855713\"]}");
	add("{\"term\":\"somatesthesia\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05667701\", \"05729127\"]}");
	add("{\"term\":\"somatosense\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05662718\"]}");
	add("{\"term\":\"somatotrophin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05419992\"]}");
	add("{\"term\":\"somatotropin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05419992\"]}");
	add("{\"term\":\"somatotype\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05006131\"]}");
	add("{\"term\":\"somberness\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04654835\", \"07548645\", \"14008947\"]}");
	add("{\"term\":\"sombreness\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04654835\", \"07548645\", \"14008947\"]}");
	add("{\"term\":\"sombrero\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04266740\", \"09010703\"]}");
	add("{\"term\":\"somebody\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00007846\"]}");
	add("{\"term\":\"someone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00007846\"]}");
	add("{\"term\":\"somersault\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00440424\"]}");
	add("{\"term\":\"somersaulting\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00440424\"]}");
	add("{\"term\":\"somerset\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00440424\", \"08903406\"]}");
	add("{\"term\":\"somesthesia\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05667701\", \"05729127\"]}");
	add("{\"term\":\"somesthesis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05667701\"]}");
	add("{\"term\":\"somewhere\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08506775\"]}");
	add("{\"term\":\"somite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02668442\"]}");
	add("{\"term\":\"somme\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01297864\", \"01298019\"]}");
	add("{\"term\":\"sommelier\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10643168\"]}");
	add("{\"term\":\"somnambulation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00285985\"]}");
	add("{\"term\":\"somnambulism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00285985\"]}");
	add("{\"term\":\"somnambulist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10630877\"]}");
	add("{\"term\":\"somniloquism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00286231\"]}");
	add("{\"term\":\"somniloquist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10643311\"]}");
	add("{\"term\":\"somniloquy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00286231\"]}");
	add("{\"term\":\"somnolence\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14053917\"]}");
	add("{\"term\":\"somrai\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06997970\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }