package org.swtk.commons.dict.wordnet.indexbyname.instance.p.a.l;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstancePAL {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"pal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09897417\"]}");
	add("{\"term\":\"palace\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"03883542\", \"03883908\", \"08069873\", \"03883763\"]}");
	add("{\"term\":\"paladin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09925991\"]}");
	add("{\"term\":\"palaeencephalon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05489781\"]}");
	add("{\"term\":\"palaemon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01989994\"]}");
	add("{\"term\":\"palaemonidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01989869\"]}");
	add("{\"term\":\"palaeoanthropology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06083739\"]}");
	add("{\"term\":\"palaeobiology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06088274\"]}");
	add("{\"term\":\"palaeobotany\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06083922\"]}");
	add("{\"term\":\"palaeoclimatology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06154777\"]}");
	add("{\"term\":\"palaeodendrology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06084278\"]}");
	add("{\"term\":\"palaeoecology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06092297\"]}");
	add("{\"term\":\"palaeoethnography\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06156211\"]}");
	add("{\"term\":\"palaeogeography\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06154897\"]}");
	add("{\"term\":\"palaeogeology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06127002\"]}");
	add("{\"term\":\"palaeolithic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15257202\"]}");
	add("{\"term\":\"palaeology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06155593\"]}");
	add("{\"term\":\"palaeontologist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10414485\"]}");
	add("{\"term\":\"palaeontology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06083438\"]}");
	add("{\"term\":\"palaeopathology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06155180\"]}");
	add("{\"term\":\"palaeornithology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06084662\"]}");
	add("{\"term\":\"palaeozoology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06084410\"]}");
	add("{\"term\":\"palaestra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03884208\"]}");
	add("{\"term\":\"palaetiology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06155348\"]}");
	add("{\"term\":\"palaic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06988978\"]}");
	add("{\"term\":\"palankeen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03883991\"]}");
	add("{\"term\":\"palanquin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03883991\"]}");
	add("{\"term\":\"palaquium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12795651\"]}");
	add("{\"term\":\"palas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12530848\"]}");
	add("{\"term\":\"palatability\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04801829\", \"05002389\"]}");
	add("{\"term\":\"palatableness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04801829\", \"05002389\"]}");
	add("{\"term\":\"palatal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07129243\"]}");
	add("{\"term\":\"palate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05317250\"]}");
	add("{\"term\":\"palatinate\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08570961\", \"08793272\"]}");
	add("{\"term\":\"palatine\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"05285651\", \"08815264\", \"10413840\", \"10414028\"]}");
	add("{\"term\":\"palatopharyngoplasty\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00690982\"]}");
	add("{\"term\":\"palau\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09000318\", \"09000531\"]}");
	add("{\"term\":\"palaver\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06621856\", \"06708607\"]}");
	add("{\"term\":\"pale\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03936190\"]}");
	add("{\"term\":\"paleacrita\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02289856\"]}");
	add("{\"term\":\"paleencephalon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05489781\"]}");
	add("{\"term\":\"paleness\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04982879\", \"04984514\", \"04984828\"]}");
	add("{\"term\":\"paleoanthropology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06083739\"]}");
	add("{\"term\":\"paleobiology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06088274\"]}");
	add("{\"term\":\"paleobotany\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06083922\"]}");
	add("{\"term\":\"paleocene\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15150952\"]}");
	add("{\"term\":\"paleocerebellum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05493971\"]}");
	add("{\"term\":\"paleoclimatology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06154777\"]}");
	add("{\"term\":\"paleocortex\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05489522\"]}");
	add("{\"term\":\"paleodendrology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06084278\"]}");
	add("{\"term\":\"paleoecology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06092297\"]}");
	add("{\"term\":\"paleoencephalon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05489781\"]}");
	add("{\"term\":\"paleoethnography\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06156211\"]}");
	add("{\"term\":\"paleogeography\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06154897\"]}");
	add("{\"term\":\"paleogeology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06127002\"]}");
	add("{\"term\":\"paleographer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10414372\"]}");
	add("{\"term\":\"paleographist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10414372\"]}");
	add("{\"term\":\"paleography\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06155037\"]}");
	add("{\"term\":\"paleolith\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03884115\"]}");
	add("{\"term\":\"paleolithic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15257202\"]}");
	add("{\"term\":\"paleology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06155593\"]}");
	add("{\"term\":\"paleomammalogy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06084566\"]}");
	add("{\"term\":\"paleontologist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10414485\"]}");
	add("{\"term\":\"paleontology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06083438\"]}");
	add("{\"term\":\"paleopathology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06155180\"]}");
	add("{\"term\":\"paleornithology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06084662\"]}");
	add("{\"term\":\"paleostriatum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05505951\"]}");
	add("{\"term\":\"paleozoic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15151883\"]}");
	add("{\"term\":\"paleozoology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06084410\"]}");
	add("{\"term\":\"palermo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08829325\"]}");
	add("{\"term\":\"palestine\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08816234\", \"08816623\"]}");
	add("{\"term\":\"palestinian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09732753\"]}");
	add("{\"term\":\"palestra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03884208\"]}");
	add("{\"term\":\"palestrina\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11241258\"]}");
	add("{\"term\":\"paletiology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06155348\"]}");
	add("{\"term\":\"palette\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"03885402\", \"03884371\", \"05135635\"]}");
	add("{\"term\":\"palfrey\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02380951\"]}");
	add("{\"term\":\"palgrave\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11241379\"]}");
	add("{\"term\":\"pali\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06985994\"]}");
	add("{\"term\":\"palilalia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14354542\"]}");
	add("{\"term\":\"palimony\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13304508\"]}");
	add("{\"term\":\"palimpsest\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06419157\"]}");
	add("{\"term\":\"palindrome\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06305609\"]}");
	add("{\"term\":\"paling\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03936551\"]}");
	add("{\"term\":\"palingenesis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13552855\"]}");
	add("{\"term\":\"palinuridae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01987057\"]}");
	add("{\"term\":\"palinurus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01987188\"]}");
	add("{\"term\":\"palisade\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03884660\"]}");
	add("{\"term\":\"paliurus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13164403\"]}");
	add("{\"term\":\"pall\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"03155743\", \"03884813\", \"07552647\"]}");
	add("{\"term\":\"palladio\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11241485\"]}");
	add("{\"term\":\"palladium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14672932\"]}");
	add("{\"term\":\"pallas\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09406891\", \"09580516\"]}");
	add("{\"term\":\"pallasite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09406999\"]}");
	add("{\"term\":\"pallbearer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10414772\"]}");
	add("{\"term\":\"pallet\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"03884371\", \"03885033\", \"03885153\", \"03885279\", \"05135635\"]}");
	add("{\"term\":\"pallette\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03885402\"]}");
	add("{\"term\":\"palliasse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03880766\"]}");
	add("{\"term\":\"palliation\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00355409\", \"00356373\"]}");
	add("{\"term\":\"palliative\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03885551\"]}");
	add("{\"term\":\"pallidity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04982879\"]}");
	add("{\"term\":\"pallidness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04984828\"]}");
	add("{\"term\":\"pallidum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05505951\"]}");
	add("{\"term\":\"pallium\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"03885729\", \"03885826\", \"05251388\", \"05494162\"]}");
	add("{\"term\":\"pallone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00484859\"]}");
	add("{\"term\":\"pallor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04984828\"]}");
	add("{\"term\":\"palm\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"06719615\", \"12602979\", \"13677693\", \"05573329\"]}");
	add("{\"term\":\"palmaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12602129\"]}");
	add("{\"term\":\"palmae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12602129\"]}");
	add("{\"term\":\"palmales\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12601978\"]}");
	add("{\"term\":\"palmature\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14354676\"]}");
	add("{\"term\":\"palmer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11241640\"]}");
	add("{\"term\":\"palmetto\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12604149\"]}");
	add("{\"term\":\"palmist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10414908\"]}");
	add("{\"term\":\"palmister\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10414908\"]}");
	add("{\"term\":\"palmistry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05785827\"]}");
	add("{\"term\":\"palmitin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14998051\"]}");
	add("{\"term\":\"palmyra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12606390\"]}");
	add("{\"term\":\"palometa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02636307\"]}");
	add("{\"term\":\"palomino\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02391780\"]}");
	add("{\"term\":\"palooka\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10686191\"]}");
	add("{\"term\":\"paloverde\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12514373\"]}");
	add("{\"term\":\"palpability\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04767279\"]}");
	add("{\"term\":\"palpation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00144705\"]}");
	add("{\"term\":\"palpebra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05321347\"]}");
	add("{\"term\":\"palpebration\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01267669\"]}");
	add("{\"term\":\"palpitation\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"14028057\", \"14358502\"]}");
	add("{\"term\":\"palsgrave\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10413840\"]}");
	add("{\"term\":\"palsy\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"14339897\", \"14581818\"]}");
	add("{\"term\":\"paltering\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00753487\"]}");
	add("{\"term\":\"paltriness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05147543\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }