package org.swtk.commons.dict.wordnet.indexbyname.instance.c.a.r;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceCAR {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"car\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"02937835\", \"02963788\", \"02963937\", \"02963378\", \"02961779\"]}");
	add("{\"term\":\"car battery\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02964661\"]}");
	add("{\"term\":\"car bomb\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02964980\"]}");
	add("{\"term\":\"car boot sale\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01120935\"]}");
	add("{\"term\":\"car care\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00268761\"]}");
	add("{\"term\":\"car carrier\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02965850\"]}");
	add("{\"term\":\"car company\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08018711\"]}");
	add("{\"term\":\"car dealer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08080486\"]}");
	add("{\"term\":\"car door\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02967273\"]}");
	add("{\"term\":\"car factory\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02764701\"]}");
	add("{\"term\":\"car horn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02764839\"]}");
	add("{\"term\":\"car insurance\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13366418\"]}");
	add("{\"term\":\"car loan\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13421197\"]}");
	add("{\"term\":\"car maker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08083599\"]}");
	add("{\"term\":\"car manufacturer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08083599\"]}");
	add("{\"term\":\"car mirror\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02969235\"]}");
	add("{\"term\":\"car park\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08633213\"]}");
	add("{\"term\":\"car part\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02765049\"]}");
	add("{\"term\":\"car pool\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08257405\"]}");
	add("{\"term\":\"car port\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02971533\"]}");
	add("{\"term\":\"car race\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07473683\"]}");
	add("{\"term\":\"car racing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00450502\"]}");
	add("{\"term\":\"car rental\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13269497\"]}");
	add("{\"term\":\"car seat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02974144\"]}");
	add("{\"term\":\"car sickness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14227295\"]}");
	add("{\"term\":\"car tire\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02974626\"]}");
	add("{\"term\":\"car traffic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08443068\"]}");
	add("{\"term\":\"car train\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02975038\"]}");
	add("{\"term\":\"car transporter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04481270\"]}");
	add("{\"term\":\"car wheel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02977462\"]}");
	add("{\"term\":\"car window\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02977678\"]}");
	add("{\"term\":\"carabao\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02411463\"]}");
	add("{\"term\":\"carabid beetle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02169803\"]}");
	add("{\"term\":\"carabidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02169638\"]}");
	add("{\"term\":\"carabineer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09913198\"]}");
	add("{\"term\":\"carabiner\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02964126\"]}");
	add("{\"term\":\"carabinier\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09913198\"]}");
	add("{\"term\":\"caracal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02130330\"]}");
	add("{\"term\":\"caracara\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01615269\"]}");
	add("{\"term\":\"caracas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09185069\"]}");
	add("{\"term\":\"carack\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02971669\"]}");
	add("{\"term\":\"caracolito\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12722884\"]}");
	add("{\"term\":\"caracul\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02416689\"]}");
	add("{\"term\":\"carafate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04356779\"]}");
	add("{\"term\":\"carafe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02964339\"]}");
	add("{\"term\":\"caragana\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12532361\"]}");
	add("{\"term\":\"caragana arborescens\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12532600\"]}");
	add("{\"term\":\"caragana sinica\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12532799\"]}");
	add("{\"term\":\"carageen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01417274\"]}");
	add("{\"term\":\"carambola\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07762527\", \"12725103\"]}");
	add("{\"term\":\"carambola tree\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12725103\"]}");
	add("{\"term\":\"caramel\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04981224\", \"07610751\", \"07617380\"]}");
	add("{\"term\":\"caramel apple\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07616267\"]}");
	add("{\"term\":\"caramel brown\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04981224\"]}");
	add("{\"term\":\"caramel bun\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07708968\"]}");
	add("{\"term\":\"caramelized sugar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07610751\"]}");
	add("{\"term\":\"carancha\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01615818\"]}");
	add("{\"term\":\"caranda\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12609541\"]}");
	add("{\"term\":\"caranda palm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12609541\"]}");
	add("{\"term\":\"caranday\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12609541\"]}");
	add("{\"term\":\"carangid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02578854\"]}");
	add("{\"term\":\"carangid fish\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02578854\"]}");
	add("{\"term\":\"carangidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02578397\"]}");
	add("{\"term\":\"caranx\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02579091\"]}");
	add("{\"term\":\"caranx bartholomaei\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02579672\"]}");
	add("{\"term\":\"caranx crysos\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02579795\"]}");
	add("{\"term\":\"caranx hippos\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02579537\"]}");
	add("{\"term\":\"carapace\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01906397\"]}");
	add("{\"term\":\"carapidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02561863\"]}");
	add("{\"term\":\"carassius\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01446039\"]}");
	add("{\"term\":\"carassius auratus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01446178\"]}");
	add("{\"term\":\"carassius carassius\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01446472\"]}");
	add("{\"term\":\"carassius vulgaris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01446472\"]}");
	add("{\"term\":\"carat\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13606330\", \"13745687\"]}");
	add("{\"term\":\"caravaggio\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10901841\"]}");
	add("{\"term\":\"caravan\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04527677\", \"08444586\"]}");
	add("{\"term\":\"caravan inn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02964471\"]}");
	add("{\"term\":\"caravanning\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01067985\"]}");
	add("{\"term\":\"caravansary\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02964471\"]}");
	add("{\"term\":\"caravanserai\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02964471\"]}");
	add("{\"term\":\"caraway\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07832702\", \"12955239\"]}");
	add("{\"term\":\"caraway seed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07843530\"]}");
	add("{\"term\":\"caraway seed bread\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07697100\"]}");
	add("{\"term\":\"carbamate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14816451\"]}");
	add("{\"term\":\"carbamic acid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14816559\"]}");
	add("{\"term\":\"carbamide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15110039\"]}");
	add("{\"term\":\"carbide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14816720\"]}");
	add("{\"term\":\"carbine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02964887\"]}");
	add("{\"term\":\"carbineer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09913198\"]}");
	add("{\"term\":\"carbo loading\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07578216\"]}");
	add("{\"term\":\"carbohydrate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14816873\"]}");
	add("{\"term\":\"carbohydrate loading\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07578216\"]}");
	add("{\"term\":\"carbolic acid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14820243\"]}");
	add("{\"term\":\"carboloy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14817393\"]}");
	add("{\"term\":\"carbomycin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02965150\"]}");
	add("{\"term\":\"carbon\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"02965287\", \"14821983\", \"14657384\"]}");
	add("{\"term\":\"carbon arc\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02965383\"]}");
	add("{\"term\":\"carbon arc lamp\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02965383\"]}");
	add("{\"term\":\"carbon atom\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14657959\"]}");
	add("{\"term\":\"carbon black\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14817703\"]}");
	add("{\"term\":\"carbon copy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02965287\"]}");
	add("{\"term\":\"carbon cycle\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13464293\", \"13464401\"]}");
	add("{\"term\":\"carbon dating\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00994818\"]}");
	add("{\"term\":\"carbon dichloride\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04423473\"]}");
	add("{\"term\":\"carbon dioxide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14821139\"]}");
	add("{\"term\":\"carbon dioxide acidosis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14043742\"]}");
	add("{\"term\":\"carbon disulfide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14821606\"]}");
	add("{\"term\":\"carbon monoxide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14821811\"]}");
	add("{\"term\":\"carbon monoxide gas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14821811\"]}");
	add("{\"term\":\"carbon monoxide poisoning\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14534003\"]}");
	add("{\"term\":\"carbon nanotube\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14646669\"]}");
	add("{\"term\":\"carbon paper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14821983\"]}");
	add("{\"term\":\"carbon process\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06693780\"]}");
	add("{\"term\":\"carbon steel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14827244\"]}");
	add("{\"term\":\"carbon tet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14822209\"]}");
	add("{\"term\":\"carbon tetrachloride\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14822209\"]}");
	add("{\"term\":\"carbon tetrahalide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14822501\"]}");
	add("{\"term\":\"carbonado\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07680213\", \"14817563\"]}");
	add("{\"term\":\"carbonara\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07847122\"]}");
	add("{\"term\":\"carbonate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14822620\"]}");
	add("{\"term\":\"carbonated water\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07952788\"]}");
	add("{\"term\":\"carbonation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13464171\"]}");
	add("{\"term\":\"carbondale\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09105689\"]}");
	add("{\"term\":\"carbonic acid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14823254\"]}");
	add("{\"term\":\"carbonic acid gas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14821139\"]}");
	add("{\"term\":\"carboniferous\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15152259\"]}");
	add("{\"term\":\"carboniferous period\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15152259\"]}");
	add("{\"term\":\"carbonisation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13464543\"]}");
	add("{\"term\":\"carbonization\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13464543\"]}");
	add("{\"term\":\"carbonnade flamande\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07879620\"]}");
	add("{\"term\":\"carbonyl\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14814696\"]}");
	add("{\"term\":\"carbonyl group\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14814863\"]}");
	add("{\"term\":\"carborundum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14823646\"]}");
	add("{\"term\":\"carboxyl\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14814966\"]}");
	add("{\"term\":\"carboxyl group\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14814966\"]}");
	add("{\"term\":\"carboxylic acid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14763539\"]}");
	add("{\"term\":\"carboxymethyl cellulose\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14818373\"]}");
	add("{\"term\":\"carboy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02965497\"]}");
	add("{\"term\":\"carbuncle\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"14207256\", \"14901637\"]}");
	add("{\"term\":\"carburetor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02965636\"]}");
	add("{\"term\":\"carburettor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02965636\"]}");
	add("{\"term\":\"carcajou\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02451814\"]}");
	add("{\"term\":\"carcase\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01761398\"]}");
	add("{\"term\":\"carcass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01761398\"]}");
	add("{\"term\":\"carcharhinidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01491180\"]}");
	add("{\"term\":\"carcharhinus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01491916\"]}");
	add("{\"term\":\"carcharhinus leucas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01492142\"]}");
	add("{\"term\":\"carcharhinus limbatus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01492561\"]}");
	add("{\"term\":\"carcharhinus obscurus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01493001\"]}");
	add("{\"term\":\"carcharhinus plumbeus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01492350\"]}");
	add("{\"term\":\"carcharias\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01489953\"]}");
	add("{\"term\":\"carcharias taurus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01490147\"]}");
	add("{\"term\":\"carchariidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01489718\"]}");
	add("{\"term\":\"carcharinus longimanus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01492753\"]}");
	add("{\"term\":\"carcharodon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01487358\"]}");
	add("{\"term\":\"carcharodon carcharias\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01487491\"]}");
	add("{\"term\":\"carcinogen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14817982\"]}");
	add("{\"term\":\"carcinoid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14260630\"]}");
	add("{\"term\":\"carcinoma\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14265819\"]}");
	add("{\"term\":\"carcinoma in situ\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14270517\"]}");
	add("{\"term\":\"carcinomatous myopathy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14102638\"]}");
	add("{\"term\":\"carcinosarcoma\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14260833\"]}");
	add("{\"term\":\"card\", \"synsetCount\":11, \"upperType\":\"NOUN\", \"ids\":[\"03037971\", \"06497998\", \"06504930\", \"06519932\", \"06645712\", \"06806283\", \"10782010\", \"14824204\", \"06639513\", \"06489042\", \"02965981\"]}");
	add("{\"term\":\"card catalog\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02966738\", \"06500310\"]}");
	add("{\"term\":\"card catalogue\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02966738\", \"06500310\"]}");
	add("{\"term\":\"card game\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00489236\"]}");
	add("{\"term\":\"card index\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02966738\"]}");
	add("{\"term\":\"card player\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09914106\"]}");
	add("{\"term\":\"card shark\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09914361\"]}");
	add("{\"term\":\"card sharp\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09914361\"]}");
	add("{\"term\":\"card sharper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09914361\"]}");
	add("{\"term\":\"card table\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02967527\", \"02967648\"]}");
	add("{\"term\":\"card trick\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00553256\"]}");
	add("{\"term\":\"cardamine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11901895\"]}");
	add("{\"term\":\"cardamine bulbifera\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11902706\"]}");
	add("{\"term\":\"cardamine bulbosa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11903290\"]}");
	add("{\"term\":\"cardamine diphylla\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11902895\"]}");
	add("{\"term\":\"cardamine douglasii\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11903441\"]}");
	add("{\"term\":\"cardamine pratensis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11902543\"]}");
	add("{\"term\":\"cardamine rotundifolia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11903105\"]}");
	add("{\"term\":\"cardamom\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07838299\", \"12378810\"]}");
	add("{\"term\":\"cardamon\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07838299\", \"12378810\"]}");
	add("{\"term\":\"cardamum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07838299\"]}");
	add("{\"term\":\"cardboard\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14823771\"]}");
	add("{\"term\":\"cardcase\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02966279\"]}");
	add("{\"term\":\"cardcastle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03550936\"]}");
	add("{\"term\":\"cardholder\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09913368\", \"09913492\"]}");
	add("{\"term\":\"cardhouse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03550936\"]}");
	add("{\"term\":\"cardia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05403572\"]}");
	add("{\"term\":\"cardiac arrest\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14048052\"]}");
	add("{\"term\":\"cardiac arrhythmia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14134156\"]}");
	add("{\"term\":\"cardiac cycle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07355904\"]}");
	add("{\"term\":\"cardiac glucoside\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15084506\"]}");
	add("{\"term\":\"cardiac glycoside\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15084506\"]}");
	add("{\"term\":\"cardiac insufficiency\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14137118\"]}");
	add("{\"term\":\"cardiac massage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00660592\"]}");
	add("{\"term\":\"cardiac monitor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02966374\"]}");
	add("{\"term\":\"cardiac murmur\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14358219\"]}");
	add("{\"term\":\"cardiac muscle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05397282\"]}");
	add("{\"term\":\"cardiac output\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15302912\"]}");
	add("{\"term\":\"cardiac pacemaker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05396803\"]}");
	add("{\"term\":\"cardiac plexus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05513880\"]}");
	add("{\"term\":\"cardiac resuscitation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00834287\"]}");
	add("{\"term\":\"cardiac rhythm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04775425\"]}");
	add("{\"term\":\"cardiac sphincter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05578763\"]}");
	add("{\"term\":\"cardiac tamponade\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14532180\"]}");
	add("{\"term\":\"cardiac valve\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05402441\"]}");
	add("{\"term\":\"cardiff\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08915613\"]}");
	add("{\"term\":\"cardigan\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02115838\", \"02966595\"]}");
	add("{\"term\":\"cardigan welsh corgi\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02115838\"]}");
	add("{\"term\":\"cardiidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01962309\"]}");
	add("{\"term\":\"cardinal\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"01544027\", \"04970626\", \"13618828\", \"09913595\"]}");
	add("{\"term\":\"cardinal bellarmine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10862326\"]}");
	add("{\"term\":\"cardinal compass point\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13853199\"]}");
	add("{\"term\":\"cardinal flower\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12189267\"]}");
	add("{\"term\":\"cardinal grosbeak\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01544027\"]}");
	add("{\"term\":\"cardinal newman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11224952\"]}");
	add("{\"term\":\"cardinal number\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13618828\"]}");
	add("{\"term\":\"cardinal richelieu\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11281473\"]}");
	add("{\"term\":\"cardinal tetra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02586776\"]}");
	add("{\"term\":\"cardinal vein\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05367376\"]}");
	add("{\"term\":\"cardinal virtue\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04854831\"]}");
	add("{\"term\":\"cardinalate\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00590985\", \"08102739\"]}");
	add("{\"term\":\"cardinalfish\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02574827\"]}");
	add("{\"term\":\"cardinalis cardinalis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01544027\"]}");
	add("{\"term\":\"cardinality\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13612789\"]}");
	add("{\"term\":\"cardinalship\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00590985\"]}");
	add("{\"term\":\"cardiogenic shock\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14090963\"]}");
	add("{\"term\":\"cardiogram\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07017173\"]}");
	add("{\"term\":\"cardiograph\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02784787\", \"02966939\"]}");
	add("{\"term\":\"cardiography\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00833753\"]}");
	add("{\"term\":\"cardioid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13932647\"]}");
	add("{\"term\":\"cardioid microphone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02967128\"]}");
	add("{\"term\":\"cardioid mike\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02967128\"]}");
	add("{\"term\":\"cardiologist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09913897\"]}");
	add("{\"term\":\"cardiology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06056806\"]}");
	add("{\"term\":\"cardiomegaly\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14358036\"]}");
	add("{\"term\":\"cardiomyopathy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14134448\"]}");
	add("{\"term\":\"cardiopathy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14126770\"]}");
	add("{\"term\":\"cardiopulmonary arrest\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14048052\"]}");
	add("{\"term\":\"cardiopulmonary exercise\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00436503\"]}");
	add("{\"term\":\"cardiopulmonary resuscitation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00834287\"]}");
	add("{\"term\":\"cardiospasm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00227578\"]}");
	add("{\"term\":\"cardiospermum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12763306\"]}");
	add("{\"term\":\"cardiospermum grandiflorum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12763638\"]}");
	add("{\"term\":\"cardiospermum halicacabum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12763769\"]}");
	add("{\"term\":\"cardiovascular disease\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14080853\"]}");
	add("{\"term\":\"cardiovascular system\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05519269\"]}");
	add("{\"term\":\"carditis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14362347\"]}");
	add("{\"term\":\"cardium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01962475\"]}");
	add("{\"term\":\"cardium edule\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01962818\"]}");
	add("{\"term\":\"cardizem\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03203321\"]}");
	add("{\"term\":\"cardoon\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07746009\", \"11980331\"]}");
	add("{\"term\":\"cardroom\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02967439\"]}");
	add("{\"term\":\"cards\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00489236\"]}");
	add("{\"term\":\"cardsharp\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09914361\"]}");
	add("{\"term\":\"cardsharper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09914361\"]}");
	add("{\"term\":\"carducci\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10902045\"]}");
	add("{\"term\":\"carduelinae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01533332\"]}");
	add("{\"term\":\"carduelis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01533487\"]}");
	add("{\"term\":\"carduelis cannabina\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01533985\"]}");
	add("{\"term\":\"carduelis carduelis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01533819\"]}");
	add("{\"term\":\"carduelis cucullata\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01534280\"]}");
	add("{\"term\":\"carduelis flammea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01534452\"]}");
	add("{\"term\":\"carduelis hornemanni\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01534612\"]}");
	add("{\"term\":\"carduelis spinus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01534153\"]}");
	add("{\"term\":\"cardura\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03234359\"]}");
	add("{\"term\":\"carduus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11965038\"]}");
	add("{\"term\":\"carduus crispus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11965220\"]}");
	add("{\"term\":\"carduus nutans\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11965423\"]}");
	add("{\"term\":\"care\", \"synsetCount\":6, \"upperType\":\"NOUN\", \"ids\":[\"00268366\", \"00831039\", \"07520286\", \"07539768\", \"05623652\", \"00656128\"]}");
	add("{\"term\":\"care delivery\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01062025\"]}");
	add("{\"term\":\"careen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00348834\"]}");
	add("{\"term\":\"career\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00283457\", \"00584283\"]}");
	add("{\"term\":\"career counseling\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06663792\"]}");
	add("{\"term\":\"career girl\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09914590\"]}");
	add("{\"term\":\"career man\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09914932\"]}");
	add("{\"term\":\"careerism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00414099\"]}");
	add("{\"term\":\"careerist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09914674\"]}");
	add("{\"term\":\"carefreeness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04679567\", \"07546254\"]}");
	add("{\"term\":\"carefulness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04670851\", \"04671415\"]}");
	add("{\"term\":\"caregiver\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09915013\", \"10184702\"]}");
	add("{\"term\":\"carelessness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00740568\", \"04672321\"]}");
	add("{\"term\":\"carelian\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06970803\", \"09726142\"]}");
	add("{\"term\":\"caress\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00145598\"]}");
	add("{\"term\":\"caressing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00855630\"]}");
	add("{\"term\":\"caret\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06831461\"]}");
	add("{\"term\":\"caretaker\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09915354\", \"09915153\"]}");
	add("{\"term\":\"caretta\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01666580\"]}");
	add("{\"term\":\"caretta caretta\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01666706\"]}");
	add("{\"term\":\"carew\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10902188\"]}");
	add("{\"term\":\"carex\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12172331\"]}");
	add("{\"term\":\"carex arenaria\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12172548\"]}");
	add("{\"term\":\"carex pseudocyperus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12172768\"]}");
	add("{\"term\":\"carfare\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13329454\"]}");
	add("{\"term\":\"carful\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13788306\"]}");
	add("{\"term\":\"cargo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02967841\"]}");
	add("{\"term\":\"cargo area\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02968086\"]}");
	add("{\"term\":\"cargo container\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02968295\"]}");
	add("{\"term\":\"cargo cult\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06235488\", \"08168750\"]}");
	add("{\"term\":\"cargo deck\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02968086\"]}");
	add("{\"term\":\"cargo door\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02968386\"]}");
	add("{\"term\":\"cargo hatch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02968476\"]}");
	add("{\"term\":\"cargo helicopter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02968574\"]}");
	add("{\"term\":\"cargo hold\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02968086\"]}");
	add("{\"term\":\"cargo liner\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02968668\"]}");
	add("{\"term\":\"cargo ship\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02968752\"]}");
	add("{\"term\":\"cargo ships\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04203545\"]}");
	add("{\"term\":\"cargo vessel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02968752\"]}");
	add("{\"term\":\"carhop\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09915536\"]}");
	add("{\"term\":\"cariama\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02016715\"]}");
	add("{\"term\":\"cariama cristata\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02016891\"]}");
	add("{\"term\":\"cariamidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02016543\"]}");
	add("{\"term\":\"carib\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06930702\", \"09746153\"]}");
	add("{\"term\":\"carib indian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09746153\"]}");
	add("{\"term\":\"carib wood\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12589542\"]}");
	add("{\"term\":\"caribbean\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08726871\", \"09258801\"]}");
	add("{\"term\":\"caribbean island\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08764775\"]}");
	add("{\"term\":\"caribbean language\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06930702\"]}");
	add("{\"term\":\"caribbean sea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09258801\"]}");
	add("{\"term\":\"caribe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02587080\"]}");
	add("{\"term\":\"caribees\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08766113\"]}");
	add("{\"term\":\"caribou\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02436556\"]}");
	add("{\"term\":\"carica\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12393449\"]}");
	add("{\"term\":\"carica papaya\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12393617\"]}");
	add("{\"term\":\"caricaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12393225\"]}");
	add("{\"term\":\"caricature\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06792908\"]}");
	add("{\"term\":\"caricature plant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12833561\"]}");
	add("{\"term\":\"caricaturist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09915622\"]}");
	add("{\"term\":\"caries\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13465686\"]}");
	add("{\"term\":\"carillon\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00545478\", \"02968981\"]}");
	add("{\"term\":\"carillon playing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00545478\"]}");
	add("{\"term\":\"carillonneur\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09915763\"]}");
	add("{\"term\":\"carina\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05234539\", \"09258984\"]}");
	add("{\"term\":\"carina fornicis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05234768\"]}");
	add("{\"term\":\"carinate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01520607\"]}");
	add("{\"term\":\"carinate bird\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01520607\"]}");
	add("{\"term\":\"caring\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07561495\"]}");
	add("{\"term\":\"carioca\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"00536492\", \"07069243\", \"09714415\"]}");
	add("{\"term\":\"carissa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11792008\"]}");
	add("{\"term\":\"carissa bispinosa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11792215\"]}");
	add("{\"term\":\"carissa grandiflora\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11792393\"]}");
	add("{\"term\":\"carissa macrocarpa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11792393\"]}");
	add("{\"term\":\"carissa plum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07762886\"]}");
	add("{\"term\":\"carjacking\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00228351\"]}");
	add("{\"term\":\"carl anderson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10836848\"]}");
	add("{\"term\":\"carl august nielsen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11226996\"]}");
	add("{\"term\":\"carl clinton van doren\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11379692\"]}");
	add("{\"term\":\"carl david anderson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10836848\"]}");
	add("{\"term\":\"carl gustaf mossander\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11213240\"]}");
	add("{\"term\":\"carl gustav jung\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11114601\"]}");
	add("{\"term\":\"carl jung\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11114601\"]}");
	add("{\"term\":\"carl lewis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11151125\"]}");
	add("{\"term\":\"carl maria von weber\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11398457\"]}");
	add("{\"term\":\"carl nielsen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11226996\"]}");
	add("{\"term\":\"carl orff\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11236376\"]}");
	add("{\"term\":\"carl rogers\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11288513\"]}");
	add("{\"term\":\"carl sandburg\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11300203\"]}");
	add("{\"term\":\"carl van doren\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11379692\"]}");
	add("{\"term\":\"carl von linne\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11153541\"]}");
	add("{\"term\":\"carl xvi gustaf\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10902340\"]}");
	add("{\"term\":\"carl xvi gustav\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10902340\"]}");
	add("{\"term\":\"carl yastrzemski\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11422337\"]}");
	add("{\"term\":\"carlina\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11965697\"]}");
	add("{\"term\":\"carlina acaulis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11965983\"]}");
	add("{\"term\":\"carlina vulgaris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11966252\"]}");
	add("{\"term\":\"carline thistle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11965836\"]}");
	add("{\"term\":\"carling float\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03669107\"]}");
	add("{\"term\":\"carlo goldoni\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11025316\"]}");
	add("{\"term\":\"carload\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13797723\", \"07992516\"]}");
	add("{\"term\":\"carlos\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11221376\"]}");
	add("{\"term\":\"carlos chavez\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10914117\"]}");
	add("{\"term\":\"carlos fuentes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11004872\"]}");
	add("{\"term\":\"carlos the jackal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11221376\"]}");
	add("{\"term\":\"carlovingian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09915972\"]}");
	add("{\"term\":\"carlovingian dynasty\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08171262\"]}");
	add("{\"term\":\"carlsbad\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09138138\"]}");
	add("{\"term\":\"carlsbad caverns\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09259157\"]}");
	add("{\"term\":\"carlsbad caverns national park\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08621260\"]}");
	add("{\"term\":\"carlyle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10902458\"]}");
	add("{\"term\":\"carmaker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08083599\"]}");
	add("{\"term\":\"carmelite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10797816\"]}");
	add("{\"term\":\"carmelite order\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08165834\"]}");
	add("{\"term\":\"carmichael\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10902598\"]}");
	add("{\"term\":\"carminative\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02969069\"]}");
	add("{\"term\":\"carmine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04970626\"]}");
	add("{\"term\":\"carnage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00224850\"]}");
	add("{\"term\":\"carnal abuse\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00848591\", \"00848797\"]}");
	add("{\"term\":\"carnal knowledge\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00847184\"]}");
	add("{\"term\":\"carnality\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07505354\"]}");
	add("{\"term\":\"carnallite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14693574\"]}");
	add("{\"term\":\"carnassial tooth\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05291148\"]}");
	add("{\"term\":\"carnation\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04978478\", \"11828937\"]}");
	add("{\"term\":\"carnation family\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11825073\"]}");
	add("{\"term\":\"carnauba\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12609081\", \"12609345\"]}");
	add("{\"term\":\"carnauba palm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12609081\"]}");
	add("{\"term\":\"carnauba wax\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12609345\"]}");
	add("{\"term\":\"carnegie\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10902740\", \"10902954\"]}");
	add("{\"term\":\"carnegie mellon university\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02969388\"]}");
	add("{\"term\":\"carnegiea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11864672\"]}");
	add("{\"term\":\"carnegiea gigantea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11864840\"]}");
	add("{\"term\":\"carnelian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14825764\"]}");
	add("{\"term\":\"carniolan bee\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02211631\"]}");
	add("{\"term\":\"carnival\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"00520389\", \"00553716\", \"00512566\"]}");
	add("{\"term\":\"carnivora\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02077567\"]}");
	add("{\"term\":\"carnivore\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01327072\", \"02077948\"]}");
	add("{\"term\":\"carnivorous bat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02143958\"]}");
	add("{\"term\":\"carnivorous plant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12799365\"]}");
	add("{\"term\":\"carnosaur\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01716149\"]}");
	add("{\"term\":\"carnosaura\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01715951\"]}");
	add("{\"term\":\"carnot\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10903132\"]}");
	add("{\"term\":\"carnot cycle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07356265\"]}");
	add("{\"term\":\"carnotite\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14693838\"]}");
	add("{\"term\":\"carob\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"07613906\", \"12513713\", \"12513931\"]}");
	add("{\"term\":\"carob bar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07614100\"]}");
	add("{\"term\":\"carob bean\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12513931\"]}");
	add("{\"term\":\"carob bean tree\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12513713\"]}");
	add("{\"term\":\"carob powder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07613906\"]}");
	add("{\"term\":\"carob tree\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12513713\"]}");
	add("{\"term\":\"caroche\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02969520\"]}");
	add("{\"term\":\"carol\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00547650\", \"07049493\"]}");
	add("{\"term\":\"caroler\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09915853\"]}");
	add("{\"term\":\"carolina\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09075291\"]}");
	add("{\"term\":\"carolina allspice\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11721535\"]}");
	add("{\"term\":\"carolina buckthorn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13162749\"]}");
	add("{\"term\":\"carolina chickadee\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01595181\"]}");
	add("{\"term\":\"carolina hemlock\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11648165\"]}");
	add("{\"term\":\"carolina jasmine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12506486\"]}");
	add("{\"term\":\"carolina lupine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12594152\"]}");
	add("{\"term\":\"carolina moonseed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11734232\"]}");
	add("{\"term\":\"carolina parakeet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01824195\"]}");
	add("{\"term\":\"carolina pond fern\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12980298\"]}");
	add("{\"term\":\"carolina spring beauty\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11879744\"]}");
	add("{\"term\":\"carolina wren\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01588661\"]}");
	add("{\"term\":\"carolinas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09075291\"]}");
	add("{\"term\":\"caroline islands\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08857708\"]}");
	add("{\"term\":\"caroling\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00547898\"]}");
	add("{\"term\":\"carolingian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09915972\"]}");
	add("{\"term\":\"carolingian dynasty\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08171262\"]}");
	add("{\"term\":\"carolinian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09761053\"]}");
	add("{\"term\":\"caroller\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09915853\"]}");
	add("{\"term\":\"carolus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10911733\"]}");
	add("{\"term\":\"carolus linnaeus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11153541\"]}");
	add("{\"term\":\"carom\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00501460\", \"07424075\"]}");
	add("{\"term\":\"carotene\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"14745397\", \"15115102\"]}");
	add("{\"term\":\"carotenemia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14590187\"]}");
	add("{\"term\":\"carotenoid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14745123\"]}");
	add("{\"term\":\"carothers\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10903285\"]}");
	add("{\"term\":\"carotid artery\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05346905\"]}");
	add("{\"term\":\"carotid body\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05347669\"]}");
	add("{\"term\":\"carotid plexus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05514020\"]}");
	add("{\"term\":\"carotin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15115102\"]}");
	add("{\"term\":\"carousal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00512052\"]}");
	add("{\"term\":\"carouse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00512052\"]}");
	add("{\"term\":\"carousel\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02969645\", \"02969824\"]}");
	add("{\"term\":\"carouser\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10788989\"]}");
	add("{\"term\":\"carp\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01442155\", \"07795099\"]}");
	add("{\"term\":\"carpal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05279313\"]}");
	add("{\"term\":\"carpal bone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05279313\"]}");
	add("{\"term\":\"carpal tunnel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05279609\"]}");
	add("{\"term\":\"carpal tunnel syndrome\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14081051\"]}");
	add("{\"term\":\"carpathian mountains\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09259329\"]}");
	add("{\"term\":\"carpathians\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09259329\"]}");
	add("{\"term\":\"carpel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11698194\"]}");
	add("{\"term\":\"carpentaria\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09320826\"]}");
	add("{\"term\":\"carpenter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09916137\"]}");
	add("{\"term\":\"carpenter ant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02223456\"]}");
	add("{\"term\":\"carpenter bee\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02212006\"]}");
	add("{\"term\":\"carpenteria\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12810314\"]}");
	add("{\"term\":\"carpenteria californica\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12810314\"]}");
	add("{\"term\":\"carpentry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00608890\"]}");
	add("{\"term\":\"carper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09916278\"]}");
	add("{\"term\":\"carpet\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09259672\", \"04125115\"]}");
	add("{\"term\":\"carpet beater\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02970859\"]}");
	add("{\"term\":\"carpet beetle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02173052\"]}");
	add("{\"term\":\"carpet bombing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00981079\"]}");
	add("{\"term\":\"carpet bug\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02173052\"]}");
	add("{\"term\":\"carpet grass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12161028\"]}");
	add("{\"term\":\"carpet knight\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09916622\"]}");
	add("{\"term\":\"carpet loom\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02970992\"]}");
	add("{\"term\":\"carpet moth\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02295344\"]}");
	add("{\"term\":\"carpet pad\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02971078\"]}");
	add("{\"term\":\"carpet shark\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01489181\"]}");
	add("{\"term\":\"carpet slipper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04248522\"]}");
	add("{\"term\":\"carpet snake\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01746577\"]}");
	add("{\"term\":\"carpet sweeper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02971234\"]}");
	add("{\"term\":\"carpet tack\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02971443\"]}");
	add("{\"term\":\"carpetbag\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02970746\"]}");
	add("{\"term\":\"carpetbagger\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09916425\"]}");
	add("{\"term\":\"carpeting\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04125115\"]}");
	add("{\"term\":\"carpetweed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11842003\"]}");
	add("{\"term\":\"carpetweed family\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11839414\"]}");
	add("{\"term\":\"carphophis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01731086\"]}");
	add("{\"term\":\"carphophis amoenus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01731213\"]}");
	add("{\"term\":\"carpinaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12306889\"]}");
	add("{\"term\":\"carping\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06723969\"]}");
	add("{\"term\":\"carpinus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12307098\"]}");
	add("{\"term\":\"carpinus betulus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12307505\"]}");
	add("{\"term\":\"carpinus caroliniana\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12307712\"]}");
	add("{\"term\":\"carpobrotus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11839823\"]}");
	add("{\"term\":\"carpobrotus edulis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11839978\"]}");
	add("{\"term\":\"carpocapsa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02287704\"]}");
	add("{\"term\":\"carpocapsa pomonella\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02287831\"]}");
	add("{\"term\":\"carpodacus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01535305\"]}");
	add("{\"term\":\"carpodacus mexicanus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01535470\"]}");
	add("{\"term\":\"carpodacus purpureus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01535641\"]}");
	add("{\"term\":\"carpophore\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11698353\"]}");
	add("{\"term\":\"carport\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02971533\"]}");
	add("{\"term\":\"carpospore\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11569179\"]}");
	add("{\"term\":\"carpus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05592578\"]}");
	add("{\"term\":\"carrack\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02971669\"]}");
	add("{\"term\":\"carrageen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01417274\"]}");
	add("{\"term\":\"carrageenan\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14825881\"]}");
	add("{\"term\":\"carrageenin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14825881\"]}");
	add("{\"term\":\"carragheen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01417274\"]}");
	add("{\"term\":\"carrefour\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03586294\"]}");
	add("{\"term\":\"carrel\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02971792\", \"10903440\"]}");
	add("{\"term\":\"carrell\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02971792\"]}");
	add("{\"term\":\"carrere\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10903623\"]}");
	add("{\"term\":\"carriage\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"02769539\", \"02972469\", \"05009987\", \"02971932\", \"03901563\"]}");
	add("{\"term\":\"carriage bolt\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02972622\"]}");
	add("{\"term\":\"carriage dog\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02112993\"]}");
	add("{\"term\":\"carriage house\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03059842\"]}");
	add("{\"term\":\"carriage return\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13464710\"]}");
	add("{\"term\":\"carriage trade\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01108620\"]}");
	add("{\"term\":\"carriage wrench\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02972986\"]}");
	add("{\"term\":\"carriageway\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02972782\"]}");
	add("{\"term\":\"carrick bend\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02973093\"]}");
	add("{\"term\":\"carrick bitt\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02973213\"]}");
	add("{\"term\":\"carrier\", \"synsetCount\":11, \"upperType\":\"NOUN\", \"ids\":[\"01316636\", \"02973345\", \"09916802\", \"09917055\", \"10302734\", \"11521648\", \"08074469\", \"14751332\", \"02690031\", \"02973559\", \"09917148\"]}");
	add("{\"term\":\"carrier bag\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04129919\"]}");
	add("{\"term\":\"carrier electrophoresis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13553262\"]}");
	add("{\"term\":\"carrier pigeon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01817677\"]}");
	add("{\"term\":\"carrier wave\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11521648\"]}");
	add("{\"term\":\"carrion\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01761536\"]}");
	add("{\"term\":\"carrion crow\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01623055\"]}");
	add("{\"term\":\"carrion flower\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13259273\"]}");
	add("{\"term\":\"carrion fungus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13061063\"]}");
	add("{\"term\":\"carrizo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12151454\"]}");
	add("{\"term\":\"carroll\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10903813\"]}");
	add("{\"term\":\"carron oil\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02973770\"]}");
	add("{\"term\":\"carrot\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"01222212\", \"07746183\", \"12958148\", \"12958438\"]}");
	add("{\"term\":\"carrot family\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12950804\"]}");
	add("{\"term\":\"carrot juice\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07941848\"]}");
	add("{\"term\":\"carrot pudding\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07633448\"]}");
	add("{\"term\":\"carrot stick\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07746296\"]}");
	add("{\"term\":\"carrottop\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10533416\"]}");
	add("{\"term\":\"carrousel\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02969645\", \"02969824\"]}");
	add("{\"term\":\"carry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00319561\"]}");
	add("{\"term\":\"carry amelia moore nation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11221051\"]}");
	add("{\"term\":\"carry nation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11221051\"]}");
	add("{\"term\":\"carryall\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02973867\"]}");
	add("{\"term\":\"carrycot\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02973993\"]}");
	add("{\"term\":\"carrying charge\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13327212\", \"13328392\"]}");
	add("{\"term\":\"carrying cost\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13327212\"]}");
	add("{\"term\":\"carrying into action\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00098324\"]}");
	add("{\"term\":\"carrying out\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00098324\", \"01129700\"]}");
	add("{\"term\":\"carson\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10904121\", \"10904349\"]}");
	add("{\"term\":\"carson city\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09133423\"]}");
	add("{\"term\":\"carson mccullers\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11188829\"]}");
	add("{\"term\":\"carson smith mccullers\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11188829\"]}");
	add("{\"term\":\"cart\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03489166\", \"02974308\"]}");
	add("{\"term\":\"cart horse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02389505\"]}");
	add("{\"term\":\"cart track\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04470745\"]}");
	add("{\"term\":\"cartage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01108023\"]}");
	add("{\"term\":\"cartagena\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08751248\", \"09047954\"]}");
	add("{\"term\":\"cartagena bark\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12684766\"]}");
	add("{\"term\":\"carte\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06504930\"]}");
	add("{\"term\":\"carte blanche\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05204969\"]}");
	add("{\"term\":\"carte du jour\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06504930\"]}");
	add("{\"term\":\"cartel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08253542\"]}");
	add("{\"term\":\"carter\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"09917366\", \"10904583\", \"10904758\"]}");
	add("{\"term\":\"carter administration\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08182982\"]}");
	add("{\"term\":\"cartesian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09917472\"]}");
	add("{\"term\":\"cartesian coordinate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06020441\"]}");
	add("{\"term\":\"cartesian coordinate system\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05736216\"]}");
	add("{\"term\":\"cartesian plane\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13883664\"]}");
	add("{\"term\":\"cartesian product\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08015510\"]}");
	add("{\"term\":\"carthage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08939722\"]}");
	add("{\"term\":\"carthaginian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09716466\"]}");
	add("{\"term\":\"carthamus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11966399\"]}");
	add("{\"term\":\"carthamus tinctorius\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11966520\"]}");
	add("{\"term\":\"carthorse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02389505\"]}");
	add("{\"term\":\"carthusian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09917559\"]}");
	add("{\"term\":\"carthusian order\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08166011\"]}");
	add("{\"term\":\"cartier\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10904928\"]}");
	add("{\"term\":\"cartilage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05295590\"]}");
	add("{\"term\":\"cartilage bone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05281054\"]}");
	add("{\"term\":\"cartilaginification\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14207408\"]}");
	add("{\"term\":\"cartilaginous fish\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01483157\"]}");
	add("{\"term\":\"cartilaginous structure\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05538794\"]}");
	add("{\"term\":\"cartilaginous tube\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05539012\"]}");
	add("{\"term\":\"carting\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01108023\"]}");
	add("{\"term\":\"cartload\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13788392\"]}");
	add("{\"term\":\"cartographer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09917667\"]}");
	add("{\"term\":\"cartography\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00926393\"]}");
	add("{\"term\":\"carton\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02974815\", \"13788477\"]}");
	add("{\"term\":\"cartonful\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13788477\"]}");
	add("{\"term\":\"cartoon\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06628817\", \"06793517\"]}");
	add("{\"term\":\"cartoon strip\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07016468\"]}");
	add("{\"term\":\"cartoonist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09917798\"]}");
	add("{\"term\":\"cartouch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02974932\"]}");
	add("{\"term\":\"cartouche\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02974932\"]}");
	add("{\"term\":\"cartridge\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"02975399\", \"02975641\", \"03709915\", \"02975150\"]}");
	add("{\"term\":\"cartridge belt\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02975856\"]}");
	add("{\"term\":\"cartridge brass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14818704\"]}");
	add("{\"term\":\"cartridge clip\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02976476\"]}");
	add("{\"term\":\"cartridge ejector\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02975992\"]}");
	add("{\"term\":\"cartridge extractor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02976173\"]}");
	add("{\"term\":\"cartridge font\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06839457\"]}");
	add("{\"term\":\"cartridge fuse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02976393\"]}");
	add("{\"term\":\"cartridge holder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02976476\"]}");
	add("{\"term\":\"cartridge paper\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"14824003\", \"14824097\"]}");
	add("{\"term\":\"cartridge remover\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02976173\"]}");
	add("{\"term\":\"cartroad\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04470745\"]}");
	add("{\"term\":\"cartwheel\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"13413435\", \"00435597\", \"02976695\"]}");
	add("{\"term\":\"cartwright\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09918144\", \"10905104\"]}");
	add("{\"term\":\"carum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12955128\"]}");
	add("{\"term\":\"carum carvi\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12955239\"]}");
	add("{\"term\":\"caruncle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05478833\"]}");
	add("{\"term\":\"caruncula\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05478833\"]}");
	add("{\"term\":\"caruso\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10905239\"]}");
	add("{\"term\":\"carvedilol\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02976854\"]}");
	add("{\"term\":\"carver\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"10005000\", \"10585500\", \"10809603\", \"10905355\"]}");
	add("{\"term\":\"carving\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"00939472\", \"00944050\", \"02977017\"]}");
	add("{\"term\":\"carving fork\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02977264\"]}");
	add("{\"term\":\"carving knife\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02977363\"]}");
	add("{\"term\":\"cary grant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11031394\"]}");
	add("{\"term\":\"carya\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12340204\"]}");
	add("{\"term\":\"carya aquatica\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12340931\"]}");
	add("{\"term\":\"carya cordiformis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12341323\"]}");
	add("{\"term\":\"carya glabra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12341144\"]}");
	add("{\"term\":\"carya illinoensis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12341594\"]}");
	add("{\"term\":\"carya illinoinsis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12341594\"]}");
	add("{\"term\":\"carya laciniosa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12341912\"]}");
	add("{\"term\":\"carya myristicaeformis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12342186\"]}");
	add("{\"term\":\"carya myristiciformis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12342186\"]}");
	add("{\"term\":\"carya ovata\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12342390\"]}");
	add("{\"term\":\"carya tomentosa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12342616\"]}");
	add("{\"term\":\"caryatid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02977807\"]}");
	add("{\"term\":\"caryocar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12394043\"]}");
	add("{\"term\":\"caryocar nuciferum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12394256\"]}");
	add("{\"term\":\"caryocaraceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12393878\"]}");
	add("{\"term\":\"caryophyllaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11825073\"]}");
	add("{\"term\":\"caryophyllaceous plant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11825724\"]}");
	add("{\"term\":\"caryophyllales\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11824551\"]}");
	add("{\"term\":\"caryophyllidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11823944\"]}");
	add("{\"term\":\"caryophylloid dicot family\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11585491\"]}");
	add("{\"term\":\"caryophylloid dicot genus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11594111\"]}");
	add("{\"term\":\"caryopsis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12177336\"]}");
	add("{\"term\":\"caryota\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12607628\"]}");
	add("{\"term\":\"caryota urens\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12607893\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }