package org.swtk.commons.dict.wordnet.indexbyname.instance.s.o.r;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceSOR {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"sorb\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07786156\"]}");
	add("{\"term\":\"sorb apple\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07786156\", \"12679607\"]}");
	add("{\"term\":\"sorb apple tree\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12679607\"]}");
	add("{\"term\":\"sorbate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14621136\"]}");
	add("{\"term\":\"sorbent\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14621338\"]}");
	add("{\"term\":\"sorbent material\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14621338\"]}");
	add("{\"term\":\"sorbet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07629957\"]}");
	add("{\"term\":\"sorbian\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06958106\", \"09770734\"]}");
	add("{\"term\":\"sorbic acid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14764157\"]}");
	add("{\"term\":\"sorbonne\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03896410\"]}");
	add("{\"term\":\"sorbus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12678701\"]}");
	add("{\"term\":\"sorbus americana\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12679364\"]}");
	add("{\"term\":\"sorbus aucuparia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12679069\"]}");
	add("{\"term\":\"sorbus domestica\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12679607\"]}");
	add("{\"term\":\"sorbus sitchensis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12679476\"]}");
	add("{\"term\":\"sorbus torminalis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12679825\"]}");
	add("{\"term\":\"sorcerer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10645222\"]}");
	add("{\"term\":\"sorceress\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10645902\"]}");
	add("{\"term\":\"sorcery\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05987679\"]}");
	add("{\"term\":\"sordidness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04815223\", \"14522695\"]}");
	add("{\"term\":\"sordino\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04271160\"]}");
	add("{\"term\":\"sore\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14206547\"]}");
	add("{\"term\":\"sore throat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14196966\"]}");
	add("{\"term\":\"sorehead\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10645992\"]}");
	add("{\"term\":\"soren aabye kierkegaard\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11124666\"]}");
	add("{\"term\":\"soren kierkegaard\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11124666\"]}");
	add("{\"term\":\"soren peter lauritz sorensen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11328734\"]}");
	add("{\"term\":\"soreness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07511113\", \"14356022\"]}");
	add("{\"term\":\"sorensen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11328734\"]}");
	add("{\"term\":\"sorex\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01894506\"]}");
	add("{\"term\":\"sorex araneus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01894671\"]}");
	add("{\"term\":\"sorex cinereus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01894786\"]}");
	add("{\"term\":\"sorex palustris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01895385\"]}");
	add("{\"term\":\"sorgho\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12159274\"]}");
	add("{\"term\":\"sorghum\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"07876079\", \"12157461\", \"12157637\"]}");
	add("{\"term\":\"sorghum bicolor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12157854\"]}");
	add("{\"term\":\"sorghum halepense\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12159422\"]}");
	add("{\"term\":\"sorghum molasses\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07876079\"]}");
	add("{\"term\":\"sorghum vulgare caudatum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12158471\"]}");
	add("{\"term\":\"sorghum vulgare rosburghii\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12159095\"]}");
	add("{\"term\":\"sorghum vulgare technicum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12159713\"]}");
	add("{\"term\":\"sorgo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12159274\"]}");
	add("{\"term\":\"soricidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01894079\"]}");
	add("{\"term\":\"sorority\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08247398\"]}");
	add("{\"term\":\"sorption\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13579693\"]}");
	add("{\"term\":\"sorrel\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"02391678\", \"07752347\", \"12200149\", \"12624720\", \"12723708\"]}");
	add("{\"term\":\"sorrel tree\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12199297\", \"12262926\"]}");
	add("{\"term\":\"sorriness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05147543\"]}");
	add("{\"term\":\"sorrow\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"14012536\", \"05842007\", \"07551058\", \"07549818\"]}");
	add("{\"term\":\"sorrower\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10354959\"]}");
	add("{\"term\":\"sorrowfulness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07550597\", \"14012536\"]}");
	add("{\"term\":\"sort\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"13579899\", \"10646084\", \"04753502\", \"05847533\"]}");
	add("{\"term\":\"sort program\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06592279\"]}");
	add("{\"term\":\"sorter\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04268226\", \"10646229\"]}");
	add("{\"term\":\"sortie\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00305677\", \"00973413\"]}");
	add("{\"term\":\"sorting\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"01018774\", \"05740701\", \"13579899\"]}");
	add("{\"term\":\"sorting algorithm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05856185\"]}");
	add("{\"term\":\"sorting program\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06592279\"]}");
	add("{\"term\":\"sortition\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00180903\"]}");
	add("{\"term\":\"sorus\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13114904\", \"13115032\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }