package org.swtk.commons.dict.wordnet.indexbyname.instance.p.r.i;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstancePRI {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"priacanthidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02573931\"]}");
	add("{\"term\":\"priacanthus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02574117\"]}");
	add("{\"term\":\"priacanthus arenatus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02574441\"]}");
	add("{\"term\":\"priam\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11266245\"]}");
	add("{\"term\":\"priapism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14234046\"]}");
	add("{\"term\":\"priapus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09593972\"]}");
	add("{\"term\":\"price\", \"synsetCount\":7, \"upperType\":\"NOUN\", \"ids\":[\"11266398\", \"13324781\", \"07181692\", \"05148930\", \"05171334\", \"13324337\", \"05152365\"]}");
	add("{\"term\":\"price bracket\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08022847\"]}");
	add("{\"term\":\"price competition\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13859399\"]}");
	add("{\"term\":\"price control\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06670209\"]}");
	add("{\"term\":\"price cut\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00353687\"]}");
	add("{\"term\":\"price cutting\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00353687\"]}");
	add("{\"term\":\"price floor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06671014\"]}");
	add("{\"term\":\"price freeze\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00810940\"]}");
	add("{\"term\":\"price gouging\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05744838\"]}");
	add("{\"term\":\"price increase\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05117407\"]}");
	add("{\"term\":\"price index\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06653830\"]}");
	add("{\"term\":\"price level\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06653830\"]}");
	add("{\"term\":\"price list\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06506529\"]}");
	add("{\"term\":\"price of admission\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13342517\"]}");
	add("{\"term\":\"price reduction\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00362929\"]}");
	add("{\"term\":\"price support\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13288434\"]}");
	add("{\"term\":\"price tag\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07287729\"]}");
	add("{\"term\":\"price war\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13859399\"]}");
	add("{\"term\":\"pricelessness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05148469\"]}");
	add("{\"term\":\"pricing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05744681\"]}");
	add("{\"term\":\"pricing system\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05913512\"]}");
	add("{\"term\":\"prick\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"00946605\", \"05534354\", \"13927849\", \"09834593\"]}");
	add("{\"term\":\"pricker\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02892139\", \"13110391\"]}");
	add("{\"term\":\"pricket\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02433394\", \"04008620\"]}");
	add("{\"term\":\"pricking\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00946605\"]}");
	add("{\"term\":\"prickle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13110391\"]}");
	add("{\"term\":\"prickle cell\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05249005\"]}");
	add("{\"term\":\"prickleback\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01457497\", \"02618272\"]}");
	add("{\"term\":\"prickliness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04956976\"]}");
	add("{\"term\":\"prickling\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05730815\"]}");
	add("{\"term\":\"prickly ash\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12242607\", \"12735515\"]}");
	add("{\"term\":\"prickly custard apple\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11715133\"]}");
	add("{\"term\":\"prickly heat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14345533\"]}");
	add("{\"term\":\"prickly lettuce\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12007980\"]}");
	add("{\"term\":\"prickly pear\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07784834\", \"11872047\"]}");
	add("{\"term\":\"prickly pear cactus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11872047\"]}");
	add("{\"term\":\"prickly pine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11638082\"]}");
	add("{\"term\":\"prickly poppy\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11922066\", \"11923178\"]}");
	add("{\"term\":\"prickly shield fern\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13221091\"]}");
	add("{\"term\":\"prickteaser\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09984664\"]}");
	add("{\"term\":\"pride\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"00759528\", \"08011720\", \"04893841\", \"07546924\", \"07523725\"]}");
	add("{\"term\":\"pride of barbados\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12510559\"]}");
	add("{\"term\":\"pride of bolivia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12594416\"]}");
	add("{\"term\":\"pride of california\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12562111\"]}");
	add("{\"term\":\"pride of place\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08639047\"]}");
	add("{\"term\":\"pridefulness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07523725\"]}");
	add("{\"term\":\"priest\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10490835\", \"10490364\"]}");
	add("{\"term\":\"priestcraft\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05651652\", \"05917321\"]}");
	add("{\"term\":\"priestess\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10491155\"]}");
	add("{\"term\":\"priesthood\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08130409\"]}");
	add("{\"term\":\"priestley\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11266532\"]}");
	add("{\"term\":\"prig\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10636540\"]}");
	add("{\"term\":\"priggishness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04907157\"]}");
	add("{\"term\":\"prilosec\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14801765\"]}");
	add("{\"term\":\"prima\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07757599\"]}");
	add("{\"term\":\"prima ballerina\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10491225\"]}");
	add("{\"term\":\"prima donna\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10491317\", \"10491444\"]}");
	add("{\"term\":\"primacy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14458819\"]}");
	add("{\"term\":\"primality\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05216164\"]}");
	add("{\"term\":\"primaquine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04008810\"]}");
	add("{\"term\":\"primary\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"04008987\", \"09421644\", \"02471711\", \"00183420\"]}");
	add("{\"term\":\"primary amenorrhea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14327074\"]}");
	add("{\"term\":\"primary atypical pneumonia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14171446\"]}");
	add("{\"term\":\"primary care\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00657276\"]}");
	add("{\"term\":\"primary care physician\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10491533\"]}");
	add("{\"term\":\"primary care provider\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10184702\"]}");
	add("{\"term\":\"primary cell\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04548047\"]}");
	add("{\"term\":\"primary censorship\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00824011\"]}");
	add("{\"term\":\"primary coil\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04008987\"]}");
	add("{\"term\":\"primary color\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04964353\"]}");
	add("{\"term\":\"primary color for light\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04964766\"]}");
	add("{\"term\":\"primary color for pigments\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04964533\"]}");
	add("{\"term\":\"primary colour\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04964353\"]}");
	add("{\"term\":\"primary colour for light\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04964766\"]}");
	add("{\"term\":\"primary colour for pigments\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04964533\"]}");
	add("{\"term\":\"primary dentition\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05289746\"]}");
	add("{\"term\":\"primary dysmenorrhea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14349714\"]}");
	add("{\"term\":\"primary election\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00183420\"]}");
	add("{\"term\":\"primary feather\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02471711\"]}");
	add("{\"term\":\"primary health care\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01091221\"]}");
	add("{\"term\":\"primary quill\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02471711\"]}");
	add("{\"term\":\"primary school\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08429706\"]}");
	add("{\"term\":\"primary sex character\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05014744\"]}");
	add("{\"term\":\"primary sex characteristic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05014744\"]}");
	add("{\"term\":\"primary sexual characteristic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05014744\"]}");
	add("{\"term\":\"primary solid solution\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15076272\"]}");
	add("{\"term\":\"primary subtractive color for light\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04965031\"]}");
	add("{\"term\":\"primary subtractive colour for light\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04965031\"]}");
	add("{\"term\":\"primary syphilis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14157833\"]}");
	add("{\"term\":\"primary tooth\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05314393\"]}");
	add("{\"term\":\"primary winding\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04008987\"]}");
	add("{\"term\":\"primate\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02472545\", \"09826498\"]}");
	add("{\"term\":\"primates\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02472219\"]}");
	add("{\"term\":\"primateship\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00598647\"]}");
	add("{\"term\":\"primatology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06083197\"]}");
	add("{\"term\":\"primaxin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04008894\"]}");
	add("{\"term\":\"prime\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"15177369\", \"15254580\", \"15320288\", \"13615208\"]}");
	add("{\"term\":\"prime factor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13615379\"]}");
	add("{\"term\":\"prime interest rate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13340894\"]}");
	add("{\"term\":\"prime meridian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08616848\"]}");
	add("{\"term\":\"prime minister\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09926439\", \"09926654\"]}");
	add("{\"term\":\"prime mover\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09527735\"]}");
	add("{\"term\":\"prime number\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13615545\"]}");
	add("{\"term\":\"prime of life\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15177369\"]}");
	add("{\"term\":\"prime quantity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13615208\"]}");
	add("{\"term\":\"prime time\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15191944\"]}");
	add("{\"term\":\"primer\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"03365691\", \"03412032\", \"06426591\"]}");
	add("{\"term\":\"primer coat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03365691\"]}");
	add("{\"term\":\"primidone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04009289\"]}");
	add("{\"term\":\"primigravida\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10491714\"]}");
	add("{\"term\":\"priming\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"03365691\", \"03412032\", \"01146559\"]}");
	add("{\"term\":\"priming coat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03365691\"]}");
	add("{\"term\":\"primipara\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10491859\"]}");
	add("{\"term\":\"primitive\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"06305722\", \"06305894\", \"09650650\"]}");
	add("{\"term\":\"primitive art\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03867479\"]}");
	add("{\"term\":\"primitive person\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09650650\"]}");
	add("{\"term\":\"primitiveness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14496208\"]}");
	add("{\"term\":\"primitivism\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04009468\", \"14496208\"]}");
	add("{\"term\":\"primness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04907157\", \"04908329\"]}");
	add("{\"term\":\"primo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07044763\"]}");
	add("{\"term\":\"primogenitor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10146343\"]}");
	add("{\"term\":\"primogeniture\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13284156\"]}");
	add("{\"term\":\"primordial dwarf\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10492032\"]}");
	add("{\"term\":\"primordium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05305658\"]}");
	add("{\"term\":\"primping\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00830220\"]}");
	add("{\"term\":\"primrose\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12111407\"]}");
	add("{\"term\":\"primrose family\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12110835\"]}");
	add("{\"term\":\"primrose jasmine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12327455\"]}");
	add("{\"term\":\"primrose path\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00417142\"]}");
	add("{\"term\":\"primula\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12111407\"]}");
	add("{\"term\":\"primula auricula\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12112323\"]}");
	add("{\"term\":\"primula elatior\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12112067\"]}");
	add("{\"term\":\"primula polyantha\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12112470\"]}");
	add("{\"term\":\"primula sinensis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12112214\"]}");
	add("{\"term\":\"primula veris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12111894\"]}");
	add("{\"term\":\"primula vulgaris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12111730\"]}");
	add("{\"term\":\"primulaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12110835\"]}");
	add("{\"term\":\"primulales\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12110558\"]}");
	add("{\"term\":\"primum mobile\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09527735\"]}");
	add("{\"term\":\"primus\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04009599\", \"10492275\"]}");
	add("{\"term\":\"primus stove\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04009599\"]}");
	add("{\"term\":\"prince\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10492384\"]}");
	add("{\"term\":\"prince albert\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04009717\", \"10831144\"]}");
	add("{\"term\":\"prince albert yew\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11679699\"]}");
	add("{\"term\":\"prince charles\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10912168\"]}");
	add("{\"term\":\"prince charming\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10493038\"]}");
	add("{\"term\":\"prince consort\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10493147\"]}");
	add("{\"term\":\"prince edward\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10969944\"]}");
	add("{\"term\":\"prince edward island\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08847742\"]}");
	add("{\"term\":\"prince eugene of savoy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10982415\"]}");
	add("{\"term\":\"prince fumimaro konoe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11128757\"]}");
	add("{\"term\":\"prince fumimaro konoye\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11128757\"]}");
	add("{\"term\":\"prince klemens wenzel nepomuk lothar von metternich\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11197522\"]}");
	add("{\"term\":\"prince of darkness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09566482\"]}");
	add("{\"term\":\"prince of smolensk\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11133067\"]}");
	add("{\"term\":\"prince of wales\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10493502\"]}");
	add("{\"term\":\"prince of wales heath\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12249628\"]}");
	add("{\"term\":\"prince otto eduard leopold von bismarck\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10871195\"]}");
	add("{\"term\":\"prince otto von bismarck\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10871195\"]}");
	add("{\"term\":\"prince peter kropotkin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11131184\"]}");
	add("{\"term\":\"prince philip\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11252465\"]}");
	add("{\"term\":\"prince rupert\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11294093\"]}");
	add("{\"term\":\"princedom\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"08576025\", \"14456581\"]}");
	add("{\"term\":\"princeling\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10493303\", \"10493374\"]}");
	add("{\"term\":\"princess\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10493649\"]}");
	add("{\"term\":\"princess diana\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10953409\"]}");
	add("{\"term\":\"princess feather\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12622566\"]}");
	add("{\"term\":\"princess grace of monaco\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11119913\"]}");
	add("{\"term\":\"princess of wales\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10953409\"]}");
	add("{\"term\":\"princess pine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13244608\"]}");
	add("{\"term\":\"princess royal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10493928\"]}");
	add("{\"term\":\"princeton\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04009811\", \"09136781\"]}");
	add("{\"term\":\"princeton university\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04009811\"]}");
	add("{\"term\":\"princeton wordnet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06651729\"]}");
	add("{\"term\":\"princewood\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12839106\", \"12839361\"]}");
	add("{\"term\":\"principal\", \"synsetCount\":6, \"upperType\":\"NOUN\", \"ids\":[\"10494031\", \"10494535\", \"13376883\", \"10668135\", \"10494230\", \"13421835\"]}");
	add("{\"term\":\"principal axis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06019454\"]}");
	add("{\"term\":\"principal diagonal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08285557\"]}");
	add("{\"term\":\"principal investigator\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10494748\"]}");
	add("{\"term\":\"principal sum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13376883\"]}");
	add("{\"term\":\"principality\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08576025\"]}");
	add("{\"term\":\"principality of andorra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09045488\"]}");
	add("{\"term\":\"principality of liechtenstein\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08980321\"]}");
	add("{\"term\":\"principality of monaco\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08990219\"]}");
	add("{\"term\":\"principalship\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00598744\"]}");
	add("{\"term\":\"principe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09015514\"]}");
	add("{\"term\":\"principen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02708510\"]}");
	add("{\"term\":\"principle\", \"synsetCount\":6, \"upperType\":\"NOUN\", \"ids\":[\"05801218\", \"06668133\", \"05882839\", \"05881099\", \"05964190\", \"05922132\"]}");
	add("{\"term\":\"principle of equivalence\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05999866\"]}");
	add("{\"term\":\"principle of liquid displacement\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06000127\"]}");
	add("{\"term\":\"principle of parsimony\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05999623\"]}");
	add("{\"term\":\"principle of relativity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05999365\"]}");
	add("{\"term\":\"principle of superposition\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06000326\", \"06000661\"]}");
	add("{\"term\":\"prinia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01568445\"]}");
	add("{\"term\":\"prinival\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03682634\"]}");
	add("{\"term\":\"print\", \"synsetCount\":7, \"upperType\":\"NOUN\", \"ids\":[\"03932813\", \"04010232\", \"04010358\", \"06690891\", \"06811608\", \"04009955\", \"06691047\"]}");
	add("{\"term\":\"print buffer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04010475\"]}");
	add("{\"term\":\"print media\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06274262\"]}");
	add("{\"term\":\"print run\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15286783\"]}");
	add("{\"term\":\"print seller\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10495420\"]}");
	add("{\"term\":\"print shop\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04011466\"]}");
	add("{\"term\":\"printed circuit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04010586\"]}");
	add("{\"term\":\"printed symbol\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06830481\"]}");
	add("{\"term\":\"printer\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04010851\", \"04011143\", \"10494882\"]}");
	add("{\"term\":\"printer cable\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04011366\"]}");
	add("{\"term\":\"printing\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"06602491\", \"06690047\", \"01105064\", \"06414934\"]}");
	add("{\"term\":\"printing business\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08086463\"]}");
	add("{\"term\":\"printing company\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08086463\"]}");
	add("{\"term\":\"printing concern\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08086463\"]}");
	add("{\"term\":\"printing ink\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14942174\"]}");
	add("{\"term\":\"printing machine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04010851\"]}");
	add("{\"term\":\"printing operation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13561994\"]}");
	add("{\"term\":\"printing press\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04006669\"]}");
	add("{\"term\":\"printing process\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06690047\"]}");
	add("{\"term\":\"printing shop\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04011466\"]}");
	add("{\"term\":\"printing unit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13629450\"]}");
	add("{\"term\":\"printmaker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10495272\"]}");
	add("{\"term\":\"printmaking\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00939292\"]}");
	add("{\"term\":\"printout\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07279743\"]}");
	add("{\"term\":\"priodontes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02458518\"]}");
	add("{\"term\":\"priodontes giganteus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02458639\"]}");
	add("{\"term\":\"prion\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09421810\"]}");
	add("{\"term\":\"prionace\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01493526\"]}");
	add("{\"term\":\"prionace glauca\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01493647\"]}");
	add("{\"term\":\"prionotus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02653558\"]}");
	add("{\"term\":\"prionotus carolinus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02653690\"]}");
	add("{\"term\":\"prior\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10495525\"]}");
	add("{\"term\":\"prioress\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09773548\"]}");
	add("{\"term\":\"priority\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05054430\", \"13973020\"]}");
	add("{\"term\":\"priority processing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13562178\"]}");
	add("{\"term\":\"priorship\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00598843\"]}");
	add("{\"term\":\"priory\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04011573\"]}");
	add("{\"term\":\"priscoan\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15154524\"]}");
	add("{\"term\":\"priscoan aeon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15154524\"]}");
	add("{\"term\":\"priscoan eon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15154524\"]}");
	add("{\"term\":\"prism\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04011716\", \"13907168\"]}");
	add("{\"term\":\"prism spectroscope\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04280183\"]}");
	add("{\"term\":\"prismatoid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13940907\"]}");
	add("{\"term\":\"prismoid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13941128\"]}");
	add("{\"term\":\"prison\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"13960317\", \"04012006\"]}");
	add("{\"term\":\"prison camp\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04608091\", \"04012288\"]}");
	add("{\"term\":\"prison cell\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02994757\"]}");
	add("{\"term\":\"prison chaplain\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09928227\"]}");
	add("{\"term\":\"prison farm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04608091\"]}");
	add("{\"term\":\"prison guard\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10169387\"]}");
	add("{\"term\":\"prison house\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04012006\", \"13960317\"]}");
	add("{\"term\":\"prison term\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15249488\"]}");
	add("{\"term\":\"prisonbreak\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00060809\"]}");
	add("{\"term\":\"prisoner\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10495671\"]}");
	add("{\"term\":\"prisoner of war\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10495916\"]}");
	add("{\"term\":\"prisoner of war camp\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04012288\"]}");
	add("{\"term\":\"prisoner of war censorship\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00823634\"]}");
	add("{\"term\":\"pristidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01499585\"]}");
	add("{\"term\":\"pristis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01499919\"]}");
	add("{\"term\":\"pristis pectinatus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01500054\"]}");
	add("{\"term\":\"pritzelago\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11914277\"]}");
	add("{\"term\":\"pritzelago alpina\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11914385\"]}");
	add("{\"term\":\"privacy\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"14439493\", \"04630289\"]}");
	add("{\"term\":\"private\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10496052\"]}");
	add("{\"term\":\"private citizen\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10477469\"]}");
	add("{\"term\":\"private corporation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08400421\"]}");
	add("{\"term\":\"private detective\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10496256\"]}");
	add("{\"term\":\"private enterprise\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08381886\"]}");
	add("{\"term\":\"private eye\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10496256\"]}");
	add("{\"term\":\"private foundation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08423957\"]}");
	add("{\"term\":\"private instructor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09950876\"]}");
	add("{\"term\":\"private investigator\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10496256\"]}");
	add("{\"term\":\"private line\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04012603\"]}");
	add("{\"term\":\"private nuisance\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05839736\"]}");
	add("{\"term\":\"private parts\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05521732\"]}");
	add("{\"term\":\"private practice\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00634063\"]}");
	add("{\"term\":\"private property\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13266525\"]}");
	add("{\"term\":\"private road\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03249091\"]}");
	add("{\"term\":\"private school\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08428127\"]}");
	add("{\"term\":\"private security force\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08227903\"]}");
	add("{\"term\":\"private treaty\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00093032\"]}");
	add("{\"term\":\"privateer\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04012443\", \"10496513\"]}");
	add("{\"term\":\"privateersman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10496513\"]}");
	add("{\"term\":\"privately held corporation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08400421\"]}");
	add("{\"term\":\"privateness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04630289\", \"14439493\"]}");
	add("{\"term\":\"privates\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05521732\"]}");
	add("{\"term\":\"privation\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01152695\", \"14517010\"]}");
	add("{\"term\":\"privatisation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01154528\"]}");
	add("{\"term\":\"privatization\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01154528\"]}");
	add("{\"term\":\"privet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12328273\"]}");
	add("{\"term\":\"privet andromeda\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12261709\"]}");
	add("{\"term\":\"privet hedge\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04012706\"]}");
	add("{\"term\":\"privilege\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"05187094\", \"05186242\", \"05165679\"]}");
	add("{\"term\":\"privilege against self incrimination\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05192078\"]}");
	add("{\"term\":\"privilege of the floor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05186937\"]}");
	add("{\"term\":\"privine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03812592\"]}");
	add("{\"term\":\"privy\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03865924\", \"04453410\"]}");
	add("{\"term\":\"privy council\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08328617\"]}");
	add("{\"term\":\"privy purse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13315325\"]}");
	add("{\"term\":\"prix de rome\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07283868\"]}");
	add("{\"term\":\"prix fixe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06509224\"]}");
	add("{\"term\":\"prix goncourt\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07284135\"]}");
	add("{\"term\":\"prize\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04495252\", \"13283562\", \"13289169\"]}");
	add("{\"term\":\"prize fight\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07486946\"]}");
	add("{\"term\":\"prize money\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13289781\"]}");
	add("{\"term\":\"prize ring\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02888904\"]}");
	add("{\"term\":\"prize winner\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09650995\"]}");
	add("{\"term\":\"prizefight\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07486946\"]}");
	add("{\"term\":\"prizefighter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10496662\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }