package org.swtk.commons.dict.wordnet.indexbyname.instance.n.o.v;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceNOV {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"nov\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15238202\"]}");
	add("{\"term\":\"nova\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09397404\"]}");
	add("{\"term\":\"novation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00197697\"]}");
	add("{\"term\":\"novel\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03838605\", \"06379324\"]}");
	add("{\"term\":\"novelette\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06380585\"]}");
	add("{\"term\":\"novelisation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00933268\"]}");
	add("{\"term\":\"novelist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10383272\"]}");
	add("{\"term\":\"novelization\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00933268\"]}");
	add("{\"term\":\"novella\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06380585\"]}");
	add("{\"term\":\"novelty\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"02790458\", \"03628657\", \"05642900\", \"04807845\"]}");
	add("{\"term\":\"november\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15238202\"]}");
	add("{\"term\":\"novena\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01045221\"]}");
	add("{\"term\":\"novgorod\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09031544\"]}");
	add("{\"term\":\"novial\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06910082\"]}");
	add("{\"term\":\"novice\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10383612\", \"10383897\"]}");
	add("{\"term\":\"noviciate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15320127\"]}");
	add("{\"term\":\"novillada\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03838834\"]}");
	add("{\"term\":\"novillero\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09856046\"]}");
	add("{\"term\":\"novitiate\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10383897\", \"15320127\"]}");
	add("{\"term\":\"novobiocin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03838949\"]}");
	add("{\"term\":\"novocain\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04013329\"]}");
	add("{\"term\":\"novocaine\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04013329\"]}");
	add("{\"term\":\"novosibirsk\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09032670\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }