package org.swtk.commons.dict.wordnet.indexbyname.instance.o.p.t;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceOPT {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"optative\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13824310\"]}");
	add("{\"term\":\"optative mood\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13824310\"]}");
	add("{\"term\":\"optez\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06910329\"]}");
	add("{\"term\":\"optic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05318579\"]}");
	add("{\"term\":\"optic axis\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06019454\", \"06019730\"]}");
	add("{\"term\":\"optic chiasm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05236211\"]}");
	add("{\"term\":\"optic chiasma\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05236211\"]}");
	add("{\"term\":\"optic cup\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02158330\"]}");
	add("{\"term\":\"optic disc\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05463658\"]}");
	add("{\"term\":\"optic disk\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05463658\"]}");
	add("{\"term\":\"optic nerve\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05485988\"]}");
	add("{\"term\":\"optic radiation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05236379\"]}");
	add("{\"term\":\"optic tract\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05485988\"]}");
	add("{\"term\":\"optical aberration\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11440253\"]}");
	add("{\"term\":\"optical bench\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03856739\"]}");
	add("{\"term\":\"optical condenser\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03091788\"]}");
	add("{\"term\":\"optical crown\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14904424\"]}");
	add("{\"term\":\"optical crown glass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14904424\"]}");
	add("{\"term\":\"optical density\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05096574\"]}");
	add("{\"term\":\"optical device\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03856861\"]}");
	add("{\"term\":\"optical disc\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03857307\"]}");
	add("{\"term\":\"optical disk\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03857307\"]}");
	add("{\"term\":\"optical fiber\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03857551\"]}");
	add("{\"term\":\"optical fibre\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03857551\"]}");
	add("{\"term\":\"optical flint\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14904576\"]}");
	add("{\"term\":\"optical fusion\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05945279\"]}");
	add("{\"term\":\"optical glass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14904258\"]}");
	add("{\"term\":\"optical illusion\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11510863\"]}");
	add("{\"term\":\"optical instrument\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03857800\"]}");
	add("{\"term\":\"optical lens\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02946696\"]}");
	add("{\"term\":\"optical maser\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03648567\"]}");
	add("{\"term\":\"optical opacity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11510657\"]}");
	add("{\"term\":\"optical phenomenon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11511038\"]}");
	add("{\"term\":\"optical prism\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04011716\"]}");
	add("{\"term\":\"optical pyrometer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03858064\"]}");
	add("{\"term\":\"optical telescope\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03858208\"]}");
	add("{\"term\":\"optician\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10399699\"]}");
	add("{\"term\":\"optics\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04957203\", \"06110385\"]}");
	add("{\"term\":\"optimisation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00260894\"]}");
	add("{\"term\":\"optimism\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05219061\", \"07556946\"]}");
	add("{\"term\":\"optimist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10399825\"]}");
	add("{\"term\":\"optimization\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00260894\"]}");
	add("{\"term\":\"optimum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05151111\"]}");
	add("{\"term\":\"option\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"00162063\", \"05798949\", \"13262498\"]}");
	add("{\"term\":\"optometrist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10400004\"]}");
	add("{\"term\":\"optometry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00633959\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }