package org.swtk.commons.dict.wordnet.indexbyname.instance.o.r.o;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceORO {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"orobanchaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12894991\"]}");
	add("{\"term\":\"orogeny\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13549020\"]}");
	add("{\"term\":\"orography\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06127753\"]}");
	add("{\"term\":\"oroide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14712866\"]}");
	add("{\"term\":\"orology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06127753\"]}");
	add("{\"term\":\"orono\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09115893\"]}");
	add("{\"term\":\"orontium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11810708\"]}");
	add("{\"term\":\"orontium aquaticum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11810859\"]}");
	add("{\"term\":\"oropharynx\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05536645\"]}");
	add("{\"term\":\"orozco\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11236912\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }