package org.swtk.commons.dict.wordnet.index.name.controller.s.p;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.c.WordnetNounIndexNameInstanceSPAC;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.d.WordnetNounIndexNameInstanceSPAD;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.g.WordnetNounIndexNameInstanceSPAG;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.i.WordnetNounIndexNameInstanceSPAI;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.l.WordnetNounIndexNameInstanceSPAL;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.m.WordnetNounIndexNameInstanceSPAM;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.n.WordnetNounIndexNameInstanceSPAN;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.r.WordnetNounIndexNameInstanceSPAR;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.s.WordnetNounIndexNameInstanceSPAS;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.t.WordnetNounIndexNameInstanceSPAT;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.v.WordnetNounIndexNameInstanceSPAV;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.w.WordnetNounIndexNameInstanceSPAW;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.a.y.WordnetNounIndexNameInstanceSPAY;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.e.a.WordnetNounIndexNameInstanceSPEA;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.e.c.WordnetNounIndexNameInstanceSPEC;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.e.e.WordnetNounIndexNameInstanceSPEE;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.e.k.WordnetNounIndexNameInstanceSPEK;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.e.l.WordnetNounIndexNameInstanceSPEL;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.e.n.WordnetNounIndexNameInstanceSPEN;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.e.r.WordnetNounIndexNameInstanceSPER;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.e.w.WordnetNounIndexNameInstanceSPEW;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.h.a.WordnetNounIndexNameInstanceSPHA;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.h.e.WordnetNounIndexNameInstanceSPHE;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.h.i.WordnetNounIndexNameInstanceSPHI;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.h.y.WordnetNounIndexNameInstanceSPHY;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.i.c.WordnetNounIndexNameInstanceSPIC;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.i.d.WordnetNounIndexNameInstanceSPID;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.i.e.WordnetNounIndexNameInstanceSPIE;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.i.f.WordnetNounIndexNameInstanceSPIF;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.i.g.WordnetNounIndexNameInstanceSPIG;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.i.k.WordnetNounIndexNameInstanceSPIK;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.i.l.WordnetNounIndexNameInstanceSPIL;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.i.n.WordnetNounIndexNameInstanceSPIN;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.i.r.WordnetNounIndexNameInstanceSPIR;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.i.t.WordnetNounIndexNameInstanceSPIT;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.i.v.WordnetNounIndexNameInstanceSPIV;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.i.z.WordnetNounIndexNameInstanceSPIZ;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.l.a.WordnetNounIndexNameInstanceSPLA;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.l.e.WordnetNounIndexNameInstanceSPLE;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.l.i.WordnetNounIndexNameInstanceSPLI;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.l.o.WordnetNounIndexNameInstanceSPLO;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.l.u.WordnetNounIndexNameInstanceSPLU;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.o.c.WordnetNounIndexNameInstanceSPOC;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.o.d.WordnetNounIndexNameInstanceSPOD;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.o.i.WordnetNounIndexNameInstanceSPOI;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.o.k.WordnetNounIndexNameInstanceSPOK;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.o.l.WordnetNounIndexNameInstanceSPOL;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.o.n.WordnetNounIndexNameInstanceSPON;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.o.o.WordnetNounIndexNameInstanceSPOO;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.o.r.WordnetNounIndexNameInstanceSPOR;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.o.t.WordnetNounIndexNameInstanceSPOT;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.o.u.WordnetNounIndexNameInstanceSPOU;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.r.a.WordnetNounIndexNameInstanceSPRA;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.r.e.WordnetNounIndexNameInstanceSPRE;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.r.i.WordnetNounIndexNameInstanceSPRI;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.r.o.WordnetNounIndexNameInstanceSPRO;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.r.u.WordnetNounIndexNameInstanceSPRU;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.u.d.WordnetNounIndexNameInstanceSPUD;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.u.m.WordnetNounIndexNameInstanceSPUM;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.u.n.WordnetNounIndexNameInstanceSPUN;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.u.r.WordnetNounIndexNameInstanceSPUR;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.u.t.WordnetNounIndexNameInstanceSPUT;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.y.e.WordnetNounIndexNameInstanceSPYE;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.y.g.WordnetNounIndexNameInstanceSPYG;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.y.h.WordnetNounIndexNameInstanceSPYH;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.y.i.WordnetNounIndexNameInstanceSPYI;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.y.m.WordnetNounIndexNameInstanceSPYM;
	import org.swtk.commons.dict.wordnet.index.name.instance.s.p.y.w.WordnetNounIndexNameInstanceSPYW;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerSP {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("spac".equals(key)) return WordnetNounIndexNameInstanceSPAC.get(TERM);
	if ("spad".equals(key)) return WordnetNounIndexNameInstanceSPAD.get(TERM);
	if ("spag".equals(key)) return WordnetNounIndexNameInstanceSPAG.get(TERM);
	if ("spai".equals(key)) return WordnetNounIndexNameInstanceSPAI.get(TERM);
	if ("spal".equals(key)) return WordnetNounIndexNameInstanceSPAL.get(TERM);
	if ("spam".equals(key)) return WordnetNounIndexNameInstanceSPAM.get(TERM);
	if ("span".equals(key)) return WordnetNounIndexNameInstanceSPAN.get(TERM);
	if ("spar".equals(key)) return WordnetNounIndexNameInstanceSPAR.get(TERM);
	if ("spas".equals(key)) return WordnetNounIndexNameInstanceSPAS.get(TERM);
	if ("spat".equals(key)) return WordnetNounIndexNameInstanceSPAT.get(TERM);
	if ("spav".equals(key)) return WordnetNounIndexNameInstanceSPAV.get(TERM);
	if ("spaw".equals(key)) return WordnetNounIndexNameInstanceSPAW.get(TERM);
	if ("spay".equals(key)) return WordnetNounIndexNameInstanceSPAY.get(TERM);
	if ("spea".equals(key)) return WordnetNounIndexNameInstanceSPEA.get(TERM);
	if ("spec".equals(key)) return WordnetNounIndexNameInstanceSPEC.get(TERM);
	if ("spee".equals(key)) return WordnetNounIndexNameInstanceSPEE.get(TERM);
	if ("spek".equals(key)) return WordnetNounIndexNameInstanceSPEK.get(TERM);
	if ("spel".equals(key)) return WordnetNounIndexNameInstanceSPEL.get(TERM);
	if ("spen".equals(key)) return WordnetNounIndexNameInstanceSPEN.get(TERM);
	if ("sper".equals(key)) return WordnetNounIndexNameInstanceSPER.get(TERM);
	if ("spew".equals(key)) return WordnetNounIndexNameInstanceSPEW.get(TERM);
	if ("spha".equals(key)) return WordnetNounIndexNameInstanceSPHA.get(TERM);
	if ("sphe".equals(key)) return WordnetNounIndexNameInstanceSPHE.get(TERM);
	if ("sphi".equals(key)) return WordnetNounIndexNameInstanceSPHI.get(TERM);
	if ("sphy".equals(key)) return WordnetNounIndexNameInstanceSPHY.get(TERM);
	if ("spic".equals(key)) return WordnetNounIndexNameInstanceSPIC.get(TERM);
	if ("spid".equals(key)) return WordnetNounIndexNameInstanceSPID.get(TERM);
	if ("spie".equals(key)) return WordnetNounIndexNameInstanceSPIE.get(TERM);
	if ("spif".equals(key)) return WordnetNounIndexNameInstanceSPIF.get(TERM);
	if ("spig".equals(key)) return WordnetNounIndexNameInstanceSPIG.get(TERM);
	if ("spik".equals(key)) return WordnetNounIndexNameInstanceSPIK.get(TERM);
	if ("spil".equals(key)) return WordnetNounIndexNameInstanceSPIL.get(TERM);
	if ("spin".equals(key)) return WordnetNounIndexNameInstanceSPIN.get(TERM);
	if ("spir".equals(key)) return WordnetNounIndexNameInstanceSPIR.get(TERM);
	if ("spit".equals(key)) return WordnetNounIndexNameInstanceSPIT.get(TERM);
	if ("spiv".equals(key)) return WordnetNounIndexNameInstanceSPIV.get(TERM);
	if ("spiz".equals(key)) return WordnetNounIndexNameInstanceSPIZ.get(TERM);
	if ("spla".equals(key)) return WordnetNounIndexNameInstanceSPLA.get(TERM);
	if ("sple".equals(key)) return WordnetNounIndexNameInstanceSPLE.get(TERM);
	if ("spli".equals(key)) return WordnetNounIndexNameInstanceSPLI.get(TERM);
	if ("splo".equals(key)) return WordnetNounIndexNameInstanceSPLO.get(TERM);
	if ("splu".equals(key)) return WordnetNounIndexNameInstanceSPLU.get(TERM);
	if ("spoc".equals(key)) return WordnetNounIndexNameInstanceSPOC.get(TERM);
	if ("spod".equals(key)) return WordnetNounIndexNameInstanceSPOD.get(TERM);
	if ("spoi".equals(key)) return WordnetNounIndexNameInstanceSPOI.get(TERM);
	if ("spok".equals(key)) return WordnetNounIndexNameInstanceSPOK.get(TERM);
	if ("spol".equals(key)) return WordnetNounIndexNameInstanceSPOL.get(TERM);
	if ("spon".equals(key)) return WordnetNounIndexNameInstanceSPON.get(TERM);
	if ("spoo".equals(key)) return WordnetNounIndexNameInstanceSPOO.get(TERM);
	if ("spor".equals(key)) return WordnetNounIndexNameInstanceSPOR.get(TERM);
	if ("spot".equals(key)) return WordnetNounIndexNameInstanceSPOT.get(TERM);
	if ("spou".equals(key)) return WordnetNounIndexNameInstanceSPOU.get(TERM);
	if ("spra".equals(key)) return WordnetNounIndexNameInstanceSPRA.get(TERM);
	if ("spre".equals(key)) return WordnetNounIndexNameInstanceSPRE.get(TERM);
	if ("spri".equals(key)) return WordnetNounIndexNameInstanceSPRI.get(TERM);
	if ("spro".equals(key)) return WordnetNounIndexNameInstanceSPRO.get(TERM);
	if ("spru".equals(key)) return WordnetNounIndexNameInstanceSPRU.get(TERM);
	if ("spud".equals(key)) return WordnetNounIndexNameInstanceSPUD.get(TERM);
	if ("spum".equals(key)) return WordnetNounIndexNameInstanceSPUM.get(TERM);
	if ("spun".equals(key)) return WordnetNounIndexNameInstanceSPUN.get(TERM);
	if ("spur".equals(key)) return WordnetNounIndexNameInstanceSPUR.get(TERM);
	if ("sput".equals(key)) return WordnetNounIndexNameInstanceSPUT.get(TERM);
	if ("spye".equals(key)) return WordnetNounIndexNameInstanceSPYE.get(TERM);
	if ("spyg".equals(key)) return WordnetNounIndexNameInstanceSPYG.get(TERM);
	if ("spyh".equals(key)) return WordnetNounIndexNameInstanceSPYH.get(TERM);
	if ("spyi".equals(key)) return WordnetNounIndexNameInstanceSPYI.get(TERM);
	if ("spym".equals(key)) return WordnetNounIndexNameInstanceSPYM.get(TERM);
	if ("spyw".equals(key)) return WordnetNounIndexNameInstanceSPYW.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceSPAC.terms());
	set.addAll(WordnetNounIndexNameInstanceSPAD.terms());
	set.addAll(WordnetNounIndexNameInstanceSPAG.terms());
	set.addAll(WordnetNounIndexNameInstanceSPAI.terms());
	set.addAll(WordnetNounIndexNameInstanceSPAL.terms());
	set.addAll(WordnetNounIndexNameInstanceSPAM.terms());
	set.addAll(WordnetNounIndexNameInstanceSPAN.terms());
	set.addAll(WordnetNounIndexNameInstanceSPAR.terms());
	set.addAll(WordnetNounIndexNameInstanceSPAS.terms());
	set.addAll(WordnetNounIndexNameInstanceSPAT.terms());
	set.addAll(WordnetNounIndexNameInstanceSPAV.terms());
	set.addAll(WordnetNounIndexNameInstanceSPAW.terms());
	set.addAll(WordnetNounIndexNameInstanceSPAY.terms());
	set.addAll(WordnetNounIndexNameInstanceSPEA.terms());
	set.addAll(WordnetNounIndexNameInstanceSPEC.terms());
	set.addAll(WordnetNounIndexNameInstanceSPEE.terms());
	set.addAll(WordnetNounIndexNameInstanceSPEK.terms());
	set.addAll(WordnetNounIndexNameInstanceSPEL.terms());
	set.addAll(WordnetNounIndexNameInstanceSPEN.terms());
	set.addAll(WordnetNounIndexNameInstanceSPER.terms());
	set.addAll(WordnetNounIndexNameInstanceSPEW.terms());
	set.addAll(WordnetNounIndexNameInstanceSPHA.terms());
	set.addAll(WordnetNounIndexNameInstanceSPHE.terms());
	set.addAll(WordnetNounIndexNameInstanceSPHI.terms());
	set.addAll(WordnetNounIndexNameInstanceSPHY.terms());
	set.addAll(WordnetNounIndexNameInstanceSPIC.terms());
	set.addAll(WordnetNounIndexNameInstanceSPID.terms());
	set.addAll(WordnetNounIndexNameInstanceSPIE.terms());
	set.addAll(WordnetNounIndexNameInstanceSPIF.terms());
	set.addAll(WordnetNounIndexNameInstanceSPIG.terms());
	set.addAll(WordnetNounIndexNameInstanceSPIK.terms());
	set.addAll(WordnetNounIndexNameInstanceSPIL.terms());
	set.addAll(WordnetNounIndexNameInstanceSPIN.terms());
	set.addAll(WordnetNounIndexNameInstanceSPIR.terms());
	set.addAll(WordnetNounIndexNameInstanceSPIT.terms());
	set.addAll(WordnetNounIndexNameInstanceSPIV.terms());
	set.addAll(WordnetNounIndexNameInstanceSPIZ.terms());
	set.addAll(WordnetNounIndexNameInstanceSPLA.terms());
	set.addAll(WordnetNounIndexNameInstanceSPLE.terms());
	set.addAll(WordnetNounIndexNameInstanceSPLI.terms());
	set.addAll(WordnetNounIndexNameInstanceSPLO.terms());
	set.addAll(WordnetNounIndexNameInstanceSPLU.terms());
	set.addAll(WordnetNounIndexNameInstanceSPOC.terms());
	set.addAll(WordnetNounIndexNameInstanceSPOD.terms());
	set.addAll(WordnetNounIndexNameInstanceSPOI.terms());
	set.addAll(WordnetNounIndexNameInstanceSPOK.terms());
	set.addAll(WordnetNounIndexNameInstanceSPOL.terms());
	set.addAll(WordnetNounIndexNameInstanceSPON.terms());
	set.addAll(WordnetNounIndexNameInstanceSPOO.terms());
	set.addAll(WordnetNounIndexNameInstanceSPOR.terms());
	set.addAll(WordnetNounIndexNameInstanceSPOT.terms());
	set.addAll(WordnetNounIndexNameInstanceSPOU.terms());
	set.addAll(WordnetNounIndexNameInstanceSPRA.terms());
	set.addAll(WordnetNounIndexNameInstanceSPRE.terms());
	set.addAll(WordnetNounIndexNameInstanceSPRI.terms());
	set.addAll(WordnetNounIndexNameInstanceSPRO.terms());
	set.addAll(WordnetNounIndexNameInstanceSPRU.terms());
	set.addAll(WordnetNounIndexNameInstanceSPUD.terms());
	set.addAll(WordnetNounIndexNameInstanceSPUM.terms());
	set.addAll(WordnetNounIndexNameInstanceSPUN.terms());
	set.addAll(WordnetNounIndexNameInstanceSPUR.terms());
	set.addAll(WordnetNounIndexNameInstanceSPUT.terms());
	set.addAll(WordnetNounIndexNameInstanceSPYE.terms());
	set.addAll(WordnetNounIndexNameInstanceSPYG.terms());
	set.addAll(WordnetNounIndexNameInstanceSPYH.terms());
	set.addAll(WordnetNounIndexNameInstanceSPYI.terms());
	set.addAll(WordnetNounIndexNameInstanceSPYM.terms());
	set.addAll(WordnetNounIndexNameInstanceSPYW.terms());
  		return set; 	} }