package org.swtk.commons.dict.wordnet.index.name.controller.p.y;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.a.e.WordnetNounIndexNameInstancePYAE;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.c.n.WordnetNounIndexNameInstancePYCN;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.d.n.WordnetNounIndexNameInstancePYDN;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.e.l.WordnetNounIndexNameInstancePYEL;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.e.m.WordnetNounIndexNameInstancePYEM;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.g.m.WordnetNounIndexNameInstancePYGM;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.g.o.WordnetNounIndexNameInstancePYGO;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.i.n.WordnetNounIndexNameInstancePYIN;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.j.a.WordnetNounIndexNameInstancePYJA;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.k.n.WordnetNounIndexNameInstancePYKN;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.l.e.WordnetNounIndexNameInstancePYLE;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.l.o.WordnetNounIndexNameInstancePYLO;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.n.c.WordnetNounIndexNameInstancePYNC;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.o.c.WordnetNounIndexNameInstancePYOC;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.o.n.WordnetNounIndexNameInstancePYON;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.o.r.WordnetNounIndexNameInstancePYOR;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.r.a.WordnetNounIndexNameInstancePYRA;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.r.e.WordnetNounIndexNameInstancePYRE;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.r.i.WordnetNounIndexNameInstancePYRI;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.r.o.WordnetNounIndexNameInstancePYRO;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.r.r.WordnetNounIndexNameInstancePYRR;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.r.u.WordnetNounIndexNameInstancePYRU;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.t.h.WordnetNounIndexNameInstancePYTH;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.u.r.WordnetNounIndexNameInstancePYUR;
	import org.swtk.commons.dict.wordnet.index.name.instance.p.y.x.i.WordnetNounIndexNameInstancePYXI;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerPY {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("pyae".equals(key)) return WordnetNounIndexNameInstancePYAE.get(TERM);
	if ("pycn".equals(key)) return WordnetNounIndexNameInstancePYCN.get(TERM);
	if ("pydn".equals(key)) return WordnetNounIndexNameInstancePYDN.get(TERM);
	if ("pyel".equals(key)) return WordnetNounIndexNameInstancePYEL.get(TERM);
	if ("pyem".equals(key)) return WordnetNounIndexNameInstancePYEM.get(TERM);
	if ("pygm".equals(key)) return WordnetNounIndexNameInstancePYGM.get(TERM);
	if ("pygo".equals(key)) return WordnetNounIndexNameInstancePYGO.get(TERM);
	if ("pyin".equals(key)) return WordnetNounIndexNameInstancePYIN.get(TERM);
	if ("pyja".equals(key)) return WordnetNounIndexNameInstancePYJA.get(TERM);
	if ("pykn".equals(key)) return WordnetNounIndexNameInstancePYKN.get(TERM);
	if ("pyle".equals(key)) return WordnetNounIndexNameInstancePYLE.get(TERM);
	if ("pylo".equals(key)) return WordnetNounIndexNameInstancePYLO.get(TERM);
	if ("pync".equals(key)) return WordnetNounIndexNameInstancePYNC.get(TERM);
	if ("pyoc".equals(key)) return WordnetNounIndexNameInstancePYOC.get(TERM);
	if ("pyon".equals(key)) return WordnetNounIndexNameInstancePYON.get(TERM);
	if ("pyor".equals(key)) return WordnetNounIndexNameInstancePYOR.get(TERM);
	if ("pyra".equals(key)) return WordnetNounIndexNameInstancePYRA.get(TERM);
	if ("pyre".equals(key)) return WordnetNounIndexNameInstancePYRE.get(TERM);
	if ("pyri".equals(key)) return WordnetNounIndexNameInstancePYRI.get(TERM);
	if ("pyro".equals(key)) return WordnetNounIndexNameInstancePYRO.get(TERM);
	if ("pyrr".equals(key)) return WordnetNounIndexNameInstancePYRR.get(TERM);
	if ("pyru".equals(key)) return WordnetNounIndexNameInstancePYRU.get(TERM);
	if ("pyth".equals(key)) return WordnetNounIndexNameInstancePYTH.get(TERM);
	if ("pyur".equals(key)) return WordnetNounIndexNameInstancePYUR.get(TERM);
	if ("pyxi".equals(key)) return WordnetNounIndexNameInstancePYXI.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstancePYAE.terms());
	set.addAll(WordnetNounIndexNameInstancePYCN.terms());
	set.addAll(WordnetNounIndexNameInstancePYDN.terms());
	set.addAll(WordnetNounIndexNameInstancePYEL.terms());
	set.addAll(WordnetNounIndexNameInstancePYEM.terms());
	set.addAll(WordnetNounIndexNameInstancePYGM.terms());
	set.addAll(WordnetNounIndexNameInstancePYGO.terms());
	set.addAll(WordnetNounIndexNameInstancePYIN.terms());
	set.addAll(WordnetNounIndexNameInstancePYJA.terms());
	set.addAll(WordnetNounIndexNameInstancePYKN.terms());
	set.addAll(WordnetNounIndexNameInstancePYLE.terms());
	set.addAll(WordnetNounIndexNameInstancePYLO.terms());
	set.addAll(WordnetNounIndexNameInstancePYNC.terms());
	set.addAll(WordnetNounIndexNameInstancePYOC.terms());
	set.addAll(WordnetNounIndexNameInstancePYON.terms());
	set.addAll(WordnetNounIndexNameInstancePYOR.terms());
	set.addAll(WordnetNounIndexNameInstancePYRA.terms());
	set.addAll(WordnetNounIndexNameInstancePYRE.terms());
	set.addAll(WordnetNounIndexNameInstancePYRI.terms());
	set.addAll(WordnetNounIndexNameInstancePYRO.terms());
	set.addAll(WordnetNounIndexNameInstancePYRR.terms());
	set.addAll(WordnetNounIndexNameInstancePYRU.terms());
	set.addAll(WordnetNounIndexNameInstancePYTH.terms());
	set.addAll(WordnetNounIndexNameInstancePYUR.terms());
	set.addAll(WordnetNounIndexNameInstancePYXI.terms());
  		return set; 	} }