package org.swtk.commons.dict.wordnet.indexbyname.instance.b.o.o;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceBOO {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"boo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07138578\"]}");
	add("{\"term\":\"boob\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05562038\", \"10059116\"]}");
	add("{\"term\":\"boob tube\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04413042\"]}");
	add("{\"term\":\"booboisie\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08198738\"]}");
	add("{\"term\":\"booby\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02056238\", \"10059116\"]}");
	add("{\"term\":\"booby hatch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02823933\"]}");
	add("{\"term\":\"booby prize\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02873326\"]}");
	add("{\"term\":\"booby trap\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05696795\", \"03644989\"]}");
	add("{\"term\":\"boocercus eurycerus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02426731\"]}");
	add("{\"term\":\"boodle\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00494319\", \"13406389\"]}");
	add("{\"term\":\"booger\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05423472\", \"09511247\"]}");
	add("{\"term\":\"boogeyman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09511247\"]}");
	add("{\"term\":\"boogie\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07077289\"]}");
	add("{\"term\":\"boojum tree\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12402750\"]}");
	add("{\"term\":\"book\", \"synsetCount\":11, \"upperType\":\"NOUN\", \"ids\":[\"02873887\", \"06406508\", \"06443410\", \"06473279\", \"07970797\", \"07971027\", \"13425421\", \"07023062\", \"06649049\", \"02873453\", \"06422547\"]}");
	add("{\"term\":\"book agent\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09885078\"]}");
	add("{\"term\":\"book bag\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02874037\"]}");
	add("{\"term\":\"book binding\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02843848\"]}");
	add("{\"term\":\"book fair\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01120659\", \"08425375\"]}");
	add("{\"term\":\"book jacket\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07262988\"]}");
	add("{\"term\":\"book louse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02264071\"]}");
	add("{\"term\":\"book lover\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09872087\"]}");
	add("{\"term\":\"book lung\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05535878\"]}");
	add("{\"term\":\"book matches\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04134081\"]}");
	add("{\"term\":\"book of account\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13425421\"]}");
	add("{\"term\":\"book of amos\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06451230\"]}");
	add("{\"term\":\"book of baruch\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06470993\"]}");
	add("{\"term\":\"book of common prayer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06468841\"]}");
	add("{\"term\":\"book of daniel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06450665\"]}");
	add("{\"term\":\"book of deuteronomy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06445145\"]}");
	add("{\"term\":\"book of ecclesiastes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06449201\"]}");
	add("{\"term\":\"book of esther\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06448387\"]}");
	add("{\"term\":\"book of exodus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06444385\"]}");
	add("{\"term\":\"book of ezekiel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06450418\"]}");
	add("{\"term\":\"book of ezra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06447853\"]}");
	add("{\"term\":\"book of facts\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06429241\"]}");
	add("{\"term\":\"book of genesis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06444046\"]}");
	add("{\"term\":\"book of habakkuk\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06452159\"]}");
	add("{\"term\":\"book of haggai\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06452607\"]}");
	add("{\"term\":\"book of hosea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06450923\"]}");
	add("{\"term\":\"book of instructions\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06433787\"]}");
	add("{\"term\":\"book of isaiah\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06449796\"]}");
	add("{\"term\":\"book of jeremiah\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06449960\"]}");
	add("{\"term\":\"book of job\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06448609\"]}");
	add("{\"term\":\"book of joel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06451078\"]}");
	add("{\"term\":\"book of jonah\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06451594\"]}");
	add("{\"term\":\"book of joshua\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06445593\"]}");
	add("{\"term\":\"book of judges\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06445835\"]}");
	add("{\"term\":\"book of judith\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06471504\"]}");
	add("{\"term\":\"book of knowledge\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06439380\"]}");
	add("{\"term\":\"book of lamentations\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06450147\"]}");
	add("{\"term\":\"book of leviticus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06444705\"]}");
	add("{\"term\":\"book of malachi\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06453134\"]}");
	add("{\"term\":\"book of maps\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06438756\"]}");
	add("{\"term\":\"book of micah\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06451772\"]}");
	add("{\"term\":\"book of mormon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06467445\"]}");
	add("{\"term\":\"book of nahum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06451983\"]}");
	add("{\"term\":\"book of nehemiah\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06448113\"]}");
	add("{\"term\":\"book of numbers\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06444919\"]}");
	add("{\"term\":\"book of obadiah\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06451382\"]}");
	add("{\"term\":\"book of proverbs\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06448978\"]}");
	add("{\"term\":\"book of psalms\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06429110\", \"06448807\"]}");
	add("{\"term\":\"book of revelation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06459567\"]}");
	add("{\"term\":\"book of ruth\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06446038\"]}");
	add("{\"term\":\"book of susanna\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06470686\"]}");
	add("{\"term\":\"book of the prophet daniel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06450665\"]}");
	add("{\"term\":\"book of tobit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06471351\"]}");
	add("{\"term\":\"book of zachariah\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06452865\"]}");
	add("{\"term\":\"book of zephaniah\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06452333\"]}");
	add("{\"term\":\"book review\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06422298\"]}");
	add("{\"term\":\"book scorpion\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01773741\"]}");
	add("{\"term\":\"book seller\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09885244\"]}");
	add("{\"term\":\"book token\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06530244\"]}");
	add("{\"term\":\"book value\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13358161\"]}");
	add("{\"term\":\"bookbinder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09885150\"]}");
	add("{\"term\":\"bookbindery\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02874133\"]}");
	add("{\"term\":\"bookbinding\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00608489\"]}");
	add("{\"term\":\"bookcase\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02874241\"]}");
	add("{\"term\":\"bookclub\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08245459\"]}");
	add("{\"term\":\"bookdealer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09885244\"]}");
	add("{\"term\":\"bookend\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02874366\"]}");
	add("{\"term\":\"booker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09885360\"]}");
	add("{\"term\":\"booker taliaferro washington\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11395672\"]}");
	add("{\"term\":\"bookfair\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01120659\", \"08425375\"]}");
	add("{\"term\":\"bookie\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09885628\"]}");
	add("{\"term\":\"booking\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01220817\", \"00271763\"]}");
	add("{\"term\":\"booking agent\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09885360\"]}");
	add("{\"term\":\"booking clerk\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09652665\"]}");
	add("{\"term\":\"bookishness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04873596\"]}");
	add("{\"term\":\"bookkeeper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09885521\"]}");
	add("{\"term\":\"bookkeeping\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00620470\"]}");
	add("{\"term\":\"booklet\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06425532\"]}");
	add("{\"term\":\"booklouse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02264071\"]}");
	add("{\"term\":\"booklover\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09872087\"]}");
	add("{\"term\":\"bookmaker\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09885628\", \"09885760\"]}");
	add("{\"term\":\"bookman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10577282\"]}");
	add("{\"term\":\"bookmark\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02874508\"]}");
	add("{\"term\":\"bookmarker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02874508\"]}");
	add("{\"term\":\"bookmobile\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02874675\"]}");
	add("{\"term\":\"bookplate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07287121\"]}");
	add("{\"term\":\"bookseller\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09885879\"]}");
	add("{\"term\":\"bookshelf\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02874800\"]}");
	add("{\"term\":\"bookshop\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02874886\"]}");
	add("{\"term\":\"bookstall\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02874886\"]}");
	add("{\"term\":\"bookstore\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02874886\"]}");
	add("{\"term\":\"bookworm\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09885965\", \"10431101\"]}");
	add("{\"term\":\"boole\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10876867\"]}");
	add("{\"term\":\"boolean algebra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06174716\"]}");
	add("{\"term\":\"boolean logic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06174716\"]}");
	add("{\"term\":\"boolean operation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13462108\"]}");
	add("{\"term\":\"boom\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"02874992\", \"02875185\", \"07492727\", \"14512397\", \"07392282\"]}");
	add("{\"term\":\"boom box\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03441092\"]}");
	add("{\"term\":\"boom town\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08689031\"]}");
	add("{\"term\":\"boomer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09847649\"]}");
	add("{\"term\":\"boomerang\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00073852\", \"02875324\"]}");
	add("{\"term\":\"boon\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14497848\"]}");
	add("{\"term\":\"boondocks\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08519693\"]}");
	add("{\"term\":\"boondoggle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00042352\"]}");
	add("{\"term\":\"boone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10877014\"]}");
	add("{\"term\":\"boor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10430560\"]}");
	add("{\"term\":\"boorishness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04825019\", \"04921753\"]}");
	add("{\"term\":\"boost\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"01213829\", \"05117708\", \"01213509\"]}");
	add("{\"term\":\"booster\", \"synsetCount\":6, \"upperType\":\"NOUN\", \"ids\":[\"02875533\", \"02875694\", \"02875890\", \"09886067\", \"10501805\", \"10697152\"]}");
	add("{\"term\":\"booster amplifier\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02875890\"]}");
	add("{\"term\":\"booster cable\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03610056\"]}");
	add("{\"term\":\"booster dose\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02875533\"]}");
	add("{\"term\":\"booster rocket\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02875694\"]}");
	add("{\"term\":\"booster shot\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02875533\"]}");
	add("{\"term\":\"booster station\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02875890\"]}");
	add("{\"term\":\"booster unit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02875694\"]}");
	add("{\"term\":\"boot\", \"synsetCount\":7, \"upperType\":\"NOUN\", \"ids\":[\"00137149\", \"00423264\", \"02876605\", \"02876762\", \"07543858\", \"03701391\", \"02876113\"]}");
	add("{\"term\":\"boot camp\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02876865\"]}");
	add("{\"term\":\"boot maker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09886475\"]}");
	add("{\"term\":\"boot sale\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01120935\"]}");
	add("{\"term\":\"bootblack\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09886223\"]}");
	add("{\"term\":\"bootboys\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08388127\"]}");
	add("{\"term\":\"booted armillaria\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13252817\"]}");
	add("{\"term\":\"bootee\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02876975\"]}");
	add("{\"term\":\"bootes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09249645\"]}");
	add("{\"term\":\"booth\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"02877328\", \"10877136\", \"02877081\", \"02877456\"]}");
	add("{\"term\":\"boothose\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02877578\"]}");
	add("{\"term\":\"bootie\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02876975\"]}");
	add("{\"term\":\"bootjack\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02877684\"]}");
	add("{\"term\":\"bootlace\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02877779\"]}");
	add("{\"term\":\"bootleg\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02877884\", \"07918760\"]}");
	add("{\"term\":\"bootlegger\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09886328\"]}");
	add("{\"term\":\"bootlegging\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00093667\", \"00093483\"]}");
	add("{\"term\":\"bootlicker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09820054\"]}");
	add("{\"term\":\"bootmaker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09886475\"]}");
	add("{\"term\":\"bootstrap\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02877992\"]}");
	add("{\"term\":\"booty\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13283562\"]}");
	add("{\"term\":\"booyong\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12220307\"]}");
	add("{\"term\":\"booze\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07917827\"]}");
	add("{\"term\":\"boozer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09801608\"]}");
	add("{\"term\":\"boozing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00749813\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }