package org.swtk.commons.dict.wordnet.indexbyname.instance.a.l.g;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceALG {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"alga\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01399755\"]}");
	add("{\"term\":\"algae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01399755\"]}");
	add("{\"term\":\"algarobilla\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11786515\"]}");
	add("{\"term\":\"algarroba\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"11786328\", \"11786515\", \"12513713\", \"12513931\"]}");
	add("{\"term\":\"algarrobilla\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11786515\"]}");
	add("{\"term\":\"algebra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06022075\"]}");
	add("{\"term\":\"algebraist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09803484\"]}");
	add("{\"term\":\"alger\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10833131\"]}");
	add("{\"term\":\"algeria\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08723211\"]}");
	add("{\"term\":\"algerian\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09709479\"]}");
	add("{\"term\":\"algerie\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08723211\"]}");
	add("{\"term\":\"algeripithecus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02482113\"]}");
	add("{\"term\":\"algidity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14227923\"]}");
	add("{\"term\":\"algiers\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08723872\"]}");
	add("{\"term\":\"algin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14924605\"]}");
	add("{\"term\":\"algol\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06914540\", \"09215444\"]}");
	add("{\"term\":\"algolagnia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07508822\"]}");
	add("{\"term\":\"algology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06084057\"]}");
	add("{\"term\":\"algometer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02699428\"]}");
	add("{\"term\":\"algometry\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01000138\"]}");
	add("{\"term\":\"algonkian\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06920935\", \"09666270\"]}");
	add("{\"term\":\"algonkin\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06920935\", \"09666270\"]}");
	add("{\"term\":\"algonquian\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06919747\", \"09666446\"]}");
	add("{\"term\":\"algonquin\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06919747\", \"09666446\"]}");
	add("{\"term\":\"algophilia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07508822\"]}");
	add("{\"term\":\"algophobia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14406276\"]}");
	add("{\"term\":\"algorism\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06013929\", \"06823549\"]}");
	add("{\"term\":\"algorithm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05855965\"]}");
	add("{\"term\":\"algren\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10833315\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }