package org.swtk.commons.dict.wordnet.indexbyname.instance.m.u.s;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceMUS {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"mus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02334612\"]}");
	add("{\"term\":\"mus musculus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02334808\"]}");
	add("{\"term\":\"mus rose\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12191615\"]}");
	add("{\"term\":\"musa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12372667\"]}");
	add("{\"term\":\"musa acuminata\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12373156\"]}");
	add("{\"term\":\"musa basjoo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12373361\"]}");
	add("{\"term\":\"musa ensete\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12374271\"]}");
	add("{\"term\":\"musa paradisiaca\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12373507\"]}");
	add("{\"term\":\"musa paradisiaca sapientum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12373720\"]}");
	add("{\"term\":\"musa textilis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12373948\"]}");
	add("{\"term\":\"musaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12372492\"]}");
	add("{\"term\":\"musales\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12370751\"]}");
	add("{\"term\":\"musca\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02193300\", \"09386707\"]}");
	add("{\"term\":\"musca domestica\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02193442\"]}");
	add("{\"term\":\"musca volitans\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14388524\"]}");
	add("{\"term\":\"muscadel\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07917697\"]}");
	add("{\"term\":\"muscadelle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07917697\"]}");
	add("{\"term\":\"muscadet\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07912868\", \"13167930\"]}");
	add("{\"term\":\"muscadine\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07775400\", \"13166027\"]}");
	add("{\"term\":\"muscae volitantes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14388524\"]}");
	add("{\"term\":\"muscardinus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02355689\"]}");
	add("{\"term\":\"muscardinus avellanarius\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02355824\"]}");
	add("{\"term\":\"muscari\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12481054\"]}");
	add("{\"term\":\"muscari comosum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12481614\"]}");
	add("{\"term\":\"muscari neglectum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12481462\"]}");
	add("{\"term\":\"muscat\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"07776129\", \"07917697\", \"08997805\", \"13168571\"]}");
	add("{\"term\":\"muscat and oman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08997476\"]}");
	add("{\"term\":\"muscat grape\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07776129\"]}");
	add("{\"term\":\"muscatel\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07776129\", \"07917697\"]}");
	add("{\"term\":\"musci\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11559386\"]}");
	add("{\"term\":\"muscicapa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01558681\"]}");
	add("{\"term\":\"muscicapa grisola\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01558823\"]}");
	add("{\"term\":\"muscicapa striata\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01558823\"]}");
	add("{\"term\":\"muscicapidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01558227\"]}");
	add("{\"term\":\"muscidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02192667\"]}");
	add("{\"term\":\"muscivora\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01557813\"]}");
	add("{\"term\":\"muscle\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"05037584\", \"05205400\", \"10359063\", \"05296556\", \"05296796\"]}");
	add("{\"term\":\"muscle builder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09882251\"]}");
	add("{\"term\":\"muscle building\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00627233\"]}");
	add("{\"term\":\"muscle cell\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05466808\"]}");
	add("{\"term\":\"muscle contraction\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00370610\"]}");
	add("{\"term\":\"muscle fiber\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05466808\"]}");
	add("{\"term\":\"muscle fibre\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05466808\"]}");
	add("{\"term\":\"muscle memory\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05769274\"]}");
	add("{\"term\":\"muscle relaxant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03805523\"]}");
	add("{\"term\":\"muscle sense\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05666830\"]}");
	add("{\"term\":\"muscle spasm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14383864\"]}");
	add("{\"term\":\"muscle system\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05469392\"]}");
	add("{\"term\":\"muscle tone\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14568817\"]}");
	add("{\"term\":\"musclebuilder\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09882251\"]}");
	add("{\"term\":\"musclebuilding\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00627233\"]}");
	add("{\"term\":\"muscleman\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09882251\", \"10359063\"]}");
	add("{\"term\":\"muscoidea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02192474\"]}");
	add("{\"term\":\"muscovite\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"09748404\", \"14707246\"]}");
	add("{\"term\":\"muscovy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09026288\"]}");
	add("{\"term\":\"muscovy duck\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01855312\"]}");
	add("{\"term\":\"muscular contraction\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00370610\"]}");
	add("{\"term\":\"muscular dystrophy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14183847\"]}");
	add("{\"term\":\"muscular structure\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05469392\"]}");
	add("{\"term\":\"muscular tissue\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05296556\"]}");
	add("{\"term\":\"muscular tonus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14568817\"]}");
	add("{\"term\":\"muscularity\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04640554\", \"05037584\", \"14068201\"]}");
	add("{\"term\":\"musculature\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05469392\"]}");
	add("{\"term\":\"musculophrenic artery\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05360149\"]}");
	add("{\"term\":\"musculophrenic vein\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05381444\"]}");
	add("{\"term\":\"musculoskeletal system\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05469633\"]}");
	add("{\"term\":\"musculospiral nerve\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05512458\"]}");
	add("{\"term\":\"musculus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05296796\"]}");
	add("{\"term\":\"musculus abductor digiti minimi manus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05298729\"]}");
	add("{\"term\":\"musculus abductor digiti minimi pedis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05298872\"]}");
	add("{\"term\":\"musculus abductor hallucis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05298994\"]}");
	add("{\"term\":\"musculus abductor pollicis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05299103\"]}");
	add("{\"term\":\"musculus adductor brevis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05299444\"]}");
	add("{\"term\":\"musculus adductor hallucis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05299858\"]}");
	add("{\"term\":\"musculus adductor longus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05299572\"]}");
	add("{\"term\":\"musculus adductor magnus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05299699\"]}");
	add("{\"term\":\"musculus anconeus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05300355\"]}");
	add("{\"term\":\"musculus articularis cubiti\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05301272\"]}");
	add("{\"term\":\"musculus articularis genus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05301443\"]}");
	add("{\"term\":\"musculus biceps brachii\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05587067\"]}");
	add("{\"term\":\"musculus biceps femoris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05586684\"]}");
	add("{\"term\":\"musculus buccinator\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05301567\"]}");
	add("{\"term\":\"musculus deltoideus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05556983\"]}");
	add("{\"term\":\"musculus intercostalis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05559920\"]}");
	add("{\"term\":\"musculus obliquus externus abdominis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05565472\"]}");
	add("{\"term\":\"musculus pectoralis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05559344\"]}");
	add("{\"term\":\"musculus pectoralis major\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05559572\"]}");
	add("{\"term\":\"musculus pectoralis minor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05559739\"]}");
	add("{\"term\":\"musculus quadriceps femoris\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05302318\"]}");
	add("{\"term\":\"musculus rhomboideus major\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05582816\"]}");
	add("{\"term\":\"musculus rhomboideus minor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05583005\"]}");
	add("{\"term\":\"musculus sartorius\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05597546\"]}");
	add("{\"term\":\"musculus scalenus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05597794\"]}");
	add("{\"term\":\"musculus serratus anterior\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05558127\"]}");
	add("{\"term\":\"musculus serratus posterior\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05558321\"]}");
	add("{\"term\":\"musculus sphincter ani\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05579344\"]}");
	add("{\"term\":\"musculus sphincter ani externus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05579535\"]}");
	add("{\"term\":\"musculus sphincter ani internus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05579688\"]}");
	add("{\"term\":\"musculus sphincter ductus choledochi\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05580260\"]}");
	add("{\"term\":\"musculus sphincter ductus pancreatici\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05580413\"]}");
	add("{\"term\":\"musculus sphincter pupillae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05580571\"]}");
	add("{\"term\":\"musculus sphincter pylori\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05580730\"]}");
	add("{\"term\":\"musculus sphincter urethrae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05579858\"]}");
	add("{\"term\":\"musculus sphincter vesicae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05580027\"]}");
	add("{\"term\":\"musculus sternocleidomastoideus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05598121\"]}");
	add("{\"term\":\"musculus temporalis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05610059\"]}");
	add("{\"term\":\"musculus teres major\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05598694\"]}");
	add("{\"term\":\"musculus teres minor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05598851\"]}");
	add("{\"term\":\"musculus tibialis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05599011\"]}");
	add("{\"term\":\"musculus transversalis abdominis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05565711\"]}");
	add("{\"term\":\"musculus trapezius\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05599525\"]}");
	add("{\"term\":\"musculus triceps brachii\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05587384\"]}");
	add("{\"term\":\"musd\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06716183\"]}");
	add("{\"term\":\"muse\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05843486\", \"09589128\"]}");
	add("{\"term\":\"muser\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10359217\"]}");
	add("{\"term\":\"musette\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03805893\"]}");
	add("{\"term\":\"musette pipe\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03806007\"]}");
	add("{\"term\":\"museum\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03806085\"]}");
	add("{\"term\":\"musgoi\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06997106\"]}");
	add("{\"term\":\"musgu\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06997406\"]}");
	add("{\"term\":\"mush\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"00309034\", \"06788770\", \"07719078\", \"09423701\"]}");
	add("{\"term\":\"musher\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10359430\"]}");
	add("{\"term\":\"mushiness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04634863\", \"04946375\"]}");
	add("{\"term\":\"mushroom\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"07750720\", \"11462169\", \"13018679\", \"13021651\", \"13021801\"]}");
	add("{\"term\":\"mushroom anchor\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03806294\"]}");
	add("{\"term\":\"mushroom cloud\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11462169\"]}");
	add("{\"term\":\"mushroom coral\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01920523\"]}");
	add("{\"term\":\"mushroom pimple\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12986808\"]}");
	add("{\"term\":\"mushroom poisoning\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14092539\"]}");
	add("{\"term\":\"mushroom sauce\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07854787\"]}");
	add("{\"term\":\"mushroom wine sauce\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07847797\"]}");
	add("{\"term\":\"mushy peas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07742501\"]}");
	add("{\"term\":\"musial\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11217934\"]}");
	add("{\"term\":\"music\", \"synsetCount\":5, \"upperType\":\"NOUN\", \"ids\":[\"01165019\", \"05726882\", \"00544270\", \"05726503\", \"07034009\"]}");
	add("{\"term\":\"music box\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03806893\"]}");
	add("{\"term\":\"music critic\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10359569\"]}");
	add("{\"term\":\"music department\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08134515\"]}");
	add("{\"term\":\"music director\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09972018\"]}");
	add("{\"term\":\"music genre\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07085982\"]}");
	add("{\"term\":\"music hall\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07033537\", \"03807073\"]}");
	add("{\"term\":\"music lesson\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00891438\"]}");
	add("{\"term\":\"music lover\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09971095\"]}");
	add("{\"term\":\"music of the spheres\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05727413\"]}");
	add("{\"term\":\"music paper\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14981291\"]}");
	add("{\"term\":\"music rack\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03807300\"]}");
	add("{\"term\":\"music school\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03807211\", \"08300570\"]}");
	add("{\"term\":\"music stand\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03807300\"]}");
	add("{\"term\":\"music stool\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03807420\"]}");
	add("{\"term\":\"music teacher\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10361074\"]}");
	add("{\"term\":\"musical\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07032286\"]}");
	add("{\"term\":\"musical accompaniment\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07045239\"]}");
	add("{\"term\":\"musical arrangement\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07052146\"]}");
	add("{\"term\":\"musical box\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03806893\"]}");
	add("{\"term\":\"musical chairs\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"00339999\", \"00487681\"]}");
	add("{\"term\":\"musical comedy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07032286\"]}");
	add("{\"term\":\"musical composition\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07051211\"]}");
	add("{\"term\":\"musical drama\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07040407\"]}");
	add("{\"term\":\"musical genre\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07085982\"]}");
	add("{\"term\":\"musical group\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08263534\"]}");
	add("{\"term\":\"musical harmony\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07040667\"]}");
	add("{\"term\":\"musical instrument\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03806455\"]}");
	add("{\"term\":\"musical instrument digital interface\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06678775\"]}");
	add("{\"term\":\"musical interval\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06871829\"]}");
	add("{\"term\":\"musical mode\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06874680\"]}");
	add("{\"term\":\"musical notation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06827728\"]}");
	add("{\"term\":\"musical note\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06878395\"]}");
	add("{\"term\":\"musical octave\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06872451\"]}");
	add("{\"term\":\"musical organisation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08263534\"]}");
	add("{\"term\":\"musical organization\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08263534\"]}");
	add("{\"term\":\"musical passage\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07058663\"]}");
	add("{\"term\":\"musical perception\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05719738\"]}");
	add("{\"term\":\"musical performance\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00101073\"]}");
	add("{\"term\":\"musical phrase\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07059411\"]}");
	add("{\"term\":\"musical rhythm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07100710\"]}");
	add("{\"term\":\"musical scale\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06869618\"]}");
	add("{\"term\":\"musical score\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06828572\"]}");
	add("{\"term\":\"musical soiree\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08272294\"]}");
	add("{\"term\":\"musical style\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07085982\"]}");
	add("{\"term\":\"musical theater\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07032286\"]}");
	add("{\"term\":\"musical theme\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07042734\"]}");
	add("{\"term\":\"musical time\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15146953\"]}");
	add("{\"term\":\"musical time signature\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06877574\"]}");
	add("{\"term\":\"musicality\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04990651\"]}");
	add("{\"term\":\"musicalness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04990651\"]}");
	add("{\"term\":\"musician\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"10359679\", \"10360025\"]}");
	add("{\"term\":\"musicianship\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05643893\"]}");
	add("{\"term\":\"musicogenic epilepsy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14112722\"]}");
	add("{\"term\":\"musicologist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10360974\"]}");
	add("{\"term\":\"musicology\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06181104\"]}");
	add("{\"term\":\"musing\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05793513\"]}");
	add("{\"term\":\"musjid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03730247\"]}");
	add("{\"term\":\"musk\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05722279\", \"14870816\"]}");
	add("{\"term\":\"musk clover\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12710066\"]}");
	add("{\"term\":\"musk deer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02437847\"]}");
	add("{\"term\":\"musk duck\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01855312\"]}");
	add("{\"term\":\"musk hog\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02400181\"]}");
	add("{\"term\":\"musk kangaroo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01882478\"]}");
	add("{\"term\":\"musk mallow\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12191615\", \"12192998\"]}");
	add("{\"term\":\"musk ox\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02413852\"]}");
	add("{\"term\":\"musk rose\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12643058\"]}");
	add("{\"term\":\"musk sheep\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02413852\"]}");
	add("{\"term\":\"musk thistle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11965423\"]}");
	add("{\"term\":\"musk turtle\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01670073\"]}");
	add("{\"term\":\"muskat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"13168571\"]}");
	add("{\"term\":\"muskellunge\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02564145\", \"07795511\"]}");
	add("{\"term\":\"musket\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03807547\"]}");
	add("{\"term\":\"musket ball\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03807768\"]}");
	add("{\"term\":\"musketeer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10361177\"]}");
	add("{\"term\":\"musketry\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"05651456\", \"08406169\"]}");
	add("{\"term\":\"muskhogean\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06926089\", \"09681743\"]}");
	add("{\"term\":\"muskhogean language\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06926089\"]}");
	add("{\"term\":\"muskiness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04988293\"]}");
	add("{\"term\":\"muskmelon\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"07771683\", \"12184880\"]}");
	add("{\"term\":\"muskogean\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06926089\", \"09681743\"]}");
	add("{\"term\":\"muskogean language\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06926089\"]}");
	add("{\"term\":\"muskogee\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"06925513\", \"09155162\", \"09682030\"]}");
	add("{\"term\":\"muskrat\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02340797\", \"14789754\"]}");
	add("{\"term\":\"muskrat fur\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14789754\"]}");
	add("{\"term\":\"muskus grass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12710066\"]}");
	add("{\"term\":\"muskwood\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12018786\"]}");
	add("{\"term\":\"muslim\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09701687\"]}");
	add("{\"term\":\"muslim calendar\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15203888\"]}");
	add("{\"term\":\"muslim ummah\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08241605\"]}");
	add("{\"term\":\"muslimah\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10361304\"]}");
	add("{\"term\":\"muslimism\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"06244979\", \"08112613\"]}");
	add("{\"term\":\"muslin\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03807933\"]}");
	add("{\"term\":\"musnud\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03808047\"]}");
	add("{\"term\":\"musophaga\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01827796\"]}");
	add("{\"term\":\"musophagidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01827650\"]}");
	add("{\"term\":\"musophobia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14408730\"]}");
	add("{\"term\":\"musquash\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02340797\"]}");
	add("{\"term\":\"muss\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14523631\"]}");
	add("{\"term\":\"mussel\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01966212\", \"07799526\"]}");
	add("{\"term\":\"mussel shrimp\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02000479\"]}");
	add("{\"term\":\"musset\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11218084\"]}");
	add("{\"term\":\"mussiness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14523631\"]}");
	add("{\"term\":\"mussitation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07401520\"]}");
	add("{\"term\":\"mussolini\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11218243\"]}");
	add("{\"term\":\"mussorgsky\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11218365\"]}");
	add("{\"term\":\"must\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"04935371\", \"07940895\", \"09386867\"]}");
	add("{\"term\":\"mustache\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05269684\"]}");
	add("{\"term\":\"mustache cup\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03808183\"]}");
	add("{\"term\":\"mustachio\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05270033\"]}");
	add("{\"term\":\"mustafa kemal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10846556\"]}");
	add("{\"term\":\"mustagh\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09346730\"]}");
	add("{\"term\":\"mustagh range\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09346730\"]}");
	add("{\"term\":\"mustang\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02383235\"]}");
	add("{\"term\":\"mustang mint\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12880439\"]}");
	add("{\"term\":\"mustard\", \"synsetCount\":3, \"upperType\":\"NOUN\", \"ids\":[\"07729508\", \"07835456\", \"11898752\"]}");
	add("{\"term\":\"mustard agent\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14981409\"]}");
	add("{\"term\":\"mustard family\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11887994\"]}");
	add("{\"term\":\"mustard gas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14981409\"]}");
	add("{\"term\":\"mustard greens\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07729508\"]}");
	add("{\"term\":\"mustard oil\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11898989\"]}");
	add("{\"term\":\"mustard plaster\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03808340\"]}");
	add("{\"term\":\"mustard sauce\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07854881\"]}");
	add("{\"term\":\"mustard seed\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07835279\"]}");
	add("{\"term\":\"mustard tree\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"12320157\", \"12928990\"]}");
	add("{\"term\":\"mustela\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02444354\"]}");
	add("{\"term\":\"mustela erminea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02444803\"]}");
	add("{\"term\":\"mustela frenata\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02445299\"]}");
	add("{\"term\":\"mustela nigripes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02446115\"]}");
	add("{\"term\":\"mustela nivalis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02445203\"]}");
	add("{\"term\":\"mustela putorius\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02445745\"]}");
	add("{\"term\":\"mustela rixosa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02445077\"]}");
	add("{\"term\":\"mustela vison\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02445646\"]}");
	add("{\"term\":\"mustelid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02443957\"]}");
	add("{\"term\":\"mustelidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02443336\"]}");
	add("{\"term\":\"musteline\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02443957\"]}");
	add("{\"term\":\"musteline mammal\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02443957\"]}");
	add("{\"term\":\"mustelus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01494853\"]}");
	add("{\"term\":\"mustelus canis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01495349\"]}");
	add("{\"term\":\"mustelus mustelus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01495210\"]}");
	add("{\"term\":\"mustelus norrisi\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01495501\"]}");
	add("{\"term\":\"muster\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"01160337\", \"08496626\"]}");
	add("{\"term\":\"muster call\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01014067\"]}");
	add("{\"term\":\"muster roll\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06508615\"]}");
	add("{\"term\":\"musth\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"15314179\"]}");
	add("{\"term\":\"mustiness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04935371\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }