package org.swtk.commons.dict.wordnet.indexbyname.instance.l.a.w;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceLAW {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"law\", \"synsetCount\":7, \"upperType\":\"NOUN\", \"ids\":[\"08226608\", \"00612411\", \"06171434\", \"05881589\", \"05879538\", \"06544321\", \"08458195\"]}");
	add("{\"term\":\"law agent\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10268888\"]}");
	add("{\"term\":\"law court\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03654773\"]}");
	add("{\"term\":\"law degree\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06717503\"]}");
	add("{\"term\":\"law enforcement\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01130458\"]}");
	add("{\"term\":\"law enforcement agency\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08365742\"]}");
	add("{\"term\":\"law firm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08080875\"]}");
	add("{\"term\":\"law merchant\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08472048\"]}");
	add("{\"term\":\"law of action and reaction\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05894873\"]}");
	add("{\"term\":\"law of archimedes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05883323\"]}");
	add("{\"term\":\"law of areas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05888463\"]}");
	add("{\"term\":\"law of averages\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05889322\"]}");
	add("{\"term\":\"law of chemical equilibrium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05886019\"]}");
	add("{\"term\":\"law of closure\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06259551\"]}");
	add("{\"term\":\"law of common fate\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06259815\"]}");
	add("{\"term\":\"law of conservation of energy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06114185\"]}");
	add("{\"term\":\"law of conservation of mass\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06114451\"]}");
	add("{\"term\":\"law of conservation of matter\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06114451\"]}");
	add("{\"term\":\"law of constant proportion\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05889461\"]}");
	add("{\"term\":\"law of continuation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06260338\"]}");
	add("{\"term\":\"law of definite proportions\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05889461\"]}");
	add("{\"term\":\"law of diminishing returns\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05889709\"]}");
	add("{\"term\":\"law of effect\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05889910\"]}");
	add("{\"term\":\"law of equal areas\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05888463\"]}");
	add("{\"term\":\"law of equivalent proportions\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05890185\"]}");
	add("{\"term\":\"law of gravitation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05890474\"]}");
	add("{\"term\":\"law of independent assortment\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05893591\"]}");
	add("{\"term\":\"law of large numbers\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05883755\"]}");
	add("{\"term\":\"law of mass action\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05891144\"]}");
	add("{\"term\":\"law of moses\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08472531\"]}");
	add("{\"term\":\"law of motion\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05894229\"]}");
	add("{\"term\":\"law of multiple proportions\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05890833\"]}");
	add("{\"term\":\"law of nations\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08471014\"]}");
	add("{\"term\":\"law of nature\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05881589\"]}");
	add("{\"term\":\"law of parsimony\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05999623\"]}");
	add("{\"term\":\"law of partial pressures\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05885076\"]}");
	add("{\"term\":\"law of proximity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06260901\"]}");
	add("{\"term\":\"law of reciprocal proportions\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05890185\"]}");
	add("{\"term\":\"law of segregation\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05893343\"]}");
	add("{\"term\":\"law of similarity\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06261163\"]}");
	add("{\"term\":\"law of the land\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08471456\"]}");
	add("{\"term\":\"law of thermodynamics\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05891400\"]}");
	add("{\"term\":\"law of volumes\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05886836\"]}");
	add("{\"term\":\"law offender\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10774117\"]}");
	add("{\"term\":\"law officer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10269156\"]}");
	add("{\"term\":\"law practice\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00633347\"]}");
	add("{\"term\":\"law school\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08299972\"]}");
	add("{\"term\":\"law student\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10269566\"]}");
	add("{\"term\":\"lawbreaker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10774117\"]}");
	add("{\"term\":\"lawcourt\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03654773\"]}");
	add("{\"term\":\"lawfulness\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04817036\"]}");
	add("{\"term\":\"lawgiver\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10268967\"]}");
	add("{\"term\":\"lawlessness\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04818378\", \"13996506\"]}");
	add("{\"term\":\"lawmaker\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10268967\"]}");
	add("{\"term\":\"lawmaking\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01128014\"]}");
	add("{\"term\":\"lawman\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10269156\"]}");
	add("{\"term\":\"lawn\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08609148\"]}");
	add("{\"term\":\"lawn bowling\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00463865\"]}");
	add("{\"term\":\"lawn cart\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02800454\"]}");
	add("{\"term\":\"lawn chair\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03655000\"]}");
	add("{\"term\":\"lawn furniture\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03655123\"]}");
	add("{\"term\":\"lawn mower\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03655235\"]}");
	add("{\"term\":\"lawn party\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"08272429\"]}");
	add("{\"term\":\"lawn tennis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00483309\"]}");
	add("{\"term\":\"lawn tool\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03423152\"]}");
	add("{\"term\":\"lawrence\", \"synsetCount\":7, \"upperType\":\"NOUN\", \"ids\":[\"09111114\", \"11140136\", \"11140358\", \"11140520\", \"11140623\", \"11140824\", \"11141098\"]}");
	add("{\"term\":\"lawrence durrell\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10966278\"]}");
	add("{\"term\":\"lawrence george durrell\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10966278\"]}");
	add("{\"term\":\"lawrence of arabia\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11140824\"]}");
	add("{\"term\":\"lawrence peter berra\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10868542\"]}");
	add("{\"term\":\"lawrencium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14667501\"]}");
	add("{\"term\":\"laws\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"06463561\"]}");
	add("{\"term\":\"lawsuit\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01185144\"]}");
	add("{\"term\":\"lawton\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09154954\"]}");
	add("{\"term\":\"lawyer\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10269647\"]}");
	add("{\"term\":\"lawyer bush\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12674197\"]}");
	add("{\"term\":\"lawyer cane\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12607486\"]}");
	add("{\"term\":\"lawyerbush\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12674197\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }