package org.swtk.commons.dict.wordnet.index.name.controller.i.r;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.a.k.WordnetNounIndexNameInstanceIRAK;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.a.n.WordnetNounIndexNameInstanceIRAN;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.a.q.WordnetNounIndexNameInstanceIRAQ;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.a.s.WordnetNounIndexNameInstanceIRAS;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.e.l.WordnetNounIndexNameInstanceIREL;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.e.n.WordnetNounIndexNameInstanceIREN;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.e.s.WordnetNounIndexNameInstanceIRES;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.i.d.WordnetNounIndexNameInstanceIRID;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.i.s.WordnetNounIndexNameInstanceIRIS;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.i.t.WordnetNounIndexNameInstanceIRIT;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.o.n.WordnetNounIndexNameInstanceIRON;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.o.q.WordnetNounIndexNameInstanceIROQ;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.r.a.WordnetNounIndexNameInstanceIRRA;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.r.e.WordnetNounIndexNameInstanceIRRE;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.r.i.WordnetNounIndexNameInstanceIRRI;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.r.u.WordnetNounIndexNameInstanceIRRU;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.t.i.WordnetNounIndexNameInstanceIRTI;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.t.y.WordnetNounIndexNameInstanceIRTY;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.u.l.WordnetNounIndexNameInstanceIRUL;
	import org.swtk.commons.dict.wordnet.index.name.instance.i.r.v.i.WordnetNounIndexNameInstanceIRVI;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerIR {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("irak".equals(key)) return WordnetNounIndexNameInstanceIRAK.get(TERM);
	if ("iran".equals(key)) return WordnetNounIndexNameInstanceIRAN.get(TERM);
	if ("iraq".equals(key)) return WordnetNounIndexNameInstanceIRAQ.get(TERM);
	if ("iras".equals(key)) return WordnetNounIndexNameInstanceIRAS.get(TERM);
	if ("irel".equals(key)) return WordnetNounIndexNameInstanceIREL.get(TERM);
	if ("iren".equals(key)) return WordnetNounIndexNameInstanceIREN.get(TERM);
	if ("ires".equals(key)) return WordnetNounIndexNameInstanceIRES.get(TERM);
	if ("irid".equals(key)) return WordnetNounIndexNameInstanceIRID.get(TERM);
	if ("iris".equals(key)) return WordnetNounIndexNameInstanceIRIS.get(TERM);
	if ("irit".equals(key)) return WordnetNounIndexNameInstanceIRIT.get(TERM);
	if ("iron".equals(key)) return WordnetNounIndexNameInstanceIRON.get(TERM);
	if ("iroq".equals(key)) return WordnetNounIndexNameInstanceIROQ.get(TERM);
	if ("irra".equals(key)) return WordnetNounIndexNameInstanceIRRA.get(TERM);
	if ("irre".equals(key)) return WordnetNounIndexNameInstanceIRRE.get(TERM);
	if ("irri".equals(key)) return WordnetNounIndexNameInstanceIRRI.get(TERM);
	if ("irru".equals(key)) return WordnetNounIndexNameInstanceIRRU.get(TERM);
	if ("irti".equals(key)) return WordnetNounIndexNameInstanceIRTI.get(TERM);
	if ("irty".equals(key)) return WordnetNounIndexNameInstanceIRTY.get(TERM);
	if ("irul".equals(key)) return WordnetNounIndexNameInstanceIRUL.get(TERM);
	if ("irvi".equals(key)) return WordnetNounIndexNameInstanceIRVI.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceIRAK.terms());
	set.addAll(WordnetNounIndexNameInstanceIRAN.terms());
	set.addAll(WordnetNounIndexNameInstanceIRAQ.terms());
	set.addAll(WordnetNounIndexNameInstanceIRAS.terms());
	set.addAll(WordnetNounIndexNameInstanceIREL.terms());
	set.addAll(WordnetNounIndexNameInstanceIREN.terms());
	set.addAll(WordnetNounIndexNameInstanceIRES.terms());
	set.addAll(WordnetNounIndexNameInstanceIRID.terms());
	set.addAll(WordnetNounIndexNameInstanceIRIS.terms());
	set.addAll(WordnetNounIndexNameInstanceIRIT.terms());
	set.addAll(WordnetNounIndexNameInstanceIRON.terms());
	set.addAll(WordnetNounIndexNameInstanceIROQ.terms());
	set.addAll(WordnetNounIndexNameInstanceIRRA.terms());
	set.addAll(WordnetNounIndexNameInstanceIRRE.terms());
	set.addAll(WordnetNounIndexNameInstanceIRRI.terms());
	set.addAll(WordnetNounIndexNameInstanceIRRU.terms());
	set.addAll(WordnetNounIndexNameInstanceIRTI.terms());
	set.addAll(WordnetNounIndexNameInstanceIRTY.terms());
	set.addAll(WordnetNounIndexNameInstanceIRUL.terms());
	set.addAll(WordnetNounIndexNameInstanceIRVI.terms());
  		return set; 	} }