package org.swtk.commons.dict.wordnet.index.name.controller.a.n;  import java.util.Collection; import java.util.Set; import java.util.TreeSet;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.b.WordnetNounIndexNameInstanceANAB;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.c.WordnetNounIndexNameInstanceANAC;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.d.WordnetNounIndexNameInstanceANAD;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.e.WordnetNounIndexNameInstanceANAE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.g.WordnetNounIndexNameInstanceANAG;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.h.WordnetNounIndexNameInstanceANAH;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.l.WordnetNounIndexNameInstanceANAL;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.m.WordnetNounIndexNameInstanceANAM;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.n.WordnetNounIndexNameInstanceANAN;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.p.WordnetNounIndexNameInstanceANAP;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.r.WordnetNounIndexNameInstanceANAR;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.s.WordnetNounIndexNameInstanceANAS;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.t.WordnetNounIndexNameInstanceANAT;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.a.x.WordnetNounIndexNameInstanceANAX;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.c.e.WordnetNounIndexNameInstanceANCE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.c.h.WordnetNounIndexNameInstanceANCH;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.c.i.WordnetNounIndexNameInstanceANCI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.c.o.WordnetNounIndexNameInstanceANCO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.c.y.WordnetNounIndexNameInstanceANCY;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.d.a.WordnetNounIndexNameInstanceANDA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.d.e.WordnetNounIndexNameInstanceANDE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.d.i.WordnetNounIndexNameInstanceANDI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.d.o.WordnetNounIndexNameInstanceANDO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.d.r.WordnetNounIndexNameInstanceANDR;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.d.v.WordnetNounIndexNameInstanceANDV;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.e.c.WordnetNounIndexNameInstanceANEC;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.e.i.WordnetNounIndexNameInstanceANEI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.e.m.WordnetNounIndexNameInstanceANEM;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.e.n.WordnetNounIndexNameInstanceANEN;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.e.r.WordnetNounIndexNameInstanceANER;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.e.s.WordnetNounIndexNameInstanceANES;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.e.t.WordnetNounIndexNameInstanceANET;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.e.u.WordnetNounIndexNameInstanceANEU;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.g.a.WordnetNounIndexNameInstanceANGA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.g.e.WordnetNounIndexNameInstanceANGE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.g.i.WordnetNounIndexNameInstanceANGI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.g.l.WordnetNounIndexNameInstanceANGL;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.g.o.WordnetNounIndexNameInstanceANGO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.g.r.WordnetNounIndexNameInstanceANGR;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.g.s.WordnetNounIndexNameInstanceANGS;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.g.u.WordnetNounIndexNameInstanceANGU;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.g.w.WordnetNounIndexNameInstanceANGW;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.h.e.WordnetNounIndexNameInstanceANHE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.h.i.WordnetNounIndexNameInstanceANHI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.h.y.WordnetNounIndexNameInstanceANHY;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.i.g.WordnetNounIndexNameInstanceANIG;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.i.l.WordnetNounIndexNameInstanceANIL;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.i.m.WordnetNounIndexNameInstanceANIM;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.i.o.WordnetNounIndexNameInstanceANIO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.i.s.WordnetNounIndexNameInstanceANIS;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.j.o.WordnetNounIndexNameInstanceANJO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.k.a.WordnetNounIndexNameInstanceANKA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.k.l.WordnetNounIndexNameInstanceANKL;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.k.u.WordnetNounIndexNameInstanceANKU;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.k.y.WordnetNounIndexNameInstanceANKY;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.l.a.WordnetNounIndexNameInstanceANLA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.n.a.WordnetNounIndexNameInstanceANNA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.n.e.WordnetNounIndexNameInstanceANNE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.n.i.WordnetNounIndexNameInstanceANNI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.n.o.WordnetNounIndexNameInstanceANNO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.n.u.WordnetNounIndexNameInstanceANNU;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.n.w.WordnetNounIndexNameInstanceANNW;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.a.WordnetNounIndexNameInstanceANOA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.b.WordnetNounIndexNameInstanceANOB;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.d.WordnetNounIndexNameInstanceANOD;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.e.WordnetNounIndexNameInstanceANOE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.g.WordnetNounIndexNameInstanceANOG;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.i.WordnetNounIndexNameInstanceANOI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.l.WordnetNounIndexNameInstanceANOL;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.m.WordnetNounIndexNameInstanceANOM;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.n.WordnetNounIndexNameInstanceANON;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.p.WordnetNounIndexNameInstanceANOP;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.r.WordnetNounIndexNameInstanceANOR;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.s.WordnetNounIndexNameInstanceANOS;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.u.WordnetNounIndexNameInstanceANOU;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.v.WordnetNounIndexNameInstanceANOV;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.o.x.WordnetNounIndexNameInstanceANOX;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.p.u.WordnetNounIndexNameInstanceANPU;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.s.a.WordnetNounIndexNameInstanceANSA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.s.e.WordnetNounIndexNameInstanceANSE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.s.h.WordnetNounIndexNameInstanceANSH;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.s.w.WordnetNounIndexNameInstanceANSW;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.t.a.WordnetNounIndexNameInstanceANTA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.t.b.WordnetNounIndexNameInstanceANTB;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.t.e.WordnetNounIndexNameInstanceANTE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.t.h.WordnetNounIndexNameInstanceANTH;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.t.i.WordnetNounIndexNameInstanceANTI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.t.l.WordnetNounIndexNameInstanceANTL;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.t.o.WordnetNounIndexNameInstanceANTO;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.t.r.WordnetNounIndexNameInstanceANTR;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.t.u.WordnetNounIndexNameInstanceANTU;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.t.w.WordnetNounIndexNameInstanceANTW;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.u.b.WordnetNounIndexNameInstanceANUB;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.u.n.WordnetNounIndexNameInstanceANUN;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.u.r.WordnetNounIndexNameInstanceANUR;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.u.s.WordnetNounIndexNameInstanceANUS;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.v.e.WordnetNounIndexNameInstanceANVE;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.v.i.WordnetNounIndexNameInstanceANVI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.x.i.WordnetNounIndexNameInstanceANXI;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.z.a.WordnetNounIndexNameInstanceANZA;
	import org.swtk.commons.dict.wordnet.index.name.instance.a.n.z.i.WordnetNounIndexNameInstanceANZI;
  import com.trimc.blogger.commons.exception.BusinessException;  public final class WordnetNounIndexNameControllerAN {  	public static Collection<IndexNoun> get(final String TERM) throws BusinessException {  		String key = TERM.substring(0, 4).toLowerCase(); 			if ("anab".equals(key)) return WordnetNounIndexNameInstanceANAB.get(TERM);
	if ("anac".equals(key)) return WordnetNounIndexNameInstanceANAC.get(TERM);
	if ("anad".equals(key)) return WordnetNounIndexNameInstanceANAD.get(TERM);
	if ("anae".equals(key)) return WordnetNounIndexNameInstanceANAE.get(TERM);
	if ("anag".equals(key)) return WordnetNounIndexNameInstanceANAG.get(TERM);
	if ("anah".equals(key)) return WordnetNounIndexNameInstanceANAH.get(TERM);
	if ("anal".equals(key)) return WordnetNounIndexNameInstanceANAL.get(TERM);
	if ("anam".equals(key)) return WordnetNounIndexNameInstanceANAM.get(TERM);
	if ("anan".equals(key)) return WordnetNounIndexNameInstanceANAN.get(TERM);
	if ("anap".equals(key)) return WordnetNounIndexNameInstanceANAP.get(TERM);
	if ("anar".equals(key)) return WordnetNounIndexNameInstanceANAR.get(TERM);
	if ("anas".equals(key)) return WordnetNounIndexNameInstanceANAS.get(TERM);
	if ("anat".equals(key)) return WordnetNounIndexNameInstanceANAT.get(TERM);
	if ("anax".equals(key)) return WordnetNounIndexNameInstanceANAX.get(TERM);
	if ("ance".equals(key)) return WordnetNounIndexNameInstanceANCE.get(TERM);
	if ("anch".equals(key)) return WordnetNounIndexNameInstanceANCH.get(TERM);
	if ("anci".equals(key)) return WordnetNounIndexNameInstanceANCI.get(TERM);
	if ("anco".equals(key)) return WordnetNounIndexNameInstanceANCO.get(TERM);
	if ("ancy".equals(key)) return WordnetNounIndexNameInstanceANCY.get(TERM);
	if ("anda".equals(key)) return WordnetNounIndexNameInstanceANDA.get(TERM);
	if ("ande".equals(key)) return WordnetNounIndexNameInstanceANDE.get(TERM);
	if ("andi".equals(key)) return WordnetNounIndexNameInstanceANDI.get(TERM);
	if ("ando".equals(key)) return WordnetNounIndexNameInstanceANDO.get(TERM);
	if ("andr".equals(key)) return WordnetNounIndexNameInstanceANDR.get(TERM);
	if ("andv".equals(key)) return WordnetNounIndexNameInstanceANDV.get(TERM);
	if ("anec".equals(key)) return WordnetNounIndexNameInstanceANEC.get(TERM);
	if ("anei".equals(key)) return WordnetNounIndexNameInstanceANEI.get(TERM);
	if ("anem".equals(key)) return WordnetNounIndexNameInstanceANEM.get(TERM);
	if ("anen".equals(key)) return WordnetNounIndexNameInstanceANEN.get(TERM);
	if ("aner".equals(key)) return WordnetNounIndexNameInstanceANER.get(TERM);
	if ("anes".equals(key)) return WordnetNounIndexNameInstanceANES.get(TERM);
	if ("anet".equals(key)) return WordnetNounIndexNameInstanceANET.get(TERM);
	if ("aneu".equals(key)) return WordnetNounIndexNameInstanceANEU.get(TERM);
	if ("anga".equals(key)) return WordnetNounIndexNameInstanceANGA.get(TERM);
	if ("ange".equals(key)) return WordnetNounIndexNameInstanceANGE.get(TERM);
	if ("angi".equals(key)) return WordnetNounIndexNameInstanceANGI.get(TERM);
	if ("angl".equals(key)) return WordnetNounIndexNameInstanceANGL.get(TERM);
	if ("ango".equals(key)) return WordnetNounIndexNameInstanceANGO.get(TERM);
	if ("angr".equals(key)) return WordnetNounIndexNameInstanceANGR.get(TERM);
	if ("angs".equals(key)) return WordnetNounIndexNameInstanceANGS.get(TERM);
	if ("angu".equals(key)) return WordnetNounIndexNameInstanceANGU.get(TERM);
	if ("angw".equals(key)) return WordnetNounIndexNameInstanceANGW.get(TERM);
	if ("anhe".equals(key)) return WordnetNounIndexNameInstanceANHE.get(TERM);
	if ("anhi".equals(key)) return WordnetNounIndexNameInstanceANHI.get(TERM);
	if ("anhy".equals(key)) return WordnetNounIndexNameInstanceANHY.get(TERM);
	if ("anig".equals(key)) return WordnetNounIndexNameInstanceANIG.get(TERM);
	if ("anil".equals(key)) return WordnetNounIndexNameInstanceANIL.get(TERM);
	if ("anim".equals(key)) return WordnetNounIndexNameInstanceANIM.get(TERM);
	if ("anio".equals(key)) return WordnetNounIndexNameInstanceANIO.get(TERM);
	if ("anis".equals(key)) return WordnetNounIndexNameInstanceANIS.get(TERM);
	if ("anjo".equals(key)) return WordnetNounIndexNameInstanceANJO.get(TERM);
	if ("anka".equals(key)) return WordnetNounIndexNameInstanceANKA.get(TERM);
	if ("ankl".equals(key)) return WordnetNounIndexNameInstanceANKL.get(TERM);
	if ("anku".equals(key)) return WordnetNounIndexNameInstanceANKU.get(TERM);
	if ("anky".equals(key)) return WordnetNounIndexNameInstanceANKY.get(TERM);
	if ("anla".equals(key)) return WordnetNounIndexNameInstanceANLA.get(TERM);
	if ("anna".equals(key)) return WordnetNounIndexNameInstanceANNA.get(TERM);
	if ("anne".equals(key)) return WordnetNounIndexNameInstanceANNE.get(TERM);
	if ("anni".equals(key)) return WordnetNounIndexNameInstanceANNI.get(TERM);
	if ("anno".equals(key)) return WordnetNounIndexNameInstanceANNO.get(TERM);
	if ("annu".equals(key)) return WordnetNounIndexNameInstanceANNU.get(TERM);
	if ("annw".equals(key)) return WordnetNounIndexNameInstanceANNW.get(TERM);
	if ("anoa".equals(key)) return WordnetNounIndexNameInstanceANOA.get(TERM);
	if ("anob".equals(key)) return WordnetNounIndexNameInstanceANOB.get(TERM);
	if ("anod".equals(key)) return WordnetNounIndexNameInstanceANOD.get(TERM);
	if ("anoe".equals(key)) return WordnetNounIndexNameInstanceANOE.get(TERM);
	if ("anog".equals(key)) return WordnetNounIndexNameInstanceANOG.get(TERM);
	if ("anoi".equals(key)) return WordnetNounIndexNameInstanceANOI.get(TERM);
	if ("anol".equals(key)) return WordnetNounIndexNameInstanceANOL.get(TERM);
	if ("anom".equals(key)) return WordnetNounIndexNameInstanceANOM.get(TERM);
	if ("anon".equals(key)) return WordnetNounIndexNameInstanceANON.get(TERM);
	if ("anop".equals(key)) return WordnetNounIndexNameInstanceANOP.get(TERM);
	if ("anor".equals(key)) return WordnetNounIndexNameInstanceANOR.get(TERM);
	if ("anos".equals(key)) return WordnetNounIndexNameInstanceANOS.get(TERM);
	if ("anou".equals(key)) return WordnetNounIndexNameInstanceANOU.get(TERM);
	if ("anov".equals(key)) return WordnetNounIndexNameInstanceANOV.get(TERM);
	if ("anox".equals(key)) return WordnetNounIndexNameInstanceANOX.get(TERM);
	if ("anpu".equals(key)) return WordnetNounIndexNameInstanceANPU.get(TERM);
	if ("ansa".equals(key)) return WordnetNounIndexNameInstanceANSA.get(TERM);
	if ("anse".equals(key)) return WordnetNounIndexNameInstanceANSE.get(TERM);
	if ("ansh".equals(key)) return WordnetNounIndexNameInstanceANSH.get(TERM);
	if ("answ".equals(key)) return WordnetNounIndexNameInstanceANSW.get(TERM);
	if ("anta".equals(key)) return WordnetNounIndexNameInstanceANTA.get(TERM);
	if ("antb".equals(key)) return WordnetNounIndexNameInstanceANTB.get(TERM);
	if ("ante".equals(key)) return WordnetNounIndexNameInstanceANTE.get(TERM);
	if ("anth".equals(key)) return WordnetNounIndexNameInstanceANTH.get(TERM);
	if ("anti".equals(key)) return WordnetNounIndexNameInstanceANTI.get(TERM);
	if ("antl".equals(key)) return WordnetNounIndexNameInstanceANTL.get(TERM);
	if ("anto".equals(key)) return WordnetNounIndexNameInstanceANTO.get(TERM);
	if ("antr".equals(key)) return WordnetNounIndexNameInstanceANTR.get(TERM);
	if ("antu".equals(key)) return WordnetNounIndexNameInstanceANTU.get(TERM);
	if ("antw".equals(key)) return WordnetNounIndexNameInstanceANTW.get(TERM);
	if ("anub".equals(key)) return WordnetNounIndexNameInstanceANUB.get(TERM);
	if ("anun".equals(key)) return WordnetNounIndexNameInstanceANUN.get(TERM);
	if ("anur".equals(key)) return WordnetNounIndexNameInstanceANUR.get(TERM);
	if ("anus".equals(key)) return WordnetNounIndexNameInstanceANUS.get(TERM);
	if ("anve".equals(key)) return WordnetNounIndexNameInstanceANVE.get(TERM);
	if ("anvi".equals(key)) return WordnetNounIndexNameInstanceANVI.get(TERM);
	if ("anxi".equals(key)) return WordnetNounIndexNameInstanceANXI.get(TERM);
	if ("anza".equals(key)) return WordnetNounIndexNameInstanceANZA.get(TERM);
	if ("anzi".equals(key)) return WordnetNounIndexNameInstanceANZI.get(TERM);
  		throw new BusinessException("TERM not found (id = %s)", TERM); 	} 	 	public static Collection<String> terms() throws BusinessException { 		Set<String> set = new TreeSet<String>();  			set.addAll(WordnetNounIndexNameInstanceANAB.terms());
	set.addAll(WordnetNounIndexNameInstanceANAC.terms());
	set.addAll(WordnetNounIndexNameInstanceANAD.terms());
	set.addAll(WordnetNounIndexNameInstanceANAE.terms());
	set.addAll(WordnetNounIndexNameInstanceANAG.terms());
	set.addAll(WordnetNounIndexNameInstanceANAH.terms());
	set.addAll(WordnetNounIndexNameInstanceANAL.terms());
	set.addAll(WordnetNounIndexNameInstanceANAM.terms());
	set.addAll(WordnetNounIndexNameInstanceANAN.terms());
	set.addAll(WordnetNounIndexNameInstanceANAP.terms());
	set.addAll(WordnetNounIndexNameInstanceANAR.terms());
	set.addAll(WordnetNounIndexNameInstanceANAS.terms());
	set.addAll(WordnetNounIndexNameInstanceANAT.terms());
	set.addAll(WordnetNounIndexNameInstanceANAX.terms());
	set.addAll(WordnetNounIndexNameInstanceANCE.terms());
	set.addAll(WordnetNounIndexNameInstanceANCH.terms());
	set.addAll(WordnetNounIndexNameInstanceANCI.terms());
	set.addAll(WordnetNounIndexNameInstanceANCO.terms());
	set.addAll(WordnetNounIndexNameInstanceANCY.terms());
	set.addAll(WordnetNounIndexNameInstanceANDA.terms());
	set.addAll(WordnetNounIndexNameInstanceANDE.terms());
	set.addAll(WordnetNounIndexNameInstanceANDI.terms());
	set.addAll(WordnetNounIndexNameInstanceANDO.terms());
	set.addAll(WordnetNounIndexNameInstanceANDR.terms());
	set.addAll(WordnetNounIndexNameInstanceANDV.terms());
	set.addAll(WordnetNounIndexNameInstanceANEC.terms());
	set.addAll(WordnetNounIndexNameInstanceANEI.terms());
	set.addAll(WordnetNounIndexNameInstanceANEM.terms());
	set.addAll(WordnetNounIndexNameInstanceANEN.terms());
	set.addAll(WordnetNounIndexNameInstanceANER.terms());
	set.addAll(WordnetNounIndexNameInstanceANES.terms());
	set.addAll(WordnetNounIndexNameInstanceANET.terms());
	set.addAll(WordnetNounIndexNameInstanceANEU.terms());
	set.addAll(WordnetNounIndexNameInstanceANGA.terms());
	set.addAll(WordnetNounIndexNameInstanceANGE.terms());
	set.addAll(WordnetNounIndexNameInstanceANGI.terms());
	set.addAll(WordnetNounIndexNameInstanceANGL.terms());
	set.addAll(WordnetNounIndexNameInstanceANGO.terms());
	set.addAll(WordnetNounIndexNameInstanceANGR.terms());
	set.addAll(WordnetNounIndexNameInstanceANGS.terms());
	set.addAll(WordnetNounIndexNameInstanceANGU.terms());
	set.addAll(WordnetNounIndexNameInstanceANGW.terms());
	set.addAll(WordnetNounIndexNameInstanceANHE.terms());
	set.addAll(WordnetNounIndexNameInstanceANHI.terms());
	set.addAll(WordnetNounIndexNameInstanceANHY.terms());
	set.addAll(WordnetNounIndexNameInstanceANIG.terms());
	set.addAll(WordnetNounIndexNameInstanceANIL.terms());
	set.addAll(WordnetNounIndexNameInstanceANIM.terms());
	set.addAll(WordnetNounIndexNameInstanceANIO.terms());
	set.addAll(WordnetNounIndexNameInstanceANIS.terms());
	set.addAll(WordnetNounIndexNameInstanceANJO.terms());
	set.addAll(WordnetNounIndexNameInstanceANKA.terms());
	set.addAll(WordnetNounIndexNameInstanceANKL.terms());
	set.addAll(WordnetNounIndexNameInstanceANKU.terms());
	set.addAll(WordnetNounIndexNameInstanceANKY.terms());
	set.addAll(WordnetNounIndexNameInstanceANLA.terms());
	set.addAll(WordnetNounIndexNameInstanceANNA.terms());
	set.addAll(WordnetNounIndexNameInstanceANNE.terms());
	set.addAll(WordnetNounIndexNameInstanceANNI.terms());
	set.addAll(WordnetNounIndexNameInstanceANNO.terms());
	set.addAll(WordnetNounIndexNameInstanceANNU.terms());
	set.addAll(WordnetNounIndexNameInstanceANNW.terms());
	set.addAll(WordnetNounIndexNameInstanceANOA.terms());
	set.addAll(WordnetNounIndexNameInstanceANOB.terms());
	set.addAll(WordnetNounIndexNameInstanceANOD.terms());
	set.addAll(WordnetNounIndexNameInstanceANOE.terms());
	set.addAll(WordnetNounIndexNameInstanceANOG.terms());
	set.addAll(WordnetNounIndexNameInstanceANOI.terms());
	set.addAll(WordnetNounIndexNameInstanceANOL.terms());
	set.addAll(WordnetNounIndexNameInstanceANOM.terms());
	set.addAll(WordnetNounIndexNameInstanceANON.terms());
	set.addAll(WordnetNounIndexNameInstanceANOP.terms());
	set.addAll(WordnetNounIndexNameInstanceANOR.terms());
	set.addAll(WordnetNounIndexNameInstanceANOS.terms());
	set.addAll(WordnetNounIndexNameInstanceANOU.terms());
	set.addAll(WordnetNounIndexNameInstanceANOV.terms());
	set.addAll(WordnetNounIndexNameInstanceANOX.terms());
	set.addAll(WordnetNounIndexNameInstanceANPU.terms());
	set.addAll(WordnetNounIndexNameInstanceANSA.terms());
	set.addAll(WordnetNounIndexNameInstanceANSE.terms());
	set.addAll(WordnetNounIndexNameInstanceANSH.terms());
	set.addAll(WordnetNounIndexNameInstanceANSW.terms());
	set.addAll(WordnetNounIndexNameInstanceANTA.terms());
	set.addAll(WordnetNounIndexNameInstanceANTB.terms());
	set.addAll(WordnetNounIndexNameInstanceANTE.terms());
	set.addAll(WordnetNounIndexNameInstanceANTH.terms());
	set.addAll(WordnetNounIndexNameInstanceANTI.terms());
	set.addAll(WordnetNounIndexNameInstanceANTL.terms());
	set.addAll(WordnetNounIndexNameInstanceANTO.terms());
	set.addAll(WordnetNounIndexNameInstanceANTR.terms());
	set.addAll(WordnetNounIndexNameInstanceANTU.terms());
	set.addAll(WordnetNounIndexNameInstanceANTW.terms());
	set.addAll(WordnetNounIndexNameInstanceANUB.terms());
	set.addAll(WordnetNounIndexNameInstanceANUN.terms());
	set.addAll(WordnetNounIndexNameInstanceANUR.terms());
	set.addAll(WordnetNounIndexNameInstanceANUS.terms());
	set.addAll(WordnetNounIndexNameInstanceANVE.terms());
	set.addAll(WordnetNounIndexNameInstanceANVI.terms());
	set.addAll(WordnetNounIndexNameInstanceANXI.terms());
	set.addAll(WordnetNounIndexNameInstanceANZA.terms());
	set.addAll(WordnetNounIndexNameInstanceANZI.terms());
  		return set; 	} }