package org.swtk.commons.dict.wordnet.indexbyname.instance.l.a.r;  import java.util.ArrayList; import java.util.Collection; import java.util.Map; import java.util.TreeMap;  import org.swtk.common.dict.dto.wordnet.IndexNoun;  import com.trimc.blogger.commons.utils.GsonUtils;  public final class WordnetNounIndexNameInstanceLAR {  	private static Map<String, Collection<IndexNoun>> map = new TreeMap<String, Collection<IndexNoun>>();  	static { 			add("{\"term\":\"laramie\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09182849\"]}");
	add("{\"term\":\"larboard\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03648242\"]}");
	add("{\"term\":\"larcener\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10266610\"]}");
	add("{\"term\":\"larcenist\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"10266610\"]}");
	add("{\"term\":\"larcenous\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"04883130\"]}");
	add("{\"term\":\"larceny\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00782543\"]}");
	add("{\"term\":\"larch\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"11639312\", \"11639587\"]}");
	add("{\"term\":\"lard\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07688166\"]}");
	add("{\"term\":\"larder\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"03891232\", \"07588181\"]}");
	add("{\"term\":\"lardizabala\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11723674\"]}");
	add("{\"term\":\"lardizabalaceae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11723468\"]}");
	add("{\"term\":\"lardner\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11137734\"]}");
	add("{\"term\":\"laredo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"09167820\"]}");
	add("{\"term\":\"large\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05103453\"]}");
	add("{\"term\":\"largemouth\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02567955\"]}");
	add("{\"term\":\"largeness\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"04796210\", \"05111246\", \"05113617\", \"05626076\"]}");
	add("{\"term\":\"largess\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04839947\", \"13286648\"]}");
	add("{\"term\":\"largesse\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"04839947\", \"13286648\"]}");
	add("{\"term\":\"larghetto\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07060795\"]}");
	add("{\"term\":\"largo\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"07060601\"]}");
	add("{\"term\":\"lari\", \"synsetCount\":2, \"upperType\":\"NOUN\", \"ids\":[\"02043352\", \"13722767\"]}");
	add("{\"term\":\"lariat\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03649692\"]}");
	add("{\"term\":\"laricariidae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02523022\"]}");
	add("{\"term\":\"larid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02043739\"]}");
	add("{\"term\":\"laridae\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02043526\"]}");
	add("{\"term\":\"larium\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03748219\"]}");
	add("{\"term\":\"larix\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11639201\"]}");
	add("{\"term\":\"lark\", \"synsetCount\":4, \"upperType\":\"NOUN\", \"ids\":[\"00430307\", \"01530258\", \"01531295\", \"01575715\"]}");
	add("{\"term\":\"larkspur\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11753781\"]}");
	add("{\"term\":\"larodopa\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14629310\"]}");
	add("{\"term\":\"larotid\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02706753\"]}");
	add("{\"term\":\"larousse\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"11138062\"]}");
	add("{\"term\":\"larrea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"12743644\"]}");
	add("{\"term\":\"larus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02044146\"]}");
	add("{\"term\":\"larva\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"02313712\"]}");
	add("{\"term\":\"larvacea\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01472928\"]}");
	add("{\"term\":\"larvacean\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"01473120\"]}");
	add("{\"term\":\"larvacide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14624315\"]}");
	add("{\"term\":\"larvicide\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14954211\"]}");
	add("{\"term\":\"laryngectomy\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00684467\"]}");
	add("{\"term\":\"laryngismus\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"00228004\"]}");
	add("{\"term\":\"laryngitis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14372448\"]}");
	add("{\"term\":\"laryngopharyngitis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14372613\"]}");
	add("{\"term\":\"laryngopharynx\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05536792\"]}");
	add("{\"term\":\"laryngoscope\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"03648463\"]}");
	add("{\"term\":\"laryngospasm\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14124439\"]}");
	add("{\"term\":\"laryngostenosis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14130305\"]}");
	add("{\"term\":\"laryngotracheobronchitis\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"14372716\"]}");
	add("{\"term\":\"larynx\", \"synsetCount\":1, \"upperType\":\"NOUN\", \"ids\":[\"05537362\"]}");
 	}  	private static void add(final String JSON) { 		IndexNoun indexNoun = GsonUtils.toObject(JSON, IndexNoun.class); 		Collection<IndexNoun> list = (map.containsKey(indexNoun.getTerm())) ? map.get(indexNoun.getTerm()) : new ArrayList<IndexNoun>(); 		list.add(indexNoun); 		map.put(indexNoun.getTerm(), list); 	} 	 	public static Collection<IndexNoun> get(final String TERM) { 		return map.get(TERM); 	}  	public static boolean has(final String TERM) { 		return map.containsKey(TERM); 	} 	 	public static Collection<String> terms() { 		return map.keySet(); 	} }